### ISSUE TITLE
Posts Sync, File-sharing problem, A suggestion

### ISSUE THREAD

**Issue by gongzisun** [RetroShare/RetroShare#1003]
If there are two separate friends groups, like A - B - C , D - E -F. As we known D E F can never get the update what A published in the channel and forum, they can't download anything from A B C,  any posts from A B C. I can't get the nightly-biuld channel update sometime, but they had push it out, someone post it in the lobby. I don't think this is a logical system.
 
I know RetroShare is a F2F software, but if you just use with your friends in the real world, i don't think we need tor/i2p support, we know each other; we don't need the ChatServer, it is for the strangers; we don't need the channel, the forum, they are not for the small group. 
 
As these features added, i think we should made the connection be P2P. I have a idea, it made RetroShare private and secure and easy to use. It like the Turtle Route, F2F will be used only for the friends system. channel, forum, file-sharing will be P2P. but this P2P could be configured by the publisher. If the publisher don't want be known, he can set the hops for people's content sync. Like that, once again, A - B - C , D - E -F, A post something, D E F can get it directly, alternative A can made them get it through some hops, like D want the file, he must through one of EFBC, and B through CDEF even through B is A's friend. or B via C via D, it could be modified how many hops must be through. It is annoymous and speedy, and everyone can get everything. 

Maybe smeone will say i don't want my posts be synced to the strangers, but how do you know your friends will never add a guy you don't know. By the way, my suggestion work only for the public posts and sharing-files. the private others can still work in the GXS Permission setting. It could be a switch to set the content be connected by everyone or just author's friends.

Right now, channel and forum were used very often, i don't think RS should keep bing a pure F2F app, it must use p2p/p2p2p...p in some features. If RS want be a pure F2F app all the time, i think Emoty is the best, the other feature are unnecessary. they can't work well. How does the new guys get the nightly-biuld update?

Be reachable doesn't mean no privacy, like i2p, every node was reachable, what should we do is force the node reach the one via some nodes. In addition, RS can creat hidden node wit tor/i2p, how could publishing the posts to anyone be no privacy?

What we want is the content be reachable even we must via several hops, it should not be limited by separate groups, we are in the one internet. RS is a distributed app, if we can't connect the others in the world, it just lost its "distributed" meaning.

RetroShare should be a widely used tool, not for one after another separate groups. 

Sorry for my bad english. hope you guys know what i mean.

**Comment by cavebeat** [comment]
i understand it,
still you explain a technology which is already available. i'd say www or torrent are using this approach.

**Comment by gongzisun** [comment]
I don't know devs want user how to use RetroShare? just for chats? like the channel forum, use to do waht? 

especially the nightly-biuld channel, it shouid be reached by everyone, but if we are in separate friends group, we can't get the update. Isn't the RS for spreading information? and i have said not totally public, it can be a switch, it can be configured by the publisher. directly or via some hops, something be reachable by everyone, something not.
If RS just want be a different tool, and refuse the other protocols for users, maybe it can't complete its anticensorship mission.

**Comment by gongzisun** [comment]
One more thing, i want it be a  i2p method, like turtle route, a hop-modifiable p2p2p way to spread， not a p2p mode, and the way is optional.
I think you might be very clear RS can work well in  only F2F mode when you founded the CahtServer.

**Comment by kdebiec** [comment]
@gongzisun You have pointed out quite important issue that RS suffers, but IMO your proposition might be costly(computer resources) for users and it require a lot of time to develop it. 

My approach is to make it easy to setup RS server that will be accessible from webpage by one click to 
any of RS's or Emoty's users. I hope I make it done in the near future (with devs support ;)).

Anyway, thanks for your contribution into RS development (maybe also Emoty? :)), especially help in spreading RS and writing docs in your language.

**Comment by gongzisun** [comment]
@kdebiec Emoty can be a pure F2F app, it can work well. you just need a ChatServer. I think the docs are also suitable to Emoty.
I want more people to use RS, but as the more time used, i feel pure F2F mode hindering RS's growth.
I want to say, all Devs, please focus on why i suggest this, not what the approach is.

**Comment by PhenomRetroShare** [comment]
Why don't use search engine?
Like it does with files.
So, when you get forum/channel link Rs search their posts list.
When you subscribe to a distant forum/channel, RS ask post list periodically and then ask for each post.
As each post get different Id, search could use it to find them.

**Comment by gongzisun** [comment]
It works only in a same network, what RS want be is a [Mesh Network](https://retroshare.readthedocs.io/en/latest/img/concept/retro_network.png), but what if the mesh network split? people in several separate groups, the information can't be transferred from group A to the others.  it could be happened.

**Comment by gongzisun** [comment]
If there is not the chatserver, we can't connect you forever, we will never get the RS nightly update, will never discuss in the forum, but we still can make our gruops, than several groups founded, but they can't get the others news,  information, files.

Although chatserver is here, i still think we shouldn't places hopes on the chatserver, not everyone can find it easily.

**Comment by gongzisun** [comment]
@PhenomRetroShare  What i know is a distant forum/channel not be subscribed by my friends connected drictly can't be founded, even i was in the same mesh network with the forum/channel owner. only the shareing file don't need be cached. even if keep it now, forum/channel can't work well, the turtle router just work for the file-sharing.

Anyway, i hope forum/channel/file be reachable even via several hops.

**Comment by gongzisun** [comment]
Nothing will change, just keep it down.
