### ISSUE TITLE
Are private messages reliable?

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#102]
Situation: me and another RetroShare user. We added eachother as friends and there was a connection between us. We initiated a private chat, through an identity in a chat lobby. I sent a couple of messages. Then I found that some of them were lost and did not reach the other side.

Note: I know that sometimes the private chat connection breaks and then automatically restores after a while. This was not the case for the above situation, the connection did not look broken on my side - the other side kept being shown as online while those private messages were lost.

**Comment by csoler** [comment]
There's a bug now that shows some users online although they are not (see for instance the turtle router statistics. No TR (tunnel requests) are relayed by these peers. I still need to investigate that.

Also, the messaging system (I mean the non distant one) does not check that messages have been delivered. We need to implement a small return receipt item/flag for that. It's on our todo list.
