### ISSUE TITLE
Segfault during account creation in -nogui

### ISSUE THREAD

**Issue by Ppjet6** [RetroShare/RetroShare#1024]
Using RetroShare 0.6.3 on Archlinux (aur/retroshare).

```
% rm -rf ~/.retroshare
% retroshare-nogui  
getRetroshareDataDirectory() unckecked: /usr/share/retroshare
RetroShare:: Successfully installed the SIGPIPE Block
Cannot hash executable! Plugins will not be loaded correctly.
defaultBaseDirectory() = /home/user/.retroshare
pubring file "/home/user/.retroshare/pgp/retroshare_public_keyring.gpg" not found. Creating a void keyring.
Pubring read successfully.
secring file "/home/user/.retroshare/pgp/retroshare_secret_keyring.gpg" not found. Creating a void keyring.
Secring read successfully.
  private trust database not found. No trust info loaded.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
****** Run State changed to "waiting_account_select"
****** Passwd state changed: want_passwd=0 key_name= prev_is_bad=0
Error: No Accounts. Use the Qt-GUI or the webinterface to create an account.

Type account number: 0
: invalid account number (should be between 0 and 18446744073709551615)

Type account number: 
[1]    3021 segmentation fault (core dumped)  retroshare-nogui
```

Maybe the program should just exit 1 with `Error: No Accounts. Use the Qt-GUI or the webinterface to create an account.` on stderr.

**Comment by myfingerhurt** [comment]
Try this,  I assume your Linux IP is 10.9.8.10. And don't type anything in your terminal
` retroshare-nogui  --webinterface 1025 --docroot /usr/share/retroshare/webui/`

 Instead, use iptables redirect zt0 to localhost  
`sudo sysctl -w net.ipv4.conf.zt0.route_localnet=1 `
`sudo iptables -t nat -A PREROUTING -d 10.9.8.10 -p tcp --dport 1025 -j DNAT --to-destination 127.0.0.1:1025`

Then open your browser `http://10.9.8.10:1025` create a new identity.

You can remove the port by
`sudo iptables -t nat -D PREROUTING -d 10.9.8.10 -p tcp --dport 1025 -j DNAT --to-destination 127.0.0.1:1025`

---------------------------------------------------------------
Or, you can do this if your Linux is not on a public domain.
` retroshare-nogui  --http-allow-all --webinterface 1025 --docroot /usr/share/retroshare/webui/`
Then open your browser `http://10.9.8.10:1025` create a new identity.

**Comment by G10h4ck** [comment]
Sure this is a bug, it should gracefully tell something to the user as you suggests instead of miserably segfault, a merge request to fix this is welcome
