### ISSUE TITLE
error for unable to locate packages

### ISSUE THREAD

**Issue by jeddah-liu** [RetroShare/RetroShare#1041]
When:
sudo apt-get install libglib2.0-dev libupnp-dev qt4-dev-tools \
    libqt4-dev libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev \
    libqt4-opengl-dev libqtmultimediakit1 qtmobility-dev libsqlcipher-dev \
    libspeex-dev libspeexdsp-dev libxslt1-dev libcurl4-openssl-dev \
    libopencv-dev tcl8.5 libmicrohttpd-dev
In:
Terminal of ubuntu 16.4 LTS
output:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libqtmultimediakit1
E: Unable to locate package qtmobility-dev

How should I do to fix it? 
issue form a ubuntu greenhand.

**Comment by felisucoibi** [comment]
I use this for ubuntu 16.04:
sudo apt-get install ibglib2.0-dev libupnp-dev libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev libspeex-dev libspeexdsp-dev libxslt1-dev cmake libcurl4-openssl-dev libopencv-dev tcl8.6 libsqlcipher-dev libmicrohttpd-dev libavcodec-dev qtmultimedia5-dev qttools5-dev libqt5x11extras5-dev qt5-default

**Comment by myfingerhurt** [comment]
Try this:

https://github.com/RetroShare/RetroShare/issues/905

**Comment by Nnabugw** [comment]
@felisucoibi 
Wow I was getting frustrated using ubuntu 16.04 too but your code worked and it was so freaking long I didn't have my hopes up but thanks a lot for solving this problem you are a good coder

**Comment by felisucoibi** [comment]
I'm happy to help, i'm not a coder just somebody that wants people to use rs i have a script for ubuntu 16.04 that makes verything for you https://github.com/felisucoibi/RetroBuild-Ubuntu-16.10-16.04
