### ISSUE TITLE
Error when trying to compile on Raspberry Pi 0 W with Raspbian

### ISSUE THREAD

**Issue by theAkito** [RetroShare/RetroShare#1048]
Tried to setup a server on my Raspi, following the instructions for installing the nogui version only. (GUI installation didn't work either.)
Note that I only use the CLI on my raspi.
uname -a outputs:
`Linux hostname 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux`

qmake outputs:
```
Project MESSAGE: ***retroshare.pri: Set Target and SDK to MacOS 10.11
Project WARNING: QMAKE: You have disabled deprecated warnings.
Project WARNING: QMAKE: You have disabled C preprocessor warnings.
```

make outputs:
```
collect2: error: ld terminated with signal 9 [Killed]
Makefile.retroshare-gui:1139: recipe for target 'retroshare' failed
make[1]: *** [retroshare] Error 1
make[1]: Leaving directory '/home/pi/Public/retroshare/trunk/RetroShare/retroshare-gui/src'
Makefile:135: recipe for target 'retroshare_gui-make_default' failed
make: *** [retroshare_gui-make_default] Error 2
```

make retroshare-nogui outputs:
```
make: Nothing to be done for 'retroshare-nogui'.
```

Annotation: Compilation with make  takes HOURS on this device, so please be careful, when proposing to compile it over and over to see if the error's gone.

**Comment by felisucoibi** [comment]
I just can say the qmake warnings are the same in any compilatin i have them also in ubuntu 16.04 but it works perfectly.

**Comment by theAkito** [comment]
@felisucoibi Are you sure? Is it always set to macOS? Also where is the exit status that shows me that everything went well? All this is very confusing. And as I said, it still won't work after ``make``.

**Comment by theAkito** [comment]
I updated the OP.

**Comment by theAkito** [comment]
I need help.

**Comment by theAkito** [comment]
So... that was really annoying. The documentation (readme) that explains the installation is WRONG. I had to correct the commands there. Now it works.
