### ISSUE TITLE
No package for Debian 9

### ISSUE THREAD

**Issue by Credomo** [RetroShare/RetroShare#1056]
Hello, 
When updated from Debian 8 to Debian 9, it's impossible to launch RS and update the Debian package. 
http://download.opensuse.org/repositories/home:/AsamK:/RetroShare/ only gives Debian 8 Packages.

**Comment by Credomo** [comment]
The only way to have RS works on Debian 9 (Stretch) as there is no repository available:

Get the package
` wget https://github.com/RetroShare/RetroShare/releases/download/v0.6.3/retroshare_0.6.3-1.20170806.3ae85dbc.stretch_amd64.deb`
Install it
`dpkg -i retroshare_0.6.3-1.20170806.3ae85dbc.stretch_amd64.deb`
Downgrade libsqlcipher0 from 3.2.0-2 to 3.2.0-1.1+b2
`wget http://snapshot.debian.org/archive/debian/20161011T120354Z/pool/main/s/sqlcipher/libsqlcipher0_3.2.0-1.1%2Bb2_amd64.deb`
`dpkg -i libsqlcipher0_3.2.0-1.1+b2_amd64.deb`
And launch RS
`retroshare`

Having a repository is so useful. Waiting to have one back
Have fun !

**Comment by magicvince** [comment]
Have also to install libmicrohttp12
`wget http://snapshot.debian.org/archive/debian/20170628T132042Z/pool/main/libm/libmicrohttpd/libmicrohttpd12_0.9.55-1_amd64.deb`
dpkg -i libmicrohttpd12_0.9.55-1_amd64.deb
then I could launch RS from terminal or startup menu

**Comment by magicvince** [comment]
Be carreful, for instance, upgrading libsqlcipher0_3.2.0-1.1+b2_amd64.deb may crash RS when starting

**Comment by ghost** [comment]
I did not test yet but seems that the bug is resolved and you just need to install via .deb

look last response on the bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850421

if the bug is fixed please update website http://retroshare.net/downloads.html

---

update:

I tried creating a fake/test identity:

in stable:

```
 $ retroshare
RetroShare:: Successfully installed the SIGPIPE Block
Cannot hash executable! Plugins will not be loaded correctly.
defaultBaseDirectory() = /home/masked/.retroshare
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read 0 trust packets.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
getAvailableAccounts() Skipping Invalid sized dir: extensions6
Rshare::Rshare waitForConnected to other instance.
Rshare::Rshare failed to connect to other instance.
(WW) Clearing PGP passphrase.
(WW) Caching PGP passphrase.
rsAccounts->PathKeyFile() : /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/keys/user_pk.pem
SSL Library Init!
SSL Verification Set
Inited SSL context: 
    Certificate: 61960b82265f5b47ab5819e914dc02a1
    cipher list: kEDH+HIGH:!DSS:!aNULL:!3DES:!EXP
    PFS enabled: YES
Creating Init File: /home/masked/.retroshare/default_cert_06.txt
	Id: 61960b82265f5b47ab5819e914dc02a1
AuthSSLimpl::InitAuth already initialized.
set the debugging to crashMode.
Detected Old Crash File: /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/retro.log
Copying to: /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/retro.log-save
Logging redirected to /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/retro.log
Switching To CrashLog Mode!
Checking For Directories
Load up Certificates, and Old Configuration (if present).
Load Configuration
setup classes / structures
Checking for DHT bootstrap file: /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/bdboot.txt
(EE) Cannot load filter file /home/masked/.retroshare/LOC06_61960b82265f5b47ab5819e914dc02a1/bdfilter.txt
bdNode::setNodeDhtMode(768), origFlags: 0
bdNode::setNodeDhtMode() newFlags: 768
p3BitDht::setRelayMode(17)
bdNode::setNodeDhtMode(4096), origFlags: 768
bdSpace::clean_node_flags(524288)
bdNode::setNodeDhtMode() newFlags: 4864
RsPluginManager::loadList(): 
   Reference executable hash: 0000000000000000000000000000000000000000
(II) Executable hash matches. Updating the list of accepted/rejected plugins.
Plugin directory : /usr/lib/retroshare/extensions6 does not exist.
Plugin directory : /home/masked/.retroshare/extensions6/ does not exist.
Examined a total of 0 plugins.
PluginManager: saving list.
  Saving current executable hash: 0000000000000000000000000000000000000000
Segmentation fault
```

after installing sqlcipher from unstable works

sudo apt install -t unstable sqlcipher


and how to install unstable? do apt pinning so you only get only some of the packages of unstable (you can do this to sqlcipher safely, or alternatively with testing)

/etc/apt/preferences.d/limit-unstable

```
Package: *
Pin: release a=unstable
Pin-Priority: 150
```

/etc/apt/sources.list.d/unstable.list

```
deb http://deb.debian.org/debian/ sid main
deb-src http://deb.debian.org/debian/ sid main
```

**Comment by meinportugal** [comment]
Hello! Please let me make some input.
I tried 2 different Debian-based distros (with an Openbox window manager) with a fresh install
both distros are based on Debian stratch
I tied to follow the procedure on and install deb from repo. Then I get the SegFault error.
I tried to git, make and make install (following the procedure here) with a fresh installed distro, and get the segafault again.

Is there something wrong with debian? I have no problems in ubuntu 14,16 and 18

How I have solved it.
Look upper in the comments:
https://github.com/RetroShare/RetroShare/issues/1056#issuecomment-335326856
The downgrading of the libsqlcipher0 from 3.2.0-2 to 3.2.0-1.1+b2 made it work.

**Comment by G10h4ck** [comment]
> Hello! Please let me make some input.
> I tried 2 different Debian-based distros (with an Openbox window manager) with a fresh install
> both distros are based on Debian stratch
> I tied to follow the procedure on and install deb from repo. Then I get the SegFault error.
> I tried to git, make and make install (following the procedure here) with a fresh installed distro, and get the segafault again.

When you talk about procedure you talk about the one described on the retroshare website?
http://retroshare.net/downloads.html#debian

**Comment by csoler** [comment]
just dont use libsqlcipher-3.2.0. Install v3.4.1 and it will just work.
Or... tell debian to ship a non buggy version of sqlcipher. The bug fix is a single line change. I never understood why they would not do it.

**Comment by meinportugal** [comment]
> > I tied to follow the procedure on and install deb from repo. Then I get the SegFault error.

> 
> When you talk about procedure you talk about the one described on the retroshare website?
> http://retroshare.net/downloads.html#debian

Yes, this one. On both clean installations they fail.

**Comment by meinportugal** [comment]
> just dont use libsqlcipher-3.2.0. Install v3.4.1 and it will just work.
> Or... tell debian to ship a non buggy version of sqlcipher. The bug fix is a single line change. I never understood why they would not do it.

May I kindly ask you please give an advice how to install v3.4.1 ?

I am runing
4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Comment by G10h4ck** [comment]
I have added the updated sqlcipher package into our debian 9 repository, if you do `apt update; apt upgrade` it should install the new version and fix the segfault, reopen the issue if you keep experiencing the problem please ;)

**Comment by meinportugal** [comment]
Thank you!
I am afraid to do it tonught, But when will do, come back if anything goes
wrong :)

чт, 18 окт. 2018 г. в 21:35, G10h4ck <notifications@github.com>:
