### ISSUE TITLE
windows retroshare crash

### ISSUE THREAD

**Issue by assasinfil** [RetroShare/RetroShare#1059]
An exception has been thrown at 0x00000000019DE660 in retroshare.exe: 0xC0000005: Access violation for reading at 0x0000000000000170.
debug
00000000019DE660 invalid octal number

**Comment by assasinfil** [comment]
I fixed this by running from the admin

**Comment by felisucoibi** [comment]
Hi they need more information to be able to track this bug.

**Comment by assasinfil** [comment]
I fixed this by re-creating the certificate. Apparently the certificate is damaged

**Comment by assasinfil** [comment]
I fixed this by re-creating the certificate. Apparently the certificate is damaged

**Comment by felisucoibi** [comment]
Please close it
