### ISSUE TITLE
Website without HTTPS!!!

### ISSUE THREAD

**Issue by NourEddineX** [RetroShare/RetroShare#1095]
You should either use the .github.io domain or just move to another host and use HTTPS..  
How a secure comminucation app team uses a non-encrypted website
if someone is under a [MITM attack](https://en.wikipedia.org/wiki/Man-in-the-middle_attack), he may be redirected to another website, to a phishing. the attacker may change the github link to another malicious one..
If you don't know how to do it.. you can contact me and I will help.  
But please stop expose people to danger.
Thank you.

**Comment by PhenomRetroShare** [comment]
Fixed???

**Comment by blaueente** [comment]
no. see also https://github.com/RetroShare/retroshare.github.io/issues/33

**Comment by Hxs2fJKjYZ** [comment]
I live in China and have been subjected to MITM before, would appreciate HTTPS..

**Comment by G10h4ck** [comment]
https://retroshare.cc is the official site now

**Comment by alfinal** [comment]
So, please, make a 301 redirect from retroshare.net to retroshare.cc and other issues described in #1545. Currently this is pretty confused because if you search retroshare in some search engines from some places you get retroshare.net upper than retroshare.cc and is true that it has not a valid certificate.

**Comment by G10h4ck** [comment]
Sadly we don't have control over the web server and the domain, we only have control over the repository from with the html files are pulled in

**Comment by G10h4ck** [comment]
Sadly we don't have control over the web server and the domain, we only have control over the repository from with the html files are pulled in

**Comment by alfinal** [comment]
I want to help. Who has the control? I see in ```whois``` that the domain was updated just last November so I suppose that somebody still maintain it last 5 years and has some interest. No public contact provided. It use officials gandy DNS servers pointing to github IP. Is other way to change it.

**Comment by G10h4ck** [comment]
retroshare.net is controlled by @cavebeat which is very difficult to contact with since around one year (at some point. retroshare.org is controlled by @drbob which is as difficult as @cavebeat to contact with, about retroshare.us I have no idea.

**Comment by G10h4ck** [comment]
let's keep talking on the other issue https://github.com/RetroShare/RetroShare/issues/1545
