### ISSUE TITLE
Forums broken in 0.6.RC2

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#112]
I'm not getting forum updates for about two weeks. Maybe it's related to this https://github.com/RetroShare/RetroShare/issues/99

Occasionally - I think it happened not more than two or three times during past two weeks - I randomly got a few messages in subscribed forums.

I did some manual intervention and removed the gxs directory from inside the node profile. After logging into the network and subscribing to a forum I was not subscribed before - I've got posts. After switching back to existing gxs directory and subscribing to the same forum - I've got no posts.

RetroShare does a very bad job at reporting what's broken, so I have no idea how to fix this. retro.log contains cryptic messages and I have no idea what to look for there, to find out if something might be related to the problem.

**Comment by csoler** [comment]
Something was probably broken in time stamps for updating messages. Is that still occurring?

**Comment by csoler** [comment]
I'm thinking that this might be the same bug caused by posts of large size. We need to add a hard-coded size limit in the interface of p3GxsForums so as to prevent posting attempts that exceed the maximum item size.
