### ISSUE TITLE
Please sign your commits/releases, provide hash verification of binaries

### ISSUE THREAD

**Issue by aral** [RetroShare/RetroShare#1165]
Since (at least the Mac version) doesn’t run in a sandbox, please sign your commits and tags for releases and provide a means of verifying the binary’s hash.

Thank you for making and sharing RetroShare (sitting in your talk in Brussels as I write) :)

**Comment by aral** [comment]
Just saw the checksums.asc.txt file. Please disregard the bit about signature verification. Would still be nice to sign the commits/releases in git though :)

**Comment by G10h4ck** [comment]
Thank you for the suggestion I have enabled signature by default on my local RS repository, hope other devs do the same ;)

The command I have used are this two:
git config user.signingkey 370AA0F3DA9F0F0BB29B56F8A1FBCA3872E87051
git config commit.gpgsign true

Cheers!
