### ISSUE TITLE
Usage of retroshare-nogui

### ISSUE THREAD

**Issue by theAkito** [RetroShare/RetroShare#1167]
How can retroshare-nogui configure shared directories and set permissions for them?

**Comment by G10h4ck** [comment]
You cannot, the workaround was to cnfigure with retroshare-gui and then run retroshare-nogui.

As of today retroshare-nogui have been obsoleted by retroshare-service that can be configured through JSON API so I suggest you to take a look at it instead.

**Comment by theAkito** [comment]
> 
> 
> You cannot, the workaround was to cnfigure with retroshare-gui and then run retroshare-nogui.
> 
> As of today retroshare-nogui have been obsoleted by retroshare-service that can be configured through JSON API so I suggest you to take a look at it instead.

I guess, I'll have to take a look at that. Is there extensive, up-to-date documentation on using the service?

**Comment by G10h4ck** [comment]
this exaplains how to learn to use  JSON API https://github.com/RetroShare/RetroShare/blob/master/jsonapi-generator/README.adoc
