### ISSUE TITLE
[Security Feature Request] Blank out the node name providing the Tunnel files

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1173]
The Upcoming Retroshare 0.6.4 release should have a security option added which blanks out the Tunnel via users nodename openly displayed to unknown remote peers as they download a file here on Retroshare. Optionally presenting and showing only Tunnel via temporary-number-string.

**Comment by ASmith-** [comment]
The issue and need is crystal clear. If a Retroshare user selects the Anonymous Only shared flag on a directory the files in that directory should only be shared Anonymously, not showing the source's node name providing those files in multiple areas in the unknown distant peers Files Downloads windows.

**Comment by felisucoibi** [comment]
I like the information of the tunnels, because this info is not secret and is good to know to wich network goes the file, usefull to know wich friends use your rs or not. To hide don't makes a difference in anonimity because the info is there.

**Comment by felisucoibi** [comment]
RS is F2F and know wich friendo is doing the bridge is part of the protocol, if u need more anonimity dont use rs, is not P2P

**Comment by ASmith-** [comment]
There are two Retroshare share file flags that directly conflict with what you wrote. The Anonymous Flag and the Browser-able Flag. 

1) If only the Anonymous Flag is set then the user clearly doesn't want any information regarding their node being listed as the source of the files being shared listed multiple times downstream to unknown users.

2) If the Browser-able Flag is Not Set then the Retroshare user clearly doesn't want anyone seeing they are the source of the files being shared, certainly not splashed downstream in a peers download window.

Solution
If the Anonymous Shared Flag is set then the tunnel should not include that node name as sharing those files.

If the Browser-able Flag is not set then the tunnel should not include that node name as sharing those files.

If anyone wishes to have their node-name splashed downstream then they can simply set the Browser-able Flag to all friends nodes, or only friends nodes.

**Comment by felisucoibi** [comment]
You are not hiding anything just making it a little more complicate to find... Is not secure to hide things and think u r secure
