### ISSUE TITLE
rs 0.6.4 crash in windows 

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1217]
I hope other users report it, i will get more info from this user, but it ends crashing...

**Comment by felisucoibi** [comment]
![screenshot_20180324-205213](https://user-images.githubusercontent.com/1285303/37868371-53944a8c-2fa5-11e8-9304-539b80080885.png)

**Comment by G10h4ck** [comment]
0.6.4 have been obsoleted by RetroShare 0.6.5

**Comment by felisucoibi** [comment]
well the bug is even in 0.6.5 in 32 bits builds when accesing big filelists, that's why asked to not use 32 bits builds in official website, now only 64 bits offered?
