### ISSUE TITLE
Feature Request add a simple Mumble Option to Public,Private Chat room options

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1220]
**Feature Request add a simple Mumble Option to Public,Private Retroshare Chat room options**

Add a simple additional Option for Retroshare users creating a Public or Private Retroshare Chat Room which simply places a Mumble icon which is visible to users which alerts users that are Mumble Voice over Internet capable that specific chatroom also has a Mumble server channel tied in as well.

Place these Mumble selected icons into the Retroshare icons in the app to pull from, all the added coding need do is add a text option to alert chat room visitors amd users that a mumble server channel is active and available for that specific Retroshare chatroom and post the Mumble icon in that chat room and listing.

Mumble Icons
![mumble svg](https://user-images.githubusercontent.com/8520894/38022010-3d0494b2-3233-11e8-98f2-27b8c4161b4c.png)
![mumble_icon](https://user-images.githubusercontent.com/8520894/38022011-3d25ab20-3233-11e8-8f71-8a863d50aac8.png)
![mumble-mic](https://user-images.githubusercontent.com/8520894/38022012-3d44d2ca-3233-11e8-9cd2-b92a3415f148.png)
![mumble_teamspeak](https://user-images.githubusercontent.com/8520894/38022015-3d60afea-3233-11e8-80d2-754c895498e0.png)

**Comment by RedEagleBox** [comment]
that  would greatly enhance RS experience ..

**Comment by G10h4ck** [comment]
VOIP plugin is currently unmaintained
