### ISSUE TITLE
TCP socket not listening

### ISSUE THREAD

**Issue by sanyanet2** [RetroShare/RetroShare#1237]
Hi, this issue is still happen https://github.com/RetroShare/RetroShare/issues/170

**Comment by G10h4ck** [comment]
I wasn't able to reproduce this bug with current RetroShare

**Comment by sanyanet2** [comment]
Can't use retroshare because of this. it simply only accept connections on 127.0.0.1
while the incoming connections are coming to 192.0.0.1  
it should be the same socket, but it does not work

Does someone know how to configure port fowarding for incoming connections from 192.0.0.1:80 to 127.0.0.1:80 on iptables?

**Comment by sehraf** [comment]
Are you running a hidden node? because hidden nodes are (for some unknown reason of the devs) restricted to 127.0.0.1.
You can use [this](https://unix.stackexchange.com/questions/293304/using-netcat-for-port-forwarding)
