### ISSUE TITLE
Potential buffer overrun in RetroShare/libretroshare/src/util/extaddrfinder.cc.

### ISSUE THREAD

**Issue by textbrowser** [RetroShare/RetroShare#124]
request is defined as char[1024]. A wild host name will overrun the buffer. Please consider using snprintf() or QByteArray.

(It appears that the function is assuming that gethostbyname() will guard against lengthy host names. On FreeBSD, I modified an entry in /etc/hosts to contain 1055 characters. A ping correctly located the entry and executed the query.)

```
    sprintf( request, 
            "GET / HTTP/1.0\r\n"
            "Host: %s:%d\r\n"
            "Connection: Close\r\n"
            "\r\n", 
            server_name.c_str(), 80);
```

**Comment by csoler** [comment]
well done! I fixed it. Thx.
