### ISSUE TITLE
Make a simple example of something with json api and javascript or other simple language

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1247]
Make a simple example of something with jsop api and javascript or other simple language, so we can copy the idea to make a web gui easily starting with the example,

**Comment by zeners** [comment]
Have you take a look at libresapi/src/webui-src/app ?
The webui is a simple website build with javascript

**Comment by felisucoibi** [comment]
Yes i did and this is not a "simple example" is just a whole project. And not sure is using json api.

**Comment by zeners** [comment]
i'll take a look to make it running standalone ... 
meantime you can look at retroshare.js, wich handles request/response with app as a server: rs.request (starting retroshare.js:211) makes a single request against the api, 
used e.g. in addpeer.js with peers/examine_cert (line 42) or peers (line 83)

**Comment by felisucoibi** [comment]
Thanks, the idea of this, is that somebody reading the rs docs, or asking somebody can have a working supersimple example of for example, asking list of friends, this example explains hot to initialize, how co connect, and receive the answer. This is very useful for somebody that starts with rs api to know how it works, and step by step make this example bigger to handle other things... also for the future in this asme example page can have different api commands to retreive information so this new dev can play with different data. Is more simple than create a big docuement, just a working example, and a small list of things this new dev can play with.

**Comment by sehraf** [comment]
I once started with a python chat bot using the json/web API. It wasn't working reliable and i lost interest in it. Anyway here is it (not guaranteeing anything :wink: )
https://gist.github.com/sehraf/5ba761c21ed4d29caefe1e81da2a55a3

**Comment by hunbernd** [comment]
Currently it can list friends' keys who were active in the last month, and from a specific user group.
Everything you need is in the RetroShareApi folder.
https://github.com/hunbernd/RSKeyExchange.net

**Comment by G10h4ck** [comment]
new JSON API readme explain how to learn it, this is much better then the old libresapi which is deprecated at this point https://github.com/RetroShare/RetroShare/blob/master/jsonapi-generator/README.adoc
