### ISSUE TITLE
Debian Stretch Segfault

### ISSUE THREAD

**Issue by shellster** [RetroShare/RetroShare#1256]
Both the gui and the nogui editions segfault in Debian stretch.  On the gui edition, you can walk through the entire setup, but after that, the "initial run" segfaults.

**Comment by csoler** [comment]
yes. This is because of sqlcipher-3.2.0. You should install sqlcipher-3.4.1, and Retroshare will work just fine. Apparently Debian has forgotten to fix this error. There's nothing we can do about it ourselves.

**Comment by shellster** [comment]
Thank you for the tip.  I have confirmed that I could just grab the libsqlcipher0 deb package from "buster" repo and after installing that, everything works.  As you can see from the following link, stretch should be the last distro affected as everything else uses a compatible version: https://packages.debian.org/search?keywords=libsqlcipher0

It would be nice if either the deb package or the documentation listed this requirement and/or a note on the website.
