### ISSUE TITLE
[Feature Request] Add Automation Options for .rscollection and .torrent files

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1257]
Feature Request: Add Automation Options for .rscollection and .torrent files

Retroshare could really use and benefit from optional automation on handling .rscollection and .torrent downloaded files from the Retroshare file sharing network.

Feature Request
A option to automatically download a .rscollection file's contents.

A option to automatically download the .rscollection file contents from any .rscollection file placed in a user specified directory.

A option to place any .torrent files downloaded from the Retroshare file sharing network to a user specified directory. (Where a torrent client would automatically then see that sitting in that folder and begin automatically downloading it).

**Comment by felisucoibi** [comment]
About torrent, is the torrent software who has to do it, and in fact it does, transmission you can set up to read a specified directory searching for torrent files, so not necessary anything from RS.

**Comment by ASmith-** [comment]
Perhaps you didn't understand what I was asking for with automation abilitys felisucoibi. Yes a torrent client can be easily setup to automatically process any tiny .torrent file downloaded to a specific directory. What I am asking for in Retroshare is to optionally have a default directory for any *.torrent downloaded file and the users torrent client application would automatically begin downloading the main Torrent file.

In regards to automation on the tiny .rscollection files, currently its a two step process. A retroshare user first downloads the tiny .rscollection file. Then mouse-clicks on that completed tiny file, selects from the mouse drop down menu to Download the rscollection files referenced by that tiny file. What I am asking for is a Retroshare user option to automatically process any tiny .rscollection file downloaded making this a single step process.

**Comment by felisucoibi** [comment]
Hi smith, i only refered to .torrent files, the .rscollection i agree with you, and i think there is already a PR for that by phenom.
