### ISSUE TITLE
upnphandler::background_setup_upnp()

### ISSUE THREAD

**Issue by textbrowser** [RetroShare/RetroShare#126]
Please inspect the result of pthread_create(). The function will return zero on success. On failure, you should delete the data object. There may be other similar instances throughout your source.

```
if(pthread_create(&tid, 0, &doSetupUPnP, (void *) data) == 0)
   pthread_detach(tid); /* so memory is reclaimed in linux */
else
   delete data;

// Return false or true?
```

**Comment by csoler** [comment]
fixed. thx.
