### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by TrallinX** [RetroShare/RetroShare#1283]
When i build retroshare i got compilation error
arch linux x64
gcc version 8.1.1 
`g++ -c -pipe -Wno-deprecated -Wno-deprecated-declarations -Wno-cpp -Wall -D_FILE_OFFSET_BITS=64 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -std=gnu++11 -Wall -W -DHAS_GNOME_KEYRING -DRS_ENABLE_GXS -DENABLE_WEBUI -DRS_AUTOLOGIN -DRS_NO_WARN_DEPRECATED -DRS_NO_WARN_CPP -DRS_GXS_TRANS -DRS_USE_BITDHT -DPLUGIN_DIR="\"/usr/lib/retroshare/extensions6\"" -DDATA_DIR="\"/usr/share/retroshare\"" -DRS_USE_LIBUPNP -DSQLITE_HAS_CODEC -DGXS_ENABLE_SYNC_MSGS -I. -I. -I../../libbitdht/src -I../../openpgpsdk/src -isystem /usr/include/gnome-keyring-1 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/upnp -I/usr/lib/qt/mkspecs/linux-g++ -o temp/linux-g++/obj/p3grouter.o grouter/p3grouter.cc
In file included from /usr/include/c++/8.1.1/map:60,
                 from ./rsitems/rsconfigitems.h:29,
                 from grouter/p3grouter.cc:189:
/usr/include/c++/8.1.1/bits/stl_tree.h: In instantiation of ‘class std::_Rb_tree<t_RsGenericIdType<16, false, 1>, t_RsGenericIdType<16, false, 1>, std::_Identity<t_RsGenericIdType<16, false, 1> >, RsGRouterTransactionChunkItem*, std::allocator<t_RsGenericIdType<16, false, 1> > >’:
/usr/include/c++/8.1.1/bits/stl_set.h:133:17:   required from ‘class std::set<t_RsGenericIdType<16, false, 1>, RsGRouterTransactionChunkItem*>’
grouter/p3grouter.cc:543:65:   required from here
/usr/include/c++/8.1.1/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.libretroshare:6539: temp/linux-g++/obj/p3grouter.o] Error 1
make[1]: Leaving directory '/home/trallinx/.cache/pacaur/retroshare/src/RetroShare-0.6.4/libretroshare/src'
make: *** [Makefile:101: sub-libretroshare-src-libretroshare-pro-make_first] Error 2
`

**Comment by G10h4ck** [comment]
Thanks for reporting, this seems happening only with GCC 8

**Comment by besendorf** [comment]
Is there any news on this? It makes RetroShare not usable on ArchLinux. The AppImage also isnt working for me. See #1295

**Comment by G10h4ck** [comment]
doesn't the precompiled package availabe here work http://retroshare.net/downloads.html#archlinux ?

Or do you refer to compiling the git version by yourself?

I don't have GCC 8 installed so I haven't been hable to investigate the problem, pull requests from someone having GCC 8 are welcome

**Comment by besendorf** [comment]
This seems to be fixed for the retroshare-git package / the current git repo when you compile it.

**Comment by G10h4ck** [comment]
AFAIK this is a GCC 8 bug or at least gentoo developers think so https://bugs.gentoo.org/664296
