### ISSUE TITLE
AppImage error when starting

### ISSUE THREAD

**Issue by besendorf** [RetroShare/RetroShare#1295]
Hi Im having issues trying to start the RetroShare AppImages. I tried the Tor version and the regular one. Below is stdout:

[user@device Downloads]$ ./RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage 
/tmp/.mount_RetroSSkr1t6/usr/bin/retroshare: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
[user@device Downloads]$ ./RetroShare-Tor.AppImage 
RetroShare:: Successfully installed the SIGPIPE Block
Hashed main executable: 373800a62f18bc0ef7edd30cced18853500837ea
defaultBaseDirectory() = /home/user/.retroshare
pubring file "/home/user/.retroshare/pgp/retroshare_public_keyring.gpg" not found. Creating a void keyring.
Pubring read successfully.
secring file "/home/user/.retroshare/pgp/retroshare_secret_keyring.gpg" not found. Creating a void keyring.
Secring read successfully.
  private trust database not found. No trust info loaded.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: eglfs, kms, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.

- Reinstalling did not fix it

**Comment by G10h4ck** [comment]
Appimage doesn't embed all libraries just the ones that appimage developers thinks are not common to their set of supported distro, it looks to me you miss some library on your system and from the error message i would say it's something like libxcb screensaver or similar

**Comment by tulsileathers** [comment]
@G10h4ck I'm seeing this on Arch. I have libxcb installed.

**Comment by G10h4ck** [comment]
Please report it to appimage developers @probonopd which may give better answhere and eventually fix it ;)

**Comment by probonopd** [comment]
Please run

```
LD_DEBUG=libs ./RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage
```

and watch for errors or maybe upload the log to a text file attachment here. Thanks.

**Comment by tulsileathers** [comment]
seems to be a problem with libfontconfig 
```
      8930:	/usr/lib/libfontconfig.so.1: error: symbol lookup error: undefined symbol: FT_Done_MM_Var (fatal)
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: eglfs, kms, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
[1]    8930 abort (core dumped)  LD_DEBUG=libs ./RetroShare-Tor-0.6.4.20180313.0e6d27ad-x86_64.AppImage
```

perhaps libfontconfig is being bundled and shouldn't be? see here https://phabricator.kde.org/D16893

**Comment by probonopd** [comment]
Please try:

```
# Download the RetroShare AppImage and extract its contents
wget https://github.com/RetroShare/RetroShare/releases/download/v0.6.4/RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage
chmod +x RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage
./RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage --appimage-extract

# Get some helper functions (we will use them to delete blacklisted libraries from the extracted AppImage) 
wget https://raw.githubusercontent.com/AppImage/pkg2appimage/master/functions.sh
. functions.sh

# Remove the blacklisted libraries from the extracted AppImage
cd squashfs-root/
delete_blacklisted 

# See if it runs now
./AppRun 
```
Does it run? If this fixes it, then the AppImage is bundling libraries (such as libfontconfig) which should not be bundled.

**Comment by G10h4ck** [comment]
I close this bug because of lack of feedback from the reporter
