### ISSUE TITLE
VOIP Call causes Retroshare to crash

### ISSUE THREAD

**Issue by geekyjoyce72** [RetroShare/RetroShare#1305]
Hello! A friend and I are testing Retroshare.

When I try to call him with the VOIP plugin though, his Retroshare application crashes. He is using Windows 7.

Here's the information provided during the crash:

Problem signature:
  Problem Event Name: APPCRASH
  Application Name: retroshare.exe
  Application Version: 0.6.4.0
  Application Timestamp: 5aa6dcd1
  Fault Module Name: VOIP.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp: 5aa6dd4f
  Exception Code: c0000005
  Exception Offset: 0001543f
  OS Version: 6.1.7601.2.1.0.256.1
  Locale ID: 1036
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by hunbernd** [comment]
Currently all plugins crash on Windows.
There is a patch that fixes it, so maybe they will work again soon.

Related issue: https://github.com/RetroShare/RetroShare/issues/750

**Comment by G10h4ck** [comment]
VOIP plugin is not maintained ATM
