### ISSUE TITLE
forum threads are blank

### ISSUE THREAD

**Issue by sdtqwe4ty** [RetroShare/RetroShare#1308]
Windows 10 Home Version 1803 OS Build:17134.165

Using the "Tor only" version of retroshare

forum posts don't appear. I can see threads with all their titles but none of the content appears.

**Comment by csoler** [comment]
By "threads" you mean the threads into a particular forum with message titles in the top right view of forums? Or do you mean the list at left that actually corresponds to individual forums?

In the former case, if you select a message title in the top right view, the message should show up in the bottom right view. If not, that is obviously a bug (very weird that such an obvious bug hasn't been seen nor reported before, but who knows...)

in the later case, it probably means that you're connected to nodes that do not hold any recent messages (less than 1 month old) in these forums, so you dont sync them. By default, RS only syncs the last month of posts. You may try to change that (right click on a forum name and select sync period -> 6 months for instance and wait for 2-3 mins).

**Comment by sdtqwe4ty** [comment]
I accidentally clicked the minus button
