### ISSUE TITLE
Trying TCP: IPv4=127.0.0.1:9050

### ISSUE THREAD

**Issue by SIX10** [RetroShare/RetroShare#1309]
Hi, whenever I try and connect to a friend by adding his certificate, it gives me this and nothing else.

**Comment by csoler** [comment]
It looks like by the IP that is used, that your friend is using a Tor hidden node. If you're using a regular Retroshare node, just install Tor on your computer and it will be able to also connect to hidden nodes using Tor Socks proxy on localhost:9050 without extra configuration.

**Comment by SIX10** [comment]
I do have Tor, should I start it up or does Retroshare automatically do that?

**Comment by csoler** [comment]
when you run a normal RS node (as opposed to a hidden node), RS should find Tor without configuration (it needs to be running of course). RS won't start it for you so you need to start it yourself.
