### ISSUE TITLE
Bug: nickname tab completion does not work in global Network -> Broadcast chat

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#131]
RetroShare version 0.6.RC2

**Comment by dimqua** [comment]
@defnax, why is this closed?

**Comment by defnax** [comment]
this is not a bug, it was never planned for BroadCast.

**Comment by cavebeat** [comment]
broadcast should also work with signed GXS-ID only like described here https://github.com/RetroShare/RetroShare/issues/95
this includes tab completion too.
