### ISSUE TITLE
I can't compile latest releases UPDATED....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1312]
NEW: ERROR

x-g++/obj/RSTextBrowser.o gui/common/RSTextBrowser.cpp
Mensajes del ensamblador:
Error fatal: no se puede crear temp/linux-g++/obj/RSTextBrowser.o: Permiso denegado
Makefile.retroshare-gui:18804: recipe for target 'temp/linux-g++/obj/RSTextBrowser.o' failed
make[1]: *** [temp/linux-g++/obj/RSTextBrowser.o] Error 2
make[1]: se sale del directorio '/home/felisuco/retroshare/master/retroshare-gui/src'
Makefile:151: recipe for target 'retroshare_gui-make_first' failed
make: *** [retroshare_gui-make_first] Error 2

OLD ERRORS:

error1:
rsserver/rsinit.cc: In static member function ‘static bool RsInit::RsClearAutoLogin()’:
rsserver/rsinit.cc:660:19: error: ‘getSelectedAccountId’ is not a member of ‘RsAccounts’
  if (!RsAccounts::getSelectedAccountId(preferredId))
                   ^~~~~~~~~~~~~~~~~~~~

error2:
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/libresapi/src'
make[1]: *** No hay ninguna regla para construir el objetivo '/home/felisuco/retroshare/master/libretroshare/src/lib/libretroshare.a', necesario para 'lib/libresapi.a'.  Alto.
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libresapi/src'
Makefile:137: recipe for target 'sub-libresapi-src-libresapi-pro-install_subtargets' failed
make: *** [sub-libresapi-src-libresapi-pro-install_subtargets] Error 2

**Comment by felisucoibi** [comment]
fter latest cyril pr seems continue and new errors appear, things with file permissions?

rm -f lib/libresapi.a
ar cqs lib/libresapi.a ApiServerMHD.o ApiServer.o json.o JsonStream.o ResourceRouter.o PeersHandler.o Operators.o IdentityHandler.o ForumHandler.o ServiceControlHandler.o StateTokenServer.o GxsResponseTask.o FileSearchHandler.o TransfersHandler.o RsControlModule.o GetPluginInterfaces.o ChatHandler.o LivereloadHandler.o TmpBlobStore.o ContentTypes.o ApiPluginHandler.o ChannelsHandler.o StatsHandler.o FileSharingHandler.o
ar: lib/libresapi.a: Permiso denegado
Makefile.libresapi:239: recipe for target 'lib/libresapi.a' failed

**Comment by felisucoibi** [comment]
Handler.cpp
rm -f lib/libresapi.a
rm: no se puede borrar 'lib/libresapi.a': Permiso denegado
Makefile.libresapi:239: recipe for target 'lib/libresapi.a' failed
make[1]: [lib/libresapi.a] Error 1 (no tiene efecto)
ar cqs lib/libresapi.a ApiServerMHD.o ApiServer.o json.o JsonStream.o ResourceRouter.o PeersHandler.o Operators.o IdentityHandler.o ForumHandler.o ServiceControlHandler.o StateTokenServer.o GxsResponseTask.o FileSearchHandler.o TransfersHandler.o RsControlModule.o GetPluginInterfaces.o ChatHandler.o LivereloadHandler.o TmpBlobStore.o ContentTypes.o ApiPluginHandler.o ChannelsHandler.o StatsHandler.o FileSharingHandler.o
ar: no se puede crear el fichero temporal mientras se escribe el archivo: No hay más ficheros archivados
Makefile.libresapi:239: recipe for target 'lib/libresapi.a' failed
make[1]: *** [lib/libresapi.a] Error 1
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libresapi/src'
Makefile:125: recipe for target 'sub-libresapi-src-libresapi-pro-make_first' failed
make: *** [sub-libresapi-src-libresapi-pro-make_first] Error 2
[sudo] contraseña para felisuco:

**Comment by felisucoibi** [comment]
new errors....

x-g++/obj/RSTextBrowser.o gui/common/RSTextBrowser.cpp
Mensajes del ensamblador:
Error fatal: no se puede crear temp/linux-g++/obj/RSTextBrowser.o: Permiso denegado
Makefile.retroshare-gui:18804: recipe for target 'temp/linux-g++/obj/RSTextBrowser.o' failed
make[1]: *** [temp/linux-g++/obj/RSTextBrowser.o] Error 2
make[1]: se sale del directorio '/home/felisuco/retroshare/master/retroshare-gui/src'
Makefile:151: recipe for target 'retroshare_gui-make_first' failed
make: *** [retroshare_gui-make_first] Error 2

**Comment by csoler** [comment]
permission problems usually mean that you tried to compile as root, or as an different users. As a result it cannot erase old .o that dont belong to the current user.

**Comment by felisucoibi** [comment]
looks like, thanks
