### ISSUE TITLE
Similar project: Briar

### ISSUE THREAD

**Issue by MMurzik** [RetroShare/RetroShare#1322]
There's another project similar to RetroShare. It is called Briar (briarproject.org) and it is targeted primarly for Android phones, while RetroShare is for desktop. Is it possible to make this two great projects to contribute to each other to make Briar and RetroShare interoperable?
Similar e-mail was sent to Briar devs

**Comment by csoler** [comment]
Briar and RS are complimentary in many aspects. Reading Briar's future plans on their webpage it seems to me that they would have a real advantage in using RS's GXS system for distributing generic data. This system has been documented in a technnical report and a presentation at FOSSDEM.
Personnally I'm totally open to discussing any collaboration between the two projects.

**Comment by felisucoibi** [comment]
Tested for one day, the pitty you need to be next to the guy you want to add as a friend.
In the other side the have the servicies:
FORUM - we have but needs rework
CHATS - we have but need rework
BLOGS - somethinw we need, to be able to have websites blog, or any other kind using same tech.
GROUPS - we have kind of private gorups inside private chats, also needs lot of work
All these should be inside rs soon...
and we also have
CHANNELS - they are very usabe now
LINKS - needs som work but can be usefull in the future.
MAIL

Also the bluetooth sinc y like it, could be nice to sinc with somebody without internet just with bluetooth
And also the ap wifi could be usefull with rs, to start a wifi hotspot and sync forums, channels etc without internet.
RS already works on lans.

**Comment by zapek** [comment]
I wonder how's the battery usage with Briar. Mobile devices don't like having to manage multiple connections that prevent the device going to sleep for large slices of time (this is also valid for the Android version of Retroshare).
