### ISSUE TITLE
Build RS fails in Mac OSX(10.13.6): cannot initialize a member subobject of type 'TransferInfo *' with an rvalue of type 'long'

### ISSUE THREAD

**Issue by xn-zhao** [RetroShare/RetroShare#1324]
Hi all,
I tried to build RS on Mac (with xCode 9.4, Mac version 10.13.6, Qt 5.9 ) with instruction (https://github.com/RetroShare/RetroShare/blob/master/MacOS_X_InstallGuide.md)
Tried to fix all other errors when building, but at the end the error occurs mostly in memory file with this content:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2051: error: cannot initialize a member subobject of type 'TransferInfo *' with an rvalue of type 'long'
      : __value_(_VSTD::forward<_Up>(__u)){};
        ^        ~~~~~~~~~~~~~~~~~~~~~~~~

Any helps? 
Thank you.

**Comment by PhenomRetroShare** [comment]
Hello,
did you have problems with #include <unordered_map> ?

**Comment by unsenep2pdev** [comment]
Here is Mac OSX fixes
https://github.com/unsenep2pdev/RetroShare/commit/15b887f4dadd23765da6e96291bbbfe2a73dc755 <https://github.com/unsenep2pdev/RetroShare/commit/15b887f4dadd23765da6e96291bbbfe2a73dc755>
https://github.com/unsenep2pdev/RetroShare/commit/e8287a2e8b8117557b8f470d08a6368550126d58 <https://github.com/unsenep2pdev/RetroShare/commit/e8287a2e8b8117557b8f470d08a6368550126d58>

You can check this version of source to run your build.

**Comment by unsenep2pdev** [comment]
Fixing DHT boot configuration on Mac OSX.
https://github.com/unsenep2pdev/RetroShare/commit/9096a927e297de8cc80968b6189da36da1f9214c <https://github.com/unsenep2pdev/RetroShare/commit/9096a927e297de8cc80968b6189da36da1f9214c>

**Comment by PhenomRetroShare** [comment]
This doesn't fix MacOS 10.13 compil:
https://travis-ci.org/PhenomRetroShare/RetroShare/jobs/434952534

**Comment by unsenep2pdev** [comment]
Travis build need to upgrade. So I don’t have to test Travis build. However, Here is my Local environment setup. You might need to upgrade a bunch version of dependencies.

Retroshare.prix File

message(***retroshare.pri:MacOSX)
        ## 11 Sep 2018 - meiyousixin - use config in one MacOS comp
        #BIN_DIR += "/usr/bin"
        #INC_DIR += "/usr/include"
        #INC_DIR += "/usr/local/include"
        #INC_DIR += "/opt/local/include"
        #LIB_DIR += "/usr/local/lib"
        #LIB_DIR += "/opt/local/lib"
        BIN_DIR += "/Applications/Xcode.app/Contents/Developer/usr/bin"
        INC_DIR += "/usr/local/opt/openssl/include"
        INC_DIR += "/usr/local/Cellar/miniupnpc/2.1/include"
        INC_DIR += "/usr/local/Cellar/libmicrohttpd/0.9.59/include"
        INC_DIR += "/usr/local/Cellar/sqlcipher/3.4.2/include"
        LIB_DIR += "/usr/local/Cellar/miniupnpc/2.1/lib"
        LIB_DIR += "/usr/local/opt/openssl/lib/"
        LIB_DIR += "/usr/local/Cellar/libmicrohttpd/0.9.59/lib"
        LIB_DIR += "/usr/local/Cellar/sqlcipher/3.4.2/lib"
        INCLUDEPATH *= "/usr/local/opt/openssl/include"
        CONFIG += c++11
        RS_UPNP_LIB = miniupnpc



If your libraries are older than this, you might hit that error. I’ve testd default environment of Mac OSX 10.13, and got exact problem like your. Mostly related to clang++ vs Linux Compiler.

Cheers!

**Comment by G10h4ck** [comment]
should be fixed now
