### ISSUE TITLE
Missing dependency on Debian 9 Buster (Testing): libgnome-keyring-dev

### ISSUE THREAD

**Issue by jeromecc** [RetroShare/RetroShare#1360]
Hello!
libgnome-keyring-dev & libgnome-keyring packages have been removed from Debian 9 Buster (Testing) because they are deprecated.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359

Upstream & Debian recommands libsecret instead.

    As announced, we are working to remove libgnome-keyring from Debian. The libgnome-keyring library is deprecated and its usage is strongly discouraged. Please update your application to use libsecret instead. Such a port should ideally happen with upstream being involved.

I check sources on Open Suse build platform. It is still depending on libgnome-keyring-dev so the build will probably fail for the next release of Restroshare unless it transitions to libsecret.

Thanks for the great work to all contributors!
Have a nice day.

**Comment by sehraf** [comment]
RS already uses libsecret when available (when compiling) so only the dependencies must be updated.

**Comment by G10h4ck** [comment]
also it depends on those things only if autologin is explicitly enabled at compile time, the build recipe should be update, also in general we are really in need of help for Debian packaging

**Comment by G10h4ck** [comment]
Now OBS builds unstable version for Debian Testing too
