### ISSUE TITLE
after latests updates rs selfcloses after a few minutes....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1365]
after latests updates rs selfcloses after a few minutes.... i' not sure wich pr caused this, probabaly the ones of the last two days but rs is closing itself after a few minutes, does anybody eslse havving this issue?

**Comment by csoler** [comment]
caused by some crash? What's the console output?

**Comment by felisucoibi** [comment]
I'm testing, i made the bug just in case more people affected, testing. I'll update with more info if there is a error log.

**Comment by felisucoibi** [comment]
it just happened again with latest build, i just started r, and in the gui i web to my files... it selfclosed,.

**Comment by csoler** [comment]
If you could send a callstack to were this happens, it could be useful!

**Comment by felisucoibi** [comment]
I know cyril, and i'm so sorry i didint, i'm just first trying to see the normal log to see if there is any error message btu when i start from command line is not crashing by now, or i did not catch it.
