### ISSUE TITLE
filelist is not sent to my friends since a few days ago....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1369]
filelist is not sent to my friends since a few days ago.... some people reported same problem inside rs.

**Comment by ASmith-** [comment]
I haven't seen any feedback whatsoever on this serious bug that I pointed out in the Retroshare Devels signed chat lobby yesterday and also in the Retroshare BUG signed forum. Rolling back to Oct. 6th build instantly returns the use of the previously shared file indexed list. retroshare_0.6.4-1.20181006.586cff2a-gui-bionic_amd64

The newest commit appears to force any Retroshare user into a total shared files re-hash, this without any heads up whatsoever indicating yet another serious lapse in informing Retroshare users, especially those of us with larger Retroshare shared files trying to breath life into the Retroshare shared files network before 'doing'. 
retroshare_0.6.4-1.20181010.18eee374-gui-bionic_amd64

The unknown which hasn't even been answered is 

"After a Retroshare user running the newest Retroshare Build initiates a total Retroshare shared files re-hash on their shared files merely to use the Retroshare Application, is the resulting re-hashed shared file list then able to be shared, seen, used by remote peers running older Retroshare builds"?

**Comment by felisucoibi** [comment]
My problem is no t a total rehash, is just the file list is not updated, but hashed, and not shared with my friend since one or two week ago, maybe more, the My files says is not been updated sins 50 days ago.

**Comment by felisucoibi** [comment]
I will try to delete the file list file inside my rs install.

**Comment by ASmith-** [comment]
My shares entirely vanished, nothing shown as shared at all, down from over 20 TB minutes earlier on the Oct 10th build, retroshare_0.6.4-1.20181010.18eee374-gui-bionic_amd64 . I returned to the Oct. 7th build retroshare_0.6.4-1.20181006.586cff2a-gui-bionic_amd64 and everything immediately returned back to normal. Given this is very abnormal, I was hesitant to rehash all of my shared files in a desperate attempt to make the RS build with the last commit on Oct. 10th operate.

**Comment by felisucoibi** [comment]
I deleted the file with the directory hicherachy , rs redid it after restart, and seems it worked, obviously this is not a normal user solution because is dangerous, anyway stil i have to check that people can receieve filelist.
