### ISSUE TITLE
API coding style problem through an example

### ISSUE THREAD

**Issue by pedro-nonfree** [RetroShare/RetroShare#1427]
We are using two methods

- [/rsPeers/acceptInvite](https://github.com/RetroShare/RetroShare/search?q=acceptInvite&unscoped_q=acceptInvite)
- [/rsPeers/GetRetroshareInvite](https://github.com/RetroShare/RetroShare/search?p=2&q=getretroshareinvite&unscoped_q=getretroshareinvite)

What is the appropriate [camel case](https://en.wikipedia.org/wiki/Camel_case): upper camel case,  lower camel case, or both (what justificates both?)

**Comment by G10h4ck** [comment]
the appropriate style is plain camel case like /rsPeers/acceptInvite but we do not accept changes only to change style, so when new function are created, or important changes that would break retro-compatibility anyway we usually enforce the style too
