### ISSUE TITLE
Problems installing on ubuntu 18.10

### ISSUE THREAD

**Issue by Hxs2fJKjYZ** [RetroShare/RetroShare#1429]
Trying to install on Ubuntu 18.10 and get the following errors:
E: The repository 'http://ppa.launchpad.net/retroshare/unstable/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

This happens with both stable and unstable repositories.

**Comment by stokito** [comment]
+1 also it says that Release list file is missing. Please recheck

**Comment by G10h4ck** [comment]
Please try using the OBS repository, instead of Cyril personal PPA (you will need to remove it before adding the OBS repo), http://retroshare.cc/downloads.html#ubuntu

**Comment by stokito** [comment]
Today I installed the new version without problems, thank you
