### ISSUE TITLE
Android App stuck on Unlocking Location

### ISSUE THREAD

**Issue by Charadon** [RetroShare/RetroShare#1436]
After connecting the android phone to my main node, if I chat with anyone and then restart the app, the app will be permanently stuck on Unlocking Locations. If you stick around long enough, eventually a notification pops up saying "Login Needed". Only workaround is to remove the app, and re-do the entire process. Not like it will matter, as if I talk to anyone this happens again.

**Comment by G10h4ck** [comment]
The qml android app is still based on the old libresapi which is unreliable for login related stuff :(
Porting it to the new JSON API would fix this

**Comment by Charadon** [comment]
Well, a good alternative I've found to the android app right now, is using something like zero-tier to connect the phone and computer to a virtual LAN and using the web interface on the phone. Works pretty well. May seem off-topic, but if someone comes across this issue, now they know how to use it on the go.

**Comment by G10h4ck** [comment]
nice trick!
