### ISSUE TITLE
Create account on Windows failed with PEM_read_X509 in OpenSSL 1.1

### ISSUE THREAD

**Issue by xn-zhao** [RetroShare/RetroShare#1437]

**Comment by xn-zhao** [comment]
HI all, 
I tried to build and run Retroshare on current master branch and get error when creating account on Windows (both in Windows 32bit and 64 bit).
When trying to debug, i found the PEM_read_X509 always return NULL in the function:


int	LoadCheckX509(const char *cert_file, RsPgpId& issuerName, std::string &location, RsPeerId &userId)
...
FILE *tmpfp = RsDirUtil::rs_fopen(cert_file, "r");
	if (tmpfp == NULL)
	{
#ifdef AUTHSSL_DEBUG
		std::cerr << "sslroot::LoadCheckAndGetX509Name()";
		std::cerr << " Failed to open Certificate File:" << cert_file;
		std::cerr << std::endl;
#endif
		return 0;
	}

	// get xPGP certificate.
	X509 *x509 = PEM_read_X509(tmpfp, NULL, NULL, NULL); //here: x509 always return NULL
	fclose(tmpfp);

of file sslfns.cc (libretroshare/lib/pqi/sslfns.cc)

I tried many method (related to PEM_read_X509) to overcome this bug but not succeed.
Any help for this thing.
Thank you.

**Comment by G10h4ck** [comment]
Are you still able to reproduce this bug? It is probably due to some change in newer openssl
