### ISSUE TITLE
VOIP plugin fails to compile on Arch Linux

### ISSUE THREAD

**Issue by Charadon** [RetroShare/RetroShare#1439]
The error is
"Project ERROR: opencv development package not found"

I have confirmed I have opencv installed, and I even installed the 32-bit version of opencv from the AUR to no avail.

**Comment by Charadon** [comment]
Okay, so I got passed that issue by changing the line in VOIP.pro from:
PKGCONFIG += opencv
To:
PKGCONFIG += opencv4
However, another issue has arisen. Now I get this error:
/usr/bin/uic gui/AudioInputConfig.ui -o ui_AudioInputConfig.h
make: *** No rule to make target 'AudioStats.h', needed by 'ui_AudioStats.h'.  Stop.

**Comment by Charadon** [comment]
So, I fixed that by cutting the file AudioStats.h to the root directory where you compile. HOWEVER afterwards I got ANOTHER error saying how it couldn't find "opencv4/cv.h"
I fixed this by pointing it to opencv4/opencv2/cvconfig.h

However now I'm getting yet ANOTHER error. 
Full output here:
[videoprocessorerror.txt](https://github.com/RetroShare/RetroShare/files/2706272/videoprocessorerror.txt)

**Comment by Charadon** [comment]
I finally managed to get it compiled.
First I had to edit QVideoDevice.cpp because of the error: "opencv/cv.h not found" to fix this, I changed the lines:
```
#include <opencv/cv.h>
#include <opencv/highgui.h>
```
To:
```
#include <opencv4/opencv2/cvconfig.h>
#include <opencv4/opencv2/highgui/highgui_c.h>
```

Afterwards it still failed to compile, but atleast that error was gone. Next I had to add AV_ to the the following in VideoProcessor.cpp
```
Line 476: CODEC_CAP_TRUNCATED >>>>> AV_CODEC_CAP_TRUNCATED
Line 477: CODEC_FLAG_TRUNCATED >>>>> AV_CODEC_FLAG_TRUNCATED
Line 478: CODEC_FLAG_PSNR >>>>> AV_CODEC_FLAG_PSNR
Line 479: CODEC_CAP_PARAM_CHANGE >>>>> AV_CODEC_CAP_PARAM_CHANGE
Line 572: CODEC_CAP_TRUNCATED >>>>> AV_CODEC_CAP_TRUNCATED 
Line 573: CODEC_FLAG_TRUNCATED >>>>> AV_CODEC_FLAG_TRUNCATED
Line 575: CODEC_FLAG2_CHUNKS >>>>> AV_CODEC_FLAG2_CHUNKS
```
Unforunately, even after compiling it, there is a loading problem and so the plugin doesn't work.
This might be because they get rejected by retroshare:
```
2a0b24f179aaea83a154bf20d70502277d793700 : REJECTED
d14049c8ef00347aa36650cf36533281d0001282 : REJECTED

```
I'm pretty sure this can be worked around by enabling "Authorize all plugins" but that option is blanked out for me.

Edit: After deleting Plugins.cfg, the plugins got accepted. However the loading problem still persists.

**Comment by Charadon** [comment]
Compiling the VOIP plugin from 6.4 official branch leads to this error at startup when the plugin is enabled:
```
#0  0x00007ffff5732d7f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff571d672 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5775878 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff57758aa in __libc_fatal () at /usr/lib/libc.so.6
#4  0x00007ffff5c01a99 in  () at /usr/lib/libpthread.so.0
#5  0x00007ffff5c01bd4 in _Unwind_ForcedUnwind () at /usr/lib/libpthread.so.0
#6  0x00007ffff5bffcd5 in __pthread_unwind () at /usr/lib/libpthread.so.0
#7  0x00007ffff5bf7d19 in  () at /usr/lib/libpthread.so.0
#8  0x0000555556af4c4a in bdThread::stop() (this=0x555557bd49e0)
    at util/bdthreads.cc:163
#9  0x0000555556ac2d0c in UdpLayer::recv_loop() (this=0x555557bd49e0)
    at udp/udplayer.cc:273
#10 0x0000555556ac2be0 in UdpLayer::run() (this=0x555557bd49e0)
    at udp/udplayer.cc:237
#11 0x0000555556af4b05 in bdthread_init(void*) (p=0x555557bd49e0)
    at util/bdthreads.cc:52
#12 0x00007ffff5bf6a9d in start_thread () at /usr/lib/libpthread.so.0
#13 0x00007ffff57f6b23 in clone () at /usr/lib/libc.so.6

```

**Comment by Charadon** [comment]
Okay, I finally got the VOIP plugin (atleast the config part right now, can't test to see if it works proper) after downloading retroshare 0.6.4 from the official repository (the opensuse one). Now if it actually works, this will be the end of my journey.

**Comment by csoler** [comment]
the plugin needs the exact same version of the software to run it. Otherwise you corrupt the stack and get random errors everywhere (like here in the UDP, which is totally unrelated).
VOIP however is really experimental. We need someone skilled enough to get rid of speex and use libav instead and make the compression better. If you're a developper you're welcome to help.

**Comment by Charadon** [comment]
Unfortunately, i'm not a developer. Just a guy who can understand the errors. However, now that I got it to compile. (Albeit with lots of trickery) maybe the issue should be marked as solved?

**Comment by csoler** [comment]
certainly. Thx!
