### ISSUE TITLE
After last PR i can see how a banned user unban itself in forums :D kind of crappy and scary...

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1447]
After last PR i can see how a banned user unban itself in forums :D kind of crappy and scary...

I just mark it as banned, and adfter a few seconds it get un banned again￼ scary, isn't it?

**Comment by valleyboy7** [comment]
Am I banned? Why?

**Comment by felisucoibi** [comment]
Fixed i hope.
