### ISSUE TITLE
[ QML/QT ]New Developers wanted to continue on Emoty 

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#1467]
Emoty is intended to be a modern social network with emphasis on simplicity, freedom and safety. It is based on top of RetroShare.

Its very simple and it would be nice some intrested devs can continoue on Emoty?
Its written in Qt/Qml. Konrad the dev of Emoty has no time on his great project.
It would be a nice skype alternative when it can be continued.

What it missed there is like Voice & Video Chat
https://github.com/Emotyco/Emoty-Desktop

**Comment by felisucoibi** [comment]
First thing to do is to be able to build it for example in ubuntu 18.10, a step by step to do it. Also the same for windows.
