### ISSUE TITLE
RS 0.6.5 Segmentation fault build

### ISSUE THREAD

**Issue by SergeyDjam** [RetroShare/RetroShare#1479]
ROSA Fresh R8.1 x86_64
RS v0.6.5 
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib64

%global optflags %{optflags} -std=c++11
%qmake_qt5 "CONFIG-=debug" "CONFIG+=release" "CONFIG+=retroshare_plugins"  \
            "TARGET+=%{name}" "QMAKE_TARGET+=%{name}" \
            PREFIX=%{_prefix} LIB_DIR=%{_libdir} \
            DATA_DIR=%{_datadir}/%{name} INC_DIR=%{_includedir}/%{name} \
            RetroShare.pro

`usr/include/qt5/QtCore -Itemp/moc -I/usr/lib64/qt5/mkspecs/linux-g++-64 -o temp/linux-g++-64/obj/ServicePermissionDialog.o gui/ServicePermissionDialog.cpp
In file included from ./gui/feeds/FeedHolder.h:27:0,
                 from gui/NewsFeed.h:26,
                 from gui/FriendsDialog.cpp:35:
../../libretroshare/src/retroshare/rsgxschannels.h:67:44: internal compiler error: Segmentation fault
  RsGxsChannelPost() : mCount(0), mSize(0) {}
                                            ^
`

**Comment by G10h4ck** [comment]
seems a compiler bug, which compiler and version are you using?
This line ´%global optflags %{optflags} -std=c++11´ should not be needed, instead you should enable C++11 in qmake command line with ´CONFIG+=c++11´

Also if you are packaging it you may find useful to take a look at 
https://github.com/RetroShare/RetroShare/tree/master/build_scripts/OBS/network:retroshare

**Comment by SergeyDjam** [comment]
@G10h4ck Thank you. But it did not help. Only all off plugin build helpers

**Comment by G10h4ck** [comment]
yeahplugins are not receiving love ATM so better disable them
