### ISSUE TITLE
Cmd + M does not minimize RetroShare 0.6.5 on macOS 10.14.3

### ISSUE THREAD

**Issue by ddobrev** [RetroShare/RetroShare#1482]
The reason is that its Mac menu lacks the relevant menu item.

**Comment by G10h4ck** [comment]
Please try installing RetroShare through this brew.sh Formula and check if you experience the same problem https://github.com/Homebrew/homebrew-core/pull/40970

**Comment by defnax** [comment]
done https://github.com/RetroShare/RetroShare/pull/2810/commits/79977a0c3731048e85499f63959343e50fa25df2 @G10h4ck  close

**Comment by G10h4ck** [comment]
Thanks @defnax
