### ISSUE TITLE
a new dependency needed, just to update docs.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1497]
Now seems is necessary doxygen

In ubuntu s simple as sudo apt install doxygen

But maybe some docs needs update.

**Comment by G10h4ck** [comment]
yeah doxygen is needed only at compile time to generate the JSON API, it is not needed if JSON API is not enbled

**Comment by felisucoibi** [comment]
sudo apt-get install ibglib2.0-dev libupnp-dev libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev libspeex-dev libspeexdsp-dev libxslt1-dev cmake libcurl4-openssl-dev libopencv-dev tcl8.6 libsqlcipher-dev libmicrohttpd-dev libavcodec-dev qtmultimedia5-dev qttools5-dev libqt5x11extras5-dev qt5-default doxygen miniupnpc libminiupnpc-dev
