### ISSUE TITLE
Github Desktop client checkout not more possible 

### ISSUE THREAD

**Issue by defnax2k** [RetroShare/RetroShare#1499]
hi,
since today update my local sources not possible, i deleted my other repository to test if checkout works with new clean clone but it doesnt helps same errors.

![image](https://user-images.githubusercontent.com/47180527/54770656-fb863400-4c03-11e9-9b2b-e96bfd1c6d14.png)

seems the problem comes from this changes @G10h4ck ?
https://github.com/RetroShare/RetroShare/commit/6bb7711e033ae7ba7fd43ab9e88ce5969abbb0ea

**Comment by hunbernd** [comment]
@G10h4ck created a folder called network:retroshare in this commit https://github.com/RetroShare/RetroShare/commit/3f2a1d52c2d3e4fb63671d68b8cf851fb088b26e.

This folder name is not allowed on Windows and causes problems for all git clients except the one shipped with msys2.

The workaround is:
- Clone the repo using msys2 command line. Or you can use the msysgit command line, but it is not perfect.
Every other mayor git clients will fail.
- Enable sparse checkout:
`git config core.sparseCheckout true`
- Create this file: .git/info/sparse-checkout
- Add this:
`*`
`!**/network:retroshare/**`
- Remove the files in networkretroshare folder created by the git client, so git won't show them as new files at every commit.
It will remove every other uncommitted files too, so save your work before doing this!
`git read-tree -u --reset HEAD`
- Use whatever you want, it should work now.

**Comment by defnax2k** [comment]
i dont want use msys2 with command line i like it very much with Github desktop i hope @G10h4ck  fix that issue soon.

**Comment by defnax** [comment]
i hope @G10h4ck can remove that from git and use a userfriendly naming for windows users, clone/ checkout is now broken. 
and cant create more a pr.
bad that i updated to latest master 😢
