### ISSUE TITLE
Retroshare-service-git forums api doesn't work

### ISSUE THREAD

**Issue by selankon** [RetroShare/RetroShare#1500]
Hi,

I installed retroshare-service-git package who expose the retroshare JSON API under libretroshare. 

After log in I try to get the forums references using:
```bash
ACCOUNT="account"; PASSWORD="pass"
curl -d '{ "account":"'$ACCOUNT'","password":"'$PASSWORD'" }' http://127.0.0.1:9092/rsLoginHelper/attemptLogin #Here it login successful
curl -u "$ACCOUNT:$PASSWORD"  http://127.0.0.1:9092/rsGxsForums/getForumsSummaries
```

It returns nothing. 

I use this curl calls to other endpoints successfully. The related code for this calls are on: https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/retroshare/rsgxsforums.h#L136 . 

My version of retroshare-service-git appears to be:
```bash
➜ apt-cache policy retroshare-service-git 
retroshare-service-git:
  Installed: 0.6.9999
```

Maybe I'm not using the correct version?

**Comment by G10h4ck** [comment]
Hi!
Could you add the `-v` option to `curl` to see which error happens?
If it is it 404 the build might be older then the commit i which the forum API has been exposed, also you can usually query more details about the version with the API call `/jsonApiServer/version`

**Comment by selankon** [comment]
Hi,
In other computer works correctly... If I look at apt policy it returns:
```
➜ apt-cache policy retroshare-service-git                                            
retroshare-service-git:
  Installed: 0.6.9999
```

And in the other computer I tried to update retroshare-service-git via basic `apt update && apt install retroshare-service-git`. I will look deeply the cause of the error.
