### ISSUE TITLE
Merging with torrent protocol?

### ISSUE THREAD

**Issue by POMATu** [RetroShare/RetroShare#1503]
Hi,

Retroshare is wonderful app. But it's really not possible to make it popular for now. Torrents do a great job and people don't wan't to use RetroShare.

I wonder if that's possible somehow to merge that with torrent protocol and torrent trackers infrastructure. If that's possible I think the network will grow really fast and we get them both to the new future.

Torrent is really bad at file duplication and centralization, I really love that RetroShare searches for individual files hashes.

I'm just philosophizing and wondering if that's possible and can help.

**Comment by csoler** [comment]
You should consider using Tribler which does what bittorrent does with onion routing.

**Comment by POMATu** [comment]
But still hashing whole folder instead of every file is too redundant.

I have no problems using torrents at my location, no need for tor, I just have problems with lack of seeds when I download. If only torrent had per-file hashing like retroshare has it would be much easier to find a peer.

**Comment by felisucoibi** [comment]
I think inside rs you can find any file you want using the search option. Is much better than bitorrent.

**Comment by POMATu** [comment]
Hmm, so look what's the problem (as example).
Yesterday I wasn't able to get english dubbed torrent from nyaa, there was no peers. I think it may gone forever however there are a lot of downloads for that torrent so I think maybe somebody still has it.

So I wonder if it's possible to search for that filenames in retroshare network. I know I may have no success it's just some kind of research.

So in this case what I need?
1) Retroshare with much contacts inside so network get's active
2) Search by filenames (that are usually pretty unique in torrent names)
3) Or maybe I can even extract hashes for every file from the torrent? Can I then search network using that hashes?

Am I right?

doing that research is really interesting for me so I can better understand how it works

**Comment by felisucoibi** [comment]
when you search you search in friends file lists and friend f friends file lists and friend of friend file lists, this give you enough peers if you have enough friends to find almost anything inside rs network.... if you need nyaa files and the file name contains nyaa try on retroshare. (you should have friends)

**Comment by POMATu** [comment]
then how to get friends on rs? Is there anywhere a board where people are sharing keys with each other?

Nobody in my surroundings uses rs and I even tried to invite them to rs with low success.

I guess I need 50 friends or around that so rs network will work

**Comment by felisucoibi** [comment]
just with 10 will, search for retroshare chatserver on google

**Comment by POMATu** [comment]
thx I'll try that

**Comment by POMATu** [comment]
Hi, so I have added myself to that group I have a lot of friends in roster now.

I also shared my downloads folder that is kinda huge.

But I still cannot search anything. I am trying to search "name contains mkv". I guess I should find any video file at least.

I also see the graph that I am separate from the others and get linked to others only though chatserver.

Am I missing something?

**Comment by csoler** [comment]
the Chat servers usually do not relay anything else than chat and forums. If you want to use file transfer (including search) you need to make friends with other people and connect to them.

**Comment by POMATu** [comment]
How can I do that actually?

So I should PM them and exchange keys?

**Comment by csoler** [comment]
See if there's a forum for exchanging keys, subscribe to it and post your key, and grab keys from that forum too.

**Comment by POMATu** [comment]
I see empty forum for exchanging keys? Should I post a key in new thread and just wait?

**Comment by POMATu** [comment]
finally I see threads

**Comment by POMATu** [comment]
awesome search is working now, thanks
