### ISSUE TITLE
Manual Check Files re-scan to push a update on a Retroshare virtually shared folder is not working properly.

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1515]
Manual Check Files re-scan to push a update on a Retroshare virtually shared folder is not working properly.

I updated 15 Retroshare shared folders moving several thousand files in several of them from one folder to another sub-folder. Several hours later the changes were not reflected at all in the local Virtual Retroshare shared files listings.

24hrs later, those changes still were not updated.

I rebooted the Regular Retroshare node, a new build whose title page states
RetroShare 0.6.5-58-g431fbf412 running on a Linux Ubuntu Bionix LTS 64bit system.

The manual selection of Files -- My FIles -- Check Directory had previously immediately or within seconds resulted in a re-scan on the highlighted folder.

It appears some developer has gotten into that vital area and it is no longer functioning. It is vital for Retroshare to properly update shared files in the shared folders and this lapse and sudden coded bug in what had been functioning correctly is a serious problem now.

**Comment by csoler** [comment]
what are the various options in preferences->files in the node that doesn't work?
In particular, look for "Auto-check shared directories every...", and the time that comes after.

**Comment by ASmith-** [comment]
Thanks csoler, the Retroshare file sorting algorithm used is not the same as the Linux kernel file sorting. Retroshare on a Linux distro is listing the following in my BLUES-SINGLES folder
BLUES-SINGLES-1-1000 (1,000 files)
BLUES-SINGLES-10001-11000 (1 file)
BLUES-SINGLES-1001-2000 (744 files)

The Linux local distro kernel lists the following
BLUES-SINGLES-1-1000 (1,000 files)
BLUES-SINGLES-1001-2000 (744 files)
BLUES-SINGLES-2001-3000 (1 file)
on down to BLUES-SINGLES-10001-11000 (1 file)

A rookie miscue on my part, I had primed the formerly empty sub-folders with a single file to allow further use of the local counting coding instead of banging up against zero. I've seen this sorting and listing issue in other applications, it would seem while the end result is sorted files being listed, the manner of how they are sorted and the resulting output is sometimes not similar.
