### ISSUE TITLE
Distant chat improvements

### ISSUE THREAD

**Issue by hunbernd** [RetroShare/RetroShare#152]
Show the distant peer's GXS-ID on the chat dialog. Currently if the other peer uses some meaningless name like "Anonymous", it is impossible to determine who is the sender.

Also the chat dialog allows one to send messages while the other peer offline, and the messages will be delivered later. The distant chat dialog lacks of this feature and disables sending if there is no active tunnel. Please, port the offline chat feature into distant chat.

**Comment by csoler** [comment]
Right. We also need to add a re-send of messages that got dropped in the middle. That can be handled at the tunnel level.
