### ISSUE TITLE
Please keep supporting Windows XP

### ISSUE THREAD

**Issue by palikacska** [RetroShare/RetroShare#1525]
Today I installed RetroShare 0.6.5 downloaded from official site retroshare.cc and got the following error.

![image](https://user-images.githubusercontent.com/19628069/56093240-407d4d80-5ec6-11e9-8af0-6802838c09db.png)

It means that the latest RetroShare binaries were compiled against a higher version of Windows API than what is present on XP. This would be just a configuration option for GCC. At least 16 million (more than the users of all desktop Linux combined) people are still using Windows XP.

Please fix compatibility in the next release.

**Comment by hunbernd** [comment]
The problem is that Qt dropped XP support.
It is likely that this error comes from QT and not directly from RetroShare.

You can try to build it with Qt 5.6.

**Comment by Kcchouette** [comment]
Bad idea, as even security update are not available on Windows XP (so retroshare will be used on a malware-owned PC...)

**Comment by palikacska** [comment]
@Kcchouette 
Lack of security updates don't automatically mean that a system is infected by malware. There are a lot more malware on devices still receiving security updates, e.g. Windows 7/10 PCs or Android phones. If you really stick to your point of veiw, it will tell stories only about one sad fact: Your brain has been successfully washed by Microsoft-sponsored tech-media that try to chase everyone into buying the reinvented wheel, new computers with new operating systems for the very same purpose.

If someone has the privacy and security awareness that makes him install RetroShare (it's not very popular among average users), he will definitely also have the technical experience to keep malwares far from his system, even on an XP machine without security updates. I'm still using Windows XP and have never been infected by malware, virus, ransomware, etc.

Please support Windows XP. It's the last Windows version that is free of telemetry and other anti-privacy features. Even Windows 7 was patched to have telemetry and phone home to Microsoft.
