### ISSUE TITLE
option for receive Distant Chat/Messages from Signed Identities/Contacts/Everyone/No one

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#153]
i think we need a feature, to not allow optional to set my security level.
Not allow to send from Anonymous Identities, a option for Distant Chat and Distant Messages.

On Messages there is a Settings.
- Accept encrypted distant messages from everyone

we need this:
- Accept Distant Messages from Everyone
- Accept Distant Messages from Signed Persons
- Accept Distant Messages from Contacts/Favorites
- Accept Distant Messages from No one

**Comment by csoler** [comment]
use a combo box then: no-one / anonymous identities / etc

**Comment by defnax** [comment]
i think we need a option for both Distant Chat/Messages
- Accept Distant Messages from Everyone
- Accept Distant Messages from Signed Persons
- Accept Distant Messages from Contacts/Favorites
- Accept Distant Messages from No one
