### ISSUE TITLE
Enhancement: Add public property to node sertificate PLEASE!!!

### ISSUE THREAD

**Issue by deltaone** [RetroShare/RetroShare#1530]
If node certificate marked as public - they automatically spread out trough network.
If node certificate marked as private - they work as usual.

PLEASE give CHOICE to your users !!!!

P.S. Current manual certificate exchange is big ass pain ;(

**Comment by csoler** [comment]
Just disable "Discovery" in preferences->network, and your public cert will not be sent to friends of friends.

We're currently working on a simpler certificate exchange rule, but the one we have now ensure 100% security. You have to know that whatever we do, security will always come first.

**Comment by deltaone** [comment]
"Discovery" not matter ...
Every node keep own list certificates of two types - public and private (current case).
When another node connect - they exchange (synchronize) public certificate lists. Private cert's exchanged as usually - by hands.

In endpoint (earlier/later) all nodes in network have same list of public certificates.

Simple, easy, secure.

**Comment by csoler** [comment]
Private PGP keys are *never* exchanged.
I don't think that all nodes in the network should have all PGP public keys of all other nodes. It is sufficient that your friends have your public PGP key. Friends of your friends may get it if discovery is enabled, but it's not needed for connecting.

**Comment by deltaone** [comment]
In my case "public" - certificate needed for connecting ...
