### ISSUE TITLE
Howto: Build Retroshare 0.6.5 on Debian Testing/Unstable - traversing libupnp,libssl,libcrypto and openssl issues

### ISSUE THREAD

**Issue by topcat** [RetroShare/RetroShare#1533]
First a thank you to the RS community for helping me build RS 0.6.5 on my Debian Testing and Unstable setups. For the sake of others having trouble compiling RS 0.6.5, below is a short note on how I managed to traverse various issues with libupnp, libssl, libcrypto and openssl.

- The config options that worked for me are :

qmake CONFIG+=debug CONFIG+=rs_jsonapi CONFIG+=no_sqlcipher RS_UPNP_LIB=miniupnpc

- The above took care of compile errors due to libupnp 1.8 and also some OpenSSL related linking errors.

-  I have multiple versions of libssl and libcrypto installed, however from my understanding versions 1.1 of each seems to be what RS 0.6.5 needs. Therefore, I ended up editing both the following Makefiles with the below library directives : 

a) /retroshare-gui/src/Makefile.retroshare-gui 
b) /retroshare-nogui/src/Makefile.retroshare-nogui 

Replace -lssl and -lcrypto under LIBS= with -l:libssl.so.1.1 -l:libcrypto.so.1.1

- Thereafter I had a successful build of RS, however I had the following errors with my certificate while trying to start RS : 

<snip>

Issues With Private Key! - Doesn't match your Cert
Check your input key/certificate:

...

main() - Fatal Error.....
Invalid Certificate configuration!

</snip>

The above issue and the solutions have been discussed under Issue #1354 (https://github.com/RetroShare/RetroShare/issues/1354)

I use the workaround suggested above wherein I export OPENSSL_CONF="" and then start retroshare, this resolves the certificate error and starts RS :)

Hope this helps :)

**Comment by G10h4ck** [comment]
Take care that if your precious RetroShare version/build used sqlcipher the build without sqlcipher will not be able to access your GXS,identity,channel,forum etc.

**Comment by G10h4ck** [comment]
The opposite is true too, right now an sqlcipher enabled build is not able to read GXS data from an sqlcipher disabled build (this last case could be fixed in the code probably without much effort)

**Comment by topcat** [comment]
Yes Gio I can confirm that my 0.6.5 build is not able to see the identity I had created in 0.6.3. So while RS 0.6.5 starts up it is unusable for me as I can't access my forums, etc. I will try to see if I can get 0.6.5 working with sqlcipher enabled and report back.

**Comment by chelovechishko** [comment]
To uncrypt sqlcipher database copy ssl password from stdout and execute in terminal emulator:
``` cpp
diff --git a/libretroshare/src/rsserver/rsloginhandler.cc b/libretroshare/src/rsserver/rsloginhandler.cc
index f94c7115b..b17ce5f19 100644
--- a/libretroshare/src/rsserver/rsloginhandler.cc
+++ b/libretroshare/src/rsserver/rsloginhandler.cc
@@ -70,6 +70,7 @@ bool RsLoginHandler::getSSLPasswdFromGPGFile(const RsPeerId& ssl_id,std::string&
 	if ( AuthGPG::getAuthGPG()->decryptTextFromFile( plain, getSSLPasswdFileName(ssl_id)) )
 	{
 		sslPassword = plain;
+		std::cout << "SHIT ssl_1 = " << sslPassword << std::endl;
 #ifdef DEBUG_RSLOGINHANDLER
 		if(sslPassword.length() > 0)
 			std::cerr << "Decrypting went ok !" << std::endl;
```

``` sh
sqlcipher
.open "_db";
PRAGMA key = "SHIT ssl_1";
ATTACH DATABASE '_db_plain' AS plaintext KEY '';
SELECT sqlcipher_export('plaintext');
DETACH DATABASE plaintext;
.quit
```

**Comment by topcat** [comment]
ok so I was able to build RS 0.6.5 with sqlcipher and now I am able to see the same Identity, Forums, Channels, etc as on my 0.6.3 build :)

The only change to the steps I had put up initially is that I used to below config options : 

qmake CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc

The rest of the steps I followed remain unchanged to what I posted earlier.

Hope this helps someone :)
