### ISSUE TITLE
after a fresh clone of the rs repository i must delete manuallly a directory....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1543]
I need to:
rm -r /home/$user/retroshare/master/supportlibs/restbed

after a fresh git clone....

**Comment by sehraf** [comment]
Same here.

**Comment by G10h4ck** [comment]
Can you paste what compile option are you using and error log?

**Comment by felisucoibi** [comment]
Did you fixed it? Why close it if Not? Rs has Like 4 real betatester, 2 of them says the problem exists, dont close it.

To reproduce it, as i said in first post, Under Ubuntu Any version, Just make a clean install of the source code And compile it, you will see Lot of things to Fix, Like this bug, i using the script to build rs from my user in github btw Ill updste it Today to show also the necessary libs etc

**Comment by G10h4ck** [comment]
I have tried to reproduce and couldn't, also didn't got more information here, can you paste the error you get on the console please?

**Comment by felisucoibi** [comment]
you can use this script.  You can see btw the necessary libs to build on ubuntu 19.04, 
https://github.com/felisucoibi/RetroBuild-Ubuntu-18.10-18.04-19.04/blob/master/rsbuild.sh

###############################################################
I recomend you and cyril use this script for fresh builds on ubuntu, because so often it finds the building problems, if you try this script, appart of this bug you will see other problems.

ake[1]: se sale del directorio '/home/felisuco/retroshare/master/libbitdht/src'
cd libretroshare/src/ && ( test -e Makefile.libretroshare || /usr/lib/qt5/bin/qmake -o Makefile.libretroshare /home/felisuco/retroshare/master/libretroshare/src/libretroshare.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.libretroshare 
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/libretroshare/src'
cd /home/felisuco/retroshare/master && ( git submodule update --init supportlibs/restbed ; cd /home/felisuco/retroshare/master/supportlibs/restbed ; git submodule update --init dependency/asio ; git submodule update --init dependency/catch ; git submodule update --init dependency/kashmir ; true ) && mkdir -p /home/felisuco/retroshare/master/supportlibs/restbed && cd /home/felisuco/retroshare/master/supportlibs/restbed && cmake -DCMAKE_CXX_COMPILER=g++ -DBUILD_SSL=OFF -DCMAKE_INSTALL_PREFIX=. -B. -H/home/felisuco/retroshare/master/supportlibs/restbed && make
Submódulo 'supportlibs/restbed' (https://github.com/Corvusoft/restbed.git) registrado para ruta 'supportlibs/restbed'
fatal: la ruta de destino '/home/felisuco/retroshare/master/supportlibs/restbed' ya existe y no es un directorio vacío.
fatal: clon de 'https://github.com/Corvusoft/restbed.git' en la ruta de submódulo '/home/felisuco/retroshare/master/supportlibs/restbed' falló
Falló al clonar 'supportlibs/restbed'. Reintento programado
**fatal: la ruta de destino '/home/felisuco/retroshare/master/supportlibs/restbed' ya existe y no es un directorio vacío.
fatal: clon de 'https://github.com/Corvusoft/restbed.git' en la ruta de submódulo '/home/felisuco/retroshare/master/supportlibs/restbed' falló
Falló al clonar 'supportlibs/restbed' una segunda vez, abortando
error: ruta especificada 'dependency/asio' no concordó con ningún archivo(s) conocido por git
error: ruta especificada 'dependency/catch' no concordó con ningún archivo(s) conocido por git
error: ruta especificada 'dependency/kashmir' no concordó con ningún archivo(s) conocido por git
CMake Error: The source directory "/home/felisuco/retroshare/master/supportlibs/restbed" does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
make[1]: *** [Makefile.libretroshare:1217: ../../supportlibs/restbed/librestbed.a] Error 1
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libretroshare/src'
make: *** [Makefile:130: sub-libretroshare-src-libretroshare-pro-make_first] Error 2
cd openpgpsdk/src/ && ( test -e Makefile.openpgpsdk || /usr/lib/qt5/bin/qmake -o Makefile.openpgpsdk /home/felisuco/retroshare/master/openpgpsdk/src/openpgpsdk.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.openpgpsdk install
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/openpgpsdk/src'
make[1]: No se hace nada para 'install'.
make[1]: se sale del directorio '/home/felisuco/retroshare/master/openpgpsdk/src'
cd jsonapi-generator/src/ && ( test -e Makefile.jsonapi-generator || /usr/lib/qt5/bin/qmake -o Makefile.jsonapi-generator /home/felisuco/retroshare/master/jsonapi-generator/src/jsonapi-generator.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.jsonapi-generator install
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/jsonapi-generator/src'
make[1]: No se hace nada para 'install'.
make[1]: se sale del directorio '/home/felisuco/retroshare/master/jsonapi-generator/src'
cd libbitdht/src/ && ( test -e Makefile.libbitdht || /usr/lib/qt5/bin/qmake -o Makefile.libbitdht /home/felisuco/retroshare/master/libbitdht/src/libbitdht.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.libbitdht install
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/libbitdht/src'
/usr/lib/qt5/bin/qmake -install qinstall /home/felisuco/retroshare/master/libbitdht/src/bitdht/bdboot.txt /usr/share/retroshare/bdboot.txt
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libbitdht/src'
cd libretroshare/src/ && ( test -e Makefile.libretroshare || /usr/lib/qt5/bin/qmake -o Makefile.libretroshare /home/felisuco/retroshare/master/libretroshare/src/libretroshare.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.libretroshare install
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/libretroshare/src'
make[1]: No se hace nada para 'install'.
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libretroshare/src'
cd libresapi/src/ && ( test -e Makefile.libresapi || /usr/lib/qt5/bin/qmake -o Makefile.libresapi /home/felisuco/retroshare/master/libresapi/src/libresapi.pro CONFIG+=debug CONFIG+=rs_jsonapi RS_UPNP_LIB=miniupnpc ) && make -f Makefile.libresapi install
make[1]: se entra en el directorio '/home/felisuco/retroshare/master/libresapi/src'
make[1]: *** No hay ninguna regla para construir el objetivo '/home/felisuco/retroshare/master/libretroshare/src/lib/libretroshare.a', necesario para 'lib/libresapi.a'.  Alto.
make[1]: se sale del directorio '/home/felisuco/retroshare/master/libresapi/src'
make: *** [Makefile:167: sub-libresapi-src-libresapi-pro-install_subtargets] Error 2

**Comment by felisucoibi** [comment]
@G10h4ck did you see it?
the solution crappy is rm -r /home/felisuco/retroshare/master/supportlibs/restbed

**Comment by G10h4ck** [comment]
The problem is you are using the same directory for source and build, two separated directory should be used something like this

```
git clone https://github.com/RetroShare/RetroShare.git sources
mkdir build
cd build
qmake CONFIG+=debug CONFIG+=rs_jsonapi ../sources/RetroShare.pro
make
```
Probably documentation around should be updated too, PR to update the documentation are welcome, as this is the correct way to build RS

Also now you can avoid to force miniupnpc usage as i fixed the compilation problem with newer libupnp

**Comment by felisucoibi** [comment]
Oks i'll update the script too
