### ISSUE TITLE
How to create a RetroShare executable for windows

### ISSUE THREAD

**Issue by phikhong** [RetroShare/RetroShare#1570]
I want to make a installation file for windows, but the file size is quite large.
Can you share your experiences with me? Thank you

**Comment by hunbernd** [comment]
Did you build it in debug mode?
It makes everything much larger.

**Comment by phikhong** [comment]
I tried again it in release mode, but still not the same as Retroshare's version:
https://retroshare.cc/downloads.html 
How to build an installer like that for windows?
and
Are there any instructions for building all release packages for all OS (Ubuntu, Windows, Mac OS)?

**Comment by hunbernd** [comment]
>How to build an installer like that for windows?

source folder/build_scripts/Windows/build.bat
>Are there any instructions for building all release packages for all OS (Ubuntu, Windows, Mac OS)?

You can find the scripts for the other platforms in the build_scripts folder too.
Check the readmes in the subfolders.
Also you will need to checkout the OBS submodule inside the repo, because it contains the recent scripts for some Linux distros.

**Comment by phikhong** [comment]
Thanks for your help!
