### ISSUE TITLE
VOIP do not compile

### ISSUE THREAD

**Issue by DTux69** [RetroShare/RetroShare#1575]

**Comment by DTux69** [comment]
Hi
OS: Mageia 7
When compiling VOIP i got:
make: ***  Aucune règle pour fabriquer la cible « AudioStats.h », nécessaire pour « ui_AudioStats.h ». Arrêt.
When modifying Makefile  line 902
ui_AudioStats.h: gui/AudioStats.ui \
		/usr/lib64/qt5/bin/uic \
		AudioStats.h \
		AudioStats.h \
		AudioStats.h
	/usr/lib64/qt5/bin/uic gui/AudioStats.ui -o ui_AudioStats.h
to :
ui_AudioStats.h: gui/AudioStats.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic gui/AudioStats.ui -o ui_AudioStats.h

VOIP is compiling

thx

**Comment by G10h4ck** [comment]
Voip plugin is unmaintained at moment.
