### ISSUE TITLE
VOIP-related Dialogs Crash GUI

### ISSUE THREAD

**Issue by benbenolson** [RetroShare/RetroShare#158]
This issue is on my laptop only, but does not affect my desktop.  Both are running Debian Jessie.

Whenever I select "VOIP" in the "Options" dialog, it crashes the entire GUI. Running it in a terminal, there is no useful output, other than the fact that it is "starting video".  However, this must not be what is causing it, because I can video call people just fine-- I just can't use my microphone.  This laptop only has one microphone, and when I try to call someone else, the entire GUI crashes, but Retroshare is clearly still running.  I am still able to send video, however.  This is also caused by me accepting any voice calls whatsoever.

I have tried using three different networks: two University networks (one of which gives you your own global IP), and my own personal network.  File transfers also don't work: it spits out information into the terminal about hashing the file, but never puts a link to the file in the chat.  I can receive files from others, however.

What other information is needed to further diagnose this issue?  I am a fairly experienced C/C++ programmer, and would love to help in any way that I can.

**Comment by csoler** [comment]
Thanks for the offer!

1 - make sure that the VOIP plugin you're loading as been compiled with the same source than the executable to load it. For instance using a self-compiled VOIP from trunk with the release RS version would likely cause problems due to changes in the API.

2 - normally RS uses the default microphone that is provided by the system. So you can change which microphone to use from the sound settings of your OS. That works fine on ubuntu, so if this is not possible on debian jessie, that means we need to implement a internal microphone switching system. Please tell us if the system settings cannot help you.

3 - about file transfer: are you talking about drag+drop-ing files in the chat window? This normally works. I'm not sure how to reproduce the bug you're describing.

Generally, when you get a crash (a deadlock, or a SEGV), a callstack of the crash is sufficient for us to fix the bug. For that, launch RS with gdb, and disable SIGPIPE (do a "handle SIGPIPE nopass noprint nostop ignore" in gdb). Run RS until is crashes or freeze, and print the callstack (type "where").

**Comment by benbenolson** [comment]
1. The VOIP plugin was the one that was included in the git repo; I've not downloaded any other.
2. Okay, that's fine. I generally don't run a full DE with tools such as that, so I suppose I'll have to install one.  If it uses the default input device, then there's no reason to implement separate switching; much more important things lie in wait.
3. I'm talking about clicking the paperclip icon in the chat window, and selecting a file.  I'll try dragging-and-dropping next, though.

Okay, I've run it in gdb, but unfortunately, it doesn't run across any signals.  The GUI simply freezes, and Retroshare clearly continues to run. It continues to print out various messages about connecting to IP addresses, but eventually the entire window goes grey.  It freezes right after it prints out `AudioInputconfig:: starting video.`:

```
Video Encoder: maximum frame rate is set to 30 Bps
AudioInputConfig:: starting video.
[New Thread 0x7fff997fa700 (LWP 24431)]
[New Thread 0x7fff92ffd700 (LWP 24433)]
[New Thread 0x7fff9b7fe700 (LWP 24434)]
[Thread 0x7fff92ffd700 (LWP 24433) exited]
[Thread 0x7fff9b7fe700 (LWP 24434) exited]
[New Thread 0x7fff9b7fe700 (LWP 24435)]
[Thread 0x7fff93fff700 (LWP 24428) exited]
[New Thread 0x7fff93fff700 (LWP 24438)]
[New Thread 0x7fff92ffd700 (LWP 24439)]
p3IdService::handle_event() Unknown Event Type: 48
[Thread 0x7fff92ffd700 (LWP 24439) exited]
[Thread 0x7fff9b7fe700 (LWP 24435) exited]
[New Thread 0x7fff9b7fe700 (LWP 24531)]
```

After that, I CTRL+C'd it, and did a backtrace:

```
#0  0x00007ffff42194db in pthread_join (threadid=140735768667904, thread_return=0x0) at pthread_join.c:92
#1  0x00007fffce826fa7 in pa_threaded_mainloop_free () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fff9807a58e in ?? () from /usr/lib/x86_64-linux-gnu/qt4/plugins/audio/libqtmedia_pulse.so
#3  0x00007fff9807a1b4 in ?? () from /usr/lib/x86_64-linux-gnu/qt4/plugins/audio/libqtmedia_pulse.so
#4  0x00007fff9807ac7f in ?? () from /usr/lib/x86_64-linux-gnu/qt4/plugins/audio/libqtmedia_pulse.so
#5  0x00007fff98072a97 in ?? () from /usr/lib/x86_64-linux-gnu/qt4/plugins/audio/libqtmedia_pulse.so
#6  0x00007fff98072d63 in qt_plugin_instance () from /usr/lib/x86_64-linux-gnu/qt4/plugins/audio/libqtmedia_pulse.so
#7  0x00007ffff4596b63 in QPluginLoader::instance() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007fffd341582c in ?? () from /usr/lib/x86_64-linux-gnu/libQtMultimediaKit.so.1
#9  0x00007fffd3414bdd in ?? () from /usr/lib/x86_64-linux-gnu/libQtMultimediaKit.so.1
#10 0x00007fffd3413123 in ?? () from /usr/lib/x86_64-linux-gnu/libQtMultimediaKit.so.1
#11 0x00007fffd3413239 in ?? () from /usr/lib/x86_64-linux-gnu/libQtMultimediaKit.so.1
#12 0x00007fffd340efee in QAudioDeviceInfo::availableDevices(QAudio::Mode) () from /usr/lib/x86_64-linux-gnu/libQtMultimediaKit.so.1
#13 0x00007fffdbd1cac7 in AudioDeviceHelper::getDefaultInputDevice () at gui/audiodevicehelper.cpp:24
#14 0x00007fffdbd1d027 in AudioDeviceHelper::getPreferedInputDevice () at gui/audiodevicehelper.cpp:48
#15 0x00007fffdbd0c806 in AudioInputConfig::on_Tick_timeout (this=0x3186370) at gui/AudioInputConfig.cpp:363
#16 0x00007fffdbd35e8f in AudioInputConfig::qt_static_metacall (_o=0x3186370, _c=QMetaObject::InvokeMetaMethod, _id=8, _a=0x7fffffffdc90) at moc_AudioInputConfig.cpp:74
#17 0x00007ffff45c871c in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x0000000000c02f08 in RsProtectedTimer::timerEvent (this=0x3150000, e=0x7fffffffe030) at util/RsProtectedTimer.cpp:68
#19 0x00007ffff45ccce3 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff4e3448c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00007ffff4e3afa8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffff45b371d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#23 0x00007ffff45e538b in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#24 0x00007ffff45e23c1 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#25 0x00007ffff720fc5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff720ff48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff720fffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff45e2d1d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007ffff4ed8f96 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007ffff45b2271 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#31 0x00007ffff45b25d5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#32 0x00007ffff45b8059 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#33 0x0000000000b019af in main (argc=1, argv=0x7fffffffe998) at main.cpp:422
```

Hopefully that helps a bit.

One note about the systems that I'm running this on: my laptop (the one where the VOIP options crash) doesn't use Pulseaudio, while the desktop does use it.  I'm fairly certain that Ubuntu uses Pulseaudio. Is that the primary system that you test on?

**Comment by defnax** [comment]
this bug is solved
