### ISSUE TITLE
Photos in Chat Rooms too small

### ISSUE THREAD

**Issue by tiotrom** [RetroShare/RetroShare#1595]
When I send a photo to someone in the chat-rooms, the photo is way too small. 
![2019-07-04_03-26](https://user-images.githubusercontent.com/34804533/60633581-9e596b80-9e0b-11e9-9e28-c6a0ea74b12e.png)

**Comment by tiotrom** [comment]
Speaking of the photo itself - the discussion there - maybe is a good idea to default to remember chat history.

**Comment by defnax** [comment]
in chat rooms are not allowed big photos only as small thumbnail maybe you dont knew it.

**Comment by tiotrom** [comment]
Ok, but why is that?

**Comment by hunbernd** [comment]
Some years ago somebody attacked the chat lobbies with the OneMillionLaughs attack through embedded svg images.
Somebody attempted to fix this issue by limiting the message size in 2000 bytes.
It made impossible to send images, because it is too small, but it didn't stop the attack.
Actually he made that patch, because he hated images in chat.
Later the attack was fixed by banning all embedded svg. There was no better solution, because it is a ~~bug~~ feature of Qt and XML.
Later the limit was risen to 6000 bytes, and image compression was added.

**Comment by hunbernd** [comment]
https://github.com/RetroShare/RetroShare/pull/1596

**Comment by tiotrom** [comment]
Ok so now you will try to restore the ability to share bigger photos as i understand right?

**Comment by csoler** [comment]
Large images in chat rooms  will cause lots of traffic and take some significant memory. This is why their size is limited. If you want bigger images the best is to encode them as jpeg instead of PNG. Personally I don't think that we should significantly increase this limit

**Comment by tiotrom** [comment]
@csoler We are trying to use RetroShare to manage our teams of volunteers and we normally share photos (like screenshots) for all kinds of reasons (like say reporting bugs). What would be the use of sending these super small and low quality photos though? They are so low quality and small that you can't make much of that. And isn't the traffic between our nodes anyway? Like we share hundreds of GB anyways via files.

**Comment by csoler** [comment]
When you send a chat msg I'd is stored at every node in the chat and transits between all pairs of connected nodes in the chat room. This is why it should not be bigger than a few kB. If you want to share larger pieces of data it makes more sense to share a link. What could be made is to have RS automatically choose between a plain image or a link (both with a thumbnail) depending on the image size.

**Comment by tiotrom** [comment]
Or maybe to display as a thumbnail and if you click it it expands into full, thus whichever node requests it as full it gets it as full. How about that? Currently I do not know what would be the use of sending a photo over chat if the photo is so small.

**Comment by csoler** [comment]
Chat rooms do not allow to request messages to distant nodes. What we can do is when the image is small show it and when it is large show a link with info about size. When downloaded show it in the chat. During download show a small progress at as tooltip. When the image is here display it.

**Comment by tiotrom** [comment]
Seems like a good idea!

**Comment by defnax** [comment]
done #1596
