### ISSUE TITLE
Reddit/imageboard idea proposal

### ISSUE THREAD

**Issue by POMATu** [RetroShare/RetroShare#1597]
Hi,

So now what we have? We have channels that are like a blogs for single content maker or for several that are close friends. There is no ability to revoke permissions neither delete the posts. This means that I don't have flexible ability to share permissions with the crowd. It also have votes for comments, that's pretty nice feature.

We also have forums. Everybody can write there, we have nested threads there which are more like reddit, but inline images there are not really good and no votes.

I wonder if it can be somehow merged in something 3rd, so we can have more social network/imageboard experience.

If it's possible somehow to have main post with nested threads with votes, filesharing, and ablitity to attach images with optional signed keys and etc it would be a killer feature, cause it will be more functional than reddit (with it's banhammer abusing all previous year).

Also was thinking about something like public pages in social networks, so I mean some channel extension that allows premoderation of posts by admin/supermoderators. That will prevent flooding and spamming on channels with shared keys. Feature can be called "Propose a new post".

Thanks

**Comment by defnax** [comment]
> We also have forums. Everybody can write there, we have nested threads there which are more like reddit, but inline images there are not really good and no votes.

Yes the voting is need i wanted since lots of years for Channel/Forum posts.
only  available for posted feature.

**Comment by defnax** [comment]
but we have a reddit clone alias Posted Links, you use it? 
it needs more improved.

**Comment by defnax** [comment]
we have posted but it cant yet replace reddit features.
Picture attachments not realy possible maximum limit is at the moment under 34KB.
only Sticker size image attachments with Posted links

**Comment by defnax** [comment]
imageboard #1753 is done 
now there is more todo here https://github.com/RetroShare/RetroShare/issues/1721
