### ISSUE TITLE
Automatic UPnP doesn't seem to be working

### ISSUE THREAD

**Issue by mr-eshua** [RetroShare/RetroShare#1598]
Hello folks,

I am trying to test latest fixes and enhancements from master branch, building it on Manjaro.
Retroshare was started fine, but UPnP automatic settings don't work anymore. It just shows I am firewalled (NAT indicator is yellow). 

Preferences -> Network -> UPnP indicator is off. Local network & External IP finder are green. No visible errors, alerts are there, retro.log has nothing unusual it seems.

Checked out my router settings, there are no UPnP port open requests from retroshare anymore. I do a roll-back to previous version from AUR it works as a charm.

Any advices would be very appreciated! Thanks

**Comment by G10h4ck** [comment]
Which commands did you run to build retroshare from master branch?

**Comment by mr-eshua** [comment]
```
qmake CONFIG+=debug
make
sudo make install
```

**Comment by G10h4ck** [comment]
qmake should print some info about UPnP library detection can you paste that?

**Comment by mr-eshua** [comment]
```
Project MESSAGE: RetroShare version 0.6.5-294-gbf461c5f3 determined via git
Project MESSAGE: QMAKE: You have disabled deprecated warnings.
Project MESSAGE: QMAKE: You have disabled C preprocessor warnings.
Project WARNING: You have enabled RetroShare direct chat which is deprecated!
Project MESSAGE: Autodetected RS_UPNP_LIB=upnp ixml threadutil
```

**Comment by G10h4ck** [comment]
So it seems that UPnP support has been compiled in

**Comment by mr-eshua** [comment]
Yup, seems so. Can I collect something else to help you understand the reason?

**Comment by G10h4ck** [comment]
libupnp version and full retroshare log might give some useful information

**Comment by PhenomRetroShare** [comment]
Hello,
Can you test PR #1603 ?

**Comment by mr-eshua** [comment]
Hi,
Thanks a lot for the fix! I tested it today, looks like UPnP rules are in place now!
![image](https://user-images.githubusercontent.com/22781783/62172753-0f713d80-b33c-11e9-9e9d-725f7934d435.png)

I was able to connect to a friend finally, he is firewalled. But what I've noticed tho, UPnP led is still off:
![image](https://user-images.githubusercontent.com/22781783/62172856-7bec3c80-b33c-11e9-978c-6f8e5b4e25a9.png)

And status of NAT is still:
![image](https://user-images.githubusercontent.com/22781783/62173039-3e3be380-b33d-11e9-9b27-84c66fc6db08.png)

Is it normal? The status was green on AUR version.

**Comment by PhenomRetroShare** [comment]
Hello,
Doesn't it become green after a moment?

**Comment by mr-eshua** [comment]
No, still no UPnP green light. Tried to wait about an hour or so, no results.

**Comment by BinaryAura** [comment]
I also have this issue. I installed via the instruction posted here: https://retroshare.cc/downloads.html#Fedora
I have retroshare 0.6.5-retroshare-gui-OBS-rpm, Ot 5.12.5.

**Comment by ghost** [comment]
Doesn't work for me in latest stable (0.6.6) for Linux (via flatpak). NAT remains yellow, no UPnP ports open (OpenWRT 21.02.1 with miniupnpd addon). Renders Retroshare useless for me.

**Comment by G10h4ck** [comment]
RetroShare flathub package is build with libupnp instead of miniupnpc, libupnp have been changing behaviour and API all the time, making it basically impossible to maintain out interface to it stable and working, and as of today i would say out piece of code using it should be rewritten from scratch :(

I have been slowly migrating our packaging recipes to miniupnpc which is simpler but much more stable maybe the time has come to port our flatpak to miniupnpc too?

https://github.com/flathub/cc.retroshare.retroshare-gui/blob/master/cc.retroshare.retroshare-gui.yaml#L62

**Comment by G10h4ck** [comment]
Just changed flatpak recipe to build against miniupnpc instead of libupnp, @timur-davletshin this should probably solve your issue, test it once a retroshare flatpak update is available ;)

**Comment by ghost** [comment]
@G10h4ck, thanks for attention. Will check it when binaries will get updated, at the moment they are "June 24, 2021".

**Comment by ghost** [comment]
@G10h4ck, it works now (fresh flatpak build)!

**Comment by G10h4ck** [comment]
Thanks for the feedback.
So for this release 0.6.6 and current master the solution is to build with miniupnpc and not with libupnp.

**Comment by tbw777** [comment]
how to fix on windows?

**Comment by G10h4ck** [comment]
Building against `miniupnpc` should fix on windows too
