### ISSUE TITLE
Can't create a Channel using API method createChannelV2

### ISSUE THREAD

**Issue by jpascualsana** [RetroShare/RetroShare#1600]
Hi, 

I'm trying to create a channel using the new API method: `rsGxsChannels/createChannelV2`. 

I'm trying to do:

```bash
curl -u "$ACCOUNT:$PASSWORD" -d '{ "description" : "no description","name" : "TestwithV2"}' http://127.0.0.1:9092/rsGxsChannels/createChannelV2
```

With the old method this curl command works properly. I don't know if i'm doing something wrong. 

I'm using `retroshare-service` instaled by OBS repository on a linux mint 19, this is the version info:

```
{'major': 0, 'minor': 6, 'mini': 5, 'extra': '-retroshare-service-OBS-deb', 'human': '0.6.5-retroshare-service-OBS-deb'}
```

**Comment by G10h4ck** [comment]
what do you get? an http error or false returned? you can pass -v option to curl so it is more verbose

**Comment by jpascualsana** [comment]
I think the error message is: `* no chunk, no close, no size. Assume close to signal end`

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9092 (#0)
* Server auth using Basic with user ''
> POST /rsGxsChannels/createChannelV2 HTTP/1.1
> Host: 127.0.0.1:9092
> Authorization: Basic ODE0MjI4NTc3YmMwYzVkYTk2OGM3OTI3MmFkY2JmY2U6cHJ1ZWJh
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 57
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 57 out of 57 bytes
< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
```

It seems method is not published on my version?

**Comment by G10h4ck** [comment]
yeah this is the interesting part `HTTP/1.1 404 Not Found` it means either the path is wrong or the version you are using is old enough to not have it yet, I recommend you compile retroshare-service from source for development purposes

**Comment by G10h4ck** [comment]
Also it seems you installed the retroshare-service stable package, in that case also try tu remove it and install retroshare-service-unstable instead

**Comment by jpascualsana** [comment]
Ok, using a compiled version of retroshare-service build from RetroShare master makes the method working
