### ISSUE TITLE
A error popup and i can't start rs.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1605]
![imagen](https://user-images.githubusercontent.com/1285303/61991941-c5e0d400-b057-11e9-8694-49b222227f6c.png)
GetIssuerName FAILED!
getRetroshareDataDirectory() found: /usr/share/retroshare
looking into $HOME/.gnupg/
Cannot copy pub keyring /home/felisuco/.gnupg/pubring.gpg to destination file /home/felisuco/.retroshare/pgp/retroshare_public_keyring.gpg. If you believe your keyring is in a different place, please make the copy yourself.
Memory still in use at end of program: 0 bytes.

**Comment by G10h4ck** [comment]
Are you able to reproduce the bug, in that case can you provide more information on how to reproduce it?

**Comment by felisucoibi** [comment]
I moved my rs config to another Ubuntu installation, And this error appeared...

**Comment by G10h4ck** [comment]
you moved the whole $HOME/.retroshare directory ?

**Comment by felisucoibi** [comment]
yes i did, in the past it used to work, but this time this error happened.

**Comment by csoler** [comment]
This is a very old warning that we inserted when we switched from 0.5 to 0.6. This warning shows up because RS cannot find your PGP keyring in ~/.retroshare/pgp, although it can find an account ID below ~/.retroshare/. So I guess that you copied the account and forgot to copy the pgp directory.
