### ISSUE TITLE
login to forum failed

### ISSUE THREAD

**Issue by ralfhauser** [RetroShare/RetroShare#161]
I registered an then, I tried to log in

![2015-10-26_08_18_06-503service unavailable](https://cloud.githubusercontent.com/assets/1681677/10723397/cb954eba-7bba-11e5-90b9-89e95eafff0c.png)

**Comment by cavebeat** [comment]
hi,

i guess its a SourceForge problem. i am logged in right now. 
do you still have this problem?

**Comment by ralfhauser** [comment]
Thanks, works again - now I am waiting for "moderator approval" of 2 posts. How long is this typically taking?
