### ISSUE TITLE
Cannot create hidden node (over tor) account in Windows

### ISSUE THREAD

**Issue by xn-zhao** [RetroShare/RetroShare#1611]
Hi all,
I tried to create hidden node (over tor) account in Windows. I follow this instruction:
https://retroshare.readthedocs.io/en/latest/tutorial/tor-hidden-rs-node/
it works normally in Ubuntu, but in Windows, after install Tor browser (https://www.torproject.org/dist/torbrowser/8.5.4/torbrowser-install-win64-8.5.4_en-US.exe)
in Windows, add 2 lines in torrc file of Tor browser folder:

HiddenServiceDir C:\Users\84902\Desktop\Tor Browser\Browser\TorBrowser\Data\Tor\hidden_rs_revy\
HiddenServicePort 32111 127.0.0.1:32111

And then, re-run the Tor browser i could not get the priv key or onion address as in Ubuntu.
When running RS, we tried to create account with hidden node (over tor) option, we got the following error:

![Capture-tor-failed](https://user-images.githubusercontent.com/5832607/62350855-2ecfbc80-b52e-11e9-9722-30225d6507cf.PNG)

Any clear instruction for Windows? And MacOS too?

Thank you.

**Comment by xn-zhao** [comment]
Hi again,
We just use another package for create  new RS tor account on Windows, this one:RetroShare-0.6.5-Windows-Portable-20190204-1-gfb005f041-Qt-5.12.0-tor.7z
And it seems can open the Tor bootstrap window, but it stops at this status:
![Capture-rs-tor](https://user-images.githubusercontent.com/5832607/62406529-a0b01080-b5d7-11e9-90a7-25911911ba7d.PNG)

When we tried to run the RS with tor, we already run the Tor browser. Maybe the onion is not the same with the tor browser or anything else?

We end this process of the app, then re-run (while remove other RS version in Windows), we get the following status of Tor:
![Capture-rs-tor-2](https://user-images.githubusercontent.com/5832607/62406702-0ef5d280-b5da-11e9-8a7f-ed0dcc8e8b3e.PNG)


Any idea about this?
Thank you.

**Comment by Nhyalgotphores** [comment]
Hello,
to first problem with latest release.
May you try
1. Download tor expert bundle from [here]([https://www.torproject.org/download/tor/)
2. Add tor.exe to path
3. Rerun the account creation

I was able to simulate it.
With this I got it working.

**Comment by xn-zhao** [comment]
Thank you, Nhyalgotphores .
I solved and think that was just Windows environment.

**Comment by defnax** [comment]
@G10h4ck close
