### ISSUE TITLE
prepare debian 10 repo appropiately

### ISSUE THREAD

**Issue by pedro-nonfree** [RetroShare/RetroShare#1612]
I do not see  `retroshare_0.6.5.diff.gz` in [debian10], is this a problem? [debian9] is different than [debian10]

when we know latest stable works as expected: update webpage pointing to the new stable version (debian 10 buster) https://retroshare.cc/downloads.html#debian

[debian9] https://download.opensuse.org/repositories/network:/retroshare/Debian_9.0/

[debian10] https://download.opensuse.org/repositories/network:/retroshare/Debian_10/

**Comment by G10h4ck** [comment]
retroshare 0.6.5 won't compile on debian 10, so you need to use retroshare-*-unstable until next release

**Comment by meinportugal** [comment]
Dear G10h4ck!
I am sorry to disturb you. I like your programm but since I mooved to debian 10 from ubuntu I am not able to install it or compile ftom source (not al packages could be installed from the debian repo, that were suggested according to the Readme instructions here)
May I kindly ask you please point me on a deb file I should download? The pne from the link above installes but retroshare crashes after trying to login to a new created account.
I see versions 6.999 in opensuse repo but do not know how to get it. Thank you very much in advance!

**Comment by G10h4ck** [comment]
it would be interesting if you can post the output of your crash.

Also make sure that the repository url in your APT sources is the one for Devian 10 and not Debian 9

**Comment by meinportugal** [comment]
Yes, sure,  please have a look:
```getRetroshareDataDirectory() found: /usr/share/retroshare
========================================================================
==                 RsInit:: starting up Retroshare core               ==
==                                                                    ==
== Account/SSL ID        : 00000000000000000000000000000000           ==
== Node type             : Hidden                                     ==
== Tor/I2P configuration : Manual                                     ==
========================================================================
main() - Fatal Error.....
Invalid Certificate configuration!

libretroshare failed to startup!
Memory still in use at end of program: 0 bytes.
RsMutex::lock() pthread_mutex_lock returned EINVAL
Caught signal 11 (SIGSEGV)
stack trace:
retroshare(_ZN15CrashStackTrace12abortHandlerEi+0x8e)[0x556101a0549e]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840)[0x7f21ff9d2840]
[0x55610385c210]
```

And the 
cat /etc/apt/sources.list
```# deb cdrom:[Debian GNU/Linux 10.0.0 _Buster_ - Official amd64 NETINST 20190706-10:23]/ buster main

#deb cdrom:[Debian GNU/Linux 10.0.0 _Buster_ - Official amd64 NETINST 20190706-10:23]/ buster main

deb http://deb.debian.org/debian/ buster main non-free contrib
# deb-src http://deb.debian.org/debian/ buster main non-free contrib

deb http://security.debian.org/debian-security buster/updates main contrib non-free
# deb-src http://security.debian.org/debian-security buster/updates main contrib non-free

# buster-updates, previously known as 'volatile'
deb http://deb.debian.org/debian/ buster-updates main contrib non-free
```

**Comment by Artemka27** [comment]
Sorry, my comment looks veru ugly. I did not manage to make it more suitable..

**Comment by G10h4ck** [comment]
can't spot retroshare repository there please take a look at this file `/etc/apt/sources.list.d/retroshare.list`

**Comment by meinportugal** [comment]
Sorry, I did not even give it a try:
https://retroshare.cc/downloads.html#debian
I saw debian 9.0 and thought it will not work.
So I have followed the instruction (firstly I removed the retroshare installed from the dpkg)
I did it like this:

```wget -qO - http://download.opensuse.org/repositories/network:retroshare/Debian_10/Release.key | sudo apt-key add -

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/network:/retroshare/Debian_10/ /' >> /etc/apt/sources.list.d/retroshare.list"
```
Now I have it in my source.list

So when I try 
```sudo apt install retroshare```
 and + Tab it advicves me retroshare-gui-unstable
Meaning I am installing retroshare-gui-unstable_0.6.9999_amd64.deb again, which crashes as we saw above

Please let me know what am I doing wrong?
I am still able to start the programm from the Appimage file, but would still love to have it installed a regular way.

Thank you in advance!

**Comment by G10h4ck** [comment]
this might be able to workaround the error you are encountering https://github.com/RetroShare/RetroShare/issues/1354#issuecomment-482910671

**Comment by meinportugal** [comment]
Ah! Sorry. Yesterday night I read it through but did not pay enough attention. My fault.
Do you maybe still could give me an idea how to start retroshare with OPENSSL_CONF="" variable preset (not from command line, but clicking an icon somewhere)
I am not in favour lowering the OpenSSL security in entire system, and it works with this preset for me fine.

(By the way, which tray icon manager I suppose to use so retroshare will have an icon there) I have installed Gnome as DE and do not see it. But in Ubuntu it works fine. This is not a big issue for me,just wondering)

Thank you very much!

**Comment by csoler** [comment]
the tray icon problem is probably connected to a bug in Qt. We just ask Qt for an icon in the tray, and it may not be compatible with all window managers for some reason. We should definitely first try to check if the notification area is available using QSystemTrayIcon::isSystemTrayAvailable() and warn the user if not.

**Comment by meinportugal** [comment]
Thank you for your reply! This is something over my skills, so I will just leave it as it is and wait for an update.
Thank you for the program once again, I like it!
p.s. does the 6.999 release means we are approaching the 7.0 version very soon? :)

**Comment by G10h4ck** [comment]
0.6.9999 stands for unstable package

**Comment by meinportugal** [comment]
Dears! In case anybody needs to run the programm on Debian 10 with Gnome DE, to create an easy startup icon just follow a simple instruction:
First run
```sudo nano /usr/share/applications/retroshare.desktop```
and then make shure this line will look like this:
```Exec=env OPENSSL_CONF="" /usr/bin/retroshare %U```
restart your session and go to chat! : )

**Comment by morpheusbeing** [comment]
I have done all of these things and still having no luck.

    SSL Library Init!
    Issues With Private Key! - Doesn't match your Cert
    Check your input key/certificate:
    /home/XXXXX/.retroshare/LOC06_6c09478200145f967f8ac3b9557f5d6c/keys/user_pk.pem &   /home/XXXXX/.retroshare/LOC06_6c09478200145f967f8ac3b9557f5d6c/keys/user_cert.pem
    Creating Init File: /home/XXXXX/.retroshare/default_cert_06.txt
	Id: 6c09478200145f967f8ac3b9557f5d6c
    ========================================================================
    ==                 RsInit:: starting up Retroshare core               ==
    ==                                                                    ==
    == Account/SSL ID        : 00000000000000000000000000000000           ==
    == Node type             : Normal                                     ==
    ========================================================================
    main() - Fatal Error.....
    Invalid Certificate configuration!

    libretroshare failed to startup! 
    Memory still in use at end of program: 0 bytes.
    RsMutex::lock() pthread_mutex_lock returned EINVAL
    Caught signal 11 (SIGSEGV)
    stack trace:
