### ISSUE TITLE
Voice calls?

### ISSUE THREAD

**Issue by POMATu** [RetroShare/RetroShare#1637]
Am I hallucinating or several years ago there was an option to do encrypted voice call in retroshare?

In the chat window there was a hangup button. Was this feature removed? If yes, why?

**Comment by csoler** [comment]
it was a plugin. The plugin (VOIP) is still alive, but not maintained so we do not distribute it anymore. 
When someone has time to take care of it, there's a few things to do in order to make it work better. I can give directions if necessary.

**Comment by defnax** [comment]
The Voice and Video is abandoned on rs (it doesnt had high priority)
thats the reason retroshare isnt yet a alternative for skype.

for Voice & Video Call i prefer to use Telegram or Ring(jami), Tox

> Am I hallucinating or several years ago there was an option to do encrypted voice call in retroshare?
> 
> In the chat window there was a hangup button. Was this feature removed? If yes, why?
