### ISSUE TITLE
Dependency error with AppImage on CentOS 7

### ISSUE THREAD

**Issue by LorMugnaini** [RetroShare/RetroShare#1656]
Downloaded and launched retroshare AppImage results in the following dependancy errors:

```
retroshare: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by retroshare)
retroshare: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by retroshare)
retroshare: /usr/lib64/libgpg-error.so.0: no version information available (required by /tmp/.mount_retrosJC2med/usr/lib/libgcrypt.so.20)
```

**Comment by G10h4ck** [comment]
Any suggestion @probonopd ? @LorMugnaini if you can provide the appimage you used and were you downloaded it that would be very helpful

**Comment by LorMugnaini** [comment]
I've used the AppImage from the official site: https://retroshare.cc/downloads.html

https://download.opensuse.org/repositories/network:/retroshare/AppImage/retroshare-gui-latest-x86_64.AppImage

**Comment by probonopd** [comment]
Please build on the oldest still-supported LTS release of Ubuntu, which is 16.04 at this point, or a similarly old distribution. Please also see https://docs.appimage.org/packaging-guide/other-resources/ingredients.html#libstdc-so-6.

**Comment by G10h4ck** [comment]
> Please build on the oldest still-supported LTS release of Ubuntu, which is 16.04 at this point, or a similarly old distribution. Please also see https://docs.appimage.org/packaging-guide/other-resources/ingredients.html#libstdc-so-6.

We build the AppImage on OBS and we need a C++11 compliant compiler, do you know if it is possible doing that on OBS + Ubuntu 16.04 ?

Edit: it seems that Ubuntu 16.04 ships GCC 5 that should support up to C++14 so indeed it support C++11, the question now is how to produce the AppImage on OBS using Ubuntu 16.04 instead of OpenSuse

**Comment by LorMugnaini** [comment]
Unfortunately I don't have anymore a CentOS7 at hand. I've just tried to install retroshare with apt repository on a Ubuntu Server 16.04 and it worked (gui interface via remote X server because the server is headless). My final goal would be to have a gui-less installation controlled only via web interface.

**Comment by G10h4ck** [comment]
> it seems that Ubuntu 16.04 ships GCC 5 that should support up to C++14 so indeed it support C++11, the question now is how to produce the AppImage on OBS using Ubuntu 16.04 instead of OpenSuse

Ping @probonopd

**Comment by probonopd** [comment]
> how to produce the AppImage on OBS using Ubuntu 16.04 instead of OpenSuse

Please ask over at the OBS project, I don't know how to do this on OBS.
An older version of openSUSE from 2016ish might do as well.

**Comment by ghost** [comment]
> it seems that Ubuntu 16.04 ships GCC 5 that should support up to C++14

GCC 5 supports C++14 when explicitly specified. C++11 by default. There is no support for C++17.
