### ISSUE TITLE
Hasciicam for video chat/ conferencing

### ISSUE THREAD

**Issue by strypey** [RetroShare/RetroShare#1690]
[Hasciicam](https://github.com/jaromil/hasciicam) (GPLv2+) is a program that renders a live video feed using ASCII characters. In theory, this means you can stream video using much less data and computing resources than a standard video stream. Could Retroshare use Hasciicam for video chat/ conferencing, or at least offer it as an option to users, especially those using Retroshare on older devices, or over slow or patchy network connections?

**Comment by defnax** [comment]
we are more intrested to have useable voice/video chat when you want help you are welcome

see here some todos for when you want improve our voice/video chat codec/Usability you are welcome 
see here : https://github.com/RetroShare/RetroShare/issues/16

**Comment by felisucoibi** [comment]
i wonder how can be better ascii to compress than binary data....

**Comment by strypey** [comment]
@felisucoibi I'm not sure what you're asking. What I think you're asking is;
How can sending ASCII data across the network use less resources than sending binary data across the network?

In both cases, you're sending binary data across the network. The question is, how much data? If each frame of the video is represented using a video codec like Theora or VP8/9, the data sent for each frame is like a graphics file (.JPG or .PNG). If each frame of the video is represented as an array of ASCII characters (like ASCII art), the data sent for each frame is like a page of text, with letters in a variety of colours. One page of ASCII text is much smaller than a one page graphics file, so the Hasciicam video feed would be much smaller than a standard streaming video feed. There's more information at the Hasciicam homepage:
https://www.dyne.org/software/hasciicam/

FYI I'm not an expert in how any of this software works. Mainly I'm just bringing it to your attention in case it's helpful.

**Comment by felisucoibi** [comment]
Understood, the compression is completeley loosy, super looosy :P in that case, yes it uses very few bytes but the image is far from a "image" concept :p

**Comment by defnax** [comment]
we need real useable video chat in HD, im not fan of ASCII ;)

**Comment by strypey** [comment]
@defnax:
> we need real useable video chat in HD

Sure, that would be great. But having Hasciicam as an option, might
allow users to do realtime video chat on slow or unreliable network
connections, which can't handle HD video without a lot of lagging,
skipping, buffering, and so on.

> im not fan of ASCII ;)

Fair enough ;) But the image quality is better than you might expect.
Here's a demonstration (starts at 0:56):
https://invidio.us/watch?v=78lN6b7b4gg
