### ISSUE TITLE
invalid use of incomplete type 'struct CUPnPControlPoint::Callback

### ISSUE THREAD

**Issue by sdgathman** [RetroShare/RetroShare#1702]
Compile of v0.6.5 on Fedora 30 (gcc-c++-9.2.1) fails with incomplete type:

~~~
upnp/UPnPBase.cpp:1558:102: error: invalid use of incomplete type 'struct CUPnPControlPoint::Callback(Upnp_EventType, void*, void*)::Upnp_State_Var_Complete'
 1558 |       (upnpCP->m_WanService->propertyMap)[std::string(sv_event->StateVarName)] = std::string(sv_event->CurrentVal);
      |                                                                                                      ^~
upnp/UPnPBase.cpp:1550:10: note: forward declaration of 'struct CUPnPControlPoint::Callback(Upnp_EventType, void*, void*)::Upnp_State_Var_Complete'
 1550 |   struct Upnp_State_Var_Complete *sv_event =
      |          ^~~~~~~~~~~~~~~~~~~~~~~
~~~

**Comment by sdgathman** [comment]
Looks like libretroshare/src/upnp was renamed to rs_upnp, and probably this is fixed in 0.6.6

**Comment by sdgathman** [comment]
I am working on an rpmfusion package (since patented codecs are involved) instead of using another repo.

**Comment by G10h4ck** [comment]
Added the label so we double check this before next release

**Comment by G10h4ck** [comment]
> I am working on an rpmfusion package (since patented codecs are involved) instead of using another repo.

you mean that patented codecs are used in retroshare? For what?

**Comment by sdgathman** [comment]
> you mean that patented codecs are used in retroshare? For what?

It requires ffmpeg, which Fedora cannot distribute at present.  I didn't investigate exactly which codecs within ffmpeg are used.

**Comment by G10h4ck** [comment]
I guess that is only if you compile it with VoIP plugin enabled which is unmaintained ATM, by default it is not compiled, so you should not need it, as you can see in the recipe we use to build retroshare-gui package ffmpeg is not even mentioned https://build.opensuse.org/package/view_file/network:retroshare/retroshare-gui-unstable/retroshare-gui-unstable.spec?expand=1

**Comment by sdgathman** [comment]
As expected, I got the 0.6.6 package compiled for Fedora 34 and 35.  The self tests fail with compile errors, which I will report as another bug.  I want the self tests to run before submitting as a package.
