### ISSUE TITLE
[Qt] RetroShare ID [short invites] is done but the Accept/Reject Friend Request on Gui is missed

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#1709]
hi,
its realy nice to have the new short retroshare ids.
but when it will be finished for me looks like not finished?

>  IMHO the possibility to add someone as friend on attempt is a really important usability feature, even in one of the most common social interaction people ask your phone number, and then give you a miss call so you have their number instead of blabbering it to you...
> 
> So I have double checked the code in PR #1571 , and it is still possible to implement an accept button after a failed connection attempt notification at user interface level.
> 
> Basically when someone adds you through an invite you provided, she will attempt connections towards you, if don't have added her yet your RS will deny the connection and an event is posted see **AuthSSLimpl::VerifyX509Callback** the event contains the data such as SSL-id and PGP-id we learnt from the connection.
> 
> With that information the UI as an example of a possible implementation, could display an "Accept" button together with the notification, when "Accept" button is pressed RsPeers::addSslOnlyFriend can be called with the info contained in the event,

https://github.com/RetroShare/RetroShare/issues/638#issuecomment-533794444

> The works on libretroshare is finished, now what is needed is work on retroshare-gui which I will not do, to handle RsEvents sent when a connection authentication is failed

> V0.6 short invites #1571
> Fix addSslOnlyFriend when adding with already known PGP #1673
> Send PGP fingerprint in broadcast discovery #1644

When i added some ones Retroshare ID on other side the New friend doesnt get any Friend Requests from me to confirm.

Me :
1. I add Friend XZY RetroShare ID

and on other Side must this happen
gets the Friend Request Notify via

2. Via FR Feed (feeds/SecurityItem), FR Mail or FR Toaster (FriendRequestToaster) which calls the Friend Requst Window to click on "Accept" Button for confirm.

2. [ New Idea ] Friend Request Tab in Network (which list all friend requests) where easyly click on Accept Button to confirm or Reject it.
3. [ New Idea ] Notify Display latest Friend Requests Count maybe in Network Dialog too.

This is very importend before a new release it must be done. its importend for RetroShare.
But its very importend to have easy one way Add/Accept Friends Requests.
￼
**idea from tox chat:** 
![fr2](https://user-images.githubusercontent.com/9952056/69259178-1c04f480-0bbe-11ea-95c2-20f88faace62.png)

![fr1](https://user-images.githubusercontent.com/9952056/69259176-1c04f480-0bbe-11ea-871d-34be2670bf43.png)
￼￼

**Comment by Winter12321** [comment]
Господа, как посмотреть свой id?
