### ISSUE TITLE
Build fails after #1700 was merged

### ISSUE THREAD

**Issue by rex4539** [RetroShare/RetroShare#1727]
Multiple errors but basically the first underline issue is the same as the CI failures.

`fatal error: rapid_json/document.h: No such file or directory`

Let's fix this one first and then move on to the next ones one by one...

If CI passes, then probably my build will compile too.

**Comment by rex4539** [comment]
https://github.com/RetroShare/RetroShare/pull/1724 fixes my local build when built with `qmake CONFIG+=debug CONFIG+=rs_macos10.15 CONFIG+=no_direct_chat`.

It still fails when built with `qmake CONFIG+=debug CONFIG+=rs_macos10.15 CONFIG+=no_direct_chat CONFIG+=rs_jsonapi CONFIG+=rs_webui`.

**Comment by G10h4ck** [comment]
Did `qmake CONFIG+=debug CONFIG+=rs_macos10.15 CONFIG+=no_direct_chat CONFIG+=rs_jsonapi` (yes json no webui) build fine before #1700 ?

**Comment by rex4539** [comment]
Not sure, haven't tried it back then :D

**Comment by rex4539** [comment]
Closing, since building with `qmake CONFIG+=debug CONFIG+=rs_macos10.15 CONFIG+=no_direct_chat` works now.

When/if the json stuff become mandatory and break the build again, I will file a new bug then.
