### ISSUE TITLE
GUI completely frozen, but rs still working in background after testing latests pr's.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1759]
GUI completely frozen, but rs still working in background after testing latests pr's.

**Comment by G10h4ck** [comment]
Which PR?

**Comment by felisucoibi** [comment]
seems your latest pr, fix the gui problem.

**Comment by felisucoibi** [comment]
it did, but now rs crashes after a few minuts, tring to find out the error log.

**Comment by G10h4ck** [comment]
Fixed with https://github.com/RetroShare/RetroShare/commit/33c2f56a8e18245e2071fb405d456986dc0bd10f
