### ISSUE TITLE
migration of website from SourceForge to GitHub

### ISSUE THREAD

**Issue by cavebeat** [RetroShare/RetroShare#177]
domain http://retroshare.org is pointing to http://retroshare.sourceforge.net/ 

@drbob should update the domain and change the forward to https://retroshare.github.io/ instead.

there is a preview available: https://cavebeat.github.io/retroshare.github.io/index.html

**Comment by cavebeat** [comment]
ping @csoler @drbob

**Comment by Croydon** [comment]
This would be a good thing.

**Comment by defnax** [comment]
done
