### ISSUE TITLE
downloaded file doesn't automatically appear in shared files

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#1770]
Hi,

i have this issue since last year on rs.
I start a file from Channels to download.
after file is finished in file transfers window... it doesnt appear in downloads dir.

i need to often click on "check files" button, then the file will be added to downloads dir.
Im not sure if im the only one with this issue? W10 64bit.

**Comment by csoler** [comment]
This should be fixed by PR 1772.

**Comment by csoler** [comment]
Fixed.

**Comment by G10h4ck** [comment]
Better keep them open until we release the fix, and then close them and remove the "Fixed but not released" flag. This should reduce bug duplication.
