### ISSUE TITLE
Anon transfers not working.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1779]
Uusually i got some anon transfers in rs, since a month or two ago anon transfers are gone, only direct connections.

**Comment by csoler** [comment]
well, this should be easy to test using another node, including on the same machine: start on DL on this node and see what you have in Uploads in the other node.

**Comment by sehraf** [comment]
All is working fine with latest master on my side. Did you (by accident) turn off anon file transfers?

**Comment by felisucoibi** [comment]
At the end problem was unpnp no opening router ports... Maybe another bug.
