### ISSUE TITLE
Specify license coverage

### ISSUE THREAD

**Issue by comradekingu** [RetroShare/RetroShare#1790]
Right now a lot of incompatible licenses are listed, with no info of what part of RetroShare they cover

https://github.com/RetroShare/RetroShare/tree/master/LICENSES

**Comment by G10h4ck** [comment]
here it is specified which licenses is used for each component https://github.com/RetroShare/RetroShare/blob/master/.reuse/dep5

**Comment by comradekingu** [comment]
How about putting that content in COPYING at the root, similar to the "LICENSES" is a convention for stating licenses.
The scenario would be this.

User wants to find out which license covers what part of the software.
User sees COPYING file.
Done.

**Comment by G10h4ck** [comment]
This seems as easy as creating a symbolic link to dep5, you are welcome to create a pull request for that
