### ISSUE TITLE
MacOS build v0.6.5 has a wrong version.

### ISSUE THREAD

**Issue by guglez** [RetroShare/RetroShare#1823]
Hi,

there is a wrong app behind v0.6.5 for MAC. It's actually 0.6.0 and not 0.6.5. Could you please upload a correct binary?
Here is a link to a wrong file:
https://github.com/RetroShare/RetroShare/releases/download/v0.6.5/Retroshare-0.6.5.OSX-10.13+.dmg

**Comment by G10h4ck** [comment]
Most probably the binary is of 0.6.5 version but then it reports a wrong version due to some bug in the build system, on MacOS we have a bunch of users but very few developers, it would be very helpful to get help to have good support on that platform

**Comment by defnax** [comment]
I get last day a iMac, I wanted test the macOS dmg from 2018 but it crashes here
MacOs 10.13.6 High Sierra

```
`Process:               retroshare [834]
Path:                  /private/var/folders/*/retroshare.app/Contents/MacOS/retroshare
Identifier:            com.retroshare
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           retroshare [834]
User ID:               501

Date/Time:             2020-03-07 14:52:47.448 +0100
OS Version:            Mac OS X 10.13.6 (17G66)
Report Version:        12
Anonymous UUID:        148B306C-B59C-ACD2-AD20-4C2BB36E294D

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/nettle/3.4.1/lib/libnettle.6.dylib
  Referenced from: /private/var/folders/gv/1w88v44d5r33tvs3qv2m94wh0000gn/T/AppTranslocation/AF729BF4-154D-4215-AC82-01E5632F500E/d/retroshare.app/Contents/Frameworks/libhogweed.4.dylib
  Reason: image not found
```

**Comment by G10h4ck** [comment]
seems you miss libnettle, you can install that with brew

**Comment by defnax** [comment]
> seems you miss libnettle, you can install that with brew

im new to macos but i get it run :)

**Comment by defnax** [comment]
I found another issue svgs not showing on settings.
![image](https://user-images.githubusercontent.com/9952056/76166793-8b98f280-6161-11ea-9aa6-afc46ac3759e.png)
im surprised less people report some issues on macOS, im not sure who created the macOS binary?
And DHT still doesn't works there I see always red, I prefer users to use fusion style for macOS users.
the macOS style isn't optimized on some tabs with icons.

Issues:

* When closing via (X) you cant bring it back more in front of the window (Dock)
* DHT always red ( bdboot.txt is missed)
* SVG icons not loaded on settings ( svg library maybe in wrong place)
* When tab icons are bigger then 16*16 it goes out of the tab (macos style)

**Comment by csoler** [comment]
SVG not showing typically is a missing qtsvg.dll on windows. There's probably something similar going on on MacOS. Maybe one of the dependencies in making the build is missing?

**Comment by defnax** [comment]
> SVG not showing typically is a missing qtsvg.dll on windows. There's probably something similar going on on MacOS. Maybe one of the dependencies in making the build is missing?

i saw the svg file on a different folder into "iconengines" instead of "imageformats"
but im not sure how is working on mac to check the dll file path.

**Comment by guglez** [comment]
> Most probably the binary is of 0.6.5 version but then it reports a wrong version due to some bug in the build system, on MacOS we have a bunch of users but very few developers, it would be very helpful to get help to have good support on that platform

I don't think so. I believe it's an old version.

**Comment by GuillaumeHemmen** [comment]
The error "Library not loaded: /usr/local/Cellar/nettle/3.4.1/lib/libnettle.6.dylib" seem to be related to the fact RetroShare is trying to load an old version of the lib. I have already `libnettle` on my system but since I upgraded my brew packages retroShare is broken.

I am not familiar with macOS development (and I haven't touched C/QT since ages) but I'll try to see if I can investigate :)

**Comment by GuillaumeHemmen** [comment]
I found a solution to the issue: I just recompiled the project with the latest libnettle version (from brew) and it works again.

I guess that the contributor just need to redo a package of the dmg, it has been a long time now since the latest macOS release of the app ;P

**Comment by GuillaumeHemmen** [comment]
Got a new development on my side:

While the re-compilation work the program now crashes after I got authenticated (using the tor network). Here is the runtime log from the app: https://gist.github.com/GuillaumeHemmen/08b66ff760070014eee403a7edc4dd89

At this point, I have no idea what's wrong and what should be done to continue the investigation

**Comment by defnax** [comment]
always solved close this @G10h4ck
