### ISSUE TITLE
[Bug] Windows QT5 installer by Sub broken

### ISSUE THREAD

**Issue by heini** [RetroShare/RetroShare#183]
While the QT4 version was fine, the QT5 version is broken. It does'nt install everything needed to actually run RS, leading to an immediate error message when starting it (see comment here: retroshare://channel?name=RetroShare%200.6%20build%202015-10-26&id=04d143f22eef5093c2a2a9d7c4477db8&msgid=2bb4fb99d3940e1e8e836e11c102fca059f512e5):

> This application failed to start because it could not find or load the Qt platform plugin "windows".
> Reinstalling the application may fix this problem."

The reason for this is that several files are missing in the installation, compared to the portable version, which works just fine (see comment here: retroshare://channel?name=RetroShare%200.6%20build%202015-11-07&id=04d143f22eef5093c2a2a9d7c4477db8&msgid=b87b27e802358ae866a2a96a70c1180d350d903c):
- The "platforms" directory, which contains the Qt platform plugin.
- 4 DLLs from the "imageformats" directory, namely
- qicns.dll
- qjp2.dll
- qwbmb.dll
- qwebp.dll
- Lots of translations from the "translations" directory (44 vs. 113)

Please fix the Qt 5 installer or start providing the working Qt4 installer again.

**Comment by defnax** [comment]
i dont know where you get that Installer Files, we are not the creator of the Installers!
Its not from the Dev Team. Contact the Author, and ask him if  he can make a PR for Installer script fixes for Qt5.

**Comment by heini** [comment]
Already tried to do that via comments in his RS channel, via reports in the RS bug forums, but I didn't get any reaction so far, so I tried it here, too. Will try to contact him personally...

OTOH: RS dev team: please provide current Windows installer packages :smirk:

**Comment by heini** [comment]
Has meanwhile been fixed.
