### ISSUE TITLE
[Linux] Unable to remove contacts from list.

### ISSUE THREAD

**Issue by XZVB12** [RetroShare/RetroShare#1848]
Hello, I want to delete contacts that haven’t been online for a long time (more than a month), but I can’t do this. When i try to delete a contact, it is temporarily moved to the general list of users, but then returned to the contact list. Changing a reputation is also impossible.
I use:
- Arch Linux x64 Kernel 5.6.2
- The latest officially compiled version of RetroShare (0.6.5), I also compiled a version from this repository, but that didn't help. (RetroShare Version: 0.6.5-1153-gdb42c7a97).

Additional Information:

QT 5.14.1
libretroshare
 - bzip2: 1.0.8, 13-Jul-2019
 - OpenSSL: OpenSSL 1.1.1f 31 Mar 2020
 - SQLite: 3.30.1
 - SQLCipher: 4.3.0 community
 - UPnP (libupnp): 1.6.25
 - Zlib: 1.2.11

Sorry to bother you and thank you for your attention.

**Comment by csoler** [comment]
hi,
Identities signed by friend nodes are automatically added to contacts. You can disable this behavior in preferences->people

**Comment by XZVB12** [comment]
@csoler  Hello, thanks for the answer. I saw this parameter, but did not expect it to cause a conflict.
The topic is closed, thanks and sorry for the trouble.
