### ISSUE TITLE
pqisslpersongrp warning

### ISSUE THREAD

**Issue by realityfabric** [RetroShare/RetroShare#185]
The warning message output in Terminal reads:

```
pqisslpersongrp::locked_createPerson WARNING INVALID HIDDEN TYPES - THIS SHOULD NOT HAPPEN!
-ID: [redacted]
-mPeerMgr->isHidden(): 0
-mPeerMgr->isHiddenPeer(id): 1
-hidden types: peer=1 own=0
--> falling back to Tor
```

The operating system is lubuntu, running on a vm.

I'm submitting this as an issue because it says here https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/pqi/pqisslpersongrp.cc#L112 that it should not happen.

Could it be because the default case is above another case?

**Comment by realityfabric** [comment]
Altering the order of the switch statement so that the default case was on the bottom did not fix this issue.

I got the exact same readout as above.

**Comment by realityfabric** [comment]
It looks like the reason the warning should not happen is because the function `locked_createPerson` should already have checked to see if the local node is a hidden node, but it doesn't appear that any such check happens inside of the function (it only checks which type of hidden node it is if the peer isn't hidden, and if it is not `HIDDEN_TYPE_TOR` or `HIDDEN_TYPE_I2P` then it prints the warning message).

It's possible I'm misunderstanding what `mPeerMgr->isHiddenPeer(id)` and `mPeerMgr->isHidden()` do (as far as I can tell they both check to see if the peer is hidden).

If I'm wrong about `mPeerMgr->isHidden()` and it is actually checking if the local node is hidden, then the function still assumes that the local node is hidden (if the peer node is hidden).

**Comment by electron128** [comment]
`mPeerMgr->isHiddenPeer(id)` is for friends, `mPeerMgr->isHidden()` is for own node.

The interesting part is: the hidden type of your friend is 1 which is RS_HIDDEN_TYPE_UNKNOWN. This value is returned by `p3PeerMgrIMPL::hiddenDomainToHiddenType` if the hidden adress does not end with ".onion" or ".i2p".

Does your friend have a proper hidden adress?
Is it correct, that you are not hidden?
Is it correct, that your friend is hidden?

**Comment by realityfabric** [comment]
> Does your friend have a proper hidden address?

No, my friend was still trying to configure Tor for the hidden service.

> Is it correct, that you are not hidden?
> Is it correct, that your friend is hidden?

Yes, my node isn't a hidden node, and yes, my friend is using a hidden node.

I hadn't realized there was a value for `RS_HIDDEN_TYPE_UNKNOWN`, I should have looked at the actual values of the RS Hidden Types.

Should the warning message be more specific about which type it is detecting? And should RetroShare handle `RS_HIDDEN_TYPE_UNKNOWN` differently than `RS_HIDDEN_TYPE_NONE`? It seems like the reason the code that "should not happen" is running is because RetroShare doesn't distinguish between a node that isn't a hidden node and a node that is a hidden node but isn't configured properly.

**Comment by electron128** [comment]
The warning message is ok. The GUI should display info why a connection to a peer may be impossible.

Examples:
"Cannot connect, because Peer uses Tor and you don't have configured Tor properly."
"Cannot make outgoing connection, because we don't have a location. Try to exchange certs again."
"Warning, you have limited connectivity, because DHT is disabled and the forwarded port does not work. Open a port or enable DHT."
