### ISSUE TITLE
forum tooltip rank down unsubscribe

### ISSUE THREAD

**Issue by cavebeat** [RetroShare/RetroShare#187]
It happens often to unsubscribe a forum by accidently clicking the first button. 

![old tooltip](https://retroshare.rocks/pics/old.png)

Please toggle "unsubscribe" and "open in new tab"
![new tooltip](https://retroshare.rocks/pics/new.png)

**Comment by chozabu** [comment]
Ahh, glad it is not just me that happens to ;) I think the DE I switched to a while ago, or QT5 handles context menus a little differently, and makes it easier to make this mistake.

Would not be suprised if this is the relevant part to change `$ egrep -r "Open in new tab" *`
`retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.cpp:             action = contextMnu.addAction(QIcon(IMAGE_TABNEW), tr("Open in new tab"), this, SLOT(openInNewTab()));`
