### ISSUE TITLE
[Question][API] Is there a way to force distant chat connection?

### ISSUE THREAD

**Issue by b1rdG** [RetroShare/RetroShare#1928]
Hi,

My workaround with distant chats is the following:

1. Initate distant chat connection:

```bash
curl -u  "id:pass"  -d '{ "to_pid":"","from_pid":"" }' http://127.0.0.1:9092/rsMsgs/initiateDistantChatConnexion
```

2. Then with the resulting distant chat tunnel id I send a message to a desktop application that spawn a chat dialog:

```bash
curl -u  "id:pass"   -d '{ "id": {"type":2,"distant_chat_id":""},"msg":"how are you" }' http://127.0.0.1:9092/rsMsgs/sendChat
```

3. After dialog is spawned on Desktop app I close it and check for distant chat status:

```bash
curl -u  "id:pass" -d '{ "pid":""}' http://127.0.0.1:9092/rsMsgs/getDistantChatStatus
{
    "info": {
        "to_id": "",
        "own_id": "",
        "peer_id": "",
        "status": 1,
        "pending_items": 0
    },
    "retval": true
}
```

Where `"status":1` is `RS_DISTANT_CHAT_STATUS_TUNNEL_DN`. To be able to talk and notify at the moment the status must be 2 (`RS_DISTANT_CHAT_STATUS_CAN_TALK`). 

So if I do `sendChat` again, the chat dialog spawn is delayed some minutes, even if I try the `initiateDistantChatConnexion` method. 

The question is, **there are any possible way to force that chat status change from 1 to 2 to send messages quickly**? 

Thanks.

**Comment by sehraf** [comment]
> The question is, there are any possible way to force that chat status change from 1 to 2 to send messages quickly?

nope, as RS has to build up the tunnel to send the message.
For distant chat to work, RS will build a tunnel to the receiving chat partner. The tunnel is similar to the ones used for file sharing. This process can take some time or fail completely. The tunnel status is represented by `status`. This cannot be forced.

**Comment by sehraf** [comment]
i don't know the current state of offline-chat messages. If i remember correctly your RS stored direct chat messages until the other peer comes online again. 
Mail works offline too (even when both parties are never online at the same time).

For chat i have no idea :question:  The distant chat **tunnel** only works when both are online at the same time.

**Comment by b1rdG** [comment]
I think you are right about the offline messages, and for distant chats are not currently supported. For the Android app, maybe I implement offline messages using "email" backend to fix this.

For the moment, as I know, there are no new chat system implementation planned, only [unseenp2p](https://github.com/unsenep2pdev/RetroShare/issues/25), and I'm not sure if this chat system is going to be adopted for the desktop app. I believe that improve the chat system is a good feature for the Android app and new users. Now, distant chats, didn't store the chat history, can't support offline messages and didn't have features that modern chat apps have.

Hopefully, in few days I will finish basic implementation for chats on Android app and I will jump to forums support. I encourage developers to think about how to improve distant chats to fit more modern features :)
