### ISSUE TITLE
In file lists see total mb,gb,tb size of total content shared by somebody.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#196]
In file lists to be able to see total mb,gb,tb size of total content shared by somebody. In dc++ it shows and is nice becasue you can try to beat others sharing more, or know if somebody has lot of content or not without exploring the whole file list.

It should be easy to implement, i think file size is inside the list info file.

**Comment by electron128** [comment]
this was implemented in 5ef4e752d98dc6268e46a710d09acc12536a0c76
