### ISSUE TITLE
[crash] Switching between channels to fast cuases crash

### ISSUE THREAD

**Issue by NyvenZA** [RetroShare/RetroShare#1965]
If you click on one channel , then click on another channel and then swap back to the first repeatadly, Retroshare crashes. 

Could reproduce with Windows Build 1513 and 1432

Crash backtrace on Windows
[20200522-build1513-channelcrash1.txt](https://github.com/RetroShare/RetroShare/files/4666452/20200522-build1513-channelcrash1.txt)

**Comment by jolavillette** [comment]
Confirmed on Ubuntu 18.04.
Seems to be a crash in a gui async thread.

Thread 215 "retroshare" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5effd700 (LWP 28094)]
0x000055556154a970 in ?? ()
(gdb) where
#0  0x000055556154a970 in ?? ()
#1  0x00007ffff467f6a9 in QMetaObject::cast(QObject const*) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00005555564896b0 in qobject_cast<QThread*> (object=0x55556153cff0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:515
#3  0x000055555677220f in RsQThreadUtils::postToObject<GxsChannelPostItem::loadMessage()::<lambda()>::<lambda()> >(GxsChannelPostItem::<lambda()>::<lambda()> &&, QObject *) (fun=..., obj=0x55556153cff0) at ./util/qtthreadsutils.h:101
#4  0x000055555676f310 in GxsChannelPostItem::<lambda()>::operator()(void) const (__closure=0x555562d6ebb8) at gui/feeds/GxsChannelPostItem.cpp:337
#5  0x0000555556772cf4 in std::_Function_handler<void(), GxsChannelPostItem::loadMessage()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#6  0x0000555556495f70 in std::function<void ()>::operator()() const (this=0x555562d6ebb8) at /usr/include/c++/7/bits/std_function.h:706
#7  0x0000555556494bc7 in std::__invoke_impl<void, std::function<void ()>>(std::__invoke_other, std::function<void ()>&&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#8  0x00005555564937ca in std::__invoke<std::function<void ()>>(std::function<void ()>&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#9  0x000055555649898e in std::thread::_Invoker<std::tuple<std::function<void ()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555562d6ebb8) at /usr/include/c++/7/thread:234
#10 0x000055555649894a in std::thread::_Invoker<std::tuple<std::function<void ()> > >::operator()() (this=0x555562d6ebb8) at /usr/include/c++/7/thread:243
#11 0x000055555649891a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::function<void ()> > > >::_M_run() (this=0x555562d6ebb0) at /usr/include/c++/7/thread:186
#12 0x00007ffff3f016df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff41d46db in start_thread (arg=0x7fff5effd700) at pthread_create.c:463
#14 0x00007ffff35be88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

**Comment by NyvenZA** [comment]
Also affected build 1524

**Comment by PhenomRetroShare** [comment]
Can you test PR #1973 ?

**Comment by felisucoibi** [comment]
it happens to me too, i forgot to report i said it in devs channel.

**Comment by NyvenZA** [comment]
With the re-write of the Channels, this issue has been resolved. 
#1994
