### ISSUE TITLE
rsFiles->alreadyHaveFile(...) should look also in extra files list

### ISSUE THREAD

**Issue by G10h4ck** [RetroShare/RetroShare#1983]
As of today if a file has been added to the extra files list, `alreadyHaveFile` return false as if the file was unknown to retroshare, instead it should return `true` and the information about the files

@csoler what do you think about this?
I think I can do a PR in few hours if you agree

**Comment by csoler** [comment]
sure. I can't see a situation where it could be a problem to have.
