### ISSUE TITLE
Moving up to C++ Standard 2011?

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#20]
I've noticed that a lot of code in Retroshare are still behind 2011/2014 standards (Aka -std=c++11) and I decided to work toward moving it up to a more current standard on my fork and I am wondering where does RetroShare developers stand on moving up to a more current standard? Should we go for C++ 2014 Standard?

**Comment by csoler** [comment]
As far as I'm concerned (and I am pretty sure drbob agrees on this), re-coding just for the sake of upgrading/unifying code standards does more arm than good. It introduces bugs, prevents former devs to find information easily, makes big commits where to hide nasty things. So we won't take patches for this. Sorry!

**Comment by ghost** [comment]
No problem!
