### ISSUE TITLE
Request that PPA update to ubuntu "focal"

### ISSUE THREAD

**Issue by RanTrycl** [RetroShare/RetroShare#2027]
I know that this version of linux mint is quite new but am greatly looking forward to reinstalling retroshare. Thank you!

**Comment by felisucoibi** [comment]
+1

**Comment by AlekzNet** [comment]
That would be great!

**Comment by G10h4ck** [comment]
Done!

https://build.opensuse.org/project/show/network:retroshare

Thanks for reminding, please reopen if in a few days the package is still not available (most probably only the unstable version will be able to build on new ubuntu)
