### ISSUE TITLE
Easier way to install `retroshare-nogui`

### ISSUE THREAD

**Issue by Atlas48** [RetroShare/RetroShare#2070]
Hi, I'm running a small arch vps, and I'm having a spot of trouble trying to install `retroshare-nogui`. Compiling from source seems to result in various unknown errors, and there's no apparent option to install such with a package manager.

If there's no package already, personally I'd like some way to access retroshare-nogui through a package manager.

**Comment by zeners** [comment]
I'm building it daily without problems, how you try to do it?
I'm using https://aur.archlinux.org/retroshare-git with patched compiler options to use webui.

**Comment by csoler** [comment]
using the code on unstable, retroshare-nogui is gone. Now you need to compile retroshare_service. See the howto in https://github.com/retroshare/rsnewwebui. Make sure to compile RS using CONFIG+="rs_jsonapi rs_webui". The later is missing in the howto.

**Comment by Atlas48** [comment]
@csoler so can we have that available on a package manager?

I *really* don't feel confident having to compile from source each time I have to update.
