### ISSUE TITLE
Maybe it's time for RETROSHARE 6.0?

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#2075]
As idea, 0.6.5 is very far from actual rs status, users that don't install beta are from the past, literally 1years form the past.

**Comment by veryprivate** [comment]
They have a valid point

**Comment by NyvenZA** [comment]
The Current master is RC1. 
There is a Development Forum post for 0.6.6 RC1 with all the bug fixes that has been addressed. This is internal on RS forums.

**Comment by felisucoibi** [comment]
> The Current master is RC1.
> There is a Development Forum post for 0.6.6 RC1 with all the bug fixes that has been addressed. This is internal on RS forums.

Thanks for answering, yes i'm testing latest's pr's, nice to see all these bugs fixeds, a pitty they dont agree with mee to change RS name from 0.6.6 to 6.6, or just 6.0 rs is in beta since 2006...

**Comment by defnax** [comment]
i agree with you the version number changes goes so very slowly now we must be on 0.7...0.8
