### ISSUE TITLE
nettle 3.4.1 required, but only 3.6 available via brew on Mac OSX (Includes Workaround)

### ISSUE THREAD

**Issue by veryprivate** [RetroShare/RetroShare#2080]
# Issue
Required nettle library version 3.4.1 no longer readily available on Mac

# System
In the current Retroshare version on Mac there is a discrepancy between version number displayed in application vs version number in the download.
Retroshare Version (reported) : 0.6.0-RC2-5290-g8269767f7
Retroshare Version (downloaded):  0.6.5
OS: maxOs Catalina 10.15.7 (19H2)

# Steps to reproduce
To display errors I am starting application from the command line.

```
cd /Applications/retroshare.app/Contents/MacOS
./retroshare 
dyld: Library not loaded: /usr/local/Cellar/nettle/3.4.1/lib/libnettle.6.dylib
  Referenced from: /Applications/retroshare.app/Contents/Frameworks/libhogweed.4.dylib
  Reason: no suitable image found.  Did find:
	/usr/local/Cellar/nettle/3.4.1/lib/libnettle.6.dylib: stat() failed with errno=13
	/usr/local/lib/libnettle.6.dylib: stat() failed with errno=13
zsh: abort      ./retroshare
```

# Thoughts
There is a nettle Framework file installed as part of the application. Why are we getting this error? A missing dependency ?
```
Frameworks/libnettle.6.dylib 
MD5 (Frameworks/libnettle.6.dylib) = a09d990f037db265d98ca0364fbc1002
```

# Work around
Install very old version of nettle library

```
# Install homebrew as per https://docs.brew.sh/Installation
# We are now going to install an old version of nettle that doesn't have a versioned tap.
# Go to the brew formulae
cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
# Brew - Go back in time to the last update for nettle 3.4.1
git checkout 2fab2c02edd
# Install this file, replace if necessary
brew reinstall ./nettle.rb
# Verify  should say nettle/3.4.1
brew info nettle
# Stop this package from being upgraded in the future
brew pin nettle
# Brew - Restore brew to normal.
git checkout master
```

**Comment by defnax** [comment]
hi, you has compiled retroshare on Mac?

**Comment by veryprivate** [comment]
No, not yet.  Originally I strongly wanted to compile for my Mac.  After using Retroshare for a few months I found it very frustrating. I have stopped using Retroshare for a few months. I may return.

**Comment by defnax** [comment]
we need help on mac platform, i has attemped to compile but get some issues.
the old build from 2019 its very outdated.

**Comment by defnax** [comment]
> No, not yet. Originally I strongly wanted to compile for my Mac. After using Retroshare for a few months I found it very frustrating. I have stopped using Retroshare for a few months. I may return.

we has published retroshare 0.6.6 for macos, needs to be tested

**Comment by Coool** [comment]
To fix it
`install_name_tool -change /usr/local/Cellar/nettle/3.4.1/lib/libnettle.6.dylib @executable_path/../Frameworks/libnettle.6.dylib libhogweed.4.dylib`

**Comment by cinealfa** [comment]
I don't understand cool what exactly am I doing with the "fix"
I get this error when I run it in terminal:
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: libhogweed.4.dylib (No such file or directory)

**Comment by Coool** [comment]
Can't you read? Can't open file libhogweed.4.dylib. You are executing command in path which don't contain libhogweed.4.dylib file.

**Comment by veryprivate** [comment]
> Can't you read? Can't open file libhogweed.4.dylib. You are executing command in path which don't contain libhogweed.4.dylib file.

Perhaps English isn't your first language but (to me) your response came across as rather curt.
Not everyone is a command line wizard.
To be honest I've been using Mac/Un*x CLIs for decades and I am having difficulty understanding what the commands are, even if it is two commands (more likely) or just one.
Also I'm having problems understanding "@executable_path".  Is that to be typed as is, or a short hand ?

**Comment by cinealfa** [comment]
Yes I can read, started reading at 18 months, and probably have improved
since then. The question is can you write? Because your initial post made
virtually no sense. The lib is not installed is obvious and not what I was
asking for. But you consider lobbing insults and single lines of useless
commands as help.  If you want help then respond politely and I will in
turn respond politely . Otherwise, I find a person who can. Btw if English
is not your first language I applaud your effort, I would recommend looking
in examples of polite english replies.

**Comment by defnax** [comment]
thats always fixed @G10h4ck please close
