### ISSUE TITLE
I2P: Switch from BOB to SAMv3

### ISSUE THREAD

**Issue by zzzi2p** [RetroShare/RetroShare#2087]
I2P has deprecated the BOB interface https://geti2p.net/en/docs/api/bob and would like to get all users moved over to SAMv3 https://geti2p.net/en/docs/api/samv3 and set a schedule for removing BOB completely in the next year.

It appears that RetroShare may be the last remaining BOB application with active users. We don't want to break RetroShare for them but we'd like them to have the stronger encryption options and good support offered by SAMv3.

**Comment by sehraf** [comment]
Hey zzz,

thanks for dropping by. I've a local branch with SAMv3 support. In a rough shape though. 
My plan is to get it merged once RS 0.6.6 is released.

**Comment by sehraf** [comment]
Update regarding http://zzz.i2p/topics/2973-proposal-remove-bob @zzzi2p 
I'm currently working on the gui bits and the plan is to merge it, when it is done. This can be either before or after the release of 0.6.6. Cyril said, that there are still a few bugs to hunt, so i'm optimistic, that i might be done before the release. 

I cannot give you a time schedule, though i agree with 
> But we should be on track to kill BOB off completely some time next year.

**Comment by zzzi2p** [comment]
Thanks for the updates, and thanks to orignal for getting SAMv3 STREAM FORWARD working for you. It's really good news that you were already working on SAM and are receptive to completing the transition.
We (Java I2P) are not in that much of a hurry, and i2pd may be willing to support BOB even longer. The important thing is that we have a plan to turn it off at some point rather than keeping it alive forever.
The motivation for you to get off BOB is that it's DSA-SHA1 only . SAMv3 offers you the SIGNATURE_TYPE option to get to EdDSA. Also, as you saw with orignal's response, both Java I2P and i2pd should be able to quickly address any issues that arise with SAMv3. I encourage you to test both in your development process. Thanks.

**Comment by sehraf** [comment]
Branch is available here https://github.com/sehraf/RetroShare/tree/pr_add_i2p_sam3
No pr yet, since i'm force pushing from time to time.

You can upgrade and downgrade between SAM and BOB.

**Comment by eyedeekay** [comment]
@sehraf I see you have forked libsam3 and adapted it, I would like to merge the necessary changes back into i2p/libsam3 if possible and have started to work on doing so here: https://github.com/i2p/libsam3/compare/branch_credit_retroshare_sehraf I appreciate all the work you did to make it work with new SIGNATURE_TYPES. I would like to test your SAM3 based branch of RetroShare but have not been able to build it yet. Can you direct me to instructions for producing a dev build? When I attempt to use the instructions at: https://retroshare.readthedocs.io/en/latest/developer/compilation/ I get the following error:

        cd openpgpsdk/src/ && ( test -e Makefile.openpgpsdk || /usr/lib/qt5/bin/qmake -o Makefile.openpgpsdk /home/user/Workspace/CPP/RetroShare/openpgpsdk/src/openpgpsdk.pro CONFIG+=debug ) && make -f Makefile.openpgpsdk 
        make[1]: Entering directory '/home/user/Workspace/CPP/RetroShare/openpgpsdk/src'
        make[1]: Nothing to be done for 'first'.
        make[1]: Leaving directory '/home/user/Workspace/CPP/RetroShare/openpgpsdk/src'
        cd libbitdht/src/ && ( test -e Makefile.libbitdht || /usr/lib/qt5/bin/qmake -o Makefile.libbitdht /home/user/Workspace/CPP/RetroShare/libbitdht/src/libbitdht.pro CONFIG+=debug ) && make -f Makefile.libbitdht 
        make[1]: Entering directory '/home/user/Workspace/CPP/RetroShare/libbitdht/src'
        make[1]: Nothing to be done for 'first'.
        make[1]: Leaving directory '/home/user/Workspace/CPP/RetroShare/libbitdht/src'
        cd libretroshare/src/ && ( test -e Makefile.libretroshare || /usr/lib/qt5/bin/qmake -o Makefile.libretroshare /home/user/Workspace/CPP/RetroShare/libretroshare/src/libretroshare.pro CONFIG+=debug ) && make -f Makefile.libretroshare 
        make[1]: Entering directory '/home/user/Workspace/CPP/RetroShare/libretroshare/src'
        cd /home/user/Workspace/CPP/RetroShare && ( git submodule update --init supportlibs/udp-discovery-cpp || true ) && mkdir -p /home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp && cd /home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp && cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ "-DCMAKE_CXX_FLAGS=-pipe -Wno-deprecated -Wno-deprecated-declarations -Wno-cpp -Wno-inconsistent-missing-override -O0 -g -fno-omit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64" -DBUILD_EXAMPLE=OFF -DBUILD_TOOL=OFF -DCMAKE_INSTALL_PREFIX=. -B. -H/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp && make
        CMake Warning (dev) in CMakeLists.txt:
          No project() command is present.  The top-level CMakeLists.txt file must
          contain a literal, direct call to the project() command.  Add a line of
          code such as

            project(ProjectName)

          near the top of the file, but after cmake_minimum_required().

          CMake is pretending there is a "project(Project)" command on the first
          line.
        This warning is for project developers.  Use -Wno-dev to suppress it.

        -- Configuring done
        -- Generating done
        -- Build files have been written to: /home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp
        make[2]: Entering directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        make[3]: Entering directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        make[4]: Entering directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        make[4]: Leaving directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        [100%] Built target udp-discovery
        make[3]: Leaving directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        make[2]: Leaving directory '/home/user/Workspace/CPP/RetroShare/supportlibs/udp-discovery-cpp'
        cd /home/user/Workspace/CPP/RetroShare && cp -r /home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/* /home/user/Workspace/CPP/RetroShare/supportlibs/libsam3 && cd /home/user/Workspace/CPP/RetroShare/supportlibs/libsam3 && make build
        cp: '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/Makefile' and '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/Makefile' are the same file
        cp: '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/README.md' and '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/README.md' are the same file
        cp: '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/examples' and '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/examples' are the same file
        cp: '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/src' and '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/src' are the same file
        cp: '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/test' and '/home/user/Workspace/CPP/RetroShare/supportlibs/libsam3/test' are the same file
        make[1]: *** [Makefile.libretroshare:1226: ../../supportlibs/libsam3/libsam3.a] Error 1
        make[1]: Leaving directory '/home/user/Workspace/CPP/RetroShare/libretroshare/src'
        make: *** [Makefile:102: sub-libretroshare-src-libretroshare-pro-make_first] Error 2

**Comment by sehraf** [comment]
Hi @eyedeekay  to be fair, my contributions to libsam3 are minimal, they can be found [here](https://github.com/sehraf/libsam3/commits/certfix)
- the first commit fixes some size checks, though i'm not 100% sure that it is correct now. I usually get lost between destination, certificate, base64 and raw byte sizes :roll_eyes: 
- the seconds patch hard codes `SILENT=True` which makes life easier for RS.

Maybe you can create the separate issue/pr to discuss the changes. 

Regarding compiling my branch: You are doing an "in-tree build" (in other words you don't use a separate build directory) this might be the problem, that would be my fault then. So thanks for pointing that out :smile: A quick fix would be to use a building directory: Create it somewhere and then append the path to your RS git tree to qmake, e.g. `cd ~/Projects/RetroShare-build; qmake ~/Projects/RetroShare`

I was hoping to have the branch merged by now but i'm struggling with the windows build at the moment ... (why can't everybody use Linux?!) Beside that it seems stable to me.

**Comment by eyedeekay** [comment]
Oh I see! I did it kind of backward and diffed the one I found in supportlibs. OK now I'm caught up, it looks like you're building off of what I opened this [PR](https://github.com/i2p/libsam3/pull/8) for a couple years ago, which I was not entirely sure I got right. Looks like you found a couple of my mistakes too :). Looking at your changes, and thinking back to when I was working on it before, I believe that is how `SAM3_PRIVKEY_MIN_SIZE` is supposed to be used in those circumstances. [Opened a PR with your changes to my certfix branch here](https://github.com/eyedeekay/libsam3/pull/2). I want to make sure that `SILENT=True` is optional for other library users, but otherwise LGTM.

Edit: got my copy compiled, confirmed that it is working so far.

**Comment by eyedeekay** [comment]
@sehraf The changes are merged into i2p/libsam3, so you should be able to use that library in the future if you want. Just use `sam3CreateSilentSession` to get your silent session.

**Comment by sehraf** [comment]
Neat! Do you plan to have "official" windows support? :sweat_smile:

**Comment by eyedeekay** [comment]
Seems pointless not to, but it seems to me like it should already work? If there's something that is blocking it from working on Windows file an issue at https://github.com/i2p/libsam3 and we can work on it there.

**Comment by sehraf** [comment]
Quick status update: everything works fine and thanks to @eyedeekay windows works, too.
I'm ironing out some last rare bugs and wait for a fix for libsam3 https://github.com/i2p/libsam3/issues/10

**Comment by eyedeekay** [comment]
Hey we fixed `SILENT=true` and tested use with `SAM`, is there a time when you expect to be able to merge this and cut a new release? We would like to deprecate `BOB` in 1-2 quarters but with RetroShare using `BOB` that may not be ideal.

**Comment by sehraf** [comment]
Ask one of the RS devs when they plan to merge this. Or just phaseout BOB support and wait for enough peopel to complain to the RS devs :man_shrugging: #2132 is ready since 7 months ...
