### ISSUE TITLE
[Javascript] Web Ui Developers wanted

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#2160]
Hi,
ouer Webui is not realy functional or yet useable.
We need some active javascript developers.

Webui needs some work at the moment cant do anything with it.
importend this features first:

* Private Chat (Network)
* Distant Chat (People)
* Send Message (Mails)
* Chats 

Later:
* Channels/Boards/Forums/Wire

**Repository:**
https://github.com/RetroShare/RSNewWebUI

**Readme (JSON API):**
https://github.com/RetroShare/RetroShare/blob/master/jsonapi-generator/README.adoc

**RetroShare interface headers:**
https://github.com/RetroShare/RetroShare/tree/master/libretroshare/src/retroshare

Todo basic ideas:
* Network -> Chat Widget for direct chats
* Network -> Friend Node ->Feature to start a Mail/Chat
* People -> Display Contacts better & feature to Start a Chat/Mail (via Button)
* Mail -> Start a New Mail, Reply/Reply all/Forward Mail features (what we have in Qt ui )

**Comment by zeners** [comment]
Can you please outline, where to get a brief description of the provided endpoints, without the knowledge of C***?
This is essentially to extend the existing frontend.

**Comment by defnax** [comment]
> Can you please outline, where to get a brief description of the provided endpoints, without the knowledge of C***?
> This is essentially to extend the existing frontend.

Hi, i dont know anything yet.
but there is doc here not sure if its useful for you:
https://github.com/RetroShare/RetroShare/tree/master/jsonapi-generator
https://github.com/RetroShare/RetroShare/blob/master/jsonapi-generator/README.adoc


You can find on the interface headers some information (on 23 headers) 
>brief, param, return:
https://github.com/RetroShare/RetroShare/tree/master/libretroshare/src/retroshare

i dont know if you mean that example:

>class RsGxsCircles: public RsGxsIfaceHelper
{
public:

	RsGxsCircles(RsGxsIface& gxs) : RsGxsIfaceHelper(gxs) {}
	virtual ~RsGxsCircles();

	/**
	 * @brief Create new circle
	 * @jsonapi{development}
	 * @param[in] circleName String containing cirlce name
	 * @param[in] circleType Circle type
	 * @param[out] circleId Optional storage to output created circle id
	 * @param[in] restrictedId Optional id of a pre-existent circle that see the
	 *	created circle. Meaningful only if circleType == EXTERNAL, must be null
	 *	in all other cases.
	 * @param[in] authorId Optional author of the circle.
	 * @param[in] gxsIdMembers GXS ids of the members of the circle.
	 * @param[in] localMembers PGP ids of the members if the circle.
	 * @return false if something failed, true otherwhise
	 */

> class RsGxsChannels: public RsGxsIfaceHelper, public RsGxsCommentService
{
public:
	explicit RsGxsChannels(RsGxsIface& gxs) : RsGxsIfaceHelper(gxs) {}

	/**
	 * @brief Create channel. Blocking API.
	 * @jsonapi{development}
	 * @param[in]  name         Name of the channel
	 * @param[in]  description  Description of the channel
	 * @param[in]  thumbnail    Optional image to show as channel thumbnail.
	 * @param[in]  authorId     Optional id of the author. Leave empty for an
	 *                          anonymous channel.
	 * @param[in]  circleType   Optional visibility rule, default public.
	 * @param[in]  circleId     If the channel is not public specify the id of
	 *                          the circle who can see the channel. Depending on
	 *                          the value you pass for
	 *                          circleType this should be be an external circle
	 *                          if EXTERNAL is passed, a local friend group id
	 *                          if NODES_GROUP is passed, empty otherwise.
	 * @param[out] channelId    Optional storage for the id of the created
	 *                          channel, meaningful only if creations succeeds.
	 * @param[out] errorMessage Optional storage for error messsage, meaningful
	 *                          only if creation fail.
	 * @return False on error, true otherwise.
	 */

**Comment by csoler** [comment]
read the README on https://github.com/retroshare/RSNewWebUI

**Comment by zeners** [comment]
thx for the answers,
i'm little bit confused: If there is doxygen used to generate the jsonapi documentation (maybe in xml), where the hell is it after build?
in the referred example there is a request against /rsFiles/turtleSearchRequest (this i'm calling an endpoint) based on RsGxsChannels::turtleSearchRequest, where does the rsFiles come into play?

**Comment by csoler** [comment]
doxygen generates xml from commented .h files (e.g. rsfiles.h), which then are turned into .h/.cpp files by an automated process. These files provide all the boilerplate code to export/receive calls and data from libretroshare to a JS client. In the end the JS client only needs to make requests to e.g. localhost/retroshare/rsfiles/some_method?someparam=somevalue

**Comment by zeners** [comment]
ok, all i need is that list of possible to make requests to
I will try to modify the configuration of doxygen / jsonapi-generator to generate that list, i'm afraid that it will take a while ...

**Comment by csoler** [comment]
Do you mean all the methods in libretroshare/src/retroshare/*.h ?

**Comment by zeners** [comment]
@csoler yeah, what is a good hint

with this i get the interesting ones: grep -c "@jsonapi" *.h|grep -v ":0"

**Comment by defnax** [comment]
> @csoler yeah, what is a good hint
> 
> with this i get the interesting ones: grep -c "@jsonapi" *.h|grep -v ":0"

hi, you want help us on the Webui right?
i listed few todos the basics which are not done yet, but i see its lots of.

**Comment by zeners** [comment]
i would try, chat already worked before, sadly to see it's gone

at first, i added the option to change the hard-coded server-port at login page and re-enabled the return-key to start login at password-input (additionally it respects the host and port from the url, overrideable with Query-Arguments named after ui visible names: Username, Port, Server), so you can create bookmarks with overridden defaults
also fixed the identity-images and timestamps

will create a PR

**Comment by defnax** [comment]
> i would try, chat already worked before, sadly to see it's gone
> 
> at first, i added the option to change the hard-coded server-port at login page and re-enabled the return-key to start login at password-input (additionally it respects the host and port from the url, overrideable with Query-Arguments named after ui visible names: Username, Port, Server), so you can create bookmarks with overridden defaults
> also fixed the identity-images and timestamps
> 
> will create a PR

thank you, yes on the old webui was always there at the moment there is nothing with chat .

maybe there are javascript chat sdk which can be used? 
https://www.cometchat.com/chat-sdks/javascript
https://github.com/chat-sdk/chat-sdk-web
https://medevel.com/12-open-source-chat-and-messaging-development-sdk-and-frameworks/
https://github.com/ChannelizeIO/Channelize-JavaScript-Chat-SDK-Sample

**Comment by defnax** [comment]
We need a useable Webui...example Zeronet has realy nice advanced webui, doesnt need to go same way like the qt ui :)
First was nice to a have a 100% useable one.

**Comment by ragrigg** [comment]
mentioned is developer forum on retro share.. installed 6.5 on windows and find that I have no forums showing. is this operational issue with install of retro share on windows 10, or there are no forums, now

**Comment by defnax** [comment]
> mentioned is developer forum on retro share.. installed 6.5 on windows and find that I have no forums showing. is this operational issue with install of retro share on windows 10, or there are no forums, now

this is the wrong issue, you want ask other questions on forums? use the new issue for answers/replies
https://github.com/RetroShare/RetroShare/issues/2195

**Comment by ragrigg** [comment]
I will work on private chat, firstly. the first step is to get agreement on what specifications will be. Correct

**Comment by ragrigg** [comment]
who else is working on this, presently and here?

**Comment by ragrigg** [comment]
what is your name, defnax...or should I just call you nax?

**Comment by defnax** [comment]
> who else is working on this, presently and here?

on webui you mean?, at the moment zener. but i dont know what he is doing as next.
yes defnax

**Comment by ragrigg** [comment]
what I want to arrive at is an agreed and detailed description of the interface everyone (participating) likes.
to this end, I will try to get in touch (somehow) with all interested parties to review the artifacts of this. defnax will you be interested in this design document. too.. or just work with Zener?

**Comment by ragrigg** [comment]
defnax what is your timezone?

**Comment by defnax** [comment]
> defnax what is your timezone?

Europe

**Comment by ragrigg** [comment]
yes. delete away

**Comment by defnax** [comment]
waiting then for the mail

**Comment by ragrigg** [comment]
oh, i will produce a rough schema so we can agree what it looks like first. then to the actual detail behaviors similarly. the approach must consider later added functions [I believe] such that we may add all QT like functionality.. correct?

**Comment by defnax** [comment]
> oh, i will produce a rough schema so we can agree what it looks like first. then to the actual detail behaviors similarly. the approach must consider later added functions [I believe] such that we may add all QT like functionality.. correct?

yes qt like but the design doesnt need to look same like the Qt gui hope it gets a better layout/design or better usability.
But best communicate us via other method first here is not best place for that. or you has telegram?

**Comment by ragrigg** [comment]
give me hint what telegram you want.. I will signup or what have you..

**Comment by ragrigg** [comment]
I see .. I will get account on telegram, now

**Comment by defnax** [comment]
not importend only send me then your nick name on telegram,

**Comment by ragrigg** [comment]
Ragrigg on telegram

**Comment by ragrigg** [comment]
CQEGAcGYxsBNBF/s4hoBCADN7d/TAbSCIIiE51ZlQtJ5hTbswrxVqO8bFxw3ntQ5
x/npdYx0Az6D8g9O8VXUvYQ2qsadLafHEEtuq5hT2EGmeQslp4ctqtp6rc0HiCij
iw3ufv+p3eyT4f1zWZUnR6NaEST4eVg0OuSTKS4Bq+d2y4HHS4t41qZ6vHf2fpqe
WiSY4WOSHjnm12IczofxPJ9DhU7Ky4Evj6frZGQwGlAOX2IzL55eA8cNGXrtGtqS
bkv4aayZyCp8sCeXwmamSdwqbmsiV6hKTmqFmY0O2GhNQc94hZGbgdXnSQZ8MeBa
YnJZCxhPAgpfXw8ww55IQFRxANMrm6UBKXSDRXkr1c2nABEBAAHNJHJhZ3JpZ2cg
KEdlbmVyYXRlZCBieSBSZXRyb1NoYXJlKSA8PsLAXwQTAQIAEwUCX+ziGgkQqEk9
0NFzilECGQEAAKCtB/997waon9ufALA8kQ+QCX4gmWqtOQrnZvrFB1dy6P+MAOn8
G7Ucwz7XkHSnEl3j13e6aAlnZ2wwd8VAdTqHM74lIzegAjPJ7rGgxH2eyxA+JXVJ
MjqZfvP8P0xyUTxfDts5Vc9GqhltFCES885GrYIJNzczg7R6bJpB8CCAYQ3V6W19
B3KUqquHHho8cjD++RlKAUG5EnYwsQzUwG+aYSn+WvpP8hcmNlFmAzbS84vYfqwd
1BrKt0En+sByzASZJHjh4tgV3b4pKBJ8lFrod9v+28TAJIsVNnC+OyUEoMv9HQlt
D1vUORoelf387nZJj+bkRfvHcXuC2Ar596iomQsiAgZHySWxQcYDBgoAAg9BxgQA
BgtNeSBjb21wdXRlcgUQDxcgUQvpEFVs4i9Y8OHF1AcD1zp8

**Comment by Kumaravinash9** [comment]
@defnax  `People -> Display Contacts better & feature to Start a Chat/Mail (via Button)` . I would like  to work on this . Is anyone working on it .

**Comment by defnax** [comment]
#2491
