### ISSUE TITLE
Unifying indentation

### ISSUE THREAD

**Issue by AsamK** [RetroShare/RetroShare#22]
Indentation is not consistent in the RS source code. Even within single files spaces and tabs are sometimes mixed at random. When viewing the files with a different tab setting than the dev who wrote it, the indentation becomes a mess. It's also annoying when editing the files.

I'd suggest unifying the indentation across all RS source code to either 4 spaces or tabs (or something else, I don't really care, as long as it's consistent). This will be a big commit and will make it harder to find out where a change came from, before this commit, but I think it'd be worth it.

e.g. [astyle](http://astyle.sourceforge.net/) can be used to do this, either with four spaces or with tabs:

``` sh
    astyle --mode=c --indent=spaces=4 CPP_FILES
    astyle --mode=c --indent=tab CPP_FILES
```

**Comment by csoler** [comment]
Indentation is a matter of taste, and is also automatically fixed up by your text editor while you're editing. So we do not need (and do not want) to re-indent the whole code, which would be a huge commit with pretty useless meaning. Sorry!
