### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by hunbernd** [RetroShare/RetroShare#231]
File added in this commit prevents compilation on Windows: https://github.com/RetroShare/RetroShare/commit/c5feafa1d23091a06fbf6c9d169cd0a86a98a902

libretroshare\src/util/stacktrace.h:9:22: fatal error: execinfo.h: No such file or directory

**Comment by hunbernd** [comment]
Solved

**Comment by realityfabric** [comment]
How was this solved?

**Comment by hunbernd** [comment]
This part of the code was disabled on windows.
Anyway it was unnecessary, just for debugging purposes.
