### ISSUE TITLE
Retroshare 0.6.6 only for Windows?

### ISSUE THREAD

**Issue by Hxs2fJKjYZ** [RetroShare/RetroShare#2387]
Tried to install for Ubuntu, get an error for the key:
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
Tried the appimage and it's still at 0.6.5.
Will the other distros, appimage and the key issue get updated soon?

**Comment by RanTrycl** [comment]
I have this question too or similar one. I tried to update just now through Ubuntu opensuse repo and got, 
```
wget -vO - https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_${VERSION_ID}/Release.key

--2021-03-25 16:47:33--  https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_20.1/Release.key

Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13

Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.

HTTP request sent, awaiting response... 404 Not Found

2021-03-25 16:47:34 ERROR 404: Not Found.
```

**Comment by retifrav** [comment]
@RanTrycl, all the available keys are listed here: https://download.opensuse.org/repositories/network:/retroshare/
The key for `20.10` (*I guess you actually meant `20.10`, not `20.1`*) is not there, maybe they just forgot to add it. I would try to take the key (*and the rest of distribution*) from `20.04`.

**Comment by G10h4ck** [comment]
Please ping the open build service from opensuse.org maintainers to fix the repository key issue

Thanks
