### ISSUE TITLE
Can't enable Advanced Settings in 0.6.6

### ISSUE THREAD

**Issue by retifrav** [RetroShare/RetroShare#2392]
I've installed the latest 0.6.6 release on Windows (*portable download, Tor binaries included*), and I can't find how to enable Advanced Settings there. I wanted to turn DHT on, and according to various sources on the internet first I need to enable Advanced Settings. Some instructions say it's in **Settings** > **User Interface**, but there is no such menu. The closest is **Preferences** > **Appearance**, but there is no such thing there either:

![rs](https://user-images.githubusercontent.com/6904927/112203764-26505c00-8c13-11eb-99db-ef3add224749.png)

Also tried CLI parameters and `RetroShare.conf` - no such thing in either of them.

Was this setting (*accidentally?*) removed in 0.6.6?

**Comment by defnax** [comment]
Network -> Network Conf.

**Comment by NyvenZA** [comment]
When you run in TOR hidden node mode, you can't turn on DHT. It is only available on the ClearNet (Non-TOR) node setup.

**Comment by retifrav** [comment]
> Network -> Network Conf.

Here's what I have there:

![rs-n](https://user-images.githubusercontent.com/6904927/112215912-353e0b00-8c21-11eb-8caf-7da1155f1df0.png)

> When you run in TOR hidden node mode, you can't turn on DHT. It is only available on the ClearNet (Non-TOR) node setup.

How does one disable hidden mode? It seems I'll need to delete my profile and run RetroShare like the very first time, because I can't find anything related to that in Preferences.

And either way, disregarding DHT, do Advanced Settings still exist in 0.6.6, or are they "enabled" by default now?

**Comment by defnax** [comment]
you need create a new profile[**Standard**] without tor, log out and create new normal profile.
Shut down RetroShare -> Restart -> Login Window -> **New Profile** -> Select Standard -> Create 
![image](https://user-images.githubusercontent.com/9952056/112220624-c5328380-8c26-11eb-82cc-2d9a2a1838fb.png)

![image](https://user-images.githubusercontent.com/9952056/112221985-6bcb5400-8c28-11eb-84a9-49460b38cc0b.png)

**Comment by retifrav** [comment]
Okay, then I was misguided by this Advanced Settings thing, apparently it doesn't exist anymore.
Having created a Standard node I can see all those settings right away.
Thank you and sorry for the confusion.
