### ISSUE TITLE
Some issues on MacOS

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#2410]
Fonts on macos are so small unreadable on my imac 21,5 high sierra 10.13.6

* Listwidget, ToolBar, Mail List, Friends List
* on lots of more places fonts and items are to small
* Tray menu left/right click does do the same (both bring the maindwindow in front)
* The tray menu need only the function to open the menu ( no popup the mainwindow )
* crash when opening the chat room notify from tray menu
* the dock icon needs a function to bring retroshare to the front ( it does not work yet )

**Comment by defnax** [comment]
* mail columns issue for star, attachments, read, spam is very small
![mail](https://user-images.githubusercontent.com/9952056/115111487-e9ad2180-9f80-11eb-892e-14bf84c76f49.png)

* The Attached Image will be not shown (native dialog used) when image is bigger then 1MB
![attach](https://user-images.githubusercontent.com/9952056/115111526-18c39300-9f81-11eb-8675-ebbcfdf7fe11.png)

**Comment by defnax** [comment]
* External IP and Port issue on my macOS with master ( it never gets updated on my iMac 10.13.6)
![ipport](https://user-images.githubusercontent.com/9952056/115111597-588a7a80-9f81-11eb-87ec-9d05676d8657.png)

**Comment by defnax** [comment]
* when using the tray menu for the chat room notify, get a crash (Remove all)
![tray](https://user-images.githubusercontent.com/9952056/115111733-fd0cbc80-9f81-11eb-828d-8dbce9fdb215.png)


> 1 QCocoaMenu::nsMenu() const qcocoamenu.mm 102 0x10bdc4214 
2 ::-[QNSStatusItem triggerSelector:button:](id, Qt::MouseButton) qcocoasystemtrayicon.mm 415 0x10bdd82cc 
3 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54febd6d 
4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54fe89c4 
5 -[NSWindow(NSEventRouting) sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54fe7c70 
6 -[NSStatusBarWindow sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54e3a885 
7 -[NSApplication(NSEvent) sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54e49236 
8 ::-[QNSApplication sendEvent:](NSEvent *) qcocoaapplication.mm 174 0x10bdc2eba 
9 -[NSApplication run] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff546a98b5 
10 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) qcocoaeventdispatcher.mm 429 0x10bdbf623 
11 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) qeventloop.cpp 138 0x108b2db6f 
12 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) qeventloop.cpp 225 0x108b2db4e 
13 QMenu::exec(QPoint const&, QAction *) qmenu.cpp 2643 0x107b6452b 
14 ChatLobbyUserNotify::iconClicked() ChatLobbyUserNotify.cpp 207 0x105d716e6 
15 void doActivate<false>(QObject *, int, void * *) qobject.cpp 3882 0x108b64cc5 
16 QSystemTrayIcon::activated(QSystemTrayIcon::ActivationReason) moc_qsystemtrayicon.cpp 241 0x107d66942 
17 QSystemTrayIcon::qt_static_metacall(QObject *, QMetaObject::Call, int, void * *) moc_qsystemtrayicon.cpp 124 0x107d66920 
18 void doActivate<false>(QObject *, int, void * *) qobject.cpp 3882 0x108b64cc5 
19 QPlatformSystemTrayIcon::activated(QPlatformSystemTrayIcon::ActivationReason) moc_qplatformsystemtrayicon.cpp 191 0x10816863b 
20 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff54febd6d 
... 


> 1 objc_msgSend (x86_64) /usr/lib/libobjc.A.dylib 0x7fff73ff3e97 
2 -[NSNotificationCenter addObserver:selector:name:object:] (x86_64) /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation 0x7fff4ed20af8 
3 ::-[QNSStatusItem triggerSelector:button:](id, Qt::MouseButton) qcocoasystemtrayicon.mm 416 0x108dd8313 
4 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4aae3d6d 
5 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4aae09c4 
6 -[NSWindow(NSEventRouting) sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4aadfc70 
7 -[NSStatusBarWindow sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4a932885 
8 -[NSApplication(NSEvent) sendEvent:] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4a941236 
9 ::-[QNSApplication sendEvent:](NSEvent *) qcocoaapplication.mm 174 0x108dc2eba 
10 -[NSApplication run] (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 0x7fff4a1a187d 
11 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) qcocoaeventdispatcher.mm 429 0x108dbf623 
12 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) qeventloop.cpp 138 0x105af1b6f 
13 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) qeventloop.cpp 225 0x105af1b4e 
14 QCoreApplication::exec() qcoreapplication.cpp 1400 0x105af60f2 
15 main (x86_64) /Users/test/Documents/GitHub/RetroShare/retroshare-gui/src/retroshare.app/Contents/MacOS/retroshare 0x103162c47 
16 start (x86_64) /usr/lib/system/libdyld.dylib 0x7fff74c1c015

**Comment by csoler** [comment]
Fonts are too small because RS currently uses explicit font sizes instead of using default fonts.
