### ISSUE TITLE
Random crashes on macOS

### ISSUE THREAD

**Issue by rex4539** [RetroShare/RetroShare#2415]
RetroShare Version: 0.6.6-5-ga6573826b
macOS 10.16 QT 5.14.1

libretroshare
 - bzip2: 1.0.6, 6-Sept-2010
 - OpenSSL: OpenSSL 1.1.1j  16 Feb 2021
 - SQLite: 3.34.1
 - SQLCipher: 4.4.3 community
 - UPnP (MiniUPnP): 2.1
 - Zlib: 1.2.11

DEFINES:"V07_NON_BACKWARD_COMPATIBLE_CHANGE_001 V07_NON_BACKWARD_COMPATIBLE_CHANGE_002 V07_NON_BACKWARD_COMPATIBLE_CHANGE_003 RS_MAJOR_VERSION=0 RS_MINOR_VERSION=6 RS_MINI_VERSION=6 RS_EXTRA_VERSION="-12-gad568aa78" RS_USE_GXS_DISTANT_SYNC RS_ENABLE_GXS RS_GXS_SEND_ALL RS_SERVICE_TERMINAL_WEBUI_PASSWORD RS_SERVICE_TERMINAL_LOGIN RS_AUTOLOGIN RS_NO_WARN_DEPRECATED RS_NO_WARN_CPP RS_GXS_TRANS RS_USE_BITDHT RS_DIRECT_CHAT RS_USE_I2P_BOB RS_NATIVEDIALOGS RS_BROADCAST_DISCOVERY RS_USE_LIBMINIUPNPC TARGET="retroshare" RS_RELEASE_VERSION RS_USE_CIRCLES"
CONFIG:"lex yacc debug exceptions depend_includepath testcase_targets import_plugins import_qpa_plugin asset_catalogs rez file_copies qmake_use qt warn_on release link_prl app_bundle incremental global_init_link_order lib_version_first sdk clang_pch_style shared shared qt_framework release macos osx macx mac darwin unix posix gcc clang llvm x86_64 qtquickcompiler rs_autologin rs_use_native_dialogs retroshare_gui gxsdistsync no_rs_gui_cmark no_retroshare_plugins retroshare_service sqlcipher no_rs_onlyhiddennode rs_gxs rs_gxs_send_all no_rs_deprecatedwarning no_rs_cppwarning rs_gxs_trans no_rs_async_chat direct_chat bitdht use_dht_stunner no_use_dht_stunner_ext_ip no_rs_jsonapi rs_bob no_rs_deep_channels_index no_rs_deep_files_index no_rs_deep_files_index_ogg no_rs_deep_files_index_flac no_rs_deep_files_index_taglib rs_broadcast_discovery no_rs_webui rs_service_webui_terminal_password rs_service_terminal_login rs_dh_init_check no_rs_cross_compiling useDhtStunner qt gui uic qrc resources idle console identities gxsforums gxschannels posted gxsgui gxscircles version_detail_bash_script"

The client randomly crashes all the time.

```
* thread #1, name = 'rs main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000100190b03 retroshare`___lldb_unnamed_symbol748$$retroshare + 115
retroshare`___lldb_unnamed_symbol748$$retroshare:
->  0x100190b03 <+115>: movq   0x20(%rax), %r12
    0x100190b07 <+119>: leaq   -0x38(%rbp), %rdi
    0x100190b0b <+123>: movq   %r14, %rsi
    0x100190b0e <+126>: callq  0x1008a7310               ; symbol stub for: QVariant::QVariant(QString const&)
Target 0: (retroshare) stopped.
(lldb) bt
* thread #1, name = 'rs main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x0000000100190b03 retroshare`___lldb_unnamed_symbol748$$retroshare + 115
    frame #1: 0x00000001001902c7 retroshare`ChatLobbyWidget::updateDisplay() + 6359
    frame #2: 0x0000000102966def QtCore`QObject::event(QEvent*) + 943
    frame #3: 0x000000010199e09a QtWidgets`QWidget::event(QEvent*) + 4698
    frame #4: 0x00000001019625ba QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
    frame #5: 0x0000000101963a46 QtWidgets`QApplication::notify(QObject*, QEvent*) + 598
    frame #6: 0x000000010293bae4 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #7: 0x000000010293ccd9 QtCore`QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 809
    frame #8: 0x0000000103e50139 libqcocoa.dylib`___lldb_unnamed_symbol677$$libqcocoa.dylib + 313
    frame #9: 0x0000000103e508a8 libqcocoa.dylib`___lldb_unnamed_symbol689$$libqcocoa.dylib + 40
    frame #10: 0x00007fff2040997c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #11: 0x00007fff204098e4 CoreFoundation`__CFRunLoopDoSource0 + 180
    frame #12: 0x00007fff20409664 CoreFoundation`__CFRunLoopDoSources0 + 242
    frame #13: 0x00007fff2040808c CoreFoundation`__CFRunLoopRun + 893
    frame #14: 0x00007fff2040764c CoreFoundation`CFRunLoopRunSpecific + 563
    frame #15: 0x00007fff286ccaa3 HIToolbox`RunCurrentEventLoopInMode + 292
    frame #16: 0x00007fff286cc805 HIToolbox`ReceiveNextEventCommon + 587
    frame #17: 0x00007fff286cc5a3 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 70
    frame #18: 0x00007fff22bff612 AppKit`_DPSNextEvent + 864
    frame #19: 0x00007fff22bfdde5 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
    frame #20: 0x00007fff22bf0159 AppKit`-[NSApplication run] + 586
    frame #21: 0x0000000103e4f623 libqcocoa.dylib`___lldb_unnamed_symbol670$$libqcocoa.dylib + 2579
    frame #22: 0x0000000102937b6f QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
    frame #23: 0x000000010293c0f2 QtCore`QCoreApplication::exec() + 130
    frame #24: 0x000000010002fc67 retroshare`main + 22775
    frame #25: 0x00007fff2032bf3d libdyld.dylib`start + 1
    frame #26: 0x00007fff2032bf3d libdyld.dylib`start + 1
```

**Comment by defnax** [comment]
please test latest builds for macos

**Comment by defnax** [comment]
@G10h4ck close this
