### ISSUE TITLE
Certificates on different version [SOLVED]

### ISSUE THREAD

**Issue by alexonelifer** [RetroShare/RetroShare#2418]
Hi there!
Me and my friends are having great issues adding each one's certificates on different versions of Retroshare (as follows): we are unable to add each other via Retroshare using different versions of the software, because the program says that's the certificate is invalid. We are quite sure that we are doing everything correctly, but still no result. We've been searching for the solution on Internet for a couple of days, but found nothing and got completely messed up. So we assume that that's a bug between older and never version of the certificates. BTW, we tried using both TOR and regular connections.
Is there's a way to fix it?
Many thanks for what you are doing!

**Comment by hunbernd** [comment]
Try to use the old longer certificate format:
![kép](https://user-images.githubusercontent.com/4907599/116848311-9c6db880-abec-11eb-821b-b9db4eb9d988.png)

**Comment by alexonelifer** [comment]
> Try to use the old longer certificate format:
> ![kép](https://user-images.githubusercontent.com/4907599/116848311-9c6db880-abec-11eb-821b-b9db4eb9d988.png)
