### ISSUE TITLE
missing appimage for 0.6.6

### ISSUE THREAD

**Issue by Tcll** [RetroShare/RetroShare#2424]
for whatever reason 0.6.4 and below have appimages
but I can't download the latest appimage to update my 0.6.5 appimage with

**Comment by Kcchouette** [comment]
https://download.opensuse.org/repositories/network:/retroshare/AppImage/retroshare-gui-latest-x86_64.AppImage
this is
> libretroshare version: 0.6.6-retroshare-gui-OBS-AppImage

**Comment by Tcll** [comment]
good to know one exists, cool :+1:

it's a shame it's not listed here though:
https://github.com/RetroShare/RetroShare/releases
would be easier to find

**Comment by Tcll** [comment]
can't edit because the menu doesn't load (probably malicious domains in JS being blocked)

but I just want to confirm the recommended appimage works for me
excellent work :+1:

**Comment by PLAYERUNKNOWNHatsune01** [comment]
Mine it's not working!

**Comment by Kcchouette** [comment]
Open new ticket, not working != missing @PLAYERUNKNOWNHatsune01

**Comment by katian** [comment]
> https://download.opensuse.org/repositories/network:/retroshare/AppImage/retroshare-gui-latest-x86_64.AppImage this is
> 
> > libretroshare version: 0.6.6-retroshare-gui-OBS-AppImage

hello, with this link the app display in the 'about' tab retroshare 0.6.5
![Capture d’écran du 2021-10-28 09-45-33](https://user-images.githubusercontent.com/1428843/139210312-bef3a661-f091-4fb9-82ea-4f32a9b3b319.png)

**Comment by G10h4ck** [comment]
Please ping open build service maintainers, Appimage building seems currently broken upstream, report back when they fix that or instructions on how to fix it on our side

Thanks
