### ISSUE TITLE
Tries to use IPV4 address as IPV6

### ISSUE THREAD

**Issue by shiroyashik** [RetroShare/RetroShare#2427]
![image](https://user-images.githubusercontent.com/73055492/120935068-b168ca80-c709-11eb-88c9-ecfc1a71a258.png)
Translation: **Connection status** Attempting to establish a TCP-connection: ipv6://[::ffff:192.168.36.21]:35555
:/

**Comment by sehraf** [comment]
This is called ipv4 [mapped](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses).

**Comment by shiroyashik** [comment]
._. ok, thank you
