### ISSUE TITLE
Debian and Ubuntu Repo are broken

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [RetroShare/RetroShare#2441]
trying to install retroshare on Debian and to Ubuntu but always get 

''E: The repository 'https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_  Release' does not have a Release file.''

''N: Updating from such a repository can't be done securely, and is therefore disabled by default.''

I try appimage but it's working either! I try flatpak it's working but I can't send images because the flatpak version can't access the HOME folder. When try select a file it just bring up some empty directory and navigating to /home/user/ don't show my directories.

Sorry for my bad English and I'm new to Linux too. If you need more details just ask and I try to provide it thanks ^w^

**Comment by PLAYERUNKNOWNHatsune01** [comment]
my bad sirs/devs really sorry to those two commands 

wget -qO - https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -

sudo sh -c "echo 'deb https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/retroshare_OBS.list"

I should changed ${Version_ID} on my current distro version like this 

wget -qO - https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_20.04/Release.key | sudo apt-key add -

sudo sh -c "echo 'deb https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/retroshare_OBS.list"

same to debian and if you got a problem on Linux Mint I like I do and see this 

pg: invalid key resource URL '/tmp/apt-key-gpghome.Mo2y2aHEHd/home:ungoogled_chromium.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key FCAE110B1118213C: 12 signatures not checked due to missing keys
gpg: key 7721F63BD38B4796: 18 signatures not checked due to missing keys
gpg: key 02456C79B2FD48BF: 1 signature not checked due to a missing key
gpg: key A6616109451BBBF2: 12 signatures not checked due to missing keys
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key C8CAB6595FDFF622: 2 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 14
gpg:       skipped new keys: 14

just do this command 

 sudo rm /etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc  
 
 And IT SHOULD remove the problem! and do it again! hope devs won't close this Issue so new on Linux like me want to use retroshare can see this ^w^

**Comment by G10h4ck** [comment]
The download page should have also a command to get those version number variables populated AFAIR, am I wrong?

Cheers
