### ISSUE TITLE
Memory corruption if you add a lot of people

### ISSUE THREAD

**Issue by programmingzor** [RetroShare/RetroShare#2463]
If you start adding a lot of friends, the software starts to become unstable. If you add more than 30-40 person, the software crashes. Sometimes, its enough to two or three new persons (or just add the same person again) to trip the program to a segmentation fault, especially if you have more contacts than 50. The profile stays unstable even after restarting it a few times, and it will lose all the newly added contacts, because Retroshare refuses to save the newly added peoeple automatically after adding it (and it expects you to close the program normally to save your profile).

**Comment by hunbernd** [comment]
I just created a new profile and imported my whole friend list (140 friends, around 10 online) at the same time, and nothing wrong happened.
I could test it only with clearnet friends, because I don't have a massive Tor friend list, so it is still possible that Tor causes the problem.

>it will lose all the newly added contacts, because Retroshare refuses to save the newly added peoeple automatically after adding it

RS saves it automatically, but if the file gets corrupted, RS will restore it from the backup.

It seems like that most of the problems come from database files get corrupted and not written to disk in time.
Sometimes DB files get corrupted when RS crashes, but not this extremely.
Isn't something on your machine that slows down file I/O?

Also please send me some crash logs!
You can install Dr mingw (https://github.com/jrfonseca/drmingw), and copy the content of the popup window here.

**Comment by programmingzor** [comment]
I have partition-level file system encryption, that probably could slow down the file system io with a few miliseconds, but it should be transparent from the viewpoint of the software. After these crashes, i have added a total 71 friends, but retroshare says on the bottom that i have 64 (but 71 is listed in the friend list). 

I have noticed that if a new person applies my friend request and adds my cert, there is a high chance that the program crashes. 
I have forgot to say i have the Linux version. It can dump debug data on the console, i will investigate and post that here instead, to see whats going on.

**Comment by programmingzor** [comment]
Retroshare just permanently damaged my profile, losing all of the contents. I wasnt even able to restore it from a backup. I stop reporting more bugs until the overall stability and reliability of this program is being seriously improved.

**Comment by programmingzor** [comment]
.......got the segfault aniway. after just adding 10 partners, and adding one of them twice suddenly:

(EE) asked to create an invalidated profile that already exists!
Caught signal 11 (SIGSEGV)
stack trace:
*****path hidden from report********************/retroshare(_ZN15CrashStackTrace12abortHandlerEi+0x8b)[0x55e486632b7b]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840)[0x7fce6194b840]
*****path hidden from report********************/retroshare(_ZN17RsFriendListModel18updateInternalDataEv+0x490)[0x55e4868137a0]
*****path hidden from report********************/retroshare(_ZN13NewFriendList21applyWhileKeepingTreeESt8functionIFvvEE+0x1a3)[0x55e48681aea3]
*****path hidden from report********************/retroshare(_ZN13NewFriendList17checkInternalDataEb+0x32)[0x55e48681b0a2]
*****path hidden from report********************/retroshare(+0x61b5e8)[0x55e48681b5e8]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x1d4)[0x7fce6211a474]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2bc103)[0x7fce62169103]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2ae)[0x7fce60f3efee]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4e288)[0x7fce60f3f288]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fce60f3f31c]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x67)[0x7fce62168727]
/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0xdd491)[0x7fce5c93a491]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13b)[0x7fce6211615b]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x92)[0x7fce6211e132]
*****path hidden from report********************/retroshare(main+0x298b)[0x55e4865ca8bb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fce6193809b]
*****path hidden from report********************/retroshare(_start+0x2a)[0x55e48660652a]
E 1629989128.864 virtual RsThread::~RsThread() deleting thread: 140523453007616 gxs trans ns that is still running! Something seems very wrong here and RetroShare is likely to crash because of this.

stack trace:
pure virtual method called
terminate called without an active exception
Caught signal 6 (SIGABRT)
stack trace:
*****path hidden from report********************/retroshare(_ZN15CrashStackTrace12abortHandlerEi+0x8b)[0x55e486632b7b]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840)[0x7fce6194b840]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7fce6194b7bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7fce61936535]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c983)[0x7fce61cfe983]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x928c6)[0x7fce61d048c6]
  *****path hidden from report********************/retroshare : RsGxsNetService::~RsGxsNetService()+0x420
  *****path hidden from report********************/retroshare : RsGxsNetService::~RsGxsNetService()+0x9
  *****path hidden from report********************/retroshare : RsGenExchange::~RsGenExchange()+0x40
  *****path hidden from report********************/retroshare : p3GxsTrans::~p3GxsTrans()+0x9
  *****path hidden from report********************/retroshare : RsServer::~RsServer()+0x2f
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x39d8c
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x39eba
  *****path hidden from report********************/retroshare : CrashStackTrace::abortHandler(int)+0xb8
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x37840
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92901)[0x7fce61d04901]
  *****path hidden from report********************/retroshare : RsFriendListModel::updateInternalData()+0x490
  *****path hidden from report********************/retroshare : NewFriendList::applyWhileKeepingTree(std::function<void ()>)+0x1a3
  *****path hidden from report********************/retroshare : NewFriendList::checkInternalData(bool)+0x32
  *****path hidden from report********************/retroshare : ()+0x61b5e8
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x1d4
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2bc103
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 : g_main_context_dispatch()+0x2ae
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 : ()+0x4e288
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 : g_main_context_iteration()+0x2c
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x67
  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 : ()+0xdd491
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x13b
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplication::exec()+0x92
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9363f)[0x7fce61d0563f]
  *****path hidden from report********************/retroshare : main()+0x298b
  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xeb
  *****path hidden from report********************/retroshare : _start()+0x2a
*****path hidden from report********************/retroshare(_ZN13RsGenExchange4tickEv+0xf8)[0x55e486c11ae8]
*****path hidden from report********************/retroshare(_ZN13RsGenExchange10threadTickEv+0x9)[0x55e486c11f49]
*****path hidden from report********************/retroshare(_ZN8RsThread7wrapRunEv+0x29)[0x55e486bc27e9]
*****path hidden from report********************/retroshare(_ZN8RsThread13rsthread_initEPv+0x1e)[0x55e486bc283e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fce61dfffa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fce61a0d4cf]
Memory still in use at end of program: 448 bytes.

**Comment by programmingzor** [comment]
I was able to create a profile - that not yet crashed- but "reliably" crashes, after a few seconds-minutes of going online. I am going to send the profile to anmo for further investigation to find out the root cause of the problem.

**Comment by programmingzor** [comment]
we (likely) found the bug in the code, and anmo is trying to come up with a patch.
