### ISSUE TITLE
Cannot compile on 32bit Ubuntu

### ISSUE THREAD

**Issue by Odysch** [RetroShare/RetroShare#2464]
Error message:
 p3filelists.cc
 In file included from /usr/include/c++/5/cstdint:35:0,
                 from ./rsitems/rsserviceids.h:27,
                  from file_sharing/p3filelists.cc:22:
 /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by G10h4ck** [comment]
Which Ubuntu version? 32bit sounds like EOL

Cheers
