### ISSUE TITLE
macOS version numbers missing

### ISSUE THREAD

**Issue by core-code** [RetroShare/RetroShare#2490]
i've downloaded version 0.6.6 but when selecting it in the Finder, no version numbers are missing.

all macOS apps are supposed to contain their version number.

both the `CFBundleVersion` and `CFBundleShortVersionString` entries in your `Info.plist` file are missing. these should be set to 0.6.6

on the other hand your Info.plist file contains the `CFBundleGetInfoString` key that has been deprecated for more than 13 years

**Comment by defnax** [comment]
maybe you can help us?  i has created the build but im not sure what i forget, im not mac expert , but i get compiled rs on my imac

I has updated the howto half year ago, but i knewer know the thing with CFBundleVersion & CFBundleShortVersionString
https://github.com/RetroShare/RetroShare/blob/master/build_scripts/OSX/MacOS_X_InstallGuide.md

**Comment by core-code** [comment]
you could give the submitted PR a try. i've used "0.6.7" as the version number now. not sure if the version number is available as a variable in that script. if not, you'll need to adjust this value before each release

**Comment by defnax** [comment]
now im not on imac to test,  need to look next days when get time to run my imac again for test

**Comment by core-code** [comment]
still unsolved in RetroShare-0.6.7a-g951be8f9a-MacOS-10.14-Qt-5.14.1.dmg

**Comment by defnax** [comment]
sorry I'm alone, no Mac users helping on Mac with compile fixes, I'm creating new osx package file
this is needed?
/usr/libexec/PlistBuddy -c "Delete :CFBundleGetInfoString" retroshare.app/Contents/Info.plist
I get error on output
Delete: Entry, ":CFBundleGetInfoString", Does Not Exist

**Comment by defnax** [comment]
can you debug retroshare?

**Comment by core-code** [comment]
> Delete: Entry, ":CFBundleGetInfoString", Does Not Exist

you must have run it twice because the deprecated key is definitely in there.

**Comment by defnax** [comment]
look https://github.com/RetroShare/RetroShare/pull/2797)

**Comment by defnax** [comment]
fixed here , now on every new dmg package created it get its version number

- https://github.com/RetroShare/RetroShare/pull/2810/commits/020e9e5927f86ef8439bd34e3f0f6231c1ceb3a0
close @G10h4ck

**Comment by core-code** [comment]
great, thanks
