### ISSUE TITLE
[BUG] Interface is completely broken

### ISSUE THREAD

**Issue by Teashrock** [RetroShare/RetroShare#2497]
![2021-10-30_19:00:20](https://user-images.githubusercontent.com/12483854/139540471-beaf599b-3003-47e8-b60f-5ca8d5534f21.png)

**Comment by defnax** [comment]
You are using list mode & the right side is hidden, you need to use the mouse and move to the left there is a splitter 

![image](https://user-images.githubusercontent.com/9952056/139541814-ed686a97-08eb-417d-a43a-00d6b2de3a42.png)

**Comment by Teashrock** [comment]
@defnax 
Thank you very much. The issue is closed now.
