### ISSUE TITLE
Could not clear gnome keyring passwd for SSLID

### ISSUE THREAD

**Issue by realityfabric** [RetroShare/RetroShare#252]
When exiting RetroShare (Ubuntu 15.10) I got the message "Could not clear gnome keyring passwd for SSLID [redacted]"

This seems like it's a pretty serious issue

**Comment by felisucoibi** [comment]
Hi I use rs on ubuntu 15.10 and I don't have this problem, strange. which desktop are you using? you changed the password of your user? I had some problems with keyring after changing mi password.

**Comment by realityfabric** [comment]
I didn't even know it was possible to change the password. I imported my private key from Windows.

**Comment by cavebeat** [comment]
is this solved? may i close?
