### ISSUE TITLE
Can't install on Debian Bullseye

### ISSUE THREAD

**Issue by heini** [RetroShare/RetroShare#2532]
Following the instructions for installing on Debian 11, I get the following error:
```
# LC_ALL=C apt-get install retroshare-gui
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 retroshare-gui : Depends: retroshare-common but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Browsing the repository, I see there's `retroshare-common-unstable`, but no `retroshare-common` for 0.6.6.

**Comment by ghost** [comment]
Get it from [ubuntu repository](https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_16.04/amd64/retroshare-common_0.6.6-1_amd64.deb). This package contains only one file bdboot.txt with a list of IP's DHT users.

**Comment by heini** [comment]
Errh, no. Please fix the Debian repo.

**Comment by ghost** [comment]
https://download.opensuse.org/repositories/network:/retroshare/Debian_10/amd64/retroshare-common_0.6.6-1_amd64.deb

**Comment by YoSiJo** [comment]
Ugly but working solution:

```bash
for DEBIAN_VERSION in 10 11; do
  export DEBIAN_VERSION
  
  wget -qO - http://download.opensuse.org/repositories/network:retroshare/Debian_${DEBIAN_VERSION}/Release.key | sudo apt-key add -
  sudo rm /etc/apt/sources.list.d/retroshare.list
  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/network:/retroshare/Debian_${DEBIAN_VERSION}/ /' >> /etc/apt/sources.list.d/retroshare.list"

  sudo apt update
  sudo apt install retroshare-gui-unstable
done
```

I agree with @heini please fix the Debian 11 repo.

**Comment by ghost** [comment]
In 0.6.6 Windows build bdboot.txt file doesn't work at all (DHT doesn't work). Tell new Windows users to take this file from Ubuntu (retroshare-common). Then DHT will turn green.

Generally, pretty unreliable program. For example, there is no auto-save (in case of failures). I would not recommend it for personal communication. To enter the internal network RetroShare can be used, if there is something of interest to you. I've heard about 70 000 users in it.

**Comment by YoSiJo** [comment]
@archipelagu Sorry, but that's not the problem this issue is dealing with.

**Comment by calbasi** [comment]
> Errh, no. Please fix the Debian repo.

I think it's easy just add the missing package at Debian repo, isn't it? So how is it possible this issue is still open 2 months later??

Could we warn the Debian repo maintainer?? Who is it?

**Comment by heini** [comment]
Nearly a year has passed since I opened this issue. It's still not installable on Debian.

- Stable is missing packages
- Testing has no valid key

Please fix your repos.

**Comment by G10h4ck** [comment]
If the repository have key problem please report it o open build service form opensuse.org which is what we use to build debian package. I suggest to test retroshare-gui-unstable which is built from 0.6.7-RC2 source code and report back as necessary

Thanks
