### ISSUE TITLE
Building retroshare 0.6.6 on Fedora Linux

### ISSUE THREAD

**Issue by d-graef** [RetroShare/RetroShare#2569]
I'm trying to build retroshare on Fedora Linux because the RPM package provided doesn't work on Fedora Linux:

https://build.opensuse.org/package/binary/download/network:retroshare/retroshare-gui-0.6.6/Fedora_34/x86_64/retroshare-gui-0.6.6-11.1.x86_64.rpm

I get the following error:

Generate XML output for dir .../rpmbuild/BUILD/RetroShare-0.6.6/libretroshare/src/unused/
Generate XML output for dir .../rpmbuild/BUILD/RetroShare-0.6.6/libretroshare/src/tests/upnp/
Generate XML output for dir .../rpmbuild/BUILD/RetroShare-0.6.6/libretroshare/src/tests/util/
Generate XML output for dir .../rpmbuild/BUILD/RetroShare-0.6.6/libretroshare/src/util/
Running plantuml with JAVA...
lookup cache used 50845/65536 hits=359547 misses=53517
finished...
make[1]: Leaving directory '/home/robin/rpmbuild/BUILD/RetroShare-0.6.6/libretroshare/src'
make: *** [Makefile:128: sub-libretroshare-src-libretroshare-pro-make_first] Error 2
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.1Wd3ul (%build)

Does someone has any hint for me?

**Comment by ghost** [comment]
What configuration options did you use? These work for me:
`qmake PREFIX=/opt/retroshare RS_MAJOR_VERSION=0 RS_MINOR_VERSION=6 RS_MINI_VERSION=6 RS_EXTRA_VERSION="-retroshare-gui-OBS-deb" CONFIG-=debug CONFIG+=release PREFIX=/opt/retroshare LIB_DIR=/opt/retroshare/lib CONFIG+=no_retroshare_plugins CONFIG+=retroshare_gui CONFIG+=no_tests CONFIG+=no_retroshare_service CONFIG+=rs_deep_search CONFIG+=c++14 CONFIG+=rs_jsonapi RetroShare.pro`
I got them from debian rules. The default ones don't work for me.

Make sure you've cloned all submodules to the right version (0.6.6, not git), it's not easy.

Submodules are in supportlibs folder. And also build_scripts/OBS
And libretroshare, libbitdht and openpgpsdk
Also, asio, catch and kashmir are automatically cloned at compile time into supportlibs/restbed/dependency

**Comment by ghost** [comment]
Oh, I see you're using a rebuild by specs. Try manually then.

**Comment by G10h4ck** [comment]
retroshare-gui-unstable which is compiled form latest source code seems to build fine on fedora, please test that and report back as necessary ;)

Thanks
