### ISSUE TITLE
UDP hole punching

### ISSUE THREAD

**Issue by ExTrimmer** [RetroShare/RetroShare#2572]
I found "tcp on udp" and stun in libretroshare repository, but the client doesn't want to use it to connect, it tries only tcp. I used wireshark on linux and didn't capture any udp packets when retroshare tried to connect. The client listens udp port, but doesn't use it to connect to other hosts. Maybe there is a way to enable udp connections?

PS: sorry for my English

**Comment by csoler** [comment]
UDP connections are generated when the DHT finds your friends. This generally takes some time. Also RS uses TCP in priority and then UDP when it doesn't manage to reach your friends. If you're behind a firewall it's more likely that you'll eventually establish UDP connections to your friends.

**Comment by ExTrimmer** [comment]
ok, but for some reason DHT doesn't work in my client, but it works in utorrent. I don't know why. Is there a way to specify, that retroshare must use udp, in settings or like "udp://"?

**Comment by csoler** [comment]
The UDP indicator only says "DHT works" when it actually finds one of your friends in the DHT. For more accurate information, see statistics->DHT.

**Comment by ExTrimmer** [comment]
Is there a way to manually specify, that retroshare must use udp, in settings or like "udp://"?

**Comment by csoler** [comment]
I remember that you can ask RS to only *listen* to UDP (option -u at start). That will prevent TCP-in connections, but not TCP-out.

**Comment by ExTrimmer** [comment]
I mean I want to ask RS to connect using UDP

**Comment by ExTrimmer** [comment]
Just fixed DHT by copying bdboot.txt from RS directory to ./Data/<userdir>/
