### ISSUE TITLE
error execvp on MacOS with RS 0.6.6

### ISSUE THREAD

**Issue by magicvince** [RetroShare/RetroShare#2581]
Many of my contacts trying to use RS 0.6.6 on MacOS can create a user but when they try to launch the application after identification, the connecting process stop with an error message "execvp : no such file or directory"
![Capture d’écran 2022-02-07 à 17 21 21-1](https://user-images.githubusercontent.com/627273/153028140-85b5e57d-9df9-45c7-975e-091f62c72a25.png)

**Comment by defnax** [comment]
rs requires tor when want use with tor, before to generate a hidden profile, tor needs to be installed.

`brew install tor 
`

please test latest 0.6.7a builds.

@G10h4ck close this
