### ISSUE TITLE
MacOS 

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#2589]
Hello,
we need help to fix some issues which are macos related any help are welcome.
At moment MacOs compile on master is broken issue with a libsam3 library which is supported only for windows/linux.
My MacOs is now to old, i have issues to run retroshare 0.6.5 (issue with libnettle https://github.com/RetroShare/RetroShare/issues/2080) on my macos 10.13.6 (High Sierra) 
Would be great if we have a active macOS devs to fix issues.

@xenomorpheus @retifrav @core-code @veryprivate @sehraf 

some  issues:
* error execvp on MacOS with RS 0.6.6 https://github.com/RetroShare/RetroShare/issues/2581
* macOS version numbers missing https://github.com/RetroShare/RetroShare/issues/2490
* Random crashes https://github.com/RetroShare/RetroShare/issues/2415
* Issues with libnettle https://github.com/RetroShare/RetroShare/issues/2080
* crash when opening the chat room notify from tray menu
* Tray menu left/right click does do the same (both bring the maindwindow in front)

**Comment by cinealfa** [comment]
Thank for the build instructions! Has anyone able to assist you?

**Comment by defnax** [comment]
Build ist solved, but we need macos devs
