### ISSUE TITLE
Unable to compile latest trunk on LinuxMint 20.3 (xubuntu focal)

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#2600]
Bonjour tout le monde !
Hi All !

Impossible de compiler trunk du 31 Mars 2022  une erreur apparait dans HomePage.cpp
Was unable to compile :  trunk 2022-03-21 An error in HomePage.cpp

> gui/HomePage.cpp: In member function ‘void HomePage::getOwnCert(QString&, QString&) const’:
> 
> gui/HomePage.cpp:237:44: error: ‘SLICE_TO_80_CHARS’ is not a member of ‘RetroshareInviteFlags’
>   237 |     invite_flags |= RetroshareInviteFlags::SLICE_TO_80_CHARS;
>       |                                            ^~~~~~~~~~~~~~~~~
> 
> At global scope
> cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
> make[1]:  [Makefile.retroshare-gui:14570 : temp/linux-g++/obj/HomePage.o] Erreur 1
> make[1] : on quitte le répertoire « /media/sauve/retroshare/2022-03-21/retroshare-gui/src »
> make:  [Makefile:128 : retroshare_gui-make_first] Erreur 2

Ainsi d'ailleurs que dans  RetroShareLink.cpp
And also in  RetroShareLink.cpp !

> gui/RetroShareLink.cpp: In static member function ‘static RetroShareLink RetroShareLink::createCertificate(const RsPeerId&)’:
> gui/RetroShareLink.cpp:576:53: error: ‘SLICE_TO_80_CHARS’ is not a member of ‘RetroshareInviteFlags’
>   576 |             invite_flags &= ~RetroshareInviteFlags::SLICE_TO_80_CHARS;
>       |                                                     ^~~~~~~~~~~~~~~~~
>
> At global scope:
> cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
> make[1]: *** [Makefile.retroshare-gui:15239 : temp/linux-g++/obj/RetroShareLink.o] Erreur 1
> make[1] : on quitte le répertoire « /media/sauve/retroshare/2022-03-21/retroshare-gui/src »
> make: *** [Makefile:128 : retroshare_gui-make_first] Erreur 2
> 

Merci d'avance !
Thanks in advance !

**Comment by csoler** [comment]
you probably need to update git submodules. Just "cd libretroshare", then "git pull". Keep me posted if that does't work.

**Comment by ghost** [comment]
Hi Csoler !
Try it

**Comment by ghost** [comment]
Sory Csoler do'nt work 

git pull https://github.com/RetroShare/RetroShare.git
remote: Enumerating objects: 167653, done.
remote: Counting objects: 100% (4489/4489), done.
remote: Compressing objects: 100% (1648/1648), done.
remote: Total 167653 (delta 2622), reused 4197 (delta 2478), pack-reused 163164
Réception d'objets: 100% (167653/167653), 116.52 Mio | 1.81 Mio/s, fait.
Résolution des deltas: 100% (116663/116663), fait.
Depuis https://github.com/RetroShare/RetroShare
 * branch                HEAD       -> FETCH_HEAD
astuce: Vous avez des branches divergentes et vous devez spécifier comment
astuce: les réconcilier. Vous pouvez le faire en lançant une des
astuce: commandes suivantes avant votre prochain tirage :
astuce: 
astuce:   git config pull.rebase false  # fusion (stratégie par défaut)
astuce:   git config pull.rebase true   # rebasage
astuce:   git config pull.ff only       # avance rapide seulement
astuce: 
astuce: Vous pouvez remplacer "git config" par "git config --global" pour que
astuce: ce soit l'option par défaut pour tous les dépôts. Vous pouvez aussi
astuce: passer --rebase, --no-rebase ou --ff-only sur la ligne de commande pour
astuce: remplacer à l'invocation la valeur par défaut configurée.

**Comment by chelovechishko** [comment]
no, there is just no
```
--- a/libretroshare/src/retroshare/rspeers.h	2022-03-17 21:30:24.961040962 +0900
+++ b/libretroshare/src/retroshare/rspeers.h	2022-03-17 22:50:38.660895623 +0900
@@ -520,6 +520,7 @@
     RADIX_FORMAT        = 0x08,
     PGP_SIGNATURES      = 0x10,
     CURRENT_EXTERNAL_IP = 0x20,
+    SLICE_TO_80_CHARS   = 0x40,
     ALL                 = 0xff,
 };
 RS_REGISTER_ENUM_FLAGS_TYPE(RetroshareInviteFlags)
```
or something like this.

**Comment by ghost** [comment]
Le clonage a été fait via la commande suivante

   git clone --recurse-submodules https://github.com/RetroShare/RetroShare.git   2022-03-21

puis pull  plusieurs fois dans la nuit avec 
      git fetch
       git pull --recurse-submodules https://github.com/RetroShare/RetroShare.git

**Comment by ghost** [comment]
Saw your comment chelovechishko it seem that effectively SLICE_TO_80_CHARS is not defined in my trunck version

**Comment by ghost** [comment]
After a new Pull rspeers.h is always without SLICE_TO_80_CHARS

enum class RetroshareInviteFlags:uint32_t {
    NOTHING             = 0x00,
    CURRENT_LOCAL_IP    = 0x01,
    FULL_IP_HISTORY     = 0x02,
    DNS                 = 0x04,
    RADIX_FORMAT        = 0x08,
    PGP_SIGNATURES      = 0x10,
    CURRENT_EXTERNAL_IP = 0x20,
    ALL                 = 0xff,
};

But for the second error it's seems to be a keyboard error !

**Comment by ghost** [comment]
i try a complete git cloning on another folder
git clone --recurse-submodules https://github.com/RetroShare/RetroShare.git New_Folder
Will takes long time but ....we'll see

**Comment by ghost** [comment]
Cloning complete
Compiling

**Comment by ghost** [comment]
Unable to ... same error 

-gnu/qt5/mkspecs/linux-g++ -o temp/linux-g++/obj/HomePage.o gui/HomePage.cpp
gui/HomePage.cpp: In member function ‘void HomePage::getOwnCert(QString&, QString&) const’:
gui/HomePage.cpp:237:44: error: ‘SLICE_TO_80_CHARS’ is not a member of ‘RetroshareInviteFlags’
  237 |     invite_flags |= RetroshareInviteFlags::SLICE_TO_80_CHARS;
      |                                            ^~~~~~~~~~~~~~~~~
At global scope:

**Comment by ghost** [comment]
et hop une autre erreur !

**Comment by ghost** [comment]
I tried to use the  chelovechishko idea and modified rspeers.h for a test
but
Another error apeared then, but at another place, in another file : friendserver.cc 

SAM3_LIBSAM3 -DRS_USE_LIBUPNP -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../libretroshare/src -I../../openpgpsdk/src -I../../libbitdht/src -I../../supportlibs/udp-discovery-cpp -I../../supportlibs/libsam3/src/libsam3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o friendserver.o friendserver.cc
friendserver.cc: In member function ‘void FriendServer::handleClientPublish(const RsFriendServerClientPublishItem*)’:
friendserver.cc:91:93: error: ‘const class RsFriendServerClientPublishItem’ has no member named ‘already_received_peers’
   91 |         sr_item.friend_invites = computeListOfFriendInvites(item->n_requested_friends,item->already_received_peers,pi->first,friends);
      |                                                                                             ^~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
make[1]: *** [Makefile.retroshare-friendserver:490 : friendserver.o] Erreur 1
make[1] : on quitte le répertoire « /media/sauve/retroshare/2022-03-21/retroshare-friendserver/src »
make: *** [Makefile:178 : retroshare_friendserver-make_first] Erreur 2

**Comment by csoler** [comment]
I just tested on Ubuntu 20. Apparently the master branch of retroshare/ is tied to a detached head of libretroshare. We'll fix it. Going into libretroshare/ and doing "git pull origin master" fixes it. These submodules are a temporary thing that we will get rid of as soon as possible.

**Comment by csoler** [comment]
For the record, when you clone, use "--depth 1" as it is much faster.

**Comment by ghost** [comment]
ok thx i'll try

**Comment by csoler** [comment]
apparently "git checkout master" in libretroshare/ also fixes it, and probably in a better way

**Comment by ghost** [comment]
've chosen git checkout master,
compiling

**Comment by ghost** [comment]
Thx for ur infos,
Compiling ok but make install does ..... Nothing !

**Comment by ghost** [comment]
2th try :+1: 
It Works !!
Thx Csoler !

Pb Solved
