### ISSUE TITLE
Debian 10 repo key signature expired

### ISSUE THREAD

**Issue by mYnDstrEAm** [RetroShare/RetroShare#2625]
On Debian10/KDE, I get this at `sudo apt-get update`:
```
Err:9 http://download.opensuse.org/repositories/network:/retroshare/Debian_10  InRelease
  The following signatures were invalid: EXPKEYSIG 62EB1A0917280DDF network OBS Project <network@build.opensuse.org>
...
An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/network:/retroshare/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 62EB1A0917280DDF network OBS Project <network@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/network:/retroshare/Debian_10/InRelease  The following signatures were invalid: EXPKEYSIG 62EB1A0917280DDF network OBS Project <network@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by drzraf** [comment]
Affects all Debian-based distrib.
https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_20.04/Release.key expired June 9th

**Comment by marek22k** [comment]
https://github.com/Shoalsteed/appsI2P/issues/13#issuecomment-1169553627
https://sourceforge.net/p/retroshare/bugs/404/
Unfortunately I have the same problem. Is there any progress in solving it?

I also wrote an email to the developers. Let's see if that brings something.

**Comment by afAtedg** [comment]
I am using Debian 10 Buster too, and I manage to solve the problem by taking the new key from the Debian 11 folder.
I don't know if it is a mistake, maybe it is stupid, but it seems to work.

https://download.opensuse.org/repositories/network:/retroshare/Debian_11/Release.key

**Comment by tattwamasii2p** [comment]
One insecure workaround is:

```sh
sudo apt -o Acquire::AllowInsecureRepositories=true \
  -o Acquire::AllowDowngradeToInsecureRepositories=true update
```

**Comment by T-X** [comment]
Is there a chance to get this into the official, main Debian repositories? So that no Debian user needs to add new repository keys?

**Comment by G10h4ck** [comment]
Please report this problem to open build service from opensuse.org maintainers which is what we use to distribute Debian packages, so they can fix it

Thanks

**Comment by marek22k** [comment]
I left a [comment](https://build.opensuse.org/project/show/network:retroshare#comment-1838681) and emailed buildservice@lists.opensuse.org.

@G10h4ck Do you have another contact person I could get in touch with? Or could you ask OpenSUSE as maintainer?

Furthermore, it looks like there are problems with the Debian 12 build. Maybe someone could take a look at that as well?
