### ISSUE TITLE
Unable to Create and Post any Forum Messages

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#2628]
Unable to Create and Post any Forum Messages

I just created another Forum and wanted to pin-up the purpose of that new Forum when I began to create a new forum post, the template was slightly grey and wouldn't permit any input, the POST button is Red and won't enable. Looks like a serious bug.

I went over to several of my subscribed and owned forums, all have the same serious RetroShare forum bug that prevents any user
input on a new forum post. Post button is RED, nothing can be newly posted in any of them.

Linux Ubuntu amd64 running RetroShare v0.6.6-545-g4cba9815f

![Retroshare_Forum_Box_Unable-2-Post](https://user-images.githubusercontent.com/8520894/179444287-0f28b05f-771c-4e59-a33d-a25ddf5f05a2.png)

**Comment by ASmith-** [comment]
This serious forum bug preventing forum posts from being composed and added, disappears when a earlier build is tried. No such bug with RetroShare v0.6.6-528-g4f799ec5 which was built June 23rd. last month. There has been only a small handful of commits that were added since then to the RetroShare Master Source Branch to the most recent commit and build which I believe carried this bug.

That should greatly help the developers locate and hopefully correct this serious RetroShare forum bug.

**Comment by csoler** [comment]
confirmed. Fix on its way.

**Comment by ASmith-** [comment]
Thank you for your attention to that issue, I'll go ahead and close it.
