### ISSUE TITLE
Great application!

### ISSUE THREAD

**Issue by AKmatiAK** [RetroShare/RetroShare#2633]
Why this isn't popular? It's all in one decentralized communications solution. I will spread info about it with my friends. Also, why I see no avaible chats, forums and boards? are there none or I must configure something?

**Comment by csoler** [comment]
Thank you for the positive feedback.

You only see the forums, chats, channels, etc that your friends are subscribed to, or the ones you created yourself.

I think that this is what slows down the adoption of the software: you need to get some friends to use it before it gets populated with new data.

**Comment by AKmatiAK** [comment]
Can someone add me to friends then to give me connections to start?


ABBTKyRaYcotvFccIpaMfgi7AxRT7Pq+2vsoEI4hhzc7k3MRti6f3wEIQUttYXRpQUuTBsAqgAo/0pIGvEn0aD/SBAPUjrw=

**Comment by o0nd7ots** [comment]
I added you.
I get the positive sentiment but can we please get this <i> issue </i> closed?
