### ISSUE TITLE
[Bug] retroshare-service does not enable the WebUI when --user-id is not "list"

### ISSUE THREAD

**Issue by ann4belle** [RetroShare/RetroShare#2641]
For some reason, passing any `--user-id` argument other than "list" when starting retroshare-service causes it to refuse to start the WebUI, even when `-W` is passed and a valid password is given.

Command I'm using:
`retroshare-service -s -P 0.0.0.0 -W -U [hex user id]`

Upon running this and entering the password, GETting `localhost:9092/index.html` returns 404. Running the exact same command but replacing the user ID with "list" and going through account selection results in expected behavior - the webui is reachable and usable at `localhost:9092/index.html`.

**Comment by ann4belle** [comment]
Note that I (obviously) built my copy of retroshare-service with RS_SERVICE_TERMINAL_LOGIN. I'm not sure how exactly selecting a user account works without that option enabled, though.

**Comment by csoler** [comment]
it should be fixed in libretroshare PR 53

**Comment by ann4belle** [comment]
Going to try and build with PR 53 and see how that goes

**Comment by ann4belle** [comment]
Can confirm that PR53 in libretroshare fixes this bug.
