### ISSUE TITLE
[Feature Request] Specify WebUI password on command line (retroshare-service)

### ISSUE THREAD

**Issue by ann4belle** [RetroShare/RetroShare#2642]
At the moment, the only way to specify the WebUI password (and thus enable the WebUI) is to pass the `-W` flag and enter the password when prompted. Due to this, running retroshare-service as an actual service (as opposed to running it manually via a terminal) is impossible. This could be worked around by writing a "launcher" script to provide the requested input, but I feel it would be better if this option were simply included in the program, or was at least a cmake option. (Note: I built my copy of retroshare-service with RS_SERVICE_TERMINAL_WEBUI_PASSWORD - would building it without that option disable the password requirement, or otherwise allow some version of the behavior I'm requesting?)

**Comment by ann4belle** [comment]
Update: attempted to work around this limitation using this python script:
```
import subprocess

retroshare = subprocess.Popen(['retroshare-service', '-s', '-P', '0.0.0.0', '-W', '-U', 'list'], stdin=subprocess.PIPE)
retroshare.communicate(input=b'boop\nboop\n1\n')
```

It launches successfully, but triggers the same behavior in #2641 - trying to access the WebUI at port 9092 returns HTTP 404. The rest of the JSON API responds, so it *is* listening - it simply refuses to read the WebUI. Specifying `-B /usr/local/share/retroshare/webui/` (the location of the webui) does not help.

Reading the output, it appears to be setting the password correctly. I have no idea what might be going wrong here.

**Comment by defnax** [comment]
hi we need some one to build the required packages im not sure whats is needed.
But webui needs profile generation feature too:

https://github.com/RetroShare/RSNewWebUI/issues/60

**Comment by ann4belle** [comment]
@defnax if the API of libretroshare was actually documented anywhere it'd probably be easier to just write a new service from that. I suspect that a big part of the reason retroshare-service is so wonky is that the API is completely undocumented (or at least, the docs aren't anywhere I can find) and everyone working on it has to figure out what each bit of code does for themselves.

**Comment by defnax** [comment]
Here little bit:

Readme (JSON API):
https://github.com/RetroShare/libretroshare/blob/master/src/jsonapi/README.adoc

RetroShare interface headers:
https://github.com/RetroShare/libretroshare/tree/a7a430008b76e53727598c4d13106e7ce95221d7/src/retroshare

**Comment by ann4belle** [comment]
C++ code isn't exactly API documentation, but at least it's better than nothing. I suppose to bypass this issue and #2641 you could run the WebUI using a separate server, but that kinda defeats the point of having RS_WEBUI as an option when compiling retroshare-service.

I'd try to fix whatever is wrong with retroshare-service in #2641 and add this feature but it's frankly well outside of my skill level to even *find* what's causing the bug or where the feature would go.

**Comment by csoler** [comment]
I will take a look at it and keep you posted.

**Comment by ann4belle** [comment]
With #2641 now mitigated by PR 53 on libretroshare, using Python's `subprocess.Popen` and passing the password twice via `communicate()` now works as a workaround for this issue.

**Comment by G10h4ck** [comment]
AFAIU this bug is solved
