### ISSUE TITLE
Provide musl libc-compiled binaries/AppImages

### ISSUE THREAD

**Issue by hardBSDk** [RetroShare/RetroShare#2648]
[musl libc](https://musl.libc.org/) create more light/safe binaries (less binary size) than glibc, the codebase of musl has less security bugs (less lines of code - lower surface attack) and better optimized binaries.

**Comment by G10h4ck** [comment]
We do use open build service from opensuse.org to generate de appimages, please ask to them to add this option, once they add support for musl libc Appimage build please ping us again so we can enable it on our repository

Thanks for reporting
