### ISSUE TITLE
Provide nightly builds

### ISSUE THREAD

**Issue by hardBSDk** [RetroShare/RetroShare#2651]
For better user testing, it's crucial that you provide nightly builds, can be GitHub Actions/GitLab CI artifacs for Windows/Linux.

**Comment by ppetr** [comment]
This should be relatively easy to set up following https://www.appveyor.com/docs/packaging-artifacts/.

**Comment by csoler** [comment]
the problem here is that you need to get the latest commit in both libretroshare and retroshare. So go to libretrohare, issue a "git pull", and it should compile fine.

**Comment by ppetr** [comment]
> the problem here is that you need to get the latest commit in both libretroshare and retroshare. So go to libretrohare, issue a "git pull", and it should compile fine.

Did you perhaps mean to comment on #2732? (There I did a fresh checkout followed by `git submodule update --init --recursive`. So perhaps the tracked submodules' versions are wrong.)

**Comment by ppetr** [comment]
I created an **unofficial** Windows build of the current master branch if someone is interested: https://github.com/ppetr/RetroShare/releases/tag/v0.6.6-67dd1999
