### ISSUE TITLE
Add screenshots to F-Droid

### ISSUE THREAD

**Issue by Korb** [RetroShare/RetroShare#2692]
https://f-droid.org/packages/org.retroshare.android.qml_app/
![Screenshot_2023_0327_231817](https://user-images.githubusercontent.com/3509797/228056815-f523b1f3-a95f-4efd-aa6d-3e6386dbcae5.jpg)

**Comment by G10h4ck** [comment]
The Android QML app is not maintained ATM, while libretroshare for android is maintained and available to build decentralized Android applications on top of it

Cheers
