### ISSUE TITLE
MacOS issues

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#2695]
Hello,
we need help to fix some issues which are macos related any help are welcome.
Would be great if we have active macOS devs to fix issues or combile and debug rs on macos.

issues:
* [**Dock**] ->  https://github.com/RetroShare/RetroShare/issues/1483

Fixed:
* Fixed [**CMD+ M**]  https://github.com/RetroShare/RetroShare/issues/1482 
* Fixed https://github.com/RetroShare/RetroShare/issues/2818
* cant reproduce more this https://github.com/RetroShare/RetroShare/issues/2581
* Fixed https://github.com/RetroShare/RetroShare/issues/2490
* Random crashes https://github.com/RetroShare/RetroShare/issues/2415

https://github.com/RetroShare/RetroShare/issues/2389#issuecomment-1046688706

Here is the instruction how build on Mac:
https://github.com/RetroShare/RetroShare/blob/master/build_scripts/OSX/MacOS_X_InstallGuide.md

Better Howto:
https://decovar.dev/blog/2021/04/01/macos-building-retroshare/#what-about-building-from-qt-creator

**Comment by barracuda156** [comment]
Well, if I figure out how to restore Qt4 support into the current version, I will work on the rest whatever is broken.
