### ISSUE TITLE
Release the current version (0.6.6) for Rasbian 11 aarch64

### ISSUE THREAD

**Issue by ppetr** [RetroShare/RetroShare#2720]
While there is a version for Raspbian 11[^1], it's only for armv7. Recent Raspberry Pi devices are 64-bit, so it'd be very useful to build and release RetroShare for it too.

FWIW, I tried to compile it manually myself, but failed, despite various attempts, I can provide more details, but that'd be for a separate issue.

Also it seems that command `retroshare-service` isn't documented. The documentation only mentions `retroshare-nogui` (https://retroshare.readthedocs.io/en/latest/search.html?q=+retroshare-nogui), which seems to have a different set of flags and set-up instructions.

[^1]: although the download page only mentions Raspbian 10 - this could also be fixed: https://retroshare.cc/downloads.html#raspbian

**Comment by G10h4ck** [comment]
Yeah the documentation is sadly lagging behind `retroshare-nogui` is abandoned and `retroshare-service` which have very few flags but is completely controllable via JSON API took its place.

About supporting Raspbian 64bit we use open build service to distribute packages, please open an issue to them, once they add support for it ping us again so we can enable it on our repository

Thanks
