### ISSUE TITLE
[Arch Linux OBS] RS crashes when navigating Permissions

### ISSUE THREAD

**Issue by jatardine** [RetroShare/RetroShare#2725]
The OBS build for Arch Linux crashes a few seconds after accessing **Settings - Permissions** and immediately when hovering over the icons. This makes it impossible to manage what RS should be allowed to do, according to the user.

This only affects the pre-compiled OBS package, not the independently maintained AUR build.

**Comment by G10h4ck** [comment]
Do this beeps happening with the current unstable OBS build?

Reopen and add info like RS log if it is still the case
Thanks

**Comment by jatardine** [comment]
If those logs would have provided any clue, I would have included them but it's indicating nothing besides a loop when attempting to connect to someone who can't get through.

I'll give the current unstable build a shot soon! Last time I checked I was still confronted with the OBS repo responding with "version inconsistency".
