### ISSUE TITLE
[OBS builds, AppImage & AUR] Missing source files for Plugins

### ISSUE THREAD

**Issue by jatardine** [RetroShare/RetroShare#2726]
I've downloaded RS using the builds provided on OBS and AUR, and additionally tested the AppImage. All of them lack the source files to manually compile plugins and the directory /usr/lib/retroshare is missing entirely, as well.

Manually creating the directory and pulling missing files might solve the issue for the AUR and OBS builds but not AppImage, which needs to be re-build from scratch.

**Comment by G10h4ck** [comment]
WE are not actively maintaining the plugins, but if you find them useful we are open to your contribution, also the recipes which generate those packages are open source so you are welcome to open pull requests to fix them

Thanks

**Comment by jatardine** [comment]
So why are those plugins included in RS for Windows but not in any other version? This doesn't make any sense.

**Comment by G10h4ck** [comment]
Probably who is packaging the windows executable is willing to spend effort on them in the hope someone try them and start helping maintaining them
