### ISSUE TITLE
Possible to restore Qt4 support for macOS? Qt5 is broken on PPC

### ISSUE THREAD

**Issue by barracuda156** [RetroShare/RetroShare#2740]
I am interested to bring RetroShare to Macports. We already have the underlying library: https://ports.macports.org/port/libretroshare (which builds fine on PowerPC systems along with x86 and aarch64). However Qt5 is hopelessly broken: we can only use Qt4 (or GTK) for PowerPC.

**Comment by barracuda156** [comment]
@csoler @thunder2 Maybe someone could advise on this, please?

**Comment by barracuda156** [comment]
Well, okay, I have found that 0.6.4 supports Qt4, while 0.6.5 already does not (or at least claims so).
I will try 0.6.4. It is builds and appears usable, I will see if Qt4 support may be restored into a newer version, or possibly some intermediate one can be used.

**Comment by o0nd7ots** [comment]
I don't think it's worth it to work on qt4 where the current version is qt6.
I suggest you use some linux distro that works with qt5.

**Comment by barracuda156** [comment]
@o0nd7ots I have fixed the build of 0.6.4 with Qt4.
It is available to install via MacPorts: https://ports.macports.org/port/retroshare-qt4

I will close the issue though, since I have no time to restore Qt4 support into the current version myself, and apparently no one else is interested.

P. S. Linux is not among options to consider, some BSD maybe, but it could be possible to fix some Qt5 version for macOS too.

**Comment by o0nd7ots** [comment]
> I will close the issue though, since I have no time to restore Qt4 support into the current version myself, and apparently no one else is interested.

In my opinion, and I'm not a developer, it's just additional burden useful in very few edge cases.

Also, why is linux not among options to consider?

**Comment by barracuda156** [comment]
@o0nd7ots Re burden: it depends. Often it is just a matter of not breaking the code during a major update but instead retaining a fallback. That was already not done, unfortunately. Nevertheless, restoring will also likely be a single-time effort. There are multiple software which currently maintains compatibility with several versions of Qt, including Qt4 (and likewise several versions of GTK).

It may be even better to introduce a GTK GUI instead, but that will be a lot of work.
