### ISSUE TITLE
Unable to compile V0.6.6 (source-with-submodules) with gcc-c++ 13.1

### ISSUE THREAD

**Issue by jmrcpn** [RetroShare/RetroShare#2748]
I was not able to successfully compile 0.6.6 with gcc-c++-13.1 until I made the 2 following modifications:

sed -i                                                  \
  -e "/^#include <sstream>/a #include <filesystem>"     \
  ./libretroshare/src/util/rsdir.cc

sed -i                                                  \
  -e "/^#include <math.h>/a #include <cstdint>"         \
  ./retroshare-gui/src/gui/statistics/Histogram.cpp

Hope that Help...

**Comment by G10h4ck** [comment]
Is this still happening in development version? If so please open a PR with the fixed files, as I am not able to reproduce this on my systems.

Thanks
