### ISSUE TITLE
Last Post view in forums shows random dates

### ISSUE THREAD

**Issue by hunbernd** [RetroShare/RetroShare#280]
If you switch the view mode in a forum to Last Post, you will get random dates for posts.

It is caused by an uninitialized variable **RsGxsMsgMetaData.mChildTs**
Its value should be calculated locally, but it never happens.
I don't know what the purpose is of this variable.

Also what would be the difference between Last Post view and Threaded view + ordering by date?

**Comment by defnax** [comment]
Fixed #456
