### ISSUE TITLE
Are there plans to provide 0.6.7 as an AppImage.

### ISSUE THREAD

**Issue by SeeJayEmm** [RetroShare/RetroShare#2825]
Are there plans to provide 0.6.7 as an AppImage?  The latest I can find is 0.6.6.

**Comment by FloraMaeWolfe** [comment]
I hope they do, the appimage is really nice.

**Comment by FloraMaeWolfe** [comment]
I just noticed in the release section there is an appimage
https://github.com/RetroShare/RetroShare/releases/tag/v0.6.7.2

**Comment by SeeJayEmm** [comment]
@FloraMaeWolfe thanks. I'm not sure how I missed that.
