### ISSUE TITLE
Where's my dear friend Cyril

### ISSUE THREAD

**Issue by zzdtszz** [RetroShare/RetroShare#2853]
Have installed 67 to the Macbook.  I take my hat off to the RS Dev Team.  Everything looks great.  But I don't see anybody.  What did I miss?  
Kindest Regards, 
dietrich
Take pity on an old man...help.
![image](https://github.com/RetroShare/RetroShare/assets/166239512/748da945-de1a-43cf-80ee-1469f84bec15)

**Comment by zzdtszz** [comment]
i managed to get back up on my feet.  :/

**Comment by csoler** [comment]
Hi Dietrich. It's been a long time! Maybe you don't see anyone in the chat because your machine has a shifted time?

**Comment by zzdtszz** [comment]
Well I'm in now. I just did some dumb things. Thanks for replying and I
hope all is well with you and yours. Strawberry season soon!
Kind regards,
Dietrich
