### ISSUE TITLE
Icons are blurry

### ISSUE THREAD

**Issue by the-architect-2030** [RetroShare/RetroShare#2869]
After following [this guide](https://mxlinux.org/wiki/hardware/high-resolution-displays/), the UI scale of the app is small, [font is small](https://github.com/RetroShare/RetroShare/issues/2868), icons are blurry as well

![Screenshot_2024-07-12_19-01-46](https://github.com/user-attachments/assets/39f5caee-8743-4c9f-8a56-99f8ebd8af46)

Some fonts are good like the left side bar.
But other parts fonts is small

![Screenshot_2024-07-12_19-10-28](https://github.com/user-attachments/assets/997278a9-e995-4dec-ae32-fb77ed42736e)

**Comment by defnax** [comment]
we need help, on macos i has issues with fonts my temporary fix
(https://github.com/RetroShare/RetroShare/pull/2843)

for main toolbar you need set icon size in settings
i never use more toolbar only left itemview looks better 
![image](https://github.com/user-attachments/assets/f145f818-5a10-4492-b79a-e16f0f2da8d3)

**Comment by defnax** [comment]
close is when its solved your problem
