### ISSUE TITLE
local ip address detection in latest build 0.6.0 Revision 7ded128b not showing right address

### ISSUE THREAD

**Issue by pl4hh** [RetroShare/RetroShare#292]
In Windows QT5 RetroShare Version: 0.6.0 Revision 7ded128b the local ip address 
seems to be showing wrong address (169.245.x.x) although my local address is in
the 192.168.x.x address space.

checking ipconfig /all for that 169er network does not yield any adapter using
that address space.

the older version qt4 0.6.0x rev 8551 just works fine showing the right address, will
check the qt4 version of the latest version in a sec.
....
Version: 0.6.0 Revision 7ded128b Windows QT 4.8.7 also shows the 169er network.

and i'm using portable install, if that is of any concern.

**Comment by hunbernd** [comment]
I noticed the same thing.

The 169.245.x.x address is some kind of fallback and only used when Windows cannot acquire address from DHCP.
I have a valid local IP, but RS is still using this fallback address.

**Comment by TheSentry** [comment]
Maybe this is the same issue as RS not recognizing that the external IP changed when the ISP assigns a new one. Could it be that RS is started so early that it gets the fallback IP address before the DHCP client can acquire the real one?

Maybe this will be fixed, too, once I finished the automatic IP renewal function.

**Comment by myfingerhurt** [comment]
Mine is Windows 10, and there is a TAP-Windows Adapter in my Network Connection, its address is 10.x.x.x, the RetroShare insists on using this Tap-adapter as my local address. But actually, my true Lan address is 192.168.x.x. 

After I delete the Tap-adapter, RetroShare uses 169.245.x.x as Lan address, well seems I have to give QT-4 a try.

 RetroShare 0.6.2 QT-5

**Comment by gongzisun** [comment]
Still exist
