### ISSUE TITLE
Qt Version in About is incorrect

### ISSUE THREAD

**Issue by realityfabric** [RetroShare/RetroShare#299]
I compiled with Qt 5.5.1, but when I checked the About section it said that I had compiled with Qt 4.8.something. I compiled on Ubuntu 15.10

**Comment by electron128** [comment]
How do you know the about window is wrong?
Maybe you used a different Qt version than you wanted to use.

If i would just type qmake, i would get the wrong Qt (on Ubuntu 15.10)

```
$ qmake --version
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

$ /usr/lib/x86_64-linux-gnu/qt5/bin/qmake --version
QMake version 3.0
Using Qt version 5.4.2 in /usr/lib/x86_64-linux-gnu
```

Next step would be to figure out how to make qmake point to qmake in Qt 5 directory.
It seems qtchooser can do this: http://manpages.ubuntu.com/manpages/wily/man1/qtchooser.1.html

**Comment by realityfabric** [comment]
When I use qmake --version I do get the 4.8.6 instead of 5.5.1, but I am compiling with Qt Creator, and I expected the version that I told it to use to be the version it used. I'll look into why Qt Creator isn't using the version of Qt I specified for it to use.

**Comment by realityfabric** [comment]
Does RetroShare no longer output an executable into /usr/bin ?

I think the problem was that I thought it was being output to /usr/bin when it was actually being output to a debug folder. The version compiled in the debug folder says that it was compiled with Qt 5.5.1.
