### ISSUE TITLE
 Create a simple Skype-like alternative Qt5 QML Gui 

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#30]
we propose to make a simple Skype-like alternative to retroshare-gui. only Chat, Lobbies and Voip/Video. Not sure what to call it - but we will probably use a different brand from retroshare. 
Here you can find the example qml model:
https://github.com/drbob/rsqml-models

make a easy clean gui like skype:
https://skypeblogs.files.wordpress.com/2014/10/mac1.png

or look example project:
https://ring.cx/

QML retroshare client:
https://github.com/Emotyco

**Comment by ohhmm** [comment]
consider plug in skins system

**Comment by defnax** [comment]
QML gui by @kdebiec needs to be continoued
https://github.com/Emotyco
