### ISSUE TITLE
RetroShare takes a very long time to close

### ISSUE THREAD

**Issue by realityfabric** [RetroShare/RetroShare#300]
It's possible it's just not closing at all, it could be stuck in a loop or something. It has been running through checkPotentialPeer and "Cleaning known IPs for all users" for over 10 hours.

There is output, so things are happening, but 10 hours is a very long time when I expected the program to close immediately.

**Comment by realityfabric** [comment]
I used ctr + c to force close the program from the terminal, and when I ran and closed it again it closed almost immediately, without going into checkPotentialPeer or "Cleaning known IPs for all users" at all

**Comment by felisucoibi** [comment]
Happens to me, it takes like 5 minutes that I can't open again rs because there is a locked file, after closing.

**Comment by realityfabric** [comment]
It's happened a few more times, and I have to forcibly close the program because of the amount of time it takes. Even 5 minutes is too much, if it's going to clean up things it should handle that while the program is running, not after the program is terminated.
