### ISSUE TITLE
There are functions which use MD5 encryption

### ISSUE THREAD

**Issue by realityfabric** [RetroShare/RetroShare#306]
MD5 encryption has been known to be vulnerable for 20 years, and has been proven to be vulnerable more than 10 years ago.

**Comment by TheSentry** [comment]
MD5 is a hashing algorithm, not encryption.

But yes, we could set an example and use SHA-3 instead.

**Comment by csoler** [comment]
MD5 should not be used for signature. Where did you find this??

**Comment by realityfabric** [comment]
It's in some of the files inside of the openpgpsdk libraries. It's possible that the md5 portions aren't actually used, but if they aren't they should be removed. The license allows for the modification of the libraries so long as the changes are logged.
