### ISSUE TITLE
IPv6 networking support

### ISSUE THREAD

**Issue by ppetr** [RetroShare/RetroShare#309]
Hi, I'd be interested in investing some spare time to help with coding to get IPv6 support to RetroShare. I haven't found a bug for this yet, so I'm opening this as a tracking bug. What are the steps that need to be done and where would be such help most useful/appreciated?

**Comment by G10h4ck** [comment]
Hi!

There are two separate branches with prototype support for IPv6

https://github.com/RetroShare/RetroShare/tree/v0.6-IPv6
https://github.com/RetroShare/RetroShare/tree/v0.6-IPv6-2

Both of them are based on the idea of using a dual stack socket in pqissl and have been tested successfully on Linux, at first glance this seemed optimal but then some concern on the portability to windows of this approach aroused, for example WinXP do not support dual stack sockets and would end up listening just to IPv6 connections.

We could decide to drop support of WinXP and keep going with this approach that just need refinements...

Another interesting idea would be to have IPv6 implemented in a separate pqissl6 i have thinked about it lot of times but the i never had the time to implement it

So you are welcome!

**Comment by kriswema** [comment]
Hej, here to show some interest in IPv6 support. I have two seperate networks that are connected via IPv6 with IPv4 over DSLite. Retroshare shows a yellow light for NAT and a green light for DHT, but I can't connect to any contacts, whether they are native IPv4 or IPv6.
Which IPv6 branch should I be experimenting with?

I think it would be safe to drop support for operating systems that aren't supported themselves anymore. You're not developing this for an early Debian or Ubuntu version, so why Windows XP? Another solution would be to ship IPv6 support for Linux and whichever operating systems support the used approach, and then add IPv6 support for the others later, or not at all.

Almost forgot: I'm running Retroshare on Debian 7, Debian 8 and Windows 10.

**Comment by ppetr** [comment]
Sorry for my late reply. Regarding Windows XP compatibility, do we have any estimate how many RetroShare users still use it? In general, I'd be more in favor of keeping up with current technologies rather than sacrificing them to support legacy systems, although I'm not a Windows user, so my opinion is a bit biased. If we want to keep IPv4 only version for Windows XP, would it be perhaps possible to achieve it with conditional compilation?

Regarding the IPv6 branches, how do they deal with IPv6 DHT? In particular, do they implement [BEP 32](http://www.bittorrent.org/beps/bep_0032.html)? I _very briefly_ checked the IPv6 code and it seems that the DHT implementation doesn't support IPv6 yet. Having IPv6 working with DHT would allow even IPv4 only users behind NAT to just run a [Teredo tunnel](https://en.wikipedia.org/wiki/Teredo_tunneling) and locate and connect to each other.

I did some experiments with [Juliusz Chroboczek's DHT library](https://github.com/jech/dht) with quite good results, and it fully supports IPv6, perhaps it could be useful for RS too.

**Comment by G10h4ck** [comment]
> Sorry for my late reply. Regarding Windows XP compatibility, do we have any estimate how many RetroShare users still use it?

I doubt there is still RetroShare users using Windows XP but I cannot guarantee...

> would it be perhaps possible to achieve it with conditional compilation?

It is a possibility but I haven't worked on it and sincerely i do prefer to do other things ;)

> Regarding the IPv6 branches, how do they deal with IPv6 DHT?

It doesn't, if you are interested in implementing IPv6 support for RS DHT to me seems reasonable to investigate how to use [opendht](https://github.com/savoirfairelinux/opendht) (That is derived from the one written by Juliuz) inside RS instead of implementing IPv6 in libbitdht that imho is a bit of a reinvented the wheel...

Cheers!
the most reasonable thing ATM is to

**Comment by ppetr** [comment]
> It doesn't, if you are interested in implementing IPv6 support for RS DHT to me seems reasonable to investigate how to use opendht...

Sounds good, I'll have a look when I get some spare time. Which IPv6 branch should I work on?

**Comment by G10h4ck** [comment]
The last edit to IPv6 code has been an year ago, so i suggest to not base your work on a old branch but to create a new one and git cherry-pick what you think is useful from the ipv6 branch

https://github.com/RetroShare/RetroShare/tree/v0.6-IPv6-2

Because in the mean time the main code could have changed enough to make merging difficult 

Cheers!

**Comment by cavebeat** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=31997461)](https://www.bountysource.com/issues/31997461-ipv6-networking-support?utm_source=31997461&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by G10h4ck** [comment]
I have solved this with this PR https://github.com/RetroShare/RetroShare/pull/1191
