### ISSUE TITLE
CppCheck results for RetroShare - Run Date 3/19/2016

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#311]
Dear RetroShare Developers,

The attached pdf is from a full cppcheck scan I ran against the entire RS project.
Please review and let me know your thoughts and how I can be of help.

-- Dietrich
[rs-cppcheck-20160319.pdf](https://github.com/RetroShare/RetroShare/files/180928/rs-cppcheck-20160319.pdf)

**Comment by csoler** [comment]
thx a lot. we'll take care of it asap.

**Comment by savchenko** [comment]
...Have you ever considered http://www.viva64.com? Maybe worth to contact them.

**Comment by sirjenster** [comment]
this  is tedious to deal with. please provide a spreadsheet format. this way it can be sorted as to type and location. work  fixing can be divvied up that way as to who can repair what and the expertise needed.

**Comment by dtschmitz** [comment]
xls format in zip attached
[rs-cppcheck-20160318-xls.zip](https://github.com/RetroShare/RetroShare/files/182105/rs-cppcheck-20160318-xls.zip)
