### ISSUE TITLE
RetroShare Reference Manual in PDF Format -- Draft -- Created 3/20/2016 for Review

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#316]
Dear RetroShare Developers,

Please find a rough draft RetroShare Reference Manual created today in PDF format (from LaTeX) for your review/feedback/use.

Let me know your thoughts.  -- Dietrich
[refman.pdf](https://github.com/RetroShare/RetroShare/files/181414/refman.pdf)

**Comment by csoler** [comment]
It's a huge document! I suppose that users can generate it themselves when needed, using 
what's described here: http://stackoverflow.com/questions/4099572/how-to-get-a-single-pdf-document-from-doxygen. We should probably add the howto to generate the file in the toplevel README.

**Comment by dtschmitz** [comment]
This type of document would be of greatest benefit to Developers, needless to say.  It's a 'draft' as mentioned and proffered as a way to provide assistance to those unfamiliar with RS apis and the object hiearchy -- coming to terms with a broader understanding of the project will only enhance their abilities to code.

As for 'users'.  I am not so interested in tendering it to them.  The wiki's format provides just enough of a veneer to satisfy their curiosity and isn't difficult to navigate to find setup information and FAQs.

I should think however, putting the doxygen HTML version on-line might be the preferred way to go.  Yes?

**Comment by csoler** [comment]
Given that generating this document requires a simple command, I don't see a point in committing a large file that is going to change on every commit. However, listing that command in the README file seems a good idea to me.

**Comment by dtschmitz** [comment]
csoler wrote:

> We should probably add the howto to generate the file in the toplevel README.

See new [issue](https://github.com/RetroShare/RetroShare/issues/321)
Closing 316.
