### ISSUE TITLE
Feature Enhancement Request: Add Message Notification for when banned

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#317]
Have RS handle the event of banning with a side effect message to the user who is being banned to notify them when their banned status is being toggled (negative, 0, positive).  This should include changing the banned state following initial banning, to notify of any and all changes toggling the banned status.

Example message text:
sprintf("User %s has changed your ban status from: %s to %s on date/time: %s\n", $user, $frstat, $tostat, $dt);

Currently, a user may be unaware they have been banned, which affects the functionality in many areas of RS.  For example, sending a message to a recipient who has banned you will never be received by the recipient.

Your thoughts please. -- Dietrich

**Comment by realityfabric** [comment]
If someone has been banned, making it easier for them to circumvent the ban by immediately notifying them (and thus allowing them to quickly create a new identity) will only make it easier for the banned user to continue to harass the person who banned them.

I've never seen this implemented anywhere else, and I see no reason why it should be implemented here.

**Comment by csoler** [comment]
@realityfabric: I agree 100%.

Besides, the banning is only local, so advertising it not only displays information that noone else cares about, but it would result in endless fights between trolls. We've had enough of this.

**Comment by sirjenster** [comment]
This a very rough equivalent to unfriending/blocking on Facebook...
My sister had friended all her relatives on Facebook. However, an old uncle, who is nice in real life,  continually posts very  judgemental and occasionally obnoxious comments on her page. These reflected rather badly on her so she unfriended/banned him.  Had he been notified of changes, it would have created family issues where none existed before.
