### ISSUE TITLE
People window scaling issue when window is resized

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#319]
In 'People', the scaling should have a 'limit' when the user resizes the window.

See the attached jpg for an example of what happens.
![screenshot from 2016-03-21 11-53-17](https://cloud.githubusercontent.com/assets/33075/13924874/6b20709e-ef5c-11e5-8887-b11a841ce5d3.png)

**Comment by defnax** [comment]
this is not a bug, a feature to resize or shrink the mainwindow small as possible, some body did this i dont know who.
