### ISSUE TITLE
Program not responding and crashes after  any operation on the .rscollection file

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#320]
When I want to download / view / modify the collection program hangs, and then crashes. 
Collection is not broken.

OS Windows 7  SP1. RetroShare  v0.6.0 Revision7ded128b

**Comment by dimqua** [comment]
I have the same problem, but program doesn't crash.

Gentoo Linux, amd64, Qt5.

**Comment by PhenomRetroShare** [comment]
Can you past RsColl file that crash?

**Comment by ghost** [comment]
[rscollection.zip](https://github.com/RetroShare/RetroShare/files/191072/rscollection.zip)

**Comment by PhenomRetroShare** [comment]
No error openning it...
Linux AntergOS 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016
x86_64 GNU/Linux
Qt5
Maybe because it's LF ending file...
Nope, working on Win7 32b...
