### ISSUE TITLE
Valgrind MemCheck Results on RetroShare -- run date 3/23/2016 -- Memory Leaks Found

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#322]
Cyril,

I've run the Valgrind MemCheck analysis tool against RetroShare tonight.  Here is the log:
[valgrind_27323.txt](https://github.com/RetroShare/RetroShare/files/187227/valgrind_27323.txt)

Essentially, Valgrind found memory leaks of a variety which will require some careful interpretation and debug to locate and fix.

I note in the console output as RetroShare exits the following:

>   Stopping plugins.
> p3discovery2::statusChange() Disconnected: f45934042cd8f72fa72f35def5aa878d
> *_Memory still in use at end of program: 215544 bytes.
> *_
> Here is a [link](http://valgrind.org/docs/manual/mc-manual.html#mc-manual.leaks) to the Valgrind Manual and the Memory Leak Detection section, which clarifies the meaning of each memory exception detected in the attached log.

Please review and let me know how I can be of help in tracking down these bugs.

-- Dietrich

**Comment by csoler** [comment]
thx for the report. I suggest you use "--track-origins=yes" in order to see where the uninitialized memory read come from. Most of the time it's false alarms due to the way libcrypto uses uninitialised memory (as a random pool??). The bad thing about this is that it totally hides the true problems.

**Comment by dtschmitz** [comment]
Cyril, I created another output file from the command line this am with:

`valgrind --leak-check=full --show-reachable=yes --error-limit=no **--gen-suppressions=all **--log-file=/home/dts/retroshare/trunk/valgrind/minimalraw.log /home/dts/retroshare/trunk/retroshare-gui/src/RetroShare06`

This creates a 'suppression' record¹ for each discrete entry.
Then, I filtered the resultant file using a Perl script as follows:

`cat minimalraw.log | ./grindmerge.pl > newrules.txt`

[grindmerge.pl.txt](https://github.com/RetroShare/RetroShare/files/188501/grindmerge.pl.txt)

[newrules.txt](https://github.com/RetroShare/RetroShare/files/188504/newrules.txt)

The perl script produces one instance of each suppression rule found in the valgrind raw output file in newrules.txt

If I could ask you to review this file to identify which rules should be used for suppression, then I'll take your edited file of rules and rerun valgrind so as to sort the wheat from the chaf (libcrypto.so, etc.).

Thank you. -- Dietrich

---

¹Footnote: To those following this ticket, valgrind:memcheck is being used to find 'bona fide' memory leaks in RetroShare.  It has been observed by me and Cyril that there is a large segment of 'false positives', for example, libcrypto.so is a prime offender of for using unitialized variables.

The 'suppression' rules that I am working on with Cyril will result in valgrind 'ignoring' those 'false positives' which are not part of the RS project per se.

Hope that helps.  -- Dietrich

**Comment by csoler** [comment]
unfortunately, there's no point in generating a suppression file against the pb caused by libcrypto, since they have the same cause (see it with --track-origins=yes) but appear in potentially random places. The only possibility (as far as I know) is to recompile libcrypto with specific flags that avoid causing these valgrind false alarms. See this: http://www.hardening-consulting.com/posts/20140512openssl-et-valgrind.html and this: http://www.mail-archive.com/openssl-users%40openssl.org/msg52081.html

Also, at every post here, I receive an email. No need to notify me otherwise.

**Comment by dtschmitz** [comment]
Yes.   I see what you mean.  Le sigh.  Closing issue.
