### ISSUE TITLE
bdNode:addPeer() is flagging LAN reserved 192.168.1.1/24 as banned

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#340]
Cyril:  I finished compiling commit  f26348b this am and now it core dumps -- here is the tail of retro.log - bdNode::addPeer() should not flag 192.168.1.1/24 as 'bad' -- these are LAN reserved:  bdNode::addPeer(9276cca28ddbf8bbeeca3cdae2fe259cfa93cf24 ip:192.168.1.1:38917, 100f03) MASQARADING AS KNOWN PEER - FLAGGING AS BAD 
Adding New Banned Ip Address: 192.168.1.1 
bdNode::sendPkt()Outgoing Packet Filtered 
bdNodeManager::doInfoCallback() 
RsGxsNetService::encryptSingleNxsItem() 
Group Id list is empty GxsTokenQueue::checkRequests() 
ERROR Request Failed: 0

[1]+ Segmentation fault (core dumped) RetroShare06

Please review and advise asap.  Thank you. -- Dietrich

**Comment by csoler** [comment]
Local IPs shouldn't be banned, obviously!

For the crash, please post here a callstack. Otherwise, there's no way I can figure out what causes it.

Thx!

**Comment by dtschmitz** [comment]
[rs-coredump.txt](https://github.com/RetroShare/RetroShare/files/206611/rs-coredump.txt)

fwiw, "Sentry" was on the Devel signed looking for you regarding a similar issue last eve. re bad addresses spamming RS, fyi...  Did you merge one of his PR's?  Thanks Dietrich

**Comment by csoler** [comment]
your callstack indicates that should you do a make clean and re-compile from scratch:

#0  0x000000000060db50 _ZN12NotifyClient27askForDeferredSelfSignatureEPKvjPhPjRi (RetroShare06)
#1  0x0000000000a2c1dd _ZN8p3Notify21notifyDiscInfoChangedEv (RetroShare06)

notifyDiscInfoChanged has no reason to call a function that asks for PGP signature. So your symbol tables are probably inconsistent across the final executable ;-)

**Comment by dtschmitz** [comment]
ok will do. thanks.

**Comment by TheSentry** [comment]
@dtschmitz I haven't submitted a PR, yet, but my issue was not with blocking addresses but making sure RS knows about the correct own address.

**Comment by dtschmitz** [comment]
@thesentry ok thanks for the heads up.

**Comment by dtschmitz** [comment]
make clean resolved my issue per @csoler 's advisement.  closing issue.
