### ISSUE TITLE
Build failure in Voidlinux

### ISSUE THREAD

**Issue by abelboldu** [RetroShare/RetroShare#349]
Hi, Im having troube to build packages on voidlinux, which I didn't had on RC2.

See 
https://github.com/voidlinux/void-packages/pull/3750
https://travis-ci.org/voidlinux/void-packages/jobs/114502245

```
/usr/bin/ld: ../../libretroshare/src/lib/libretroshare.a(rsthreads.o): undefined reference to symbol 'sem_getvalue@@GLIBC_2.2.5'

/lib64/libpthread.so.0: error adding symbols: DSO missing from command line

collect2: error: ld returned 1 exit status
```

Any help on what dependency is missing?

**Comment by xtraeme** [comment]
This is missing `-lrt`

**Comment by csoler** [comment]
My first guess is -lpthread.

**Comment by xtraeme** [comment]
True, my first comment was wrong. It's in libpthread. The real issue is ld(1) `--as-needed`. Probably the arguments in the linking target are not properly ordered.

See https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Importance_of_linking_order

**Comment by Vaelatern** [comment]
Any progress on this?
