### ISSUE TITLE
Allow using multiple anonymization networks simultaneously

### ISSUE THREAD

**Issue by HulaHoopWhonix** [RetroShare/RetroShare#357]
When configuring RetroShare to use I2P I noticed that I cannot configure it to listen on Tor. Please allow incoming connections on multiple proxies.

**Comment by HulaHoopWhonix** [comment]
Was the feature request rejected or added?

**Comment by cavebeat** [comment]
it was not added to https://github.com/RetroShare/RetroShare/blob/master/TODO.txt so it is rejected.

**Comment by dimqua** [comment]
Is it even possible?
