### ISSUE TITLE
clang-analyzer output: scan-build-2016-04-24-200507-12319-1

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#358]
unzip and view using scan-view 
[scan-build-2016-04-24-200507-12319-1.zip](https://github.com/RetroShare/RetroShare/files/234365/scan-build-2016-04-24-200507-12319-1.zip)

Summary in pdf format:
[scan-build-results.zip](https://github.com/RetroShare/RetroShare/files/234390/scan-build-results.zip)

Memory Leaks:
http://i.imgur.com/hmU2IR8.png

**Comment by csoler** [comment]
thx a lot for this.

Memory leaks in openpgp-sdk are generally tricky to clean. I hope that if they can be seen by a static analyzer, they'll be easier to correct ;-)

**Comment by cavebeat** [comment]
is it still open, may i close it?
