### ISSUE TITLE
Compilation on Linux fails without -DUBUNTU flag

### ISSUE THREAD

**Issue by merkeld** [RetroShare/RetroShare#364]
Compilation on Linux fails without -DUBUNTU flag. Besides that I think this variable should be renamed to something like USE_GNOME_KEYRING.

GCC error messages:
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc: In static member function 'static bool RsLoginHandler::tryAutoLogin(const RsPeerId&, std::__cxx11::string&)':
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc:215:26: error: 'RsInitConfig' has not been declared
  const int KEY_DAT_LEN = RsInitConfig::load_cert.length();
                          ^
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc:216:45: error: 'RsInitConfig' has not been declared
  unsigned char\* key_data  = (unsigned char_)RsInitConfig::load_cert.c_str();
                                             ^
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc: In static member function 'static bool RsLoginHandler::enableAutoLogin(const RsPeerId&, const string&)':
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc:421:60: error: request for member 'c_str' in 'RsLoginHandler::getAutologinFileName', which is of non-class type 'std::__cxx11::string(const RsPeerId&) {aka std::__cxx11::basic_string<char>(const t_RsGenericIdType<16u, false, 1u>&)}'
  FILE_ helpFile = RsDirUtil::rs_fopen(getAutologinFileName.c_str(), "w");
                                                            ^
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc:431:26: error: 'RsInitConfig' has not been declared
  const int KEY_DAT_LEN = RsInitConfig::load_cert.length();
                          ^
../../../RetroShare/libretroshare/src/rsserver/rsloginhandler.cc:432:44: error: 'RsInitConfig' has not been declared
  unsigned char\* key_data = (unsigned char*)RsInitConfig::load_cert.c_str();

**Comment by G10h4ck** [comment]
This should be fixed in master branch, feel free to reopen if it's not the case
