### ISSUE TITLE
How to Install On Raspberry Pi 3

### ISSUE THREAD

**Issue by liberodark** [RetroShare/RetroShare#368]
Hello,

How to Install RetroShare 0.6 On Raspberry Pi 3 ?

Cordialy

**Comment by TheSentry** [comment]
Raspberry Pi 3 is a hardware platform, it's like asking on how to install RetroShare 0.6 on a PC. It really depends on what operating system you're using.

If you use Raspbian, which is based on Debian, then you can simply build it yourself by following the [instructions in the wiki](https://github.com/RetroShare/RetroShare/wiki/Compile).

I'm not sure if there are already deb-packages for Raspbian, yet.

**Comment by liberodark** [comment]
On Raspbian 8

**Comment by TheSentry** [comment]
Have you tried compiling it using the information in the wiki? Or in the README.md? It works on my Raspberry B running Raspbian Wheezy.

**Comment by cavebeat** [comment]
@liberodark 
https://blog.cavebeat.org/2013/08/howto-compile-retroshare-on-raspberry-pi/
https://blog.cavebeat.org/2015/02/build-retroshare-v0-6-x-prealpha-on-debian-wheezy/
and more up to date, in the wiki https://github.com/RetroShare/RetroShare/wiki/Compile
