### ISSUE TITLE
7 icons on the toolbar when I start retroshare06 on ubuntu 16.04 gnome-panel

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#369]
Here you can see what happens when I start RS, i'm using ubuntu 16.04, with gnome-panel desktop.

To reproduce it:
sudo apt-get install gnome-panel
log out and log in with gnome-panel desktop.
Start retroshare06

![captura de pantalla de 2016-05-04 22-57-17](https://cloud.githubusercontent.com/assets/1285303/15028962/b4490062-124b-11e6-90d2-43204289c622.png)

**Comment by PhenomRetroShare** [comment]
Hello,
This is not due to retroshare. It's a Qt-Ubuntu issue:
https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1542691
