### ISSUE TITLE
Problem after latest compile ongoing

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/RetroShare#376]
Debian Testing 8.4 Qt5 .

gdb output as requested

[gdb.txt](https://github.com/RetroShare/RetroShare/files/259034/gdb.txt)

**Comment by PhenomRetroShare** [comment]
Add this to your gdb:
handle SIGPIPE nostop noprint pass

**Comment by cavebeat** [comment]
@morpheusbeing do you want to update the issue, is it already resolved or can i close it?
