### ISSUE TITLE
No traffic besides DHT, chat lobby list doesn't load.

### ISSUE THREAD

**Issue by yurivict** [RetroShare/RetroShare#391]
I use the FreeBSD port, version 0.6.0.

It seems to connect, NAT and DHT lights are green, it shows 2.3k DHT users. But Down/Up numbers in the bottom right cornet are always zero, and "Public Lobbies" list doesn't get populated as it should.

"Nat" option is set to "Manually Forwarded Port". Specified port is open.

I am not sure how to troubleshoot this.

**Comment by csoler** [comment]
You should only see the lobbies that your connected friends are subscribed to. Same for forums, channels, etc.

No up/dn traffic seems like you're not connected to anyone. Have you exchanged certificates with friends already? Are you connected to some of them (See network tab)?

Sorry for the "make sure it's plugged-in" question, but that's really what it looks like ;-)

**Comment by yurivict** [comment]
Sorry, I didn't realize that I need to have friends to do something in retroshare.

It works fine. Thanks!
