### ISSUE TITLE
Crash on Windows 7 x64 at starting

### ISSUE THREAD

**Issue by lrq3000** [RetroShare/RetroShare#397]
When starting RetroShare-0.6.0-20160206-7ded128b on Windows 7 64-bits Home Premium, after the creation of a node and my account, and after I get asked about enabling various modules, then I see the RetroShare banner, and then RetroShare just crashes. I don't even get to see the main window. There are no errors and I never installed it before on this machine. I checked the process manager, the process indeed kills itself suddenly.

I tried both QT4 and QT5 versions, and I tried both the normal install and the portable mode on another partition. I always get the same crash at the exact same point.

**Comment by lrq3000** [comment]
Ok I got something more explicit by using the nogui binary (you should maybe specify in your wiki or forum this method to generate a log in case of troubleshooting, because I read them and I didn't find any clue about it).

Here is what I get:

```
(II) Executable hash matches. Updating the list of accepted/rejected plugins.
p3ServerConfig::switchToOperatingMode(1)
p3ServerConfig::switchToOperatingMode() D/L: 10000 U/L: 10000
p3ServerConfig::switchToOperatingMode() Turtle Mode: 1
Enabling turtle routing for this Session
Force Any Configuration before Startup (After Load)
FATAL ERROR: getLocalAddresses failed!
Memory still in use at end of program: 220 bytes.
```

These are the last lines, after that the program crashes.

I have several cards: one for ethernet, one for Wifi, and 3 virtuals, but they are all disabled except the one I am currently using (wifi). I never got such an error with any other network app I've been using.

**Comment by G10h4ck** [comment]
This bug should be already fixed in master branch, feel free to reopen if it's not the case
