### ISSUE TITLE
retroshare-nogui -G does not create password hash?

### ISSUE THREAD

**Issue by text-editor** [RetroShare/RetroShare#404]
retroshare-nogui with the -G flag is not creating a password hash for me, just ignoring the flag and starting normally it seems

**Comment by csoler** [comment]
that's an old option that is not active anymore. We should remove it.

**Comment by sehraf** [comment]
@text-editor what RS version are you using? The -G option should not be displayed (which is the case here using latest git version)

**Comment by text-editor** [comment]
0.6. Didn't know it was removed, assumed it just wasn't documented well because I found sparse references to it.

Thanks for pointing that out

**Comment by sehraf** [comment]
it was part of the old ssh/rpc system which is now replaced by the json api
