### ISSUE TITLE
Compilation of nogui fails

### ISSUE THREAD

**Issue by Kcchouette** [RetroShare/RetroShare#439]
On debian 8.5 (jessie), I tried to install the nogui version of RetroShare - the commit https://github.com/RetroShare/RetroShare/commit/713deac7582cde19764b7f528668ea83b0f9894d.

I have done:

```
$ git clone https://github.com/RetroShare/RetroShare.git
$ cd RetroShare/
$ qmake
$ make retroshare-nogui
```

And `make retroshare-nogui` fails.

I attached my log here: [output.txt](https://github.com/RetroShare/RetroShare/files/367877/output.txt)

Thank you for making RetroShare nogui :)

**Comment by csoler** [comment]
try with "make" instead of "make retroshare-nogui". It's probably missing libretroshare and so on.

**Comment by Kcchouette** [comment]
Thank you for your quick answer.

But if I try `make` instead of `make retroshare-nogui`, the make has error about the GUI that I don't have (`Project ERROR: Package x11 not found` in this case).

I'm trying to build it on a server, and don't really want to install graphical dependance (like xorg and things like that) for just building a non-graphical software.

Is there a way to fix the make or is there a way to help you fixing this issue by testing something else?

Thanks.

**Comment by csoler** [comment]
Once libretroshare, libbitdht and openpgp-sdk are made you should be able to make retroshare-nogui.

**Comment by Kcchouette** [comment]
You're right, thank you!

So here how to compile the no-gui version:

```
cd retroshare/libbitdht/src && qmake && make clean && make
cd ../../openpgpsdk/src && qmake && make clean && make
cd ../../libretroshare/src && qmake && make clean && make
cd ../../libresapi/src && qmake && make
cd ../../retroshare-nogui/src && qmake && make clean && make 
```

I'm closing this issue! Thank you :)

Edit: Fix `libresapi` command (remove the make clean)

**Comment by Kcchouette** [comment]
Can fix #272

**Comment by sehraf** [comment]
interesting though that it works manually but not automatically (using make retroshare-nogui) ...
both gui and nogui have the same dependencies:

```
retroshare_gui.file = retroshare-gui/src/retroshare-gui.pro
retroshare_gui.depends = libretroshare libresapi
retroshare_gui.target = retroshare-gui

retroshare_nogui.file = retroshare-nogui/src/retroshare-nogui.pro
retroshare_nogui.depends = libretroshare libresapi
retroshare_nogui.target = retroshare-nogui
```

**Comment by Kcchouette** [comment]
@sehraf : I don't get the point too. Maybe I should share the Makefile it creates after a qmake?

**Comment by sehraf** [comment]
i'm not familiar with Makefiles ...
just tried to build nogui only here and it did work so the problem might be related to you/your environment. What Qt version do you use? (I'm using 5.7.0). Also worth mentioning: you log shows that everything is built and the lib files (.a) are created. Did yoz try a clean build, too? (using make clean and make distclean)

**Comment by Kcchouette** [comment]
> What Qt version do you use?

If you speak about my qmake version/others software version, I use a stable up-do-date Debian Jessie.
So for example, for qmake, I'm using version 4.8.6.

The problem is not it do not build (because I can build it manually, as said [here](https://github.com/RetroShare/RetroShare/issues/439#issuecomment-233739702)), but the automatically build (as written [here](https://github.com/RetroShare/RetroShare/issues/439#issue-165978208)) is failing.

I've started from a clean clone of Retroshare, on a clean environment where Retroshare was not installed; doing like the README/Wiki said (so no clean build/make clean/make distclean).

**Comment by sehraf** [comment]
i meant that 
`make retroshare-nogui`
works here (i should have said so 😉 )

**Comment by Kcchouette** [comment]
@sehraf but is it on a fresh Linux who has  any component of restroshare installed? And on a Debian Jessie?

Else I've no idea, it can be a environment problem or debian problem?

**Comment by sehraf** [comment]
No, on an Arch with RS installed and in a clean environment

> Else I've no idea, it can be a environment problem or debian problem?

no idea

**Comment by Kcchouette** [comment]
Arch distro have a gui? Because I don't even have xorg!

**Comment by sehraf** [comment]
The basic installation has nothing 😸 you need to setup xorg or wayland or whatever you want (i think you can even use mir ... but it's not in the official repos).
Alternately you can use a Arch-bases ditro like Antergos or Manjaro.

**Comment by Kcchouette** [comment]
So no idea…

**Comment by Kcchouette** [comment]
@sehraf : On a new install on virtualbox of Debian Jessie with the debian GUI, the `make retroshare-nogui` return the same error. Seems to be a problem with debian Jessie distro.

**Comment by sehraf** [comment]
can you try qt5? maybe the bug related to qt4?

**Comment by Kcchouette** [comment]
@sehraf README (and wiki) asks qt4 for all the linux distro

**Comment by sehraf** [comment]
this doesn't answer the question :D 
nobody seems to care to update things like this ... (also devs don't seem to care to define things like this)

**Comment by Kcchouette** [comment]
@sehraf and @csoler with qt5-qmake, it seems working. I have a bin to launch in the retroshare-nogui folder.

**Comment by csoler** [comment]
the problem is the order of subdirs in retroshare.pro I suppose.
If we put retroshare-gui in last position, the compilation will break, but after retroshare-nogui is compiled.

**Comment by sehraf** [comment]
corret me if i'm wrong but the subdirs order shouldn't matter when a make target is used
maybe @AsamK  can to shed light upon this

**Comment by AsamK** [comment]
@sehraf that's correct, the order doesn't matter, because the dependencies are stated explicitely in the .pro file. You can even compile with -j4 and still the libraries are compiled before the compilation of retroshare-nogui starts.

@Kcchouette in your output file, the compilation of all libraries was successful, only the linking of retroshare-nogui failed. Apparently in the linking command many libraries are missing, see below. I don't know why this happened, maybe an issue with qt4 qmake.

in your file:
         g++ -m64 -Wl,-O1 -o RetroShare06-nogui temp/linux-g++-64/obj/notifytxt.o temp/linux-g++-64/obj/retroshare.o temp/linux-g++-64/obj/TerminalApiClient.o     -rdynamic ../../libretroshare/src/lib/libretroshare.a ../../libresapi/src/lib/libresapi.a

should be like this:
        g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o RetroShare06-nogui temp/linux-g++/obj/notifytxt.o temp/linux-g++/obj/retroshare.o temp/linux-g++/obj/TerminalApiClient.o   -rdynamic ../../libretroshare/src/lib/libretroshare.a ../../libbitdht/src/lib/libbitdht.a -lsqlcipher -lpthread -ldl ../../openpgpsdk/src/lib/libops.a -lbz2 -lgnome-keyring -lglib-2.0 -lssl -pthread -lupnp -lthreadutil -lixml -lcrypto -lz ../../libresapi/src/lib/libresapi.a -lmicrohttpd

**Comment by Kcchouette** [comment]
@AsamK But manually with qt4-qmake, it works (see [here](https://github.com/RetroShare/RetroShare/issues/439#issuecomment-233739702))
