### ISSUE TITLE
Can't start the web-ui

### ISSUE THREAD

**Issue by Kcchouette** [RetroShare/RetroShare#440]
I'm sorry but after compiling with success retroshare-no-gui (see #439), importing a existing .retroshare to my server, doing a 

```
screen 
./RetroShare06-nogui --webinterface 9090 # in RetroShare/retroshare-nogui/src/
```

and then a `distant_machine:~/ >  ssh rs_host -P port -L 9090:localhost:9090 -N`
and going to `http://localhost:9090/` return to me 

```
Error: can't open the requested file. path="/usr/share/RetroShare06/webui/index.html"

directory "/usr/share/RetroShare06/webui/" does not exist!
```

Have I forgotten to execute a command?
I think it's because I forget to write `--docroot /usr/share/RetroShare06/webui/`? But where can I find it?

Thank you.

**Comment by csoler** [comment]
by default RS looks in /usr/share/Retroshare06/webui.

You can change this using the --docroot option. If you compiled the webui, the files are in
libresapi/src/webui/

**Comment by Kcchouette** [comment]
Oh, `qmake && make clean && make` in `libresapi/src` remove the files in the `webui` folder, so I've edited [this issue](https://github.com/RetroShare/RetroShare/issues/439#issuecomment-233739702).

Running `./RetroShare06-nogui --webinterface 9090  --docroot /home/user/RetroShare/libresapi/src/webui/` fix my problem.

Is there a list of what we can do using with webui?

Thanks

**Comment by csoler** [comment]
No there's no list. But the web UI is pretty self-explanatory. It only offers a small subset of the functions otherwise offered by the Qt UI, mainly file transfer, chat, add/remove friends, create identities and profiles.

**Comment by Kcchouette** [comment]
For file transfer for example, I can just download from a retroshare link. I can not adding a share folder or thing like that?

**Comment by csoler** [comment]
saddly no. But if you can find someone with enough motivation/time to work on the webUI, you'd be
very welcome!

**Comment by Kcchouette** [comment]
I'm very interesting of helping that. What's the basis to know before helping?

**Comment by csoler** [comment]
Look at the code in libresapi and see what's missing. Basically there's 2 ways to help in webUI depending on your skills:
- add missing functionality. Take inspiration from what's offered by Qt UI. Suggestions: add a big "options" tab that allows to setup most RS parameters that Qt UI shows in Options. That's a lot of work, but it would be very useful to have that.
- add better looking webUI style (images, css, colors, etc). See how e.g. web UI of the "transmission" software looks like. The current look of web UI of RS only serves functionality ;-)

**Comment by Kcchouette** [comment]
@csoler Can I know why mithril was choosen for webui? (and, for example, not nodejs)?

**Comment by cavebeat** [comment]
@Kcchouette  
my guess: Light-weight , Only 7.8 kB gzipped, no dependencies.
So it fits to https://www.gnu.org/software/libmicrohttpd/ 
maybe @electron128 can give some input.

**Comment by dimqua** [comment]
Why webui switched from [React](https://facebook.github.io/react/)?
