### ISSUE TITLE
Hide or move to the last place "News" feed button.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#484]
For a normal user, this button is useless, maybe a log small button somewhere or if not the last one of the buttons.... the first one should be, Chat, or Files (best name than" shared files" for the button), or the most used ones, new users don't really understand what is for, and old users don't use it at all, they already have the network done... it's technical info and has the most important place in the default button list now.

Also rename it to Log, because a new user will not understand why news, and feed are not a feed (rss) or news... it's just a log.

Bests

**Comment by G10h4ck** [comment]
This is solved in master branch
