### ISSUE TITLE
Simplify button names.... "File sharing" to Files "Chat Lobbies" to Chat....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#485]
DEPRECATED NEW DESING HERE https://github.com/RetroShare/RetroShare/issues/615

Simplify button names to make interface easier and compact.... 
"File sharing" > Files 
"Chat Lobbies" > Chat
Messages > Mail
"News Feed" > remove it or move to the last an change it to "Log"
Posted > Links (its about Links to websites....)

what do yo think?

**Comment by pangoSE** [comment]
I like these suggestions.

**Comment by felisucoibi** [comment]
DEPRECATED NEW DESING HERE https://github.com/RetroShare/RetroShare/issues/615

**Comment by felisucoibi** [comment]
https://github.com/RetroShare/RetroShare/issues/640
