### ISSUE TITLE
UI Problems at Ubuntu Xenial

### ISSUE THREAD

**Issue by thiras** [RetroShare/RetroShare#490]
At latest ubuntu xenial;
1. Clonned Icons at status menu => https://imgur.com/a/1nkcU
2. Broken notifications (friend get online notifications) at right down corner => https://imgur.com/a/L9QlF

I'm using official unstable ppa.

**Comment by felisucoibi** [comment]
They know both problems, the first one seems to be a qt problem of 16.04, and seems is not going to be fixed, the other one I reported it since 15.04... and still there, using gnome-panel as desktop, which deskstop are you using?

**Comment by thiras** [comment]
Default desktop. Unity on gnome.

> the first one seems to be a qt problem of 16.04, and seems is not going to be fixed

So if it's ubuntu's qt problem, why only RS replicate this bug?

**Comment by TheSentry** [comment]
It's not a Qt problem, at least not Qt alone, because I use Ubuntu with KDE desktop and I have none of the problems you describe.
