### ISSUE TITLE
Ghost uploads and downloads....

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#496]
so often i check my rs and i'm not downloading or uploading anything, even file lists etc... nothing.... but some upload and download stuff going on.... why? I checked to see all hiddepn downloads and uploads etc....sometimes just a few kbts others 500K/s up and down.,...

**Comment by G10h4ck** [comment]
That is that you are forwarding tunnels packets for your friends

**Comment by felisucoibi** [comment]
Please reopen this, it has ghost uploads and downloads wit the non anon mode on... you can see in the screenshot the "sin descargas anonimas" that menas non anon downloads but, 200k/s sending somewhere...

![captura de pantalla de 2016-09-30 11-04-53](https://cloud.githubusercontent.com/assets/1285303/18986636/fe6e4be4-86fd-11e6-8b04-fca49192890f.png)
