### ISSUE TITLE
Add a tag for the latest release

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#5]
The revision that is 0.6.rc2 (rev 8551 in the old svn repository) needs to be tagged.

**Comment by cavebeat** [comment]
RC2 == r8551 == https://github.com/RetroShare/RetroShare/commit/89187bd453dbf0112dcee05cb0e71bd18875b6bd

**Comment by cavebeat** [comment]
it got tagged RC2
https://github.com/RetroShare/RetroShare/releases/tag/v0.6.0-RC2

**Comment by SarcoRS** [comment]
Reopening, because completely another revision was tagged RC2, not the one that was 8551 in the old SourceForge svn repository.

The meaning of this 0.6.0-RC2 tag of the revision that @cavebeat quoted in his post is to keep compatibility with the old, SourceForge svn repository, as long as that repository isn't completely abandoned (it is not, because the transition of the RetroShare project to github is not over yet).

**Comment by cavebeat** [comment]
https://github.com/RetroShare/RetroShare/releases/tag/v0.6.0-RC2-SVN

**Comment by chozabu** [comment]
https://github.com/RetroShare/RetroShare/tags - for anyone wondering what happened ;)
