### ISSUE TITLE
Take more attention to the issue tracker without removing them just to make it more clean

### ISSUE THREAD

**Issue by timofonic** [RetroShare/RetroShare#501]
Hello.

I see _TOO MANY_ FOSS projects have really filled issue trackers that rarely get properly maintained. That shows lots of issues about project management.

Another main issue is the lack of a proper user friendly website, difficult configuration and lack of documentation for both users of developers. Wiki pages are often quite unmaintained and there's lack if a clear site where user gets enough idea about the project about why it's more attractive.

Kind regards.

**Comment by cavebeat** [comment]
I'd would be happy to see you helping with the wiki.

**Comment by timofonic** [comment]
@cavebeat 

I would love to!

 I really need some mind stimulating activities, my ADHD and other crap is making things really difficult on whatever project. I always wanted to learn computer programming and electronics, but unfortunately I never finish things and this is depressing me a lot :/ 

I have tons of ideas and opinions, to the point not saying them stress me a lot. And it's an issue if you can't do what you want to do because your chaotic way that rarely focus on something with proper results.

I really think how other geeks managed to surpass issues, as I know many ADHD people that did it (but others not and suffer it too). Unfortunately, I think would require a bunch of patient mentors that motivate and make me focus on tasks intead infinite derailing. 

Other than that, I would love to help at simple tasks and evolve from it progressively.

**Comment by cavebeat** [comment]
is there a way to get in contact? send me a mail for example.

**Comment by cavebeat** [comment]
https://github.com/RetroShare/documentation <-- feel free to fork it. 
each commit to the repo triggers https://retroshare.readthedocs.io to be rebuilt 

I've set it up just now.
