### ISSUE TITLE
Connect with retroshare://... connection link

### ISSUE THREAD

**Issue by ohhmm** [RetroShare/RetroShare#503]
Problem with spaces. Also problem on Windows.

**Comment by cavebeat** [comment]
Please provide some examples.

**Comment by ohhmm** [comment]
MacOS:
Make retroshare link to any location with spaces in its name and you'll see the bug.

Windows:
I'll try to remember to put it tomorrow when I'll be nearby my Windows workstation.

**Comment by TheSentry** [comment]
> MacOS:
> Make retroshare link to any location with spaces in its name and you'll see the bug.

If you describe the bug in detail, even devs without MacOS can maybe fix it.

**Comment by ohhmm** [comment]
Didn't I provide sufficient detail? "Problem with spaces" in connection link.
I understand I not much understandable because of my thought accent.
Just for fun.

**Comment by ohhmm** [comment]
This is the problem on Windows, not related to spaces thus
![image](https://cloud.githubusercontent.com/assets/190779/18810385/4c6ec2d4-829d-11e6-9dde-65e5c2b8b746.png)

**Comment by PhenomRetroShare** [comment]
Fixed by PR#540 and PR#548 all merged.
