### ISSUE TITLE
Sign distro with a certificate

### ISSUE THREAD

**Issue by ohhmm** [RetroShare/RetroShare#504]

**Comment by cavebeat** [comment]
Please provide some description.

**Comment by ohhmm** [comment]
why you closing issues that was no fixed? issue board needed to not forget wishes of users. you just destroy useful information. this is security issue. a virus may obtain control of retroshare.

**Comment by cavebeat** [comment]
You provided no description whatsoever, so we can only guess from the title what you mean. 
i asked you to provide some description, you refused. 
I do not destroy, i just close it. it's still available and it's not deleted. If it's someday enhanced and useful, it's possible to reopen it. 
If you continue to filibuster/DDoS the Issue tracker with incomplete issues, i'll close them.

**Comment by ohhmm** [comment]
@cavebeat, with all respect, the ticket name is self-descriptive and if there is no description then description is the ticket heading. Why is it big deal for you? It just saves our time. This was not a problem with this on other Github projects. I guess is something related to some conventions in a company. Please, be no so judging. I just trying to help you guys, because I like your project and it has huge problems in usability and adequateness. Each issues I proposed before I dig in its code is a not of important things to not forget it. Its not hard to figure out that "Sign distro with a certificate" ticket means that RetroShare installer should be Signed with a valid globally known certificate to make OS pass it slightly to installation and give a user good impression. Also to make sure was no viral code modification of file by MIM attack.

**Comment by G10h4ck** [comment]
Distributed packages are signed
