### ISSUE TITLE
RetroShare leaks file descriptors to child processes

### ISSUE THREAD

**Issue by AsamK** [RetroShare/RetroShare#51]
When RS executes another process, e.g. when opening a downloaded file, all open file descriptors, including sockets, are leaked to the child process.
I noticed this when I wanted to restart RS, but couldn't because the listening port was already in use by firefox. I had started firefox by opening a web link in RS and then the listening socket fd was leaked to the firefox process, where it remained open, even after RS was closed.

RS should set the FD_CLOEXEC flag on all file descriptors. It can be used like this:

```
fcntl(fd, F_SETFD, previous_flags | FD_CLOEXEC)
```

(Repost from the internal forum, so it won't get lost)

**Comment by chozabu** [comment]
:+1:

**Comment by AsamK** [comment]
@defnax where has this been fixed?
