### ISSUE TITLE
[Debian 8] Trying to install from repository fails, missing dependency

### ISSUE THREAD

**Issue by KALRONG** [RetroShare/RetroShare#511]
While trying to install from the repository apt shows the following error (sorry its in spanish):

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 retroshare06 : Depende: libmicrohttpd10 (>= 0.9.20) pero no es instalable
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

Checking in apt looks like libmicrohttpd10 is only avaliable for the mips arch and the rest are now using libmicrohttpd12.

**Comment by KALRONG** [comment]
Installing from the releases seems to work and not complain about dependencies.

**Comment by GATOQSECOMIO** [comment]
hola, tengo interés en este proyecto, donde existe alguna comunidad en español en la que pueda inscribirme actualmente en la que proveerme de contactos y alguna guía, gracias de antemano. disculpa que  responda por aquí.

**Comment by KALRONG** [comment]
GATOQSECOMIO solo puedo recomendarte que te pases a leer los post al respecto en mi blog
