### ISSUE TITLE
[Debian 8] Missing dependencies when compiling from source

### ISSUE THREAD

**Issue by KALRONG** [RetroShare/RetroShare#512]
The following dependencies listed on the documentation are no longer avaliable in Debian Stretch:

libqtmultimediakit1
qtmobility-dev

They have been replaced by QT5 versions and retroshare fails to compile with the new versions.

**Comment by csoler** [comment]
This needs to be updated. The correct dependencies on stretch are: 

libglib2.0-dev, libupnp-dev, libssl-dev, libxss-dev, libgnome-keyring-dev, libbz2-dev, libspeex-dev, libspeexdsp-dev, libxslt1-dev, cmake, libcurl4-openssl-dev, libopencv-dev, tcl8.6, libsqlcipher-dev, libmicrohttpd-dev, libavcodec-dev, qtmultimedia5-dev, qttools5-dev, libqt5x11extras5-dev, qt5-default

**Comment by KALRONG** [comment]
Thanks for the update, I think I installed those same ones but the compiling failed as its looking for the libraries in the qt4 folder.

**Comment by csoler** [comment]
you need to make sure you're using the right qt. Just do "make distclean" and then "qmake-qt5", or "qmake-qt4" according to which one you want to use.

**Comment by KALRONG** [comment]
oh ok, didn't know that, thanks a lot!

**Comment by bheesham** [comment]
Triage: is this issue resolved?
