### ISSUE TITLE
Implement save/load Chat History for Lobbies & Distant Chat

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#52]
What i see, there is missed yet saving/loading distant Chats or Chat lobbies Chat History.

you can check this classes if you want implement it:

libretroshare:
rsserver:
p3history.cc/.h
serialiser:
rshistoryitems.cc/.h
retroshare:
rshistory.h

retroshare-gui:
ChatPage.cpp/.h/.ui

**Comment by AsamK** [comment]
For chat lobbies the history is actually implemented, it is just not saved to disk. I made a PR for this some time ago: #21
For distant chat it's true, there's no implementation yet.

**Comment by csoler** [comment]
I don't see why it would not work for distant chat. A distant chat peer is just a virtual peer, so it shoul dbe seen as a peer by the history. That probably means that there's somewhere a check to disable it when the peer is not a real peer, probably at the same place than chat lobbies.

**Comment by defnax** [comment]
@AsamK  I has tested your PR, for Lobbies now working, need to be fixed for Distant Chat too.
