### ISSUE TITLE
Create a windows build with the new file database to not create a gap of users...

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#521]
Today the ubuntu build is being distributed making incompatible, ubuntu users with windows users in file lists exchange, that makes 2 networks, the ubuntu one and the windows one (mac too) like happend from 0.5 to 0.6 that made lot of people say goodbye to retroshare, or from a more stable build to ubuntu (0.6) and the unestable windows build that made people to not use rs because of lots of hangs in windows for months of not updated client...

I just suggest if hard changes are made, to free them at the same time windows/linux/mac if not the network breaks for months...

**Comment by csoler** [comment]
The Ubuntu stable release is the same version than the windows release. You're probably talking about the unstable ppa, which obviously contains latest developments and are not meant to be entirely compatible with the official released version.

**Comment by felisucoibi** [comment]
Sorry I thought was the stable ppa, I close it.
