### ISSUE TITLE
Add "Uninstall" section in README.md

### ISSUE THREAD

**Issue by Hopetech** [RetroShare/RetroShare#522]
I think that this is important information to communicate.

**Comment by bvbfan** [comment]
make uninstall ?

**Comment by andreybleme** [comment]
@Hopetech There is already a "uninstall" section on README.
It shows "make uninstall". Do you mean something different from it?

**Comment by Hopetech** [comment]
@andreybleme Since commit #526 we have an "uninstall section" (but only for linux).
