### ISSUE TITLE
Fedora libs path

### ISSUE THREAD

**Issue by FacundoAcevedo** [RetroShare/RetroShare#537]
Right now I'm compiling RS, I've found, after installing libsqlcipher, that 'make' on RS still doesn't work, so I read a little and find that in 'libretroshare/src/libretroshare.pro' doesn't point to the libs path, so here is what I've modified to do it work:

```
@@ -160,13 +160,14 @@ linux-* {
                DEFINES *= NO_SQLCIPHER
                PKGCONFIG *= sqlite3
        } else {
+               ;SQLCIPHER_OK = $$system(pkg-config --exists sqlcipher && echo yes)
                SQLCIPHER_OK = $$system(pkg-config --exists sqlcipher && echo yes)
                isEmpty(SQLCIPHER_OK) {
                        # We need a explicit path here, to force using the home version of sqlite3 that really encrypts the database.
-                       exists(../../../lib/sqlcipher/.libs/libsqlcipher.a) {
-                               LIBS += ../../../lib/sqlcipher/.libs/libsqlcipher.a
-                               DEPENDPATH += ../../../lib/
-                               INCLUDEPATH += ../../../lib/
+                       exists(/usr/local/lib/libsqlcipher.a) {
+                               LIBS += /usr/local/lib/libsqlcipher.a
+                               DEPENDPATH += ../../../usr/local/lib/
+                               INCLUDEPATH += ../../../usr/local/lib/
                        } else {
                                error("libsqlcipher is not installed and libsqlcipher.a not found. SQLCIPHER is necessary for encrypted database, to build with unencrypted database, run: qmake CONFIG+=NO_SQLCIPHER")
```

I'm sorry I do not know about this kind of make files, so i can't do a PR.

**Comment by sehraf** [comment]
Did you run `qmake` again after installing libsqlcipher?
What does `pkg-config --exists sqlcipher && echo yes` show on you system?

**Comment by FacundoAcevedo** [comment]
Yes, I've run qmake after installing libsqlcipher, but make didn't work.

`pkg-config --exists sqlcipher && echo yes`
Do not display anything, but:
`whereis libsqlcipher
=> libsqlcipher: /usr/local/lib/libsqlcipher.a /usr/local/lib/libsqlcipher.so /usr/local/lib/libsqlcipher.la
whereis sqlcipher
=> sqlcipher: /usr/local/bin/sqlcipher
`

**Comment by sehraf** [comment]
So the actual problem is that `pkg-config` is unable to find the lib for some reason

**Comment by csoler** [comment]
I suppose it's because it has been installed in /usr/local/lib, which is not expected.  Normally, when you "sudo apt-get libsqlcipher-dev" you get the files in /usr/lib. So is the pkg-config file:

> /usr/lib/x86_64-linux-gnu/pkgconfig/sqlcipher.pc
> Did you install it the normal way, or manually? What's your system?

**Comment by FacundoAcevedo** [comment]
I'm running this on Fedora 24 (64bits), I've manually installed libsqlcipher following the readme of RS, but I've run `make install` at last.

**Comment by sehraf** [comment]
Do you have this file `/usr/lib/pkgconfig/sqlcipher.pc`?
If not do you have this file `/usr/local/lib/pkgconfig/sqlcipher.pc`?
This file tells `pkg-config` where to find what. If you only have the latter file you try the fix mentioned at the end of this section https://people.freedesktop.org/~dbn/pkg-config-guide.html#using ( e.g. using  `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`) Then `pkg-config` should be able to find sqlcipher and you should be able to use the unmodified source code.

**Comment by FacundoAcevedo** [comment]
i have `/usr/local/lib/pkgconfig/sqlcipher.pc` 
After doing the export it works , thanks to all! :D
