### ISSUE TITLE
Create a beta version for windows, or a final version for windows and linux

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#553]
Windows users by now have to use final versions that are not upgraded so often, now there's a big change, file list sharing that windows users cant try or use, and its 95% of rs users, so I suggest to build a beta version for windows users or create a new final version, I really would like to help creating windows versions but i don't know how to do it with linux. 
Maybe a Beta for windows every month, only one. I was able to download from retroshare in the channel, and there they publish it every day. Theres also a script .bat to do it automatically, maybe use this script or offer it in the web if the author agree.
Bests

**Comment by cavebeat** [comment]
Hi,

Most users which i know, use:
Thunders Builds retroshare://channel?name=RetroShare%20Windows%20builds%20by%20Thunder&id=a06bc5e5d6d05acad52ab796e2d547cb

**Comment by felisucoibi** [comment]
Is better an official .exe, just for security.... I downloaded that version from the rs channel and is not working well on windows 7, btw... how can I add a rs link to the download queue? should be a way to do it...

**Comment by hunbernd** [comment]
File sharing --> Downloads
Right click on downloads list --> Paste RetroShare Link

There are 2 other channels that offer builds:
retroshare://channel?name=RetroShare builds by Sub&id=04d143f22eef5093c2a2a9d7c4477db8
retroshare://channel?name=RetroShare Windows x86_64 builds&id=701ac743586d18b438cf630c2506f3ab

**Comment by felisucoibi** [comment]
but this option is not on RS, at least is not in RS today build for linux- ubuntu. I'll check for it later on windows.

**Comment by hunbernd** [comment]
This option appears in the menu only if you have an RS file link in your clipboard

**Comment by felisucoibi** [comment]
thanks sorry for my ignorance :P

**Comment by felisucoibi** [comment]
I close it, I created my own builds for windows and linux and for me is enough to share them with my friends... but still should be nice to have a windows build somehow more often, if not people use other people builds and is not safe.
