### ISSUE TITLE
Please improve or remove Polish translation

### ISSUE THREAD

**Issue by aidecoe** [RetroShare/RetroShare#566]
Polish translation is really, really bad. It's better to not have it at all rather than having it in this state.

**Comment by dimqua** [comment]
You can fix it, if you wish: https://www.transifex.com/beluga/retroshare/language/pl/.

**Comment by cavebeat** [comment]
the link does fire a 403/only allowed for transifex members.

Polish  39% 2,477 strings to translate 
https://www.transifex.com/beluga/retroshare/

@aidecoe would be nice if you could contribute some strings to improve the polish translation.
