### ISSUE TITLE
Wiki Plugin

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#574]
Would it be possible to have a plugin that allows users of Retroshare to collaborate on a decentralized wiki? The means for syncing data is already in place, all that would be needed is the required UI and some form of conflict management algorithm and i think OT would be perfect for that purpose.

**Comment by defnax** [comment]
look here we has a wiki prototyp since few years but nobody to continoue on it:
https://github.com/RetroShare/RetroShare/issues/29

**Comment by csoler** [comment]
if you're a programmer, you're welcome to help. The work that is needed on this wiki plugin is mainly GUI work.

**Comment by trenkert** [comment]
Bump

**Comment by alfinal** [comment]
I think that this issue should be closed as duplicated of #29
