### ISSUE TITLE
ensure the robustness of the crypto layer, use tweetNaCl

### ISSUE THREAD

**Issue by ldnd** [RetroShare/RetroShare#576]
Complex crypto libraries are unreliable and hard to audit, see the vulnerabilities record of openssl.

If at all possible, a  switch to tweetNaCl in retroshare would be a remarkable improvement, as mentioned also in #443. Performance of tweetnacl is not an issue, when needed the same api is also available through nacl or sodium. It is important that the library is compact and auditable.

**Comment by G10h4ck** [comment]
Good suggestion, a merge request is welcome, in the meantime i close the issue
