### ISSUE TITLE
The 2 STEPS FIRST TIME user registration mockup proposal UPDATED 2017

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#588]
I did a php+html+javascript mockup here:
https://github.com/felisucoibi/RetroShareNewUserMockup
If you are css html designer you can help to make more visual and beautiful my proposal there.
Here screenshots.
STEP1
![step1](https://cloud.githubusercontent.com/assets/1285303/20787463/3132d188-b7ac-11e6-8fbb-0ac333f46cf6.png)
STEP2 UPDATED 2016 WITH AVATAR
![paso2](https://cloud.githubusercontent.com/assets/1285303/21588841/125907d4-d0eb-11e6-8c62-4516855a3f4f.png)
STEP3 REMOVED, now is the HOME screen:
https://github.com/RetroShare/RetroShare/issues/618

**Comment by leethax666** [comment]
I like this. It should be super easy to create a profile. Also, have them pick an avatar when they join.

**Comment by felisucoibi** [comment]
Nice idea the avatar, i'll update the mockup later.

**Comment by defnax** [comment]
yes Avatars are needed :) we dont want or support any Chat Servers for rs.
but you want code this idea? :)

**Comment by felisucoibi** [comment]
I updated step2 and step3 is removed for the new HOME wellcome section
https://github.com/RetroShare/RetroShare/issues/618

**Comment by defnax** [comment]
But you forget the real avatar, i dont mean gxs.
And maybe select Social net view or Toolbar view at last.

**Comment by felisucoibi** [comment]
My idea is that the first time, if you use the easy first time user "mode" the first gxid and the real avatar have same name, same photo, after that you can create as much new gxids you want. For the first time a user dont understand what is "real avatar" and gxid avatar. So before boring a first commer with all this let user to start using forums etc with his brand new identity that is the same as the real user (that btw is what is conmon, almost everybody uses the same user as gxid when begin with rs), if you are a experience user you can skip easy mode at beginning...

Don't understand the second sentence, please explain me.

**Comment by defnax** [comment]
Your Friend First time has no Avatar i mean select one and use maybe for gxs too then same.
Its boring when friends has no avatars.

**Comment by felisucoibi** [comment]
defnax i don't understand you, there is only 2 steps one for create the random data and the other to introduce user password and avatar, that's all in the second step you add the avatar, so the avatar will be after installing RS ready.

**Comment by felisucoibi** [comment]
Updated the first time user i close this bug:
https://github.com/RetroShare/RetroShare/issues/640
