### ISSUE TITLE
i2p incoming connections fail when the i2p router is not located at localhost

### ISSUE THREAD

**Issue by anon3000** [RetroShare/RetroShare#610]
Retroshare will not receive incoming connections from an i2p hidden service while the i2p router is located on a lan (not on localhost) and the hidden service is properly configured to direct traffic to the device Retroshare is running on.

In my setup, my i2p router is located at 192.168.1.115 (a headless server running Debian)
Retroshare is running on a computer located at 192.168.1.118 (a desktop running Windows 7)
My version of Retroshare is 0.6.1 on Windows.

On i2p, I've created a standard hidden service server tunnel which targets the host 192.168.1.118:[port].
On Retroshare, I have given the Hidden Service Configuration screen the port number and the b32 address associated with the server tunnel. The option to change the ip address from 127.0.0.1 is greyed out.

Testing this connection with a working outgoing i2p proxy results in a failure. If I check my i2p logs, I can see error messages associated with a failure of the hidden service to reach the server listening on 192.168.1.118:[port]. When I sniff my traffic in Windows, I can see this attempt to connect is being received in my desktop running Retroshare, but nothing comes to fruition from it.

An i2p router which runs on the same machine as Retroshare has complete and immediate success when it is set up with an identical server tunnel which points to 127.0.0.1:[port].

**Comment by sehraf** [comment]
RetroShare hidden nodes only accept connection from local host and not from any other lan address. There are many people complaining but nothing was changed yet. 

Am 24. Dezember 2016 02:55:07 MEZ, schrieb anon3000 <notifications@github.com>:
>Retroshare will not receive incoming connections from an i2p hidden
>service while the i2p router is located on a lan (not on localhost) and
>the hidden service is properly configured to direct traffic to the
>device Retroshare is running on.
>
>In my setup, my i2p router is located at 192.168.1.115 (a headless
>server running Debian)
>Retroshare is running on a computer located at 192.168.1.118 (a desktop
>running Windows 7)
>My version of Retroshare is 0.6.1 on Windows.
>
>On i2p, I've created a standard hidden service server tunnel which
>targets the host 192.168.1.118:[port].
>On Retroshare, I have given the Hidden Service Configuration screen the
>port number and the b32 address associated with the server tunnel. The
>option to change the ip address from 127.0.0.1 is greyed out.
>
>Testing this connection with a working outgoing i2p proxy results in a
>failure. If I check my i2p logs, I can see error messages associated
>with a failure of the hidden service to reach the server listening on
>192.168.1.118:[port]. When I sniff my traffic in Windows, I can see
>this attempt to connect is being received in my desktop running
>Retroshare, but nothing comes to fruition from it.
>
>An i2p router which runs on the same machine as Retroshare has complete
>and immediate success when it is set up with an identical server tunnel
>which points to 127.0.0.1:[port].
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RetroShare/RetroShare/issues/610

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by electron128** [comment]
RetroShare and I2P/Tor must run on the same node. Else an attacker on the same network can see that your are using RetroShare and he can see your ssl-id. Maybe this is ok for a private and trusted local network. But it is not ok if you use your computer in an untrusted public wifi network.

**Comment by anon3000** [comment]
I already run one i2p router 24/7 on my network. I have no interest in running a second router just for RS. I trust and have control over my local network, and do not find running RS and i2p on different machines on my network dangerous to my security.

It certainly is true that running RS and i2p/tor on different machines is dangerous if this is being done on an untrusted network. For everyone else, perhaps there should be a tooltip/warning when a user sets the i2p/tor hidden service to be anything other than localhost, so that they are informed of any potential danger of using Retroshare this way.
