### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/RetroShare#611]
Recently upgraded Debian Testing, now RS will not compile, lots of errors.

    openpgpsdk/openssl_crypto.c: In function ‘test_secret_key’:
    openpgpsdk/openssl_crypto.c:48:9: error: dereferencing pointer to incomplete type ‘RSA {aka struct   rsa_st}’
     test->n=BN_dup(skey->public_key.key.rsa.n);
         ^~
    openpgpsdk/openssl_crypto.c: In function ‘ops_dsa_verify’:
    openpgpsdk/openssl_crypto.c:395:9: error: dereferencing pointer to incomplete type ‘DSA_SIG {aka struct DSA_SIG_st}’
     osig->r=sig->r;
         ^~
    openpgpsdk/openssl_crypto.c:411:9: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
     odsa->p=dsa->p;
         ^~
    Makefile:685: recipe for target 'temp/linux/obj/openssl_crypto.o' failed
    make: *** [temp/linux/obj/openssl_crypto.o] Error 1  
    make: *** Waiting for unfinished jobs....

Not sure where the problem lies, seems to be related to crypto file sharing area which is being worked on

**Comment by defnax** [comment]
Please report these compiling isues on rs forums.
There you get more help.
