### ISSUE TITLE
Outgoing mail folder emptied after exit without sending mail

### ISSUE THREAD

**Issue by MMurzik** [RetroShare/RetroShare#613]
Steps to reproduce the bug:
1. Create an e-mail to *offline* friend node
2. Click "Send". Mail will go to the "outgoing" folder to has been sent later
3. Exit RetroShare. Them start RetroShare again.
4. Outgoing mail folder will be empty and no mail will be delivered to the recipients

**Comment by felisucoibi** [comment]
Ye this happens and should be fixed soon.

**Comment by Hxs2fJKjYZ** [comment]
How soon is soon?
Bug is still present.

**Comment by Hxs2fJKjYZ** [comment]
Bump

**Comment by G10h4ck** [comment]
Are you still able to reproduce this bug? Is it is the case reopen the issue please
