### ISSUE TITLE
My proposal for the first time user HOME UPDATED

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#618]
After following the 2 step user FIRST set up i proposed here:
https://github.com/RetroShare/RetroShare/issues/588
The user is ready to explore RS and this is the window Home ready to explore...
If they don't have any FRIEND or chatserver they will not see any option in RS:

![home](https://cloud.githubusercontent.com/assets/1285303/21679811/414f6d78-d346-11e6-8d35-22602564f1cc.png)

If they have at least a friend, they can start using RS.
![dsg](https://cloud.githubusercontent.com/assets/1285303/21582996/f60b30d0-d06c-11e6-86d5-e8890e21700d.png)

**Comment by dimqua** [comment]
I suggest to include links to [Telecomix](http://91.121.136.132/telecomix) and [PirateParty](http://retrochat.piratenpartei.at/) chatservers.

**Comment by hunbernd** [comment]
It is a bad idea to do not allow to the user to change network settings, before cert exchange.
* altering the port changes the cert
* maybe a tor/i2p proxy is needed to connect

**Comment by felisucoibi** [comment]
True hunbernd, i'll update the mockup to allow Options button.

**Comment by felisucoibi** [comment]
Updated the mockup with the options button also in the NON FRIENDS version of the home.

**Comment by felisucoibi** [comment]
I close this because is everithing in one post here https://github.com/RetroShare/RetroShare/issues/640
