### ISSUE TITLE
Tor,I2P Socks5 Proxied Retroshare Connections failing to connect to Hidden Nodes

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#619]
If the Regular Retroshare node operator is optionally using the Socks5 Proxied routed connection to a Retroshare Hidden Tor and/or I2P Node they do not connect to those Retroshare Hidden Node peers unless they bootup Tor and/or I2P 3-4 minutes PRIOR to their booting up the Regular Retroshare node.

If they mix that sequence up and bootup their tor, i2p routers later after booting up their Regular Retroshare node then Retroshare fails to connect to their Retroshare Hidden node peers no matter if 1hr or 1day elapses.

What appears to be happening is the Retroshare Regular node coding only tests to see if a remote Hidden node peer is online at bootup and only then successfully initiates a connection.

If the above sequence of booting up Regular Retroshare node and then 10 min or hours later booting up their Socks5 proxys, verifying tor,i2p are up and running via Options -- Hidden Services tab and then attempting to force a connection via Network -- peer connection -- connect, that fails as well.

When this out of explicit sequence of bootup application order occurs and the Regular Retroshare node operate then reboots Retroshare, Retroshare immediately connects to the Hidden nodes peers indicating this bug occurs because the application is only attempting to connect Socks5 proxy connections to a Retroshare Hidden node very early in the initial bootup sequence. When its not seeing any Socks5 proxy connections at bootup, the bug exists preventing those to be created later and immediately then used to initiate successful connections to their Retroshare Hidden nodes peers.

**Comment by G10h4ck** [comment]
Cannot reproduce

**Comment by sanyanet2** [comment]
Might be related: https://github.com/RetroShare/RetroShare/issues/170
