### ISSUE TITLE
Bug: Retroshare Regular nodes using the Tor Socks5 proxy leaks their IPv4 Address to Retroshare Hidden Server operators

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#631]
Bug: Retroshare Regular nodes using the Tor Socks5 proxy leaks their IPv4 Address to Retroshare Hidden Server operators

Time Length of Bug
Over 3 years

Retroshare regular nodes using the Socks5 Tor Proxy leaks their IPv4 address to Retroshare hidden nodes even though the users IPv4 address is not used to connect to the Retroshare Hidden Node which connect via the encrypted, encoded xyz.onion or xyz.i2p address only.

Snapshot
There is absolutely no need to leak the Retroshare regular nodes IPv4 address to Retroshare Hidden Node Operators, its a security weakness that has existed for over 3 years now and should be plugged now right away. Retroshare hidden nodes operating as tor hidden services do not accept UDP nor TCP connections, leaking the Retroshare Regular users IPv4 Address to a Retroshare tor and i2p hidden node operator is a unwanted, unneeded feature which presents a security leak. This also has caused confusion to quite a few Retroshare regular node users who mistakenly thought that their configuring Retroshare to connect via a Socks5 tor proxy their IPv4 Address wasn't fully visible and shown in their connection details to the remote Retroshare Hidden Node peer user.

**Comment by G10h4ck** [comment]
This is not a bug, if you are not an hidden node, your ip address is not a secret, if you want to hide it from a particular node remove discovery permission for that node in permission matrix
