### ISSUE TITLE
Newest Source Code Revision re-Hashes the same files thousands upon thousands of times

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#636]
retroshare0.6.1.20170109.2ed98302-gui-precise_amd64
Caught re-hashing the same files thousands upon thousands of times. This new bug caused a 1244ms lag in my platform system clock which I noticed when the tor guards began reporting back and changing to another tor circuit as a result of this rather nasty bug.

p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""  
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="ec6513a36e46fcc6cb124d43dee65401d01f696c"
  hash   ="ec6513a36e46fcc6cb124d43dee65401d01f696c"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
p3GxsReputation::cleanup() 
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="ec6513a36e46fcc6cb124d43dee65401d01f696c"
  hash   ="ec6513a36e46fcc6cb124d43dee65401d01f696c"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="505329b3e539bde8d6bc09cdc7d6c2ce02b427ec"
  hash   ="505329b3e539bde8d6bc09cdc7d6c2ce02b427ec"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="1bd91e90947b0c8e99e3ec44c4a51bfe3a9eadc7"
  hash   ="1bd91e90947b0c8e99e3ec44c4a51bfe3a9eadc7"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"

p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
p3IdService::getGroupData() Failed to decode ServiceString ""
 hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"
  hash   ="628cab6165335de8f6939754be5d4cd78d66c2b6"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c0a66a6885db8577fe50eba5e864aa9dbec2a52a"
  hash   ="c0a66a6885db8577fe50eba5e864aa9dbec2a52a"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="ff71adb5580aa5b3c7483c3c1027cc41214376c0"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="eb7e21a1523fde0d54109fd205c3e6aae4fb75da"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="4ac2e9f8184d7fe888b8f2ef56c049481fbac1b2"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c7a49e28cd3cb64d4433f9c10f339be77378b366"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="c02ff6f04b2e12524744f3a6dcf2250801398333"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="8c5a47f40a5ed6562955065129f293477bed12a1"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="ef958dfe43e40f6c25b78f2d72dab9875c0fefa2"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="cab91da2e9c1501582b0962244b7db007e6736d5"
  hash   ="a87500003abf38d4a28098b37f68c0db0ec66485"

**Comment by ASmith-** [comment]
This endless, constant hashing bug including the same files over and over again is not seen in retroshare0.6.1.20161231.97957bdc-precise_amd64.

I am however seeing quite a bit of activity regarding a time stamping key. Seems like a lot of activity to carry out this new feature. Is this new time stamping key feature now a endless loop or at some point it decides to not be a constant stream of what seems to be far more keys than I have on my keychange in total.

What would be the reason for time stamping more keys than I have on my entire keychange? I'm sure the 2,000 keys I have on my keyring have been superceded now by at least 5x that number in the cascade of time stamping key. This in retroshare0.6.1.20161231.97957bdc  Dec. 31st 2016 Commit 97957bdc on a Linux Ubuntu Precise amd64 system.

snippet out of many thousands:
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 8ed59f4fc07daa6f
(II) time stamping key 08930ea0d5998dcd8dc2faaed26d7c36 for the following reason: Used in signature checking: Chat lobby f1ee2c4d0982d13
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 6841392d6fe78a6f
(II) time stamping key 77ee977c996d403e1743064573b53a81 for the following reason: Used in signature checking: Chat lobby 6841392d6fe78a6f
(II) time stamping key 7fc3f8caa0d0504edbf68e3545509958 for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 614f37916d11b296
(II) time stamping key 7fc3f8caa0d0504edbf68e3545509958 for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key 06407af834ae886a558602a9d0c0be5a for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key 06407af834ae886a558602a9d0c0be5a for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 8ed59f4fc07daa6f
(II) time stamping key 08930ea0d5998dcd8dc2faaed26d7c36 for the following reason: Used in signature checking: Chat lobby f1ee2c4d0982d13
(II) time stamping key 77ee977c996d403e1743064573b53a81 for the following reason: Used in signature checking: Chat lobby 55c591a0d18dcee7
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 55c591a0d18dcee7
(II) time stamping key 77ee977c996d403e1743064573b53a81 for the following reason: Used in signature checking: Chat lobby 6841392d6fe78a6f
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 614f37916d11b296
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 6841392d6fe78a6f
(II) time stamping key 06407af834ae886a558602a9d0c0be5a for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key 06407af834ae886a558602a9d0c0be5a for the following reason: Used in signature checking: Chat lobby 8dc613aad10b8c2a
(II) time stamping key ed1399a25d661835f8630e59a97b666c for the following reason: Used in signature checking: Chat lobby 8dc613aa

**Comment by felisucoibi** [comment]
it's output of the new reputation system, should be comented but is not hasingh the same file it's hashing i think identities...

**Comment by felisucoibi** [comment]
with the latest commit this output is removed, the hash one.
