### ISSUE TITLE
Build broken with Qt < 4.7

### ISSUE THREAD

**Issue by AsamK** [RetroShare/RetroShare#64]
d9fd60ee added a place holder to retroshare-gui/src/gui/chat/CreateLobbyDialog.ui, which was only added in Qt 4.7. CentOS is still using Qt 4.6 so the build is broken there.
To fix this the placeholder should be removed to the .ui file and added manually in the .cpp file with a check for the qt version.

Exact error:
[  680s] g++ -c -m64 -pipe -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_REENTRANT -DRS_ENABLE_GXS -DRS_RELEASE_VERSION -DHAVE_XSS -DUBUNTU -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtUiTools -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtScript -I/usr/include -Iretroshare-gui -I../../libretroshare/src -I../../libresapi/src -Itemp/moc -Itemp/ui -o temp/linux-g++-64/obj/ChatLobbyWidget.o gui/ChatLobbyWidget.cpp
[  681s] In file included from gui/chat/CreateLobbyDialog.h:6,
[  681s]                  from gui/ChatLobbyWidget.cpp:8:
[  681s] temp/ui/ui_CreateLobbyDialog.h: In member function 'void Ui_CreateLobbyDialog::retranslateUi(QDialog*)':
[  681s] temp/ui/ui_CreateLobbyDialog.h:249: error: 'class QLineEdit' has no member named 'setPlaceholderText'

**Comment by csoler** [comment]
you can use #if QT_VERSION > .... to make sure this code is not compiled. We used this multiple times already. Look for instance in the cert creation dialog.
