### ISSUE TITLE
Debian compile problems

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/RetroShare#646]
Still having problems compiling according to directions given on Debian Testing latest updates and git into a clean never before used directory:

    gcc -c -m64 -pipe -g -fPIC -Wall -W -D_REENTRANT -DRS_ENABLE_GXS -DENABLE_WEBUI -DOPENSSL_NO_IDEA -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/retroshare06 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o temp/linux/obj/openssl_crypto.o openpgpsdk/openssl_crypto.c
    openpgpsdk/openssl_crypto.c: In function ‘test_secret_key’:
    openpgpsdk/openssl_crypto.c:48:9: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     test->n=BN_dup(skey->public_key.key.rsa.n);
         ^~
    openpgpsdk/openssl_crypto.c: In function ‘ops_dsa_verify’:
    openpgpsdk/openssl_crypto.c:395:9: error: dereferencing pointer to incomplete type ‘DSA_SIG {aka    struct DSA_SIG_st}’
     osig->r=sig->r;
         ^~
    openpgpsdk/openssl_crypto.c:411:9: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
     odsa->p=dsa->p;
         ^~
    Makefile.openpgpsdk:684: recipe for target 'temp/linux/obj/openssl_crypto.o' failed

**Comment by G10h4ck** [comment]
This should be already fixed in current master branch, feel free to reopen the issue if it's not the case
