### ISSUE TITLE
The need to add a configure for a Retroshare Hidden Nodes only build

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#663]
The need to add a configure for a Retroshare Hidden Nodes only build

I'm still needing a configure option to build Retroshare that can only produce a Hidden Service node to forward the consideration to include with the Tails devels and I2P devel teams. 

I asked for this 3 months ago and again today to see if there's been any effort in that direction. The inclusion of Retroshare with Tails would be a significant expansion of Retroshare users and Retroshare Hidden nodes.

There is a parallel development of the Tor Hidden Service Tails with I2P and neither have any included software apps that could be mistakenly used to give-up the users raw IPv4, hence the Regular Retroshare Node creation ability must be disabled entirely making it impossible for a Tails or I2P Inprevida user to mistakenly use that feature and get themselves seriously in jeopardy as a result.

**Comment by defnax** [comment]
we develope Retroshare for all, not for the experts!
If you want you can fork Retroshare and Decelope it for Tor/I2P only!
It not RetroShare's Main Goal!
