### ISSUE TITLE
not lounching using deb packages 0.6.1-1.20160831.53e26983.stretch_amd64

### ISSUE THREAD

**Issue by j0rgeSD** [RetroShare/RetroShare#666]
Using debian testing 
installing 
retroshare06-nogui_0.6.1-1.20160831.53e26983.stretch_amd64.deb
retroshare06-feedreader-plugin_0.6.1-1.20160831.53e26983.stretch_amd64.deb  .
retroshare06-voip-plugin_0.6.1-1.20160831.53e26983.stretch_amd64.deb
retroshare06_0.6.1-1.20160831.53e26983.stretch_amd64.deb

:$ dpkg -l |grep retroshare
ii  retroshare06                                                0.6.1-1.20160831.53e26983~stretch           amd64        Secure communication with friends
ii  retroshare06-feedreader-plugin                              0.6.1-1.20160831.53e26983~stretch           amd64        RetroShare FeedReader plugin
ii  retroshare06-voip-plugin                                    0.6.1-1.20160831.53e26983~stretch           amd64        RetroShare VOIP plugin

:$ RetroShare06
RetroShare:: Successfully installed the SIGPIPE Block
Cannot hash executable! Plugins will not be loaded correctly.
defaultBaseDirectory() = /home/XXXXXXXXXX/.retroshare
(WW) Error in PGPHandler::validateAndUpdateSignatures(). Validation failed for at least some signatures.
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read 6e trust packets.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
getAvailableAccounts() Skipping Invalid sized dir: extensions6
RsTryAutoLogin()
Using attribute: XXXXXXXXXXXXXXXXXXXXXXXXXXX
Got SSL passwd ******************** from gnome keyring
Autologin has succeeded
AuthGPG::GPGInit() called with own gpg id : D8002EB7A0BA837D
Invalid Certificate
AuthGPG::GPGInit finished.
PGP Auth Success! ID: XXXXXXXXXXXXXXXXXXXXXXX
let's store the ssl Password into a pgp ecrypted file
rsAccounts->PathKeyFile() : /home/XXXXXXX/.retroshare/LOC06_XXXXXXXXXXXXXXXXXXXXXXXXXX/keys/user_pk.pem
SSL Library Init!
SSL Verification Set
Inited SSL context: 
    Certificate: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    cipher list: kEDH+HIGH:!DSS:!aNULL:!3DES:!EXP
    PFS enabled: YES
RetroShare will AutoLogin next time
RsStoreAutoLogin()
Stored passwd ************************ into gnome keyring
Creating Init File: /home/XXXXXXXXXX/.retroshare/default_cert_06.txt
	Id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AuthSSLimpl::InitAuth already initialized.
set the debugging to crashMode.
Detected Old Crash File: /home/XXXXXXX/.retroshare/LOC06_XXXXXXXXXXXXXXXXXXXXXXXXXXXX/retro.log
Copying to: /home/XXXXXX/.retroshare/LOC06_XXXXXXXXXXXXXXXXXXXXX/retro.log-save
Logging redirected to /home/XXXXXXXXX/.retroshare/LOC06_XXXXXXXXXXXXX/retro.log
Switching To CrashLog Mode!
Checking For Directories
Load up Certificates, and Old Configuration (if present).
Load Configuration
setup classes / structures
Checking for DHT bootstrap file: /home/XXXXXXXXXXX/.retroshare/LOC06_XXXXXXXXXXXXXXXXXXXX/bdboot.txt
bdNode::setNodeDhtMode(768), origFlags: 0
bdNode::setNodeDhtMode() newFlags: 768
p3BitDht::setRelayMode(17)
bdNode::setNodeDhtMode(4096), origFlags: 768
bdSpace::clean_node_flags(524288)
bdNode::setNodeDhtMode() newFlags: 4864
Encrypted hash cache file present. Reading it.
Could not read one entry! Giving up.
RsPluginManager::loadList(): 
   Reference executable hash: 0000000000000000000000000000000000000000
   Accepted hash: 04cca04da3bcf5d743b96a7700e1649ee06fa383
   Accepted hash: 19d3d612ba88d941fa52ece57122bc35be8ce561
(II) Executable hash matches. Updating the list of accepted/rejected plugins.
Found plugin /usr/lib/retroshare/extensions6/libFeedReader.so
  Loading plugin...
  Loading plugin /usr/lib/retroshare/extensions6/libFeedReader.so
    -> hashing.
    -> hash = 19d3d612ba88d941fa52ece57122bc35be8ce561
    -> hash authorized. Loading plugin. 
    -> plugin revision number: 1407347075
       plugin API number     : 101
       retroshare svn  number: 1407347075
   -> Added function entry for symbol RETROSHARE_PLUGIN_provide
Found plugin /usr/lib/retroshare/extensions6/libVOIP.so
  Loading plugin...
  Loading plugin /usr/lib/retroshare/extensions6/libVOIP.so
    -> hashing.
    -> hash = 04cca04da3bcf5d743b96a7700e1649ee06fa383
    -> hash authorized. Loading plugin. 
    -> plugin revision number: 1407347075
       plugin API number     : 101
       retroshare svn  number: 1407347075
   -> Added function entry for symbol RETROSHARE_PLUGIN_provide
Examined a total of 2 plugins.
PluginManager: saving list.
  Saving current executable hash: 0000000000000000000000000000000000000000
  04cca04da3bcf5d743b96a7700e1649ee06fa383 : ACCEPTED
  19d3d612ba88d941fa52ece57122bc35be8ce561 : ACCEPTED
Segmentation fault

**Comment by ghost** [comment]
I also get a segfault on Void Linux (musl) simply using the VoIP options tab. RetroShare06 crashes if I attempt to scroll around inside that tab.

`Creating audioInputConfig object`
`Video Encoder: maximum frame rate is set to 30 Bps`
`AudioInputConfig:: starting video.`
`input device : `
`Segmentation fault`

**Comment by KALRONG** [comment]
Having the same seg fault, in my case this is the source of the segfault:

[ 4040.614608] RetroShare06[2294]: segfault at 12 ip 00007f342a6ea75d sp 00007ff                                                                                                                                                             c17b5fe70 error 4 in libcrypto.so.1.1[7f342a58d000+262000]

**Comment by KALRONG** [comment]
Looks like the problem in Debian is related to stretch using the new version of the libraries 1.1 instead of 1.0 and several functions have changed

**Comment by G10h4ck** [comment]
This should be already fixed in master branch, please reopen the issue if it's not the case
