### ISSUE TITLE
Misleading status of users in lobbies

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#67]
Currently, when joining a lobby, all users are displayed online and active. RetroShare starts marking users as AFK and changing their status icon from green to gray only 30 minutes later. This is highly misleading and annoying.

Suggested changes:
- revert the approach and show all users as AFK when joining a lobby
- let RetroShare mark an user as non-AFK and change his status icon to green as soon as he types something and the message appears in chat
- let users customize when RetroShare should mark users as AFK back by providing a setting in minutes (personally, I would like to see an user marked AFK if he did not type anything for more than one minute)

**Comment by csoler** [comment]
I agree, except for the 1 minute delay. It's far too low.

**Comment by SarcoRS** [comment]
And this is why I suggested to add a local setting, so each user could set a value that suits him. My idea is to consider somebody AFK or not strictly on end-user side, without the need to exchange any kind of keep-alive packets over the network, but strictly based on the last time when the end user has seen a chat message from that particular user reaching his RetroShare instance and getting displayed in lobby chat window.

**Comment by chozabu** [comment]
:+1:

**Comment by cavebeat** [comment]
merged and close
