### ISSUE TITLE
Build macOS Release on Cloud Service

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#670]
The [service](https://www.macincloud.com) allows you to rent time on a real, physical Mac with complete XTools etc. RetroShare will no longer need its own Mac to ship macOS binaries in a timely fashion.

**Comment by dimqua** [comment]
It costs money, but RS is non-commercial project.

**Comment by ghost** [comment]
So did the computers on which RS is developed, as well as the home internet connections used to upload it. All sorts of commercially purchased stuff goes into making RS.

Buying time on the cloud is a lot cheaper than a new mac and not limited to one owner. The login can be shared by the whole team. The pay-as-you-go plan means it only needs to be used for the length of a compile cycle.

RS needs to improve its macOS release methods. The macOS version should not continually be months to years behind Windows and Linux.

**Comment by ASmith-** [comment]
That's fine, its a option and an alternative that anyone interested in making Retroshare Mac builds can consider which is one more option than before the parent thread author left that information. Thank-you for your suggestion and posting that option nixitixin.

**Comment by ghost** [comment]
@ASmith- You're certainly welcome. The idea wasn't just anyone interested but the dev team. I would like to see Mac builds that any Mac owner can just download and install without doing his own build. RS already builds Mac binaries but does so on a severely delayed basis revolving around its lack of hardware access. The cloud service is a way around that problem.

**Comment by G10h4ck** [comment]
We are distributing retroshare dmg built with travisci, in addition we are trying to get retroshare into brew.sh https://github.com/Homebrew/homebrew-core/pull/40970#pullrequestreview-253925055
