### ISSUE TITLE
Retroshare.net seen as malware by avast...

### ISSUE THREAD

**Issue by TB54** [RetroShare/RetroShare#699]
Hello everyone,

Sorry, newbie here (and not a good english speaker...).
When you try to access the site **retroshare.net** or **retroshare.sourceforge.net**, it appears unavailable, and a malware alert appears in avast.
It still can be downloaded threw other websites (https://sourceforge.net/projects/retroshare/), but that malware alert is a really big problem to reassure friends who does'nt know retroshare...

Anyone knows what's hapenning ?

Have a nice day,
Tom

**Comment by TB54** [comment]
The problem is over since yesterday, but if someone knows what happened, I'm still interested (in case it happens again : I would like to be able to explain it to the friends whom I ask to use retroshare).

(To be honest, I feel a little like in a Kafka novel : the main site of your software is down for days, it's seen as a threat by computers... and nobody mention it, here or on the retroshare forums. Am I missing something ?).

**Comment by dimqua** [comment]
This domain name was previously available on [FreeDNS ](https://freedns.afraid.org/) service for free use. I think that's why it was blocked by Avast (and not by many others).

Can you check [this](http://ru.retroshare.es/), please?

**Comment by TB54** [comment]
Hello, and thank you !
Yes, your link is detected as a threat by avast.
