### ISSUE TITLE
21 day old through Present Builds all forcing users to reset their previous font type and size in each subscribed chatrooms

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#707]
21 day old through Present Builds all forcing users to reset their previous font type and size in each subscribed chatrooms

All the new builds 2 wks through latest, force users to reset their previous font type and size in each of their subscribed chatrooms. Retroshare users are being forced to reset to their user preferred Font types and sizes over again and again here with each new Retroshare build install. That's really randy isn't it? **Why is this continuously happening where users configuration changes keep being tossed out with each and every new Build and replaced by the unwanted default values?**

**Comment by csoler** [comment]
why? Well, because the trunk of the software is in heavy development. If you want a stable version, you might prefer to not update it at every commit.

**Comment by felisucoibi** [comment]
Agree with csoler.... don use beta if you don't want beta builds.

**Comment by ASmith-** [comment]
I recall the request by the Retroshare Developers to post and bring to their attention any new Retroshare Source code master branch merges and update created problems. 

I don't recall any heads-up mention that users configuration in Options and now renamed to Preferences would not be able to be saved.

**Comment by dimqua** [comment]
trunk is not even beta, it's alpha :-)
