### ISSUE TITLE
Removing somebody from friend list causes spam to be received

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#75]
If I remove somebody from friend list, his RetroShare instance starts notifying me about willing to become friends. I get friend request notices in event log. I get friend request messages in mail. Removing the friend request messages doesn't help - new ones just keep arriving.

I am going to take a wide guess about what's going on.

RetroShare is friend-to-friend by design. In order to befriend somebody, the key exchange has to be mutual. So there are two different situations here.
1. X and Y are not friends. X adds Y to friend list. Y keeps being noticed that he is in the friend list of X now.
2. X and Y are friends. Y removes X from his friend list. But he keeps belonging to the friend list of X.

These are two different situations with the same intermediary state.

My guess is that currently RetroShare can't make a difference between these situations and treats the similar intermediary state the same way.

Suggested change: when X and Y are friends and X removes Y from friend list - Y's RetroShare instance should get a notice and automatically remove X from its friend list as well.

**Comment by AsamK** [comment]
You're right, this is annoying. However I'm not really in favor of automatically modifying the friendlist.
How about adding an option to ignore certain pgp ids, i.e. not showing connection attempts from them. That would help in both cases you described. Ignoring peers that you removed from your friendlist and ignoring peers that added you but that you do not want to add yourself.

**Comment by SarcoRS** [comment]
Your suggestion will do as well and will do it even better. However, this is just one of many places where ignoring functionality needs to be added/improved, but let's keep this ontopic here indeed and just focus on PGP ids.

Bonus points if this ignore feature will come with built-in functionality of import/export the ignore lists, since it's pretty expected that friends may want to share their PGP id ignore lists. And please, let's have these ignore lists persistently saved into some readable plain text format.

**Comment by AsamK** [comment]
How about adding the import/export of ignore list to the import/export of friend list. If you want to share the ignore list with friends you just have to remove the friends from the export file.

I'm for storing the ignore list in the same (encrypted) file as the friendlist, if that's possible, don't know much about how RS stores it config.

**Comment by csoler** [comment]
That's going to be one more list to handle (put peers in, pull them out for some reason, etc), which in the end is going to annoy even more people. The feed item is designed to only show one instance of each friend connection attempt. I don't see how your news feed can be filled of these connection attempts. Besides, you can remove them using the appropriate checkbox in config->notify->feed

**Comment by chozabu** [comment]
I'm sure up for more lists:
- list of blocked PGPIDs
- list of blocked GXSIDs
- list of blocked GXSMessageIDs

But I don't think they need to be thought of as a list any more than the forums are thought of as a list.  
Rather than exporting to a file, I'd perfer to be able to offer to share them over the network ;)

**Comment by csoler** [comment]
If you start that way, I know exactly who is going to use a modified RS instance to create tons of GXS IDs that won't be in your list and spam everyone with them. That needs more than just a block list. The reputation system should be used. You might for instance have something like: allow distant messages/chat from everyone with reputation >= some value (that needs a proper GUI translation for non technical users). 

Reputation should be a local measure (user defined) that is also gathered from friends. This way it cannot be easily tweaked by strangers, but has a rather consistent value across the network (it's hard for you to reduce someone's reputation unless your friend do as well).

**Comment by csoler** [comment]
Then forums might have a built-in reputation threshold, which causes messages to be automatically blocked/hidden whenever your reputation gets bad enough, and re-transmitted when it gets high. That would work on old messages too.

**Comment by AsamK** [comment]
I'm looking forward to a working reputation system for gxs ids.

IMHO for pgp ids a ignore list would be useful. I generally want to see when people try to connect, so I can't disable connection attempt notification globally, but there maybe connection attemps by people that i don't want to add. They could be added to an ignore list, with a new button on the notification. To see which people are ignored, a third state could be added to the keyring (the list with all known pgp keys), that shows keys as friend/no friend/ignored.

**Comment by defnax** [comment]
> I'm sure up for more lists:
> 
> list of blocked PGPIDs
>     list of blocked GXSIDs
>     list of blocked GXSMessageIDs
> 
> But I don't think they need to be thought of as a list any more than the forums are thought of as a list.
> Rather than exporting to a file, I'd perfer to be able to offer to share them over the network ;)

@chozabu 
Yes that would be the best idea, thats more useful.

If PGP Id is blocked, dont allow connection attempt, dont notify me and more

I hope we get soon Blocked Friends List (PGP IDs) and Blocked People List (GXS IDs)
