### ISSUE TITLE
Add libsodium encryption to add Mesh Net connectivitys

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#753]
The Retroshare Project platform application is a perfect fit for global Mesh Nets. The current stumbling block is the overwhelming number of existing Mesh Nets use the libsodium encryption library for their wicked fast connections instead of the old openssl librarys. Another problem is the popular CJDNS libsodium implementation is a direct pipeline to the remote peers system which doesn't use relay servers to further dump content snoopers to obfuscate the locations of the peers.

The Solution

PipeSocks is a relatively new project which consists of a tiny library which drills right through State Sponsored censor firewalls, provides relay servers and creates a Socks5 proxy tunnel using the libsodium encryption library. https://github.com/pipesocks/pipesocks and offered under GPL v3.0 license https://github.com/pipesocks/pipesocks/blob/master/LICENSE

A PipeSocks addition to the Retroshare Hidden Node offerings would do more than open the viable avenue for the Retroshare project as a fully able Mesh Net application, that addition would also pave the way for wicked fast file transfers and video, audio streaming as well as VOIP sessions bandwidth speed which are nearly impossible on Tor,I2P multi-hop networks.

**Comment by G10h4ck** [comment]
Not a bug
