### ISSUE TITLE
[webpage and build system] Use https everywhere!

### ISSUE THREAD

**Issue by LGD-Fr** [RetroShare/RetroShare#755]
- http://retroshare.net/ should use https instead ;
- the OBS repo are not reliable: both the key and the packages are downloaded with http only !

For fedora, the [copr](https://copr.fedorainfracloud.org/) build system exists for instance.

Today, the most "reliable" way to download the program is to fetch the code with git and then to compile it, that's not very user-friendly.

"**secure** communications and file sharing with friends", as it's written! How is it possible to be taken seriously with these (simple) vulnerabilities? It's good to use GPG and TLS in the software, it's better when you use it to secure the download of the software, as far as I know.

**Comment by dimqua** [comment]
Builds are hosted on github, not on retroshare.net website.

>both the key and the packages are downloaded with http only

https://download.opensuse.org/repositories/home:/AsamK:/RetroShare/

**Comment by LGD-Fr** [comment]
I'm not dreaming @dimqua !

Go to http://retroshare.net/downloads.html !

![image](https://cloud.githubusercontent.com/assets/9968286/24076664/bfe0c8d4-0c36-11e7-8db1-bfcfe648e8f6.png)

![image](https://cloud.githubusercontent.com/assets/9968286/24076666/cbe69d5c-0c36-11e7-87b8-b8086cbee92f.png)

**Comment by LGD-Fr** [comment]
The doc of OBS is still using http :-(
![image](https://cloud.githubusercontent.com/assets/9968286/24076679/1c6b1fd2-0c37-11e7-9e77-32fdd3ada2a3.png)

**Comment by lucarabistouille** [comment]
And the repositories hosted on github are the same ones: https://download.opensuse.org/repositories/home:/AsamK:/RetroShare/Fedora_24/home:AsamK:RetroShare.repo

**Comment by Kcchouette** [comment]
As you now use all https on every website, I think this issue can be close @LGD-Fr @cavebeat
