### ISSUE TITLE
Add Optional Network Connection Selection to open up more VPN-CJDNS-Mesh Net Use

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#757]
Currently RetroShare06 simply borrows the system platform's network connection it is using system-wide automatically to connect with on RetroShare. This seriously curtails wider adoption and use of non-system wide network connections be it a select VPN, eth1, tun0 et al.

Adding a optional Network Connection drop-down menu for RetroShare users to select how they want RetroShare to connect would immediately open up far more areas for many RetroShare users to fully deploy and use those alternative network tunnels and connections.

[updated to include]
I should also mention many RetroShare users have repeatedly asked about easier ways to use RetroShare via a LAN (Local Area Network). The option I am suggesting to provide RetroShare users select the network connection for RetroShare to use would also instantly solve that. For example your LAN uses eth1 and your system platform uses eth0 for all your Internet connections, you'd simply select in your RetroShare Preferences -- network -- network connection eth1 and all RetroShare connections would then be via your LAN.

**Comment by ohhmm** [comment]
++ B.A.T.M.A.N. ++ as an option too

**Comment by G10h4ck** [comment]
This has already been answered in RetroShare forum

**Comment by ohhmm** [comment]
Couldn't you be so kind to put a link to the discussion in RetroShare forum that you mentioned, please, thank you much, appreciate, much obliged, etc.
