### ISSUE TITLE
Reword 'The DHT is OFF, so Retroshare cannot find your Friends' so its less confusing

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#761]
Reword 'The DHT is OFF, so Retroshare cannot find your Friends' so its less confusing

The RetroShare Connection Assistant pop-up presents the following to new and established RetroShare users:

The DHT is OFF, so Retroshare cannot find your Friends.

Retroshare has tried All Known Addresses, with no success
The DHT is needed if your friends have Dynamic IP Addresses.
Only Advanced Retroshare users should switch off the DHT.

The problem and issue that exists is that RetroShare uses DHT and also Discovery (together or separately) to locate a peer and connect to them. More and more established RetroShare users are turning off DHT and running their Network configuration at Private : Discovery Only

Thereafter any newly added RetroShare peer using the assistant connection pop-up is going to see a error message attempting to force a connection which goes through DHT and then tells them DHT is needed if your friends have Dynamic IP Addresses. 

I'm running the RetroShare Network configuration at Private: Discovery Only and have no problem connecting with a peer's dynamic IP address.

Retroshare Hidden Nodes do not offer nor use DHT at all. Tor doesn't normally support DHT/UDP and although I2P does, Retroshare doesn't appear to support DHT/UDP on I2P either. Nonetheless the Peer Connection Pop-Up attempts to connect to a known/unknown Peer using DHT which is Never Going to Work. So why have that pop-up falsely indicate its attempting to use DHT to connect to a Peer?

Solution:

If the Network Configuration is set at Private: Discovery Only, then disable the Connection Assistant pop-up screen. In the background, continue to search for and connect with peers newly added and established.

If a Retroshare is running as a Hidden Node, then disable the Connection Assistant pop-up screen.

Reword the wording on the Connection Assistant pop-up screen to:

Presently Unable to Connect with this Peer

RetroShare has attempted connections with All Known Addresses on this peer without success using the distributed hash-table network (DHT). Perhaps the peer has their Network configuration set to 'Private: Discovery Only' or they are offline.

**Comment by G10h4ck** [comment]
Next time please do a merge request it's easier than writing this long issue
