### ISSUE TITLE
Plugin Bug not letting me sign in! Fix ASAP!

### ISSUE THREAD

**Issue by theAkito** [RetroShare/RetroShare#764]
After a LOT of work on my Debian-based OS that was required due to missing QT modules, I finally successfully compiled and installed RetroShare06. But now when I try to login, it asks me twice, each for a separate and apparently unrecognized plugin, to be accepted or refected. I tried rejecting and accepting each, but the program always ends up in a Segmentation fault. Please fix this fast, I can't use RetroShare at all due to this problem.
Output when starting RetroShare06 in console:
Plugin directory : /home/name/.retroshare/extensions6/ does not exist.
Examined a total of 2 plugins.
PluginManager: saving list.
  Saving current executable hash: 0000000000000000000000000000000000000000
  8e117902689878f489d4774860645fbec0fda47b : ACCEPTED
  a5c0506ed0b232486c5f9768c10a8e673b7fb63b : ACCEPTED
Segmentation fault
The two ACCEPTED items are the two plugins that prompt me for verification each time I try to login.

[comment: reposted this from sourceforge.net , since the retroshare ticketing doesn't seem active there...]

**Comment by electron128** [comment]
> But now when I try to login, it asks me twice, each for a separate and apparently unrecognized plugin,
> to be accepted or refected. I tried rejecting and accepting each,
> but the program always ends up in a Segmentation fault.
How do you know it is a plugin problem, if it happens even when rejecting the plugins?

You can try to
- delete all plugins (or move them a another location)
- create a new profile

Can you provide a stacktrace from the crash?

**Comment by theAkito** [comment]
The problem is, that I did a fresh install of RetroShare06. I didn't install any plugins, nor did I change/add anything to the default installation, except when fixing the Qt5 dependency issues. This is the default installation.

> Can you provide a stacktrace from the crash?

What do you mean?

> create a new profile

I created 2 new profile after my old one didn't work. All had exactly the same issue.

> delete all plugins (or move them a another location)

I'm not even sure if the plugins are there in the first place.

**Comment by theAkito** [comment]
I don't know exactly why, but my log output changed (full version):
`RetroShare:: Successfully installed the SIGPIPE Block
Cannot hash executable! Plugins will not be loaded correctly.
defaultBaseDirectory() = /home/name/.retroshare
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read 2 trust packets.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: extensions6
getAvailableAccounts() Skipping Invalid sized dir: pgp

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3203:14: Not using units is deprecated. Assuming 'px'.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3203:14: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3208:8: Not using units is deprecated. Assuming 'px'.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3208:8: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4105:11: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4105:11: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4437:62: Using one color stop with linear-gradient() is deprecated.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4470:61: Using one color stop with linear-gradient() is deprecated.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4486:61: Using one color stop with linear-gradient() is deprecated.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4502:59: Using one color stop with linear-gradient() is deprecated.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4516:62: Using one color stop with linear-gradient() is deprecated.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4727:11: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4727:11: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5148:11: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5148:11: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: mate-applications.css:216:16: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: mate-applications.css:216:16: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: mate-applications.css:421:16: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: mate-applications.css:421:16: Expected a string.

(retroshare:6497): Gtk-WARNING **: Theme parsing error: other-applications.css:163:13: not a number

(retroshare:6497): Gtk-WARNING **: Theme parsing error: other-applications.css:163:13: Expected a string.
getAccountIds:
****
AuthGPG::GPGInit finished.
PGP Auth Success! ID: ***
opening sslPassphraseFile : /home/***sl_passphrase.pgp
pgp_pwd_callback() called.
Decrypting went ok !
rsAccounts->PathKeyFile() : /home/****/user_pk.pem
SSL Library Init!
SSL Verification Set
Inited SSL context: 
    Certificate: 0****
    cipher list: ****
    PFS enabled: YES
Creating Init File: /home/name/.retroshare/default_cert_06.txt
	Id: ****
AuthSSLimpl::InitAuth already initialized.
set the debugging to crashMode.
Detected Old Crash File: /home/name/.retroshare/****/retro.log
Copying to: /home/name/.retroshare/****/retro.log-save
Logging redirected to /home/name/.retroshare/L****/retro.log
Switching To CrashLog Mode!
Checking For Directories
Load up Certificates, and Old Configuration (if present).
Load Configuration
setup classes / structures
Checking for DHT bootstrap file: /home/name/.retroshare/****/bdboot.txt
(EE) Cannot load filter file /home/name/.retroshare/****/bdfilter.txt
bdNode::setNodeDhtMode(768), origFlags: 0
bdNode::setNodeDhtMode() newFlags: 768
p3BitDht::setRelayMode(17)
bdNode::setNodeDhtMode(4096), origFlags: 768
bdSpace::clean_node_flags(524288)
bdNode::setNodeDhtMode() newFlags: 4864
RsPluginManager::loadList(): 
   Reference executable hash: 58b96ca98885a0cb4362bde644170377c9a91c2d
(WW) Executable hashes do not match. Executable hash has changed. Discarding the list of accepted/rejected plugins.
Plugin directory : /usr/lib/retroshare/extensions6 does not exist.
Plugin directory : /home/name/.retroshare/extensions6/ does not exist.
Examined a total of 0 plugins.
PluginManager: saving list.
  Saving current executable hash: 0000000000000000000000000000000000000000
Segmentation fault`

**Comment by csoler** [comment]
It looks like you've got a much simpler problem: at start, RS hashes its own executable. Here, apparently, it cannot. That means it cannot read the file at all. It also normally creates the missign directories, and apparently this does not succeed either.

It seems to me that you have a unix right problem here. Something must be wrong in your install. Maybe you copied some files while being root, or anything that prevents RS to write in /home/yourname/.retroshare/

I agree that RS should not crash anyway, and warn you about the impossibility to write/access files. But fixing the ownership and write permission of directories on your side might help.

This is another clue that your hacked something badly:

opening sslPassphraseFile : /home/sl_passphrase.pgp

This file should be in /home/[yourloginname]/.retroshare/[your location ID]/keys

it should not be in /home, where RS cannot write anyway.

**Comment by DarbyCrash** [comment]
Hi. I have the same issue on Debian Stretch.
Saving current executable hash: 0000000000000000000000000000000000000000
Segmentation fault
Jun  1 18:34:28 debian kernel: [49331.273899] RetroShare06[28214]: segfault at 12 ip 00007f887d3c891f sp 00007ffed857fe60 error 4 in libcrypto.so.1.1[7f887d26a000+264000]
I've installed 0.6.1 deb package founded here.

**Comment by bodems** [comment]
I have the same issue, also on Debian Stretch, installed via the Repo:
(EE) Cannot load filter file /home/bodems/.retroshare/LOC06_a33b4055b8886601873bf45d6c3ec5fa/bdfilter.txt
bdNode::setNodeDhtMode(768), origFlags: 0
bdNode::setNodeDhtMode() newFlags: 768
p3BitDht::setRelayMode(17)
bdNode::setNodeDhtMode(4096), origFlags: 768
bdSpace::clean_node_flags(524288)
bdNode::setNodeDhtMode() newFlags: 4864
Plugin directory : /usr/lib/retroshare/extensions6 does not exist.
Plugin directory : /home/bodems/.retroshare/extensions6/ does not exist.
Examined a total of 0 plugins.
PluginManager: saving list.
  Saving current executable hash: 0000000000000000000000000000000000000000
Local changes in trust database. Writing to disk...
Done.
[1]    20254 segmentation fault (core dumped)  RetroShare06

**Comment by julien-nc** [comment]
The same thing is happening to me. I don't understand why this is happening with the version i compiled myself and not with the Ubuntu unstable release from the repository. For both cases, i use the same fresh new profile.
