### ISSUE TITLE
New Windows Retroshare user installs, runs RetroShare and adds peer without Qt installed !!!

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#765]
New Windows Retroshare user installs, runs RetroShare and adds peer without Qt installed !!!

Problem
A new Windows 10 Retroshare user installs, runs RetroShare and adds peer without Qt installed.
 A major dependance the Retroshare application didn't even check to see if it was installed! **That's like a WTF moment in locating that problem which I successfully did with some effort.**

Problem
I don't build the Windows packages but something is obviously very wrong or entirely missing in the built packages in this case the (newest) regular .exe install placed on a Windows 10 system for required dependencys prior to even allowing Retroshare to be installed.

Solution
Double check all Windows Retroshare builds and with Retroshare Windows builders to make certain Retroshare dependancys are checked by the Windows application installer prior to allowing it to be installed.

**Comment by G10h4ck** [comment]
Cannot reproduce
