### ISSUE TITLE
Security Risk with Web Interface enabled as a default

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#771]
Security Risk with Web Interface enabled as a default

Problem
I didn't notice for a full 2 weeks the Web Interface is enabled as a default, that's a security risk and should only be enabled as a option not as a default. I'm sure new Retroshare wouldn't even realize the Web Interface has been enabled and either discover it much later than a couple weeks or only if another Retroshare user mentioned it.

Solution
Make the Retroshare Web Interface a user option which is not enabled as a default.

**Comment by ASmith-** [comment]
Security Risk with Web Interface enabled as a default

I didn't notice for a full 2 weeks the Web Interface is enabled as a default, that's a security risk and should only be enabled as a option not as a default. I'm sure new Retroshare wouldn't even realize the Web Interface has been enabled and either discover it much later than a couple weeks or only if another Retroshare user mentioned it.

**Comment by felisucoibi** [comment]
Web interface is only accesible by localhost so no security problem in theory, maybe you found another way to acces web interface from other computer?

**Comment by G10h4ck** [comment]
Web interface is disabled by default
