### ISSUE TITLE
Update to last version of libmicrohttpd

### ISSUE THREAD

**Issue by albuic** [RetroShare/RetroShare#783]
Transition from libmicrohttpd10 to libmicrohttpd12 as install is not easily possible on Debian Stretch.
Maybe the code doesn't need any change but only the dependency should be changed.

**Comment by electron128** [comment]
Did you recompile with the new library?

**Comment by albuic** [comment]
I didn't try... I will try tomorrow and tell you if it works.

**Comment by sehraf** [comment]
Not sure what version libmicrohttpd10 / libmicrohttpd12 are but i can say for that RS works fine with the latest version of libmicrohttpd (0.9.53) on Archlinux. So no code changes are needed (unless there are some Debian specific changes)

**Comment by albuic** [comment]
I can confirm what @sehraf said : no need to change any code for libmicrohttpd (version 0.9.51 on my debian) but the debian package should authorized the updated dependency.
Moreover debian stretch does not have the package qtmobility-dev so I had to install libqt5x11extras5-dev to compile it.
So for me, the "install package dependencies" should be : 
```bash
sudo apt-get install libglib2.0-dev libupnp-dev qt4-dev-tools \
    libqt4-dev libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev \
    libqt4-opengl-dev libqtmultimediakit1 libqt5x11extras5-dev libsqlcipher-dev \
    libspeex-dev libspeexdsp-dev libxslt1-dev libcurl4-openssl-dev \
    libopencv-dev tcl8.5 libmicrohttpd-dev
```

**Comment by G10h4ck** [comment]
libresapi is now deprecated in favour of JSON API
