### ISSUE TITLE
"Makefile:557: recipe for target 'VOIPPlugin.o' failed" while compiling under Debian Jessie amd64

### ISSUE THREAD

**Issue by akintranslator** [RetroShare/RetroShare#794]
This is my first swing at creating an issue here, I hope I don't mess up.
I am trying to compile latest release (i.e. RetroShare-0.6.2.tar.gz) (and encountered the same problem from git repository too) under Debian Jessie amd64.
In other dependency issues, I was able to figure out what the problem might be.
But from this error I could not understand anything:
make command emits the following error:
"make[1]: Entering directory '/home/******/RetroShare-0.6.2/plugins'
cd VOIP/ && /usr/lib/x86_64-linux-gnu/qt4/bin/qmake /home/******/RetroShare-0.6.2/plugins/VOIP/VOIP.pro CONFIG+=debug -o Makefile
cd VOIP/ && make -f Makefile 
make[2]: Entering directory '/home/******/RetroShare-0.6.2/plugins/VOIP'
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/AudioInputConfig.ui -o ui_AudioInputConfig.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/AudioStats.ui -o ui_AudioStats.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/AudioWizard.ui -o ui_AudioWizard.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/VOIPToasterItem.ui -o ui_VOIPToasterItem.h
g++ -c -m64 -pipe -D__STDC_CONSTANT_MACROS -Wall -g -D_REENTRANT -Wall -W -fPIC -DQT_WEBKIT -DRS_ENABLE_GXS -DENABLE_WEBUI -DQT_PLUGIN -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I../../libretroshare/src -I../../retroshare-gui/src -I../../retroshare-gui/src/temp/ui -I/usr/include/opencv -I. -I. -o VOIPPlugin.o VOIPPlugin.cpp
In file included from VOIPPlugin.cpp:34:0:
gui/AudioInputConfig.h:33:23: fatal error: QAudioInput: No such file or directory
 #include <QAudioInput>
                       ^
compilation terminated.
Makefile:557: recipe for target 'VOIPPlugin.o' failed
make[2]: *** [VOIPPlugin.o] Error 1
make[2]: Leaving directory '/home/******/RetroShare-0.6.2/plugins/VOIP'
Makefile:40: recipe for target 'sub-VOIP-make_default' failed
make[1]: *** [sub-VOIP-make_default] Error 2
make[1]: Leaving directory '/home/******/RetroShare-0.6.2/plugins'
Makefile:180: recipe for target 'plugins-make_default' failed
make: *** [plugins-make_default] Error 2"

What should I do?

**Comment by electron128** [comment]
go to https://packages.debian.org
scroll down to "Search the content of packages"
insert "QAudioInput" (because the error message says: QAudioInput: No such file or directory)
you will find two packages:
https://packages.debian.org/search?searchon=contents&keywords=QAudioInput&mode=exactfilename&suite=stable&arch=any
qtmobility-dev 
qtmultimedia5-dev
It seems one package is for Qt 4 and the other for Qt 5.
Your error message contains lots of references to qt4, like "-I/usr/include/qt4/QtCore"
Because of this, install the qt4 package qtmobility-dev.

If the error persists, we may have a problem in the build config.
Your log says "-I/usr/include/qt4/QtMultimedia", but the Debian site lists the file "/usr/include/QtMultimediaKit/QAudioInput" for qtmobility-dev. The build config could be wrong.

**Comment by akintranslator** [comment]
@electron128 
Thank you for the reply. I am trying to figure out dependencies of the packages!... When and if I find a solution or hit a road block I shall post here!....

**Comment by jrabbit** [comment]
The default qmake is for qt4. qmake5 gets put in `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake` that got me pretty far then i had to install some missing qt5 deps. I can't login to master or v0.6.2 though...

**Comment by akintranslator** [comment]
Dear Friends,
Sorry while I am downloading and compiling retroshare image, I run out of disk space on my LVM based system and being a veteran noob threshed the file system trying to enlarge the partition where I run out of disk space.
That's why I had to reinstall entire system and lost many things.
Anyway I manage to find a working AppImage for debian 64 bit system:
https://github.com/RetroShare/RetroShare/issues/684
The actual AppImage is located at https://bintray.com/probono/AppImages/RetroShare06/0.6.1.glibc2.16#files
I hope this is useful to somebody!...
