### ISSUE TITLE
Retroshare Hidden Nodes can't possibly 'Use as a direct source when available'

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#810]
Retroshare Hidden Nodes can't possibly 'Use as a direct source when available' 

The Problem
The wording is a little confusing as to what is being requested when available.

The Solution
Change text to 'Use added friends for source when available'. 

This builds understanding towards a preference for downloaded file chunks coming from some friend/peer that you have added vs from an anonymous source via anonymous tunnels.

**Comment by csoler** [comment]
@ASmith- "Direct" means "one retroshare link". When using a Tor hidden node, this link goes over 3 hops of the Tor network as you say. There's no problem in having "direct" transfers over Tor.

**Comment by ASmith-** [comment]
Which was rather confusing due to two factors csoler

1) The wording used which I outlined in my edited post 9 days ago.

2) I had repeatedly spoken to you about a direct connection P2P need as a option for Retroshare users to enable them as fast as possible file transfers, you added this 'Use as a Direct Source connection if available' option which further added to the confusion on my part if you had actually added my suggestion (No) but instead had added something entirely different which perhaps at most might marginally help in speeding up a file transfer to a directly added friend if that option had been selected (enabled).

I still see the clear and present need for a direct connection P2P option for Retroshare to allow maximum file transfer speeds if that is what the peer choose to have with that selected manually added friend. The F2F network lapses whenever a directly added peer is in a rather remote for your network friends to reach. Resulting in severe restrictions on file transfer speeds among friends in that very scenero. I suspect in the midst of a highly congested network peer pairing that is not so readily apparent.
