### ISSUE TITLE
Feature request: add support for /me in chat lobbies and private chats

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#82]
Lots of chat programs can automatically convert `/me laughs` to `* SarcoRS laughs`.

RetroShare needs to be able to do this too. In both chat lobbies and private chats,

**Comment by cavebeat** [comment]
:+1:

**Comment by hunbernd** [comment]
https://github.com/RetroShare/RetroShare/pull/189

**Comment by electron128** [comment]
This feature was implemented by hunbernd and merged in #189. Thank you hunbernd.
