### ISSUE TITLE
Unable to compile nogui with introserver enabled Linux

### ISSUE THREAD

**Issue by MarkR84** [RetroShare/RetroShare#824]
Trying to create a "chatserver" and with "CONFIG += introserver" uncommented in "retroshare-nogui/src/retroshare-nogui.pro", nogui fails to compile.

"introserver.cc:67:23: error: ‘RsProfileConfigDirectory’ is not a member of ‘RsInit’" might be an issue and the compile ends with "make: *** [temp/linux-g++-64/obj/introserver.o] Error 1".

The system is Ubuntu 14.04.1 LTS

libbitdht, openpgpsdk, libretroshare, liblibresapi, and openpgpsdk compile seemingly fine.

The order:
sudo apt-get install libsqlcipher-dev libgpgme11-dev libgpg-error-dev libupnp-dev libssl-dev libgnome-keyring-dev libbz2-dev libqt5-dev g++ libxss-dev git qtmultimedia5-dev qttools5-dev libqt5x11extras5-dev libmicrohttpd-dev

git clone https://github.com/RetroShare/RetroShare.git
mv RetroShare retroshare
*uncomment "CONFIG += introserver" in "retroshare-nogui/src/retroshare-nogui.pro"*
cd ~/retroshare/libbitdht/src && qmake && make clean && make -j2
cd ~/retroshare/openpgpsdk/src && qmake && make clean && make -j2
cd ~/retroshare/libretroshare/src && qmake && make clean && make -j2
cd ~/retroshare/liblibresapi/src && qmake && make clean && make -j2
cd ~/retroshare/openpgpsdk/src && qmake && make clean && make -j2
cd ~/retroshare/retroshare-nogui/src && qmake && make clean && make -j2

Then the above errors.

**Comment by G10h4ck** [comment]
The introserver code is not actively maintained and should be removed as dead code if no one fix it, ATM i close this bug as there is no maintainer for that part of code

**Comment by IITFA** [comment]
This isn't resolved, thus this shouldn't be closed. It should remain open until someone begins maintaining the introserver code and fixes it. Closing this issue is simply sweeping the problem under the rug.
