### ISSUE TITLE
Feature request: make it easier to mail people from chat lobbies

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#83]
Currently the popup menu that gets displayed when right clicking on nicknames in chat lobbies has two items: `Mute participant` and `Start private chat`.

Suggestion: add a third item named `Send message` which will open the `New Message` window with GXSID of said user already filled. This will make it easier to message users since it will skip the tedious step of browsing the huge list of IDs in Messages window to select a destination.

**Comment by AsamK** [comment]
:+1:

**Comment by dimqua** [comment]
https://github.com/RetroShare/RetroShare/commit/2c1743f5bb5f71ef506a0a0aac0355eda7b24c37
