### ISSUE TITLE
Serious Retroshare Transport overhead-loss 100 KB/sec UL less than 7 KB/sec recieved

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#838]
500KB/sec UL speed max potential, a single remote peer is using 100 KB/sec Uploaded to them. LESS than 10 KB/sec is reaching the remote target peer. That's over 90% overhead-loss being consumed and not reaching the remote peer. That should be unacceptable by the developers here. Typical P2P transfers have LESS than 10% overhead loss, generally 5% or LESS. Over 90% overhead losses should be unacceptable by the Retroshare developers here.

I have complained about Retroshare's extreme overhead losses to distant peers from Retroshare 0.5 all the way through 0.6.2 now. When is this critical flaw going to be addressed and fixed here? 

Solution and a Path
A optional P2P mode would at least mitigate this critical routing flaw until a Retroshare developer attends to lowering a 90% overhead loss to remote peers down to 10% or less.

99.43 KB/sec Bandwidth Uploading -- 6.86 KB/sec Received at the Remote Peer
over 90% Overhead LOSS.
![retroshare06-uploaded-90kb-6kb-recieved](https://cloud.githubusercontent.com/assets/8520894/26436562/37b2b182-40cc-11e7-97fb-e8a31f266d15.png)

**Comment by csoler** [comment]
It's not overhead. Your RS node is most likely forwarding data along encrypted file transfer tunnels for other peers. The low FT rate that you see is most likely due to a lack of bandwidth somewhere along your own file transfer tunnels, not necessarily at your own place.

**Comment by ASmith-** [comment]
What you stated is possible but cannot be 100% discerned without a P2P option added to Retroshare which would allow a direct comparison to what is lost via the Retroshare global routing vs a direct P2P connection and weighing the bandwidth UL/DL losses from both cases.

Its very unusual to see anyone downloading a large 1+GB file and only have 10 KB/sec available in download bandwidth on their end to do that. I can give 500-1MB UL bandwidth to them so I suspect there is something wrong with Retroshare global routed relay network. Once data leaves my local system on Retroshare the data stream is routed via various Retroshare relay nodes and I suspect it is those nodes that are sucking the life out of Retroshare file sharing transfers. 

I see some overhead losses by the relays in the Tor Network and corresponding 20-30% lower target peers DL speed but never as much as what I suspect is happening on the Retroshare global routed network. Again, the option of a P2P direct connection would provide without little doubt what is possible and the difference between the two would be entirely measurable and evident. VOIP would likely function far better on a P2P option as well. There is a clear need for a P2P Option to be added to Retroshare.

**Comment by cavebeat** [comment]
i suggest to use http://www.bittorrent.org/introduction.html instead for comparison @ASmith- 

i vote for close
