### ISSUE TITLE
Why does not the site use https?

### ISSUE THREAD

**Issue by q158073378252010** [RetroShare/RetroShare#839]
Why does not the site use https?

**Comment by ASmith-** [comment]
Hi q, could you post the link site you are referring to please? Github has and uses https here. This is the link of your issue post https://github.com/RetroShare/RetroShare/issues/839
This page is encrypted using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 128 bit keys, TLS 1.2
Looks ok, reports as encrypted before it was transmitted over the internet indicating a end-end encrypted communication.

**Comment by zeners** [comment]
@ASmith- what's about http://retroshare.net/ ?

**Comment by q158073378252010** [comment]
@ASmith-  I am referring to http://retroshare.net/, why not use https.

**Comment by zeners** [comment]
@q158073378252010: i tried https://retroshare.net/ and it results in an untrustet certificate warning. Looks like the site is hosted and delivered from github, but presented under a non github domain. 

Unfortunately https://retroshare.github.io/ redirects to http://retroshare.net/, so https is lost in favor of a non-cert-warning user-experience.

**Comment by cavebeat** [comment]
hmm, 
looks like there is a free to use cloudflare option
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

i'll have a look at it soon. still it's not a perfect solution.

**Comment by nicopace** [comment]
It should be super simple to use https://letsencrypt.org/ ... and it is free

**Comment by cavebeat** [comment]
atm the site is hosted at github. github is not able to use letsencrypt for a CNAME record. that's the problem here @nicopace

**Comment by nicopace** [comment]
Oh... good to know, sorry then :(

**Comment by nicopace** [comment]
Hint: you can use http://surge.sh/ for your static site with SSL

**Comment by kdebiec** [comment]
@cavebeat Github Pages with custom domains gained support for HTTPS: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
