### ISSUE TITLE
Issue: Why does the Retroshare Global Router consume 1.1 MB/sec in the background?

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#851]
_This github issue is a re-post by Agurer from the Retroshare Bugs nested discussion because this long lasting problem and issue has remained on the Retroshare project for 3+ Years and continues to plague Retroshare Users encountering heavy abuse, leeching and use in the background by the Retroshare Global Router relaying 240+ tunnels/second sucking up all their bandwidth leaving the Retroshare user barely anything in the foreground for their own uploads and downloads._

Original Post in the Retroshare Bugs forum: Why Turtle-Router needs 1.1MB/sec? by Agurer
Why Turtle-Router needs 1.1MB/s?

Reply in the nested replies in the Retroshare Bugs forum by ASmith on this question, post.

**Finding and Observing a Retroshare Peer that is linked to very heavy transport relay tunnel requests via your node in the background.**

Right mouse-click on your Retroshare system-tray icon. Select Statistics -- Turtle Router. Expand the Statistics screen to full screen. 

   1) Look for 'Red' marked tunnel requests which are in my Statistics 240+ and greater requests per second.

   2) Look at the directly added peer with the highest tunnel requests and generally any with 'Red' marked tunnel requests that correspond to a line ----------------------> that peer name.

This shows you the activity list via your directly added friends. Those doing this or directly linked to this kind of activity show-up there with a great deal more activity than 95% of your other peers ( generally ).

This narrows 'WHO' is soaking up a great deal of your bandwidth in the background from a pile of directly added peers who are not engaged in what can look like abusive Retroshare use.

You can then send them a 'Mail' dialogue on your seeing this and asking them about dialling back their heavy use. You can also of course deny that peer connection to your node.

Sadly it does not appear the Retroshare Developers individual peer Max values have any effectiveness and ability in curbing an excessive leeching via a directly added peer by pushing 50-100 KB/sec Max values on them.

Also sadly there is no individual peer No Anon DL selection to cut-off that peers heavy leeching short of the now only option which is to 'Deny that peer) and remove them as a peer.

**Steps to Helping Retroshare Users with this on-going problem towards a solution**

**The Retroshare Developers Should make the Individual Max Peer Values function to help curb this on a heavy user or lecher.**

**The Retroshare Developers Should add a individual peer No Anon DL option to allow Retroshare users to immediately curb a heavy background abuse and leeching on Retroshare users which has gone on for well over 3 years here and will continue to do so until the Retroshare Developers add the coding and tools to allow Retroshare users to optionally deal with this on their end.**

**Comment by G10h4ck** [comment]
This is not a bug
