### ISSUE TITLE
Can't build android version with latest android studio and Qt-5.7

### ISSUE THREAD

**Issue by inferrna** [RetroShare/RetroShare#852]
Following instructions got:
```
The installed SDK tools version (25.3.0) does not include Gradle scripts. The minimum Qt version required for Gradle build to work is 5.9.0
Ошибка при сборке/установке проекта RetroShare (комплект: Android for armeabi-v7a (GCC 4.9, Qt 5.7.1 for Android armv73))
```
very similar issue here:
https://github.com/driftyco/ionic/issues/10604

**Comment by G10h4ck** [comment]
Take in account the minimum qt version required for retroshare android qml app is 5.7.1

Do you get the same error with my fork on the branch qmlapp_pex_alpha?
https://github.com/G10h4ck/RetroShare/tree/qmlapp_pex_alpha

**Comment by inferrna** [comment]
> Do you get the same error with my fork on the branch qmlapp_pex_alpha?

Yes. Possible solution is:
Android Studio -> Tools -> Android -> SDK Manager -> SDK Tools -> SHOW Package Details
then downgrade to the latest version that supports ant. So, I have got 5.9 version working with grade and not tried it.

**Comment by esutton** [comment]
@inferrna  What is latest version that supports ant?

I cannot figure out how to get my Android Qt 5.6.2 apps to build under Qt 5.9.1 ?

**Comment by G10h4ck** [comment]
I have compiled RetroShare android wtih Qt 5.9.2 without problems
