### ISSUE TITLE
Android build instructions need to be updated

### ISSUE THREAD

**Issue by inferrna** [RetroShare/RetroShare#858]
https://github.com/RetroShare/RetroShare/blob/master/README-Android.asciidoc
Line
```
sed -i "s|^NDK_TOOLCHAIN_PATH =.*|NDK_TOOLCHAIN_PATH = ${NDK_TOOLCHAIN_PATH}|" qmake.conf
```
is no more actual, since NDK_TOOLCHAIN_PATH now defined in mkspecs/common/android-base-head.conf and mkspecs/common/linux-android.conf files.

**Comment by G10h4ck** [comment]
Yes those build instructions are out of date, android development and documentation has continued in my fork in the branch qmlapp_pex_alpha, so this kind of thing will be fixed once I prepare a pull request and it get reviewed and merged

https://github.com/G10h4ck/RetroShare/tree/qmlapp_pex_alpha

**Comment by G10h4ck** [comment]
This will be addressed once https://github.com/RetroShare/RetroShare/pull/863 get merged

**Comment by G10h4ck** [comment]
This is solved in master branch ;)
