### ISSUE TITLE
RetroShare Crashing shortly after multiple strings of distant peer clock offset greater than 2 minutes shown

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#877]
RetroShare Crashing shortly after multiple strings of distant peer clock offset greater than 2 minutes notices shown. (the same distant peer ID string repeatedly shown over and over again)

I've repeatedly seen in the terminal output a string from a distant peer creating a series of clock offset's greater than 2 minute notices being displayed. This peer's ID string is not in my People list. 

The need for Retroshare users to accurately set and keep their system clocks synced with atomic clock servers has been repeatedly stated by users to the Retroshare developers, repeatedly asked about by new users and the problem this kind of behavior exhibits shows the developers have not mitigated this problem when a Retroshare user has a system clock time offset greater than 2 minutes continuously on the Retroshare network.

Solution
Add a very visible popup notice when the system clock time is found to be greater than 2 minutes on a poll of their peers.

Right now, a repeated series of notices is sent out in a debugging string whenever a distant peer posts a chat message or other networked time-stamped data stream whenever their system clock is 2 minutes or more ahead or behind your system clock. I automatically step my system clock to the nearest atomic clock server automatically 4x a day to keep mine at within 3 1/1000'ed of a second. 0.003 +/- seconds avg typical.

On any linux box and windows boxes with NTP installed, anyone can do this manually by issuing these three commands one at a time.

$ sudo service ntp stop
$ sudo ntpd -gq
$ sudo service ntp start

Composed into a simple bash file which the user copies into their text editor and saves into their home folder and changes the file property to 'executable' under filename settime.sh

#!/bin/bash
#settime.sh
#synch system clock using the National Time Protocal
#and regional atomic clock servers to adjust system time
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
echo "Adjusting System Clock using Stepped NTP Servers"

Thereafter all the user need do is either add this to a reboot and 2x a day automated cron tasks or open a terminal when they boot their system up and run settime.sh 
$ ./settime.sh

Telling distant peers who do not even have the partys faulty system clock notice ID string on their People database to track them back and some how take the time to tell them to straighten out their system clock and probably replace the battery that died and run NTP doesn't make sense nor help in any fashion mitigate this ongoing problem. The solution that is a step towards helping find and prevent this problem is by putting the 'Notice' on the users system up front in a popup window.

Include in the Retroshare documents early on the need to keep and maintain very accurate platform clock times synced with nearby atomic clock servers.

**Comment by PhenomRetroShare** [comment]
Hello, the crash don't come from these lines, isn't it?
I've test to switch my clock and nothing happens, else the message.
You can found a notification for each peers offset if you select it in notify settings (check Friend Connected).
