### ISSUE TITLE
Compile error while passing the qmake CONFIG+=libresapilocalserver configuration

### ISSUE THREAD

**Issue by topcat** [RetroShare/RetroShare#879]
The following error is seen in trying to compile code with the qmake CONFIG+=libresapilocalserver configuration option set. 

api/ApiServerLocal.cpp: In member function ‘void resource_api::ApiLocalConnectionHandler::handlePendingRequests()’:
api/ApiServerLocal.cpp:84:58: error: invalid use of incomplete type ‘class QStringList’

Solution:

Adding an #include QStringList  at the top of ApiServerLocal.cpp solves this.

Will try fixing this and sending a pull request.

**Comment by G10h4ck** [comment]
this has been fixed in https://github.com/RetroShare/RetroShare/pull/882
