### ISSUE TITLE
(Revision 812e6068) Core dump when changing Settings->Appearance->Style to gtk2

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#894]
Environment: Gnome-Shell 3.24.2 Arch Linux SMP 4.11.6 x86_64
journalctl:
Jun 22 12:38:23 dts systemd-coredump[20804]: Failed to get ACL: Operation not supported
Jun 22 12:38:24 dts systemd-coredump[20804]: Process 19481 (RetroShare06) of user 1000 dumped core.
                                             
                                             Stack trace of thread 19481:
                                             #0  0x00007fe6aef58b2c gdk_display_open (libgdk-x11-2.0.so.0)
                                             #1  0x00007fe6aef28732 gdk_display_open_default_libgtk_only (libgdk-x11-2.0.so.0)
                                             #2  0x00007fe6af2ed275 gtk_init (libgtk-x11-2.0.so.0)
                                             #3  0x00007fe6e819fd55 n/a (libqgtk2style.so)
                                             #4  0x00007fe6e81a146b n/a (libqgtk2style.so)
                                             #5  0x00007fe7564953a3 _ZN13QStyleFactory6createERK7QString (libQt5Widgets.so.5)
                                             #6  0x00007fe75642c686 _ZN12QApplication8setStyleERK7QString (libQt5Widgets.so.5)
                                             #7  0x00000000006d2cca _ZN6Rshare8setStyleE7QString (RetroShare06)
                                             #8  0x0000000000909522 _ZN14AppearancePage20updateInterfaceStyleEv (RetroShare06)
                                             #9  0x00007fe754c4a465 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                             #10 0x00007fe756518fc1 _ZN9QComboBox19currentIndexChangedEi (libQt5Widgets.so.5)
                                             #11 0x00007fe75651afd3 n/a (libQt5Widgets.so.5)
                                             #12 0x00007fe75651c4bc n/a (libQt5Widgets.so.5)
                                             #13 0x00007fe75651c651 n/a (libQt5Widgets.so.5)
                                             #14 0x00007fe756521fad n/a (libQt5Widgets.so.5)
                                             #15 0x00007fe754c4a465 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                             #16 0x00007fe756519659 n/a (libQt5Widgets.so.5)
                                             #17 0x00007fe754c1b87c _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5)
                                             #18 0x00007fe756427445 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #19 0x00007fe75642f24f _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #20 0x00007fe754c1bb98 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #21 0x00007fe75642e222 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb (libQt5Widgets.so.5)
                                             #22 0x00007fe756482615 n/a (libQt5Widgets.so.5)
                                             #23 0x00007fe756484f4a n/a (libQt5Widgets.so.5)
                                             #24 0x00007fe75642746c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #25 0x00007fe75642ecf4 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #26 0x00007fe754c1bb98 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #27 0x00007fe755749a93 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
                                             #28 0x00007fe75574b575 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                                             #29 0x00007fe755723c0b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                                             #30 0x00007fe74a3cf1b0 n/a (libQt5XcbQpa.so.5)
                                             #31 0x00007fe750a49a47 g_main_context_dispatch (libglib-2.0.so.0)
                                             #32 0x00007fe750a49c78 n/a (libglib-2.0.so.0)
                                             #33 0x00007fe750a49d0c g_main_context_iteration (libglib-2.0.so.0)
                                             #34 0x00007fe754c73e7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #35 0x00007fe754c1a21a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #36 0x00007fe754c22a74 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                             #37 0x000000000068e3ca main (RetroShare06)
                                             #38 0x00007fe753b4143a __libc_start_main (libc.so.6)
                                             #39 0x00000000006d12ea _start (RetroShare06)
                                             
                                             Stack trace of thread 20142:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x0000000000d86b47 _ZN6pqissl10moretoreadEj (RetroShare06)
                                             #2  0x0000000000d2d853 _ZN11pqistreamer9tick_recvEj (RetroShare06)
                                             #3  0x0000000000d2f826 _ZN17pqithreadstreamer9data_tickEv (RetroShare06)
                                             #4  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #5  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #6  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #7  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #8  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19584:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000ceb7d3 _ZN7AuthGPG9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19588:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe750a49bf9 n/a (libglib-2.0.so.0)
                                             #2  0x00007fe750a49f92 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007fe73f60b426 n/a (libgio-2.0.so.0)
                                             #4  0x00007fe750a70ac5 n/a (libglib-2.0.so.0)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19585:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe752e6e8e0 n/a (libxcb.so.1)
                                             #2  0x00007fe752e70679 xcb_wait_for_event (libxcb.so.1)
                                             #3  0x00007fe74a36cd49 n/a (libQt5XcbQpa.so.5)
                                             #4  0x00007fe754a40cbd n/a (libQt5Core.so.5)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19587:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe750a49bf9 n/a (libglib-2.0.so.0)
                                             #2  0x00007fe750a49d0c g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007fe750a49d51 n/a (libglib-2.0.so.0)
                                             #4  0x00007fe750a70ac5 n/a (libglib-2.0.so.0)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19923:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x00007fe710fb4b11 _ZN18p3FeedReaderThread9data_tickEv (libFeedReader.so)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19929:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x0000000000d990e5 _ZN8UdpLayer9recv_loopEv (RetroShare06)
                                             #2  0x0000000000d97abf bdthread_init (RetroShare06)
                                             #3  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #4  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 20139:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe750a49bf9 n/a (libglib-2.0.so.0)
                                             #2  0x00007fe750a49d0c g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007fe754c73e7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #4  0x00007fe754c1a21a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #5  0x00007fe754a3c40a _ZN7QThread4execEv (libQt5Core.so.5)
                                             #6  0x00007fe754a40cbd n/a (libQt5Core.so.5)
                                             #7  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #8  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19973:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000b70726 _ZN8p3I2pBob9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19976:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19593:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe750a49bf9 n/a (libglib-2.0.so.0)
                                             #2  0x00007fe750a49d0c g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007fe754c73e7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #4  0x00007fe754c1a21a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #5  0x00007fe754a3c40a _ZN7QThread4execEv (libQt5Core.so.5)
                                             #6  0x00007fe749c76d45 n/a (libQt5DBus.so.5)
                                             #7  0x00007fe754a40cbd n/a (libQt5Core.so.5)
                                             #8  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #9  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19978:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19983:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19985:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19979:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19990:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753bdc1fa sleep (libc.so.6)
                                             #2  0x0000000000d9b95f _ZN9UdpBitDht3runEv (RetroShare06)
                                             #3  0x0000000000d97abf bdthread_init (RetroShare06)
                                             #4  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #5  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19991:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000d33c26 _ZN8RsServer9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19980:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 20018:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x00007fe7572e2988 n/a (libmicrohttpd.so.12)
                                             #2  0x00007fe7572e2c9d n/a (libmicrohttpd.so.12)
                                             #3  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #4  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19981:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19982:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000c035ce _ZN15RsGxsNetService9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 20136:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe752a32ee1 n/a (libpulse.so.0)
                                             #2  0x00007fe752a246f1 pa_mainloop_poll (libpulse.so.0)
                                             #3  0x00007fe752a24d8e pa_mainloop_iterate (libpulse.so.0)
                                             #4  0x00007fe752a24e40 pa_mainloop_run (libpulse.so.0)
                                             #5  0x00007fe752a32e29 n/a (libpulse.so.0)
                                             #6  0x00007fe74f413fe8 n/a (libpulsecommon-10.0.so)
                                             #7  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #8  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19986:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753bdc1fa sleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19988:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000d6e348 _ZN12ftController9data_tickEv (RetroShare06)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19586:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe750a49bf9 n/a (libglib-2.0.so.0)
                                             #2  0x00007fe750a49d0c g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007fe73d57a55d n/a (libdconfsettings.so)
                                             #4  0x00007fe750a70ac5 n/a (libglib-2.0.so.0)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19922:
                                             #0  0x00007fe753c042bd poll (libc.so.6)
                                             #1  0x00007fe712e66d31 n/a (libusb-1.0.so.0)
                                             #2  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #3  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19924:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x00007fe710fb4b11 _ZN18p3FeedReaderThread9data_tickEv (libFeedReader.so)
                                             #3  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #4  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #5  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #6  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #7  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19930:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x0000000000d990e5 _ZN8UdpLayer9recv_loopEv (RetroShare06)
                                             #2  0x0000000000d97abf bdthread_init (RetroShare06)
                                             #3  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #4  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19974:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19975:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19987:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19989:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19984:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 19977:
                                             #0  0x00007fe753bdc2bd __nanosleep (libc.so.6)
                                             #1  0x00007fe753c06c54 usleep (libc.so.6)
                                             #2  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #3  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #4  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #5  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #6  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 20134:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x0000000000d86b47 _ZN6pqissl10moretoreadEj (RetroShare06)
                                             #2  0x0000000000d2d853 _ZN11pqistreamer9tick_recvEj (RetroShare06)
                                             #3  0x0000000000d2f826 _ZN17pqithreadstreamer9data_tickEv (RetroShare06)
                                             #4  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #5  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #6  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #7  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #8  0x00007fe753c0e25f __clone (libc.so.6)
                                             
                                             Stack trace of thread 20135:
                                             #0  0x00007fe753c063d3 __select (libc.so.6)
                                             #1  0x0000000000d86b47 _ZN6pqissl10moretoreadEj (RetroShare06)
                                             #2  0x0000000000d2d853 _ZN11pqistreamer9tick_recvEj (RetroShare06)
                                             #3  0x0000000000d2f826 _ZN17pqithreadstreamer9data_tickEv (RetroShare06)
                                             #4  0x0000000000bb8939 _ZN15RsTickingThread7runloopEv (RetroShare06)
                                             #5  0x0000000000bb8810 _ZN8RsThread2goEv (RetroShare06)
                                             #6  0x0000000000bb887e _ZN8RsThread13rsthread_initEPv (RetroShare06)
                                             #7  0x00007fe75477f297 start_thread (libpthread.so.0)
                                             #8  0x00007fe753c0e25f __clone (libc.so.6)

**Comment by dtschmitz** [comment]
![image](https://user-images.githubusercontent.com/33075/27511034-c904714e-58ea-11e7-9f62-56bed49995cc.png)

**Comment by BabushkaRetroShare** [comment]
I had a similar problem when I was running GNOME 3 (Wayland) and I guess you have the same problem. Try running `export GDK_BACKEND=x11` before running RS from the command line and see if that helps.

**Comment by dtschmitz** [comment]
@BabushkaRetroShare wrote:

> @I had a similar problem when I was running GNOME 3 (Wayland) and I guess you have the same problem. Try running export GDK_BACKEND=x11 before running RS from the command line and see if that helps.

From Xwayland it core dumps with the addition of this environment variable.
RS core dumps when I switch to X.org also.
I am recompiling with CONFIG+=debug and will run it through gdb.

Stay tuned.  Chopper 9 video footage at 11pm. ;)

**Comment by dtschmitz** [comment]
[core.zip](https://github.com/RetroShare/RetroShare/files/1100475/core.zip)
output of gdb stack trace (with where):

> (gdb) where
#0  0x00007f7f43eff670 in raise () from /usr/lib/libc.so.6
#1  0x00007f7f43f00d00 in abort () from /usr/lib/libc.so.6
#2  0x00007f7f45062807 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#3  0x00007f7f3abacf5d in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) ()
   from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f7f3abafe5a in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) ()
   from /usr/lib/libQt5XcbQpa.so.5
#5  0x00007f7f3ae732ab in ?? ()
   from /usr/lib/qt/plugins/platforms/libqxcb.so
#6  0x00007f7f45d68bdd in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) () from /usr/lib/libQt5Gui.so.5
#7  0x00007f7f45d79202 in QGuiApplicationPrivate::createPlatformIntegration() () from /usr/lib/libQt5Gui.so.5
#8  0x00007f7f45d79d2d in QGuiApplicationPrivate::createEventDispatcher() () from /usr/lib/libQt5Gui.so.5
#9  0x00007f7f45258855 in QCoreApplicationPrivate::init()
---Type <return> to continue, or q <return> to quit---

END

Reviewed error with @csoler : this is an upstream Qt error beyond RS developers control.
No corrective action taken.
Closing ticket.

**Comment by dtschmitz** [comment]
A Qt5 update was applied to my system today (qt5-styleplugins  5.0.0.1r36-2) which fixed this reported crash as just tested now. cc: @csoler
