### ISSUE TITLE
Need updating the Building guide, libqtmultimediakit1 and qtmobility-dev are no longer available.

### ISSUE THREAD

**Issue by myfingerhurt** [RetroShare/RetroShare#905]
Ubuntu 16.04 LTS
```
sudo apt-get install libglib2.0-dev libupnp-dev qt4-dev-tools \
    libqt4-dev libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev \
    libqt4-opengl-dev **libqtmultimediakit1** **qtmobility-dev** libsqlcipher-dev \
    libspeex-dev libspeexdsp-dev libxslt1-dev libcurl4-openssl-dev \
    libopencv-dev tcl8.5 libmicrohttpd-dev

E: Unable to locate package libqtmultimediakit1
E: Unable to locate package qtmobility-dev
```
-------------------------------------------------------------------------
I figured it out.

```
sudo apt-get install libglib2.0-dev libupnp-dev \
     libssl-dev libxss-dev libgnome-keyring-dev libbz2-dev \
     libsqlcipher-dev libspeex-dev libspeexdsp-dev libxslt1-dev \
     libcurl4-openssl-dev libopencv-dev tcl8.5 libmicrohttpd-dev \
     qttools5-dev libqt5x11extras5-dev qtchooser qt5-default

```
---------------------------------------------------------------------------
One more thing is incorrect

```
make retroshare-nogui  <- wrong
```
The whole procedure should be 

```
$ git clone --branch master --single-branch https://github.com/RetroShare/RetroShare.git 
$ cd ./Retroshare
$ qmake
$ make retroshare_nogui
$ make retroshare_nogui-clean
$ sudo make retroshare_nogui-install_subtargets
$ sudo retroshare-nogui  --webinterface 1025 --docroot /usr/share/retroshare/webui/ -U 20300047b887ab57bea564xxxxxxxxxxx
```

Install should have copied webui, if there is nothing in `/usr/share/retroshare/webui/` then build it first and install again 
```
~/RetroShare/libresapi/src/webui-src/make-src$ sh build.sh
$ sudo make retroshare_nogui-install_subtargets
```

**Comment by realityfabric** [comment]
Why is this closed when #1041 is literally the exact same thing, and the problem hasn't been resolved?

The README instructions for how to compile on Debian based systems still says to use ```libqtmultimediakit1``` and ```qtmobility-dev```, which can't be downloaded from any of the standard Ubuntu repositories (main, universe, restricted, and multiverse).

I was able to install the dependencies as listed by @myfingerhurt on Ubuntu 16.04. I haven't tested anything further.

**Comment by realityfabric** [comment]
The Compile Guide for GNU/Linux doesn't work from the Wiki, either. I went to the Wiki after I received errors when running make in the instructions from the README.

https://github.com/RetroShare/documentation/wiki/Compile

### Checkout the source code
```
mkdir ~/retroshare
cd ~/retroshare 
git clone https://github.com/RetroShare/RetroShare.git trunk
```
### Set Version Numbers
```
cd ~/retroshare/libretroshare/src
./version_detail.sh
cd ~/retroshare/retroshare-gui/src
./version_detail.sh
```

If you follow these instructions, ```~/retroshare/libretroshare``` doesn't exist. It would be ```~/retroshare/trunk/libretroshare```. And as of 3d2f33c757f8c46774b28b898786d75301af7933 there is no ```version_detail.sh``` in either folder indicated (```libretroshare/src/``` and ```retroshare-gui/src/```).

When following the README instructions, after running ```qmake CONFIG+=debug``` I receive this output:
```
Project MESSAGE: RetroShare version 0.6.4-889-g3d2f33c determined via git
Project MESSAGE: QMAKE: You have disabled deprecated warnings.
Project MESSAGE: QMAKE: You have disabled C preprocessor warnings.
```

Not sure if I should create a new issue for the bits about being unable to compile with make.

**Comment by stokito** [comment]
Guys, I also tried to build on Ubuntu 18.10 and it looks like missing:
    sudo apt install qt5-default
continue to build but please check your instructions, that first of impression about the project.

**Comment by ajeyaajeya** [comment]
This necessitates qt5 .
I am trying https://github.com/gnuradio/gr-inspector which needs qt4. How do I do it?

I have done
```
wget https://sourceforge.net/projects/qwt/files/qwt/6.1.0/qwt-6.1.0.zip
unzip qwt-6.1.0.zip
qmake qwt.pro
make

```
But fails
when I do make on the gr inspector build folder 

```
node1:~/gr-inspector/build> cmake ..
-- Build type not specified: defaulting to release.
CMake Deprecation Warning at CMakeLists.txt:56 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
--
-- Python checking for PyQt4
-- Python checking for PyQt4 - found
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Qt4 (missing: QT_QWTPLOT3D_INCLUDE_DIR QT_QWTPLOT3D_LIBRARY)
  (found suitable version "4.8.7", minimum required is "4.2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindQt4.cmake:1327 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:152 (find_package)


-- Configuring incomplete, errors occurred!
See also "/users/ajeya/gr-inspector/build/CMakeFiles/CMakeOutput.log".
See also "/users/ajeya/gr-inspector/build/CMakeFiles/CMakeError.log".
```
