### ISSUE TITLE
Crashes after 5-10 mins

### ISSUE THREAD

**Issue by dkiziridis** [RetroShare/RetroShare#914]
getRetroshareDataDirectory() found: /usr/share/RetroShare06
Getting variants for style: ":/qss/chat/compact/public"
getRetroshareDataDirectory() found: /usr/share/RetroShare06
getRetroshareDataDirectory() found: /usr/share/RetroShare06
Getting variants for style: ":/qss/chat/standard/private"
getRetroshareDataDirectory() found: /usr/share/RetroShare06
getRetroshareDataDirectory() found: /usr/share/RetroShare06
Getting variants for style: ":/qss/chat/standard/history"
getRetroshareDataDirectory() found: /usr/share/RetroShare06
(II) Checking incoming connection address: 79.129.231.16 => Accepted (i.e. whitelisted, or not blacklisted).
pqissllistenner::finaliseConnection() connected to IPv4=79.129.231.16:54960
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
[1]    16450 abort (core dumped)  RetroShare06

**Comment by ASmith-** [comment]
**To use gdb to catch RetroShare issues:**

**<< If Retroshare is not yet running >>**
0. In the folder where Rs executable is, open a terminal window, start gdb and follow this series of numbered steps

1. $ gdb
2. $ <gdb> set logging on gdb-20160804.txt
3. $ <gdb> handle SIGPIPE ignore nopass nostop noprint
4. $ <gdb> exec-file ./RetroShare06 ( or whatever your Retroshare Gui executable filename is )
5. $ <gdb> run
When Retroshare hangs/locksup or crashes then enter Control-C
6. <gdb> thread apply all bt full
Continue using the Enter Key to extract all the stack information into the gdb.txt log file
When you have extracted all the stack information you can then list the top 10 backtrace threads if you optionally want.
6a. <gdb> thread apply all bt full 10

7. <gdb> quit

**<< If RetroShare is already running but locked/crashed >>**
Open a terminal window and locate the process number (PID) for Retroshare06 by $ top or by $ ps -eaf | grep -i retroshare06

1. launch gdb $ gdb
2. $ <gdb> set logging on gdb.txt
attach gdb to the discovered RetroShare PID 
3. $ <gdb> attach PID
4. $ <gdb> thread apply all bt full
Continue using the Enter Key to extract all the stack information into the gdb.txt log file
5. $ <gdb> quit

Now read/investigate/report gdb.txt ( the log file generated )

Save this as a text file to a Retroshare shared folder and paste the link to it in the Retroshare Devels signed forum and chat lobby so the Retroshare developers can look it over.

**Remember the Retroshare binary you are using the gdb debug testing utility on (RetroShare06 Gui or Nogui) must be a debug enabled Retroshare build. Add the following qmake command to set that in motion prior to your make command to compile the source code.**

qmake CONFIG+=debug

**Comment by G10h4ck** [comment]
are you still able to reproduce this bug? If so reopen the issue please
