### ISSUE TITLE
Editing old,old Channel Posts pushes those to the top

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#919]
**Editing old,old Channel Posts pushes those to the top**

Lacking a years long need, request and multiple suggestions for a Channel owners ability to delete old Channel posts to enable faster loading of the most current Retroshare Channel items and files, the developers added a 'edit' feature.

**Gutting outdated Channel posts using the edit tool in aleu of a proper deletion command results in a gutted Channel post being placed at the top of the Channel.**

Busy Channels with lots of attached files slowly drag down the loading of the Channel over time as more and more old and outdated Channel posts add to the loading time to finish until practicality is exceeded and existing subscribers have to chose between a long wait period to even preview the newest items or unsubscribe from that Channel. New potential subscribers are also turned off to a long loading time on busy existing channels containing many Channel Posts with attached files and just as likely to quickly unsubscribe early on.

The same phenomena has been seen and worked on decades ago on the clearnet websites where site owners and operators saw a drastic drop in visitors as their page load times increased due to heavy content being loaded in before that visitor could do anything on that website.

If the developers cannot add a proper delete function for the Channel owners to use and trim their old outdated Channel posts to speed up Retroshare loading times, then work on edited Channel posts older than 30 days from the present not being date stamped with the current date and bounced on top allowing Channel Owners to edit out the attached files and comments from those old outdated Channel posts directly leading to much faster Retroshare Channel loading and functionality for its users.

**Comment by felisucoibi** [comment]
I just wanna say... I like how it's now, when edit go up so people knows something changed....

**Comment by ASmith-** [comment]
Without a delete function then all a channel administrator/creator/owner can do is edit out old, outdated channel posts using the editing tool which then pushes those empty shells to the top. That is not helpful to 95% who aren't going to juggle 10 channel posts and constantly use the editing function to gut the oldest one and recycle it to the top as a endless e-cycle scheme.

The vast majority of existing channel owners have 100's of outdated channel posts which all drag down the loading on subscribed channels until they choke out on the subscribers giving up because each additional channel post and files slows down the loading before they can browse, download or use that channel. They cannot simply gut out those 100 because that would leave a wasteland at the top and channel subscribers would leave, leaving them in a chat 22 situation. **The solution is to add a delete function and encourage channel owners/creators/administrators to trim out old outdated channel posts to keep their channels from suffering ever longer lag times in loading in all of the data base fields, files and items that are stored.**
