### ISSUE TITLE
../ChatServer README.md Documentation for install is invalid

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#921]
cc: @csoler @cavebeat @sehraf 

The Chatserver README.md install directions need to be updated.
When following this step:

`Chatserver changes in libretroshare /build/retroshare/libretroshare/src/pqip3peermgr.cc in p3peermgr.cc replace setServicePermissionFlags(gpg_id,service_flags) with setServicePermissionFlags(gpg_id,RS_SERVICE_PERM_NONE)`

gcc errors out.

const RS_SERVICE_PERM_NONE is not found using grep anywhere in the RS projects.

Please review and advise.

**Comment by cavebeat** [comment]
wrong repository

**Comment by dtschmitz** [comment]
[Screenshot from 2017-07-04 17-24-59.zip](https://github.com/RetroShare/RetroShare/files/1123090/Screenshot.from.2017-07-04.17-24-59.zip)
Per your request (in the RS Dev chat lobby, here is confirmation that you are the owner of RS and Chatserver (above screenshot image shows ownership)

**Comment by cavebeat** [comment]
This is not a valid point as i am _technically_ the owner of all RetroShare/* and cavebeat/* repositories. Which means i care about permissions and create repositories. I am not pushing directly to the core project for example, though i could. So to speak i am _root_ in this Organisation. I am not owning anything here, nor i am named (or name myself) as the lead dev or maintainer or founder. I am not accountable for your accusations for not maintaining or being lazy for keeping the chatserver up-to-date. 
This, especially the chatserver itself, is a community driven project and needs community contribution. 

Feel free to re-create the issue in the chatserver repository. This here is the wrong place for this discussion. The issue section has not been necessary until now and has been opened just for you. The chatserver is small enough to communicate directly the issue.

Feel free to fork and contribute code (do it yourself or search for a coder which can do it or will do it for money) or put a bounty on it to motivate anyone interrested to solve the issue. 

I am interrested in having a working retroshare chatserver codebase, and will gladly welcome any upstream patches and be thankful for that.

If you still think you need to continue with your behaviourial patterns (blaming, commanding, insulting, trolling, accusing. ...) i consider this as hostile and abusive and will be obliged to take action against it.
