### ISSUE TITLE
Can't register for Retroshare forum

### ISSUE THREAD

**Issue by WombatPete** [RetroShare/RetroShare#932]
There's simply no place to do it and every attempt to contact someone about this has failed to produce a response.

Help?

Thanks in advance...

**Comment by cavebeat** [comment]
hi, 
which forum? 

Have you tried like described here:? https://retroshare.readthedocs.io/en/latest/user-guide/interface/#create-forums

best regards cave

**Comment by WombatPete** [comment]
Hello!
Actually, I meant http://retroshare.sourceforge.net/forum/index.php

**Comment by cavebeat** [comment]
@hmm, 
i see, the registration is disabled... i'll check if it is an issue from sourceforge or it got disabled by accident. 
anyway, the issues on github are more active than the forum on SF. 
and the internal forums are the place where the real discussions take place. so there is no big loss in not using the Forum for you.

**Comment by WombatPete** [comment]
Yes, I was just told (by csoler) that the sourceforge forum doesn't work anymore, that I need to THIS one has replaced it.

**Comment by WombatPete** [comment]
I'll read your link to reach the internal forums. I've come to this as a skype-replacement-plus, so I need to understand how to get to them, how to figure out who to link to when it's not my actual circle of actual IRL friends.

**Comment by cavebeat** [comment]
uhh, 
so the question related to sourceforge is "solved". the forum is just for history (and users with a working id). anyway, it's mostly unused. and laggy (sourceforge)

so questioning in the issues is an option. 
better is to have connectivity to a few people with access to RS-Forums. 

>You see forums your friends are subscribed to, and you forward subscribed forums to your friends. This automatically promotes interresting forums in the network. Forum messages get deleted after 12 months. 

so important is to have connectivity to at least someone. 

may i close the issue? feel free to reopen for a new question with a new title.

**Comment by WombatPete** [comment]
Yes, absolutely. I'll look around and figure out how to find someone with access to RS Forums. Not sure how you do that with a stranger why would they be on broadcasts, etc.? But obviously there's an answer to that, because it works - part of the learning curve. Yes, you can close this; the VOIP issue is the main one now. Thank you!

**Comment by cavebeat** [comment]
the bootstrapping is the hardest part here. usually there should be some chatservers at https://retroshare.rocks, but unfortunately they are offline at the moment. 

connecting strangers is not the best idea, though it helps to see how RetroShare works. And it actually works well (despite your VOIP bug). maybe you want to come the the IRC channel #retroshare at Freenode. so we can discuss directly your options.

**Comment by WombatPete** [comment]
Don't know whether you'll see this in a closed topic, but I did go to the retroshare channel at freenode.
I've been going there, going into webchat and entering the room under various names. 
Not sure I'm doing that properly, either, as the only activity I've seen are people (silently) entering the room and (silently) leaving it.

**Comment by cavebeat** [comment]
i see it, 
i am online at IRC now, how about you?
