### ISSUE TITLE
HTTPS for Website

### ISSUE THREAD

**Issue by Simted** [RetroShare/RetroShare#935]
Noticed that http://retroshare.net/ is lacking HTTPS.

Is it possible for this to be sorted?

**Comment by cavebeat** [comment]
duplicate of https://github.com/RetroShare/RetroShare/issues/839

TL;DR the homepage is hosted at GitHub-Pages, which are HTTP only.

**Comment by alfinal** [comment]
@cavebeat I think you forgot close it as duplicated.
