### ISSUE TITLE
where can i download the android app apk

### ISSUE THREAD

**Issue by treaki** [RetroShare/RetroShare#940]
judging your repository there is an android app. But i can't find anywhere a apk download to install it. Not at https://github.com/RetroShare/RetroShare/releases not at http://retroshare.net/

so where can i download your app??

thanks in advance

**Comment by felisucoibi** [comment]
It's inside the retroshare network in a channel, still is beta, do you use rs in desktop?

**Comment by WombatPete** [comment]
I  do. Which channel? How well/poorly does it work?

**Comment by felisucoibi** [comment]
IT WORKS VERY BAD BY NOW I HOPE IN NEXT MONTHS THIS WORKS WELL

**Comment by WombatPete** [comment]
Thank you for that. I looking forward to it working well!

**Comment by G10h4ck** [comment]
retroshare://channel?name=RetroShare%20Android%20builds%20by%20G10h4ck&id=e78125439fff723b3b15bb77b8f25dba
