### ISSUE TITLE
Retroshare-nogui RAM usage does not stop growing

### ISSUE THREAD

**Issue by julien-nc** [RetroShare/RetroShare#956]
I use retroshare-nogui on debian jessie installed from deb repository "retroshare06-git" package. It always entirely fills the RAM after a few hours and gets killed by the system. Configuration is close to the default one (except file shares). For example, it takes between 6 and 10 hours to fill 4GB of RAM. This problem makes it impossible for me to run my RS instance permanently.

I compiled retroshare-nogui from repository commit d60bb781b87217a6eba01360cdaeffa77276d005 with debug flag and performed a massif heap profiling during 4 hours : 
[massif.out.341.txt](https://github.com/RetroShare/RetroShare/files/1165451/massif.out.341.txt)
With massif-visualizer, i can see that two allocation spots are representing almost 80% of RAM occupation.

* ```RsGxsMsgMetaData* meta``` in RsGenExchange::processRecvdMessages
* ```this->bin_data``` in RsTlvBinaryData::setBinData

I didn't go further with memcheck to see if those allocations were involved in memory leaks. I didn't check if graphical Retroshare RAM usage always grows as well.

Do you think some free/delete are missing somewhere ? Is it possible this problem is caused by something else ?

I can perform a detailed memcheck if needed.

Thanks for developing RS, it rocks !

**Comment by csoler** [comment]
thx a lot for your post. It provides exactly the info I need to fix these bugs (I use massif-vizualizer on your file). It seems that there is a memory leak indeed, but I didn't know that it was so serious!

**Comment by dtschmitz** [comment]
Great analysis @eneiluj :)

**Comment by julien-nc** [comment]
@csoler Wow, quick reaction ! Glad to help.

@dtschmitz Thanks.

I first thought i had done something wrong (config or user action) that could lead to this huge memory usage.

Does it seem easy to fix ? I guess it is quite complex to identify where/when those allocations should be freed.

**Comment by csoler** [comment]
Well, yeah, it's not easy to figure out at all. The data is passed to services who need to delete them. If you want to try to find it, you're very welcome. But it's a real challenge. I won't take a look at it before tonight. If you find anything, I'll catch up when I come back.

**Comment by csoler** [comment]
I just committed a possible fix, but I'm not 100% sure about it. Can you please re-test ? (I do not manage to reproduce this bug, and it seems that it is due to the mPendingValidate list not being cleared fast enough. Are you sync-ing a lot of forums/channels which would explain that the validate list is still filled when the next sync round is performed ?)

**Comment by julien-nc** [comment]
I recompiled and launched a new massif analysis. I'll get the results tomorrow morning and let you know.

I think i'm not syncing a lot of forums/channels. I'm sharing a certificate/identity on two machines, one with RS-gui which subscribed to 10 forums and the other with RS-nogui. Maybe the forums are updated on the RS-nogui node but i didn't explicitly asked it to do so.

**Comment by julien-nc** [comment]
Warning, your change led to a segfault crash after a few minutes. It happened each time i ran RS-nogui.

gdb shows me it happens in libretroshare/src/gxs/rsgenexchange.cc on line 3019. Is it really because of your change ? Maybe the ```msg``` you delete line 3042 is sometimes deleted again line 3019...

**Comment by ASmith-** [comment]
Segfaults on multiple Retroshare 0.6.3 nogui nodes on Ubuntu Xenial / Mint 18.1 LTS amd64 running sqlite linkage on the previous PPA commit 20170720.baac33d9. This problem of segfaults likely goes back farther in the project development and before the 0.6.3 tag commits were added.

**Comment by G10h4ck** [comment]
Are you still able to reproduce this bug? If so reopen the issue please
