### ISSUE TITLE
Debian 8 

### ISSUE THREAD

**Issue by sissisi** [RetroShare/RetroShare#959]
Hi,

With Debian stretch, the release key to verify package (retroshare stable) does not work 
Indeed,  RSA signing.key to verify packets integrity use DSA 1024, and debian stretch considers DSA 1024 is considered obselete.
Consequently, i ca not install retroshare (stable).

Can you update public key ? I speak this key:

http://download.opensuse.org/repositories/home:AsamK:RetroShare/Debian_8.0/Release.key

Thanks.

Bests regards

**Comment by albuic** [comment]
I can confirm the problem.

**Comment by G10h4ck** [comment]
the new OBS network:retroshare  repository should work fine
