### ISSUE TITLE
Cannot acquire file lock /home/name/.retroshare/pgp/lockResource temporarily unavailable

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#962]
Error reads
Could not request lock on file /home/name/.retroshare/pgp/lockResource temporarily unavailable
Cannot acquire file lock /home/name/.retroshare/pgp/lockResource temporarily unavailable
etc. etc. resulting in immediate problems, then downstream when a concurrent node is booted up its unable to read the changed pgp /folder files.

Why would a multi-concurrent node possible application attempt to co-share the same read-write /pgp directory files creating all kinds of problems immediately and then afterwards?

Doesn't this underscore each node should have its own /pgp/ directory when it is invariably going to encounter one or more other nodes attempting to write to the same pgp directory files at the same time while its attempting to do so to update the various concurrent Retroshare interactions then if and when the application stumbles, crashes, seg faults, aborts or some other less than rare event happens then all of those temporary oops writes is lost creating further downstream problems when that node is next rebooted.

Concurrently running nodes that only read and write to the same /pgp/ files is also going to additionally invariably run into being completely unable to read the pgp directory at bootup, creating yet another error producing a cascading of the outlined problem above downstream to create additional other problems.

Solution
Each node should have its own /pgp/ folder and files bypassing any buggy folder locks which seems to have come from a token ring network model that doesn't have hundreds of variable timed loop routines which further pits the folder lock in full conflict against the other concurrent nodes attempting to update the same pgp folder and files.

**Comment by ASmith-** [comment]
Retroshare Single Node (no concurrent Retroshare Nodes active) operations should never have a Lock File injected into the ./retroshare/pgp folder unless the coding in the Retroshare application wrongly attempts multiple writes at the same time inside the application running solely itself, not with a concurrent node running.

On a hunch I selected 'quit' Retroshare, the program exited as best it can now and then checked the ./retroshare/pgp folder for a still existing BUG lock file and trash temporary gpg files that have been lodged there for who knows how long, likely messing up the pgp directory count in the process at bootup causing further errors and problems because the Retroshare application then doesn't appear to correctly see the /pgp folder, as seen by the debug output.

![retroshare-pgp-folder-lock](https://user-images.githubusercontent.com/8520894/28704618-5e1e00f2-7320-11e7-8217-b58fcf4172b1.png)

The above ./retroshare/pgp folder screen-shot was taken 'after' the Retroshare application running only 1 node on this system was exited correctly. The screen-shot clearly shows a lock file is still existing along with 4 pgp temporary trash files as well.

BUG
Files that should not be there are:

lock <--Should not exist after exit and interferes with Retroshare reboot causing further problems
retroshare_public_keyring.gpg.4uy7FY <--temporary trash file still existing
retroshare_pubic_keyring.gpg.7Q1nb <--temporary trash file still existing
retroshare_public_keyring.gppg.cviwCI <--temporary trash file still existing
retroshare_public_keyring.gpg.Ux2FIq  <--temporary trash file still existing

Best Solution
If there is only One Node operating then do not use a gpg lock file at all

Additional Solutions
Meanwhile Single Retroshare Applications (no concurrent nodes running) should
Absolutely remove any existing lock file at exit
Absolutely clear out any and all temporary trash gpg files at start-up (if only 1 node is operating) and at exit when only sole running node is exited.

**Comment by csoler** [comment]
> lock <--Should not exit after exit and interferes with Retroshare reboot causing further problems

Actually you're wrong. The lock file *does not lock because it's here*, it locks because RS has a handle on it. When RS doesn't run, the file is still here, but it does not lock anything.

> retroshare_public_keyring.gpg.4uy7FY <--temporary trash file still existing
> retroshare_pubic_keyring.gpg.7Q1nb <--temporary trash file still existing

These are saved files after modifications of the PGP keyring. For security, they are not deleted, so that you can recover your keys if something bad happens.

**Comment by ASmith-** [comment]
The lock file is there to prevent multiple attempts to rewrite a file at the same time, so why is a lock file being used when only one node is running. That makes no sense at all.

I and others often see a failure to read the Retroshare pgp directory at bootup and its being bypassed causing problems because the Retroshare application is not seeing something its expecting with either the directory changed or a file it expected is not there or 'something'. This seems to cause problems downstream when that error is shown in debug output at bootup.
