### ISSUE TITLE
There is an issue to Mail service on Retroshare

### ISSUE THREAD

**Issue by jeddah-liu** [RetroShare/RetroShare#963]
There is an iusse I found today. When I click someone's cert link sent with the mail, and I rensent my sert invition back to this guy, my mail stuck and stopped functioning. I restarted my Retreoshare but it wasn't help a little. Then I uninstalled the desktop version of my Retro and downloaed a portable version, when I shtarted the new one, this issue was still there. If someone send me a mail, there will be tips on the inbox icon, and when I send mails to other, the sent icon works well, but I can open any of them by clicking on each icon. While the icon is clicked, there is nothing displayed on the right side field where the mail lists should be display. Anyone meet the same issue?

**Comment by G10h4ck** [comment]
are you still able to reproduce this bug? if so please reopen it
