### ISSUE TITLE
Error in PGPHandler and Skipping Invalid sized dir: pgp at bootup with newest PPA Commit

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#970]
**Error in PGPHandler and Skipping Invalid sized dir: pgp at bootup with newest PPA Commit**

$ ./retroshare_0.6.3-1.20170729.3fb318fd-gui-xenial_sqlite_tor_amd64
RetroShare:: Successfully installed the SIGPIPE Block
Hashed main executable: 55beb138212688b97fc4dabbfd4870cb41644187
defaultBaseDirectory() = /home/name/.retroshare
(WW) Error in PGPHandler::validateAndUpdateSignatures(). Validation failed for at least some signatures.
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read bfc trust packets.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
getAvailableAccounts() Skipping Invalid sized dir: extensions6

retroshare_0.6.3-1.20170729.3fb318fd-gui-xenial_sqlite_tor_amd64 <---- Most Recent PPA Commit
Linux Xenial amd64 LTS distro Qt version 5.5

**Comment by csoler** [comment]
This is totally normal. No issues there.
