### ISSUE TITLE
dosent work on virtual x server

### ISSUE THREAD

**Issue by treaki** [RetroShare/RetroShare#975]
following system:

debian 8, 
```
#as normal user
Xvfb :x -screen 0 1280x720x16 &
export DISPLAY=:x
x11vnc -localhost --rfbport 590x -forever -shared&
openbox &
```
then logged in to it and let some retroshare running, result:

![bildschirmfoto-localhost xx-y_zensur](https://user-images.githubusercontent.com/1477872/28755185-48f6a10c-7555-11e7-8a29-2752ce37ab1a.png)

retroshare is not usable, all windows are gray no matter what i do (starting lxde, mate setings tools, relogging, switching color depts, etc)

please fix that, thanks

**Comment by csoler** [comment]
have you tried with other Qt applications (RS uses Qt) and other remote display viewers (such as x11vnc. There's ssvnc for instance) ? This kind of bug looks like x11vnc doesn't forward Qt widgets, or something like it.

**Comment by treaki** [comment]
other Qt applications: yes, it worked

i guess the problem isnt x11vnc but Xvfb. Because if i run it on my "real x server" it worked. I am using Xvfb a lot but since than had only problems with retorshare. I would be really glad if you who have more inside in the retroshare code could try it out with the given Xvfb command. Thanks!

**Comment by treaki** [comment]
ok, now it is working, maybe the problem is that i am using

```sudo -u retroshareuser RetroShare06```

to let it run. But that was working with the "normal x server" but isnt working now... It would be glad if you could try out any possible setup where you dont use the usual x server and/or the x server and display window manager isnt run by the same user as retroshare...

Its still not working with my original setup but if i let the Xvfb, openbox and x11vnc run as the retroshare user it is working strangely. But there was no problem running them from different users on my normal x server setup...
