### ISSUE TITLE
Add a Hidden Node Only Configure Flag Build to Retroshare so it can be added to Tails

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#980]
**Add a Hidden Node Only Configure Flag Build to Retroshare so it can be added to Tails**

The popular Tails mobile Tor OS would like to add Retroshare to its Tails software that it includes. The problem as I have repeatedly mentioned to the developers here is that No Way in Hell would the Tails Developers add Retroshare in its present form where any Tails user would mistakenly build a Regular Retroshare Node breaking the Tails Security Model exposing that users location.

Adding a Configure Flag to the Retroshare Source Code which results in only a Hidden Node would be produced, allows the Tails Team of developers to further consider adding Retroshare to the software they provide to its many thousands of users.

This seems like such a simple and direct request, I don't know why there is any opposition much less all the inaction in doing that rather simple request here. Are the developers here afraid of the Tails Development team looking at the Retroshare source coding or some other concern? 

I don't see anything but a Win-Win for Tails and for the Retroshare project by simply adding a Configure Flag which would result in only a Retroshare Hidden Node being produced.

**Comment by myfingerhurt** [comment]
#1001
Is this what you hoped for?

**Comment by ASmith-** [comment]
Done, this need is only a small step in having the Tails OS team add Retroshare to its bundled software inclusion. Such doesn't happen in a day, but this is progressing forward with the possibility of providing far more Retroshare users as a direct result.
