### ISSUE TITLE
C++ style comments are not allowed in ISO C90

### ISSUE THREAD

**Issue by ngleb** [RetroShare/RetroShare#983]
After the commit https://github.com/RetroShare/RetroShare/commit/733f81269ccbc45c8d5e5f5807a94e685ce0c0d4 I can no longer build RS under Gentoo with the following error:
```
utility_functions.c:29:5: error: C++ style comments are not allowed in ISO C90
     // cppcheck-suppress memleak
     ^
```
Is there anything that can be done to avoid this issue?

Thanks!

**Comment by G10h4ck** [comment]
I am not sure the pegmarkdwon is used at all and by which part of RS, the fix seems easy it should be enough to remove
// cppcheck-suppress memleak

and add

/* cppcheck-suppress memleak */

As you cant est it would you mind to create a merge request ?

**Comment by ngleb** [comment]
Here it is: https://github.com/RetroShare/RetroShare/pull/986

Compiled without the error.

**Comment by G10h4ck** [comment]
Thank you for reporting and fixing :)
