### ISSUE TITLE
What source code includes are needed for a Retroshare Chat-Only Build?

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#985]
**What source code includes are needed for a Retroshare Chat-Only Build?**

**The Problem with the Swiss Army Retroshare mega Tool-Set Project Model Now**

Retroshare has grown into a bloated CPU,RAM hyper-resource extensive using application where its resource use, bandwidth consumption is far beyond what is expected, needed nor wanted. Project developers must take into account a dozen tools source code downstream of their focus commit changes that could be altered or trashed by their changes making many unknown dire outcomes that pop-up more and more often as the Retroshare coding is thrashed and released then thrashed again and again to re-patch the commit that was just added.

Retroshare individual users often have a single CPU and a cable asymetric Internet connection. Retroshare operates in a P2P F2F functional network that is way under powered on all of the current Retroshare one shoe fits all model application project. CPU demand, RAM demand and Network upload speeds all are seriously stressed and resource hungry far beyond any application offering several of the tools found in Retroshare now.

**The Solution**
Break the existing Retroshare one shoe fits all people and all modes of operations in its existing project model into a RetroActive Core which only contains a Retroshare Chat build and all other major tools are optional module addons that can be added, or not added or removed later at any time and not adversely impact the RetroActive Core. This would be the first step into moving the Retroshare Project into a model consisting of what is essential and what is optionally wanted only depending on the users hardware, needs and resources.

This would also allow the developers to focus entirely in a far more narrow area of coding and optimize each section rather than have the left hand not knowing what the right hand is doing when they adjust the coding in a tool area and have that adversely effect a entirely different tool in adverse ways.

This would allow a wider range of Retroshare users and also further open the door to Android development on a Retroshare Chat Only build. Those with limited data packages cannot use the existing Retroshare bloated, resource intensive application which quickly burns up their data allowance in the background and they then go MIA. CPU intensive Retroshare makes it currently difficult at times to use on any i386 platform. These problems could all be mitigated and helped with a Retroshare Chat Only build and working towards a RetroActive Core.

None of the swiss army knife tools, none of the plugins, circles, forums, channels, file sharing, ban lists, mail tools, only a working Retroshare Chat Only Build without all of the bloated overhead feeding all of those other endless looped tool routines.

A Retroshare Chat Only RetroActive Core would be the first step towards unravelling the bloated Retroshare application project for optimized design and targeted focus on optional modules which contain the other various portions and tools.

**List the needed includes in order for a Retroshare Chat Only Core to be built containing None of the heavy ballast and resource thirsty coding, loops used for supporting Circles,Forums,Channels,Files,Mail etc as a reply below.**

**Comment by myfingerhurt** [comment]
https://github.com/Emotyco/RetroShare

This is a chat only fork.

**Comment by kdebiec** [comment]
@myfingerhurt No, it's not. To disable the rest unused functionality in Emoty and not only, we are waiting for service's switches.
