### ISSUE TITLE
RetroShare-0.6.3-1.20170803.27ee9ca4-trusty-x86_64.AppImage

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#987]
Links for RetroShare-0.6.3-1.20170803.27ee9ca4-trusty-x86_64.AppImage
MD5:
https://drive.google.com/file/d/0B_aJegxr2_uHQ1RSVkFNM19SSEU/view?usp=sharing
Executable:
https://drive.google.com/file/d/0B_aJegxr2_uHT0dvTnNPa1dFejg/view?usp=sharing

The AppImage was built using a VM host Ubuntu Trusty 14.04 at the advisement of @probonod (linuxdeployqt author).  Turns out this bodes well for users of Debian 9 who currently cannot run RS.

**Comment by alfinal** [comment]
This issue could be closed as is talking about an old release offering two broken links.
