### ISSUE TITLE
Data loss after RetroShare crash

### ISSUE THREAD

**Issue by SarcoRS** [RetroShare/RetroShare#99]
My RetroShare instance (0.6.RC2 - the latest official Windows build) crashed and I had to kill it with task manager.

After restart RetroShare lost the custom groups in network window that I was using to group friends into.

Also, all network Tor settings were reset to wrong values, the onion address field was empty. I had to apply all settings manually again and restart it one more time.

Are these particular settings stored in the sqlite/sqlcipher backend or just in a file?

**Comment by AsamK** [comment]
Those settings are stored in the encrypted file config/peers.cfg. There is also a peers.cfg.tmp backup file, that will be used if the first file is corrupted. This file contains the groups and all your friends' locations. So it's strange you only lost the groups and not all peers.
