### ISSUE TITLE
v0.6.3 d'nt build plugins on Qt5

### ISSUE THREAD

**Issue by SergeyDjam** [RetroShare/RetroShare#997]
I build on qt5
and crash build whith errors:

> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPChatWidgetHolder.cpp:165: undefined reference to `ChatWidget::addTitleBarWidget(QWidget*)'
> VOIPChatWidgetHolder.o:/home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPChatWidgetHolder.cpp:166: more undefined references to `ChatWidget::addTitleBarWidget(QWidget*)' follow
> VOIPChatWidgetHolder.o: In function `VOIPChatWidgetHolder::VOIPChatWidgetHolder(ChatWidget*, VOIPNotify*)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPChatWidgetHolder.cpp:283: undefined reference to `ChatWidget::addChatHorizontalWidget(QWidget*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPChatWidgetHolder.cpp:300: undefined reference to `ChatWidget::addChatBarWidget(QWidget*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPChatWidgetHolder.cpp:301: undefined reference to `ChatWidget::addChatBarWidget(QWidget*)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::ReceivedInvitation(t_RsGenericIdType<16u, false, 1u> const&, int)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:36: undefined reference to `Settings'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:36: undefined reference to `RshareSettings::getChatFlags()'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:36: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:36: undefined reference to `ChatDialog::getChat(ChatId, unsigned int)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::ReceivedVoipHangUp(t_RsGenericIdType<16u, false, 1u> const&, int)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:60: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:60: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::ReceivedVoipAccept(t_RsGenericIdType<16u, false, 1u> const&, int)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:84: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:84: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::ReceivedVoipBandwidthInfo(t_RsGenericIdType<16u, false, 1u> const&, int)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:157: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:157: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::AnswerAudioCall(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:187: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:187: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::AnswerVideoCall(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:208: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:208: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::HangupAudioCall(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:229: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:229: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::HangupVideoCall(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:250: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:250: undefined reference to `ChatDialog::getExistingChat(ChatId)'
> VOIPGUIHandler.o: In function `VOIPGUIHandler::ReceivedVoipData(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:116: undefined reference to `Settings'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:116: undefined reference to `RshareSettings::getChatFlags()'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:116: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPGUIHandler.cpp:116: undefined reference to `ChatDialog::getChat(ChatId, unsigned int)'
> VOIPToasterItem.o: In function `VOIPToasterItem::chatButtonSlot()':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:80: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:80: undefined reference to `ChatDialog::chatFriend(ChatId const&, bool)'
> VOIPToasterItem.o: In function `VOIPToasterItem::declineButtonSlot()':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:95: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:95: undefined reference to `ChatDialog::chatFriend(ChatId const&, bool)'
> VOIPToasterItem.o: In function `VOIPToasterItem::VOIPToasterItem(t_RsGenericIdType<16u, false, 1u> const&, QString const&, VOIPToasterItem::voipToasterItem_Type)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:50: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:50: undefined reference to `ChatDialog::chatFriend(ChatId const&, bool)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:60: undefined reference to `RsHtml::RsHtml()'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:60: undefined reference to `RsHtml::formatText(QTextDocument*, QString const&, unsigned long, QColor const&, double, int)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:62: undefined reference to `AvatarWidget::setFrameType(AvatarWidget::FrameType)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:63: undefined reference to `ChatId::ChatId(t_RsGenericIdType<16u, false, 1u>)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterItem.cpp:63: undefined reference to `AvatarWidget::setId(ChatId const&)'
> VOIPToasterItem.o: In function `Ui_VOIPToasterItem::setupUi(QWidget*)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/./ui_VOIPToasterItem.h:136: undefined reference to `AvatarWidget::AvatarWidget(QWidget*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/./ui_VOIPToasterItem.h:174: undefined reference to `StyledLabel::StyledLabel(QWidget*)'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::notifyEnabled(QString)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:72: undefined reference to `Settings'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::testToasterItem(QString)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:174: undefined reference to `rsPeers'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:182: undefined reference to `ToasterItem::ToasterItem(QWidget*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:183: undefined reference to `ToasterItem::ToasterItem(QWidget*)'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::setNotifyEnabled(QString, bool)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:77: undefined reference to `Settings'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::VOIPToasterNotify(RsVOIP*, VOIPNotify*, QObject*)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:34: undefined reference to `ToasterNotify::ToasterNotify(QObject*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:34: undefined reference to `ToasterNotify::~ToasterNotify()'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::voipAudioCallReceived(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:325: undefined reference to `rsPeers'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::voipVideoCallReceived(t_RsGenericIdType<16u, false, 1u> const&)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:349: undefined reference to `rsPeers'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::toasterItem()':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:153: undefined reference to `ToasterItem::ToasterItem(QWidget*)'
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:162: undefined reference to `ToasterItem::ToasterItem(QWidget*)'
> VOIPToasterNotify.o: In function `VOIPToasterNotify::~VOIPToasterNotify()':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/gui/VOIPToasterNotify.cpp:49: undefined reference to `ToasterNotify::~ToasterNotify()'
> moc_VOIPToasterNotify.o: In function `VOIPToasterNotify::qt_metacall(QMetaObject::Call, int, void**)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/moc_VOIPToasterNotify.cpp:116: undefined reference to `ToasterNotify::qt_metacall(QMetaObject::Call, int, void**)'
> moc_VOIPToasterNotify.o: In function `VOIPToasterNotify::qt_metacast(char const*)':
> /home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP/moc_VOIPToasterNotify.cpp:111: undefined reference to `ToasterNotify::qt_metacast(char const*)'
> moc_VOIPToasterNotify.o:(.data.rel.ro._ZTI17VOIPToasterNotify[_ZTI17VOIPToasterNotify]+0x10): undefined reference to `typeinfo for ToasterNotify'
> moc_VOIPToasterNotify.o:(.data.rel.ro._ZTV17VOIPToasterNotify[_ZTV17VOIPToasterNotify]+0x70): undefined reference to `ToasterNotify::hasSetting(QString&)'
> moc_VOIPToasterNotify.o:(.data.rel.ro._ZTV17VOIPToasterNotify[_ZTV17VOIPToasterNotify]+0x78): undefined reference to `ToasterNotify::notifyEnabled()'
> moc_VOIPToasterNotify.o:(.data.rel.ro._ZTV17VOIPToasterNotify[_ZTV17VOIPToasterNotify]+0x80): undefined reference to `ToasterNotify::setNotifyEnabled(bool)'
> moc_VOIPToasterNotify.o:(.data.rel.ro._ZTV17VOIPToasterNotify[_ZTV17VOIPToasterNotify]+0x90): undefined reference to `ToasterNotify::testToasterItem()'
> moc_VOIPToasterNotify.o:(.data.rel.ro+0x0): undefined reference to `ToasterNotify::staticMetaObject'
> collect2: error: ld returned 1 exit status
> make[2]: *** [Makefile:266: libVOIP.so] Error 1
> make[2]: Leaving directory '/home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins/VOIP'
> make[1]: *** [Makefile:44: sub-VOIP-make_first] Error 2
> make[1]: Leaving directory '/home/admin/rpmbuild/BUILD/RetroShare-0.6.3/plugins'
> make: *** [Makefile:202: plugins-make_first] Error 2
> error: Неверный код возврата из /var/tmp/rpm-tmp.81362 (%build)
> 
> 
> Ошибки сборки пакетов:
>     Неверный код возврата из /var/tmp/rpm-tmp.81362 (%build)

This is problem in v0.6.1, v0.6.2

My system Linux ROSA Fresh R8.1, kernel 4.9.34-nrj-desktop-1rosa-x86_64, qt5.6.1

qmake_qt5 "CONFIG-=debug" "CONFIG+=release" PREFIX=%{_prefix} LIB_DIR=%{_libdir} \
            DATA_DIR=%{_datadir}/%{name} INC_DIR=%{_includedir}/%{pkname} \
            RetroShare.pro

**Comment by SergeyDjam** [comment]
up 
0.6.5 too

**Comment by G10h4ck** [comment]
plugins are not considered stable ATM, so consider them only if you plan to do some development, otherwise they should be disabled at build time
